### ISSUE TITLE
Allow Decrypting to Temporary "Buffer"

### ISSUE THREAD

**Issue by kevincox** [open-keychain/open-keychain#1014]
Currently when decrypting files the only output option is to another file.  It would be nice if the result of the decryption could be displayed in a text area inside the app so that it is less likely to hit the disk.  This is also a lot easier to use if I just want to copy a piece of the text.  Similarly having an option to put the result in the clipboard would also be nice.

**Comment by kevincox** [comment]
I see what you mean but I often encrypt sort pieces of text like passwords and the intents system isn't ideal for this.  I could share to my text editor bur I want to try to keep the file off the disk.  I just want to copy out a bit of text and paste is somewhere, like the web browser.

**Comment by dschuermann** [comment]
If you use a good text editor nothing is saved on the disk. It is shared via Android's binder system (kernel memory sharing).
