### ISSUE TITLE
Add export keys functionality to Remote OpenPGP API

### ISSUE THREAD

**Issue by David-Development** [open-keychain/open-keychain#1017]
It would be awesome if it might be possible to export the keys (public keys) and probably with special permissions also the private keys via the Remote API. 

(I want to build a sync client to sync the public keys between multiple devices. For initial sync the private keys should be synced as well. (Sure, it has to be secure)).

**Comment by Valodim** [comment]
An export of public keys should be possible I guess. Can you elaborate on your plans for syncing keys?

**Comment by David-Development** [comment]
Sure.
There will be one public webserver which handles all the requests of the clients.

The sync should work as follows:
Client sends the exported keys and the ownertrust file to the webserver (encrypted with your private key).
All other clients are polling the server for updates (maybe every 30 minutes - configurable)

In Java you can create a watchdog to observ a file for changes. And then export and upload the keys when something changed.
I think this is not possible in Android. But a "static" sync (e.g. every 30 minutes) should work as well. 

So even when the webserver gets hacked the keys are still secure - apart from the fact that they do not contain any sensitive information.

I noticed that it will be neccesarry that the API also supports the export and import of ownertust files. Otherwise the sync doesn't make really sense.

**Comment by Valodim** [comment]
Sorry, we don't do ownertrust (see [here](https://github.com/open-keychain/open-keychain/wiki/Trust-and-Certification-Model)). Keys are usually synchronized with keyservers, so the only information you would be able to synchronize this way would be the fingerprints of keys.

**Comment by David-Development** [comment]
You're right but sometimes keys are not available on keyservers so I want to sync them though (with their corresponding ownertrust). The sync process is completely secure so there shouldn't be a security risk. 
Afaik it's not possible to import only fingerprints of keys (Correct me if I'm wrong).

**Comment by dschuermann** [comment]
There will be a backup API. See https://github.com/open-keychain/open-keychain/pull/1724 . Stay tuned for updates.
