### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1022]
Just started collecting some useful libraries here:
https://github.com/klinker41/android-chips
https://github.com/baoyongzhang/android-PullRefreshLayout
https://github.com/mikepenz/LollipopShowcase
https://github.com/wasabeef/awesome-android-ui

**Comment by Valodim** [comment]
experimental snackbar support in the [t/snackbar branch](https://github.com/open-keychain/open-keychain/tree/t/snackbar)

**Comment by Valodim** [comment]
"Snackbars do not block input on the screens on which they appear."

This does not work correctly for activities where we have a button at the bottom right now
