### ISSUE TITLE
Signature check not OK is a warning?

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1024]
This seems wrong, but not sure if this is expected behavior in some places? DecryptVerifyResult.success() returns true even if signature verification failed

**Comment by timbray** [comment]
I’m looking at PgpDecryptVerify.decryptVerify() and it looks like it calls
the DecryptVerifyResult constructor correctly… when can success() give the
wrong answer?

On Sun, Jan 11, 2015 at 1:48 PM, Vincent <notifications@github.com> wrote:

> This seems wrong, but not sure if this is expected behavior in some
> places? DecryptVerifyResult.success() returns true even if signature
> verification failed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-keychain/open-keychain/issues/1024>.
>



-- 
- Tim Bray (If you’d like to send me a private message, see
https://keybase.io/timbray)

**Comment by dschuermann** [comment]
Hmmm maybe this is confusing, but "DecryptVerifyResult.success()" returns true if the method has been executed correctly. You need to check the OpenPgpSignature object for infos about the signature result.

**Comment by dschuermann** [comment]
@Valodim can we close this one?
