### ISSUE TITLE
poor error message on online key lookup fail

### ISSUE THREAD

**Issue by alanthehat** [open-keychain/open-keychain#1027]
App version: 3.1.2 (31200)

After making several searches on online keyservers I received a red band error message at the top of my screen. (Repeated for several searches) 
I tapped on it & the unhelpful message was "an error occurred". 
No references, no suggestion where the error was in the app or infrastructure, nothing. 

I then 'rotated keyservers' twice & the message didn't come back.

**Comment by timbray** [comment]
Was this associated with a particular failed search?  Or bad network connection?  Looking for hints on how to replicate.

**Comment by alanthehat** [comment]
I felt that it was about too many searches as I was going through my contacts. 
It failed on several different searches, both specific email addresses & keywords.
I was on a broadband connection that seems reliable. 
The problem started with sks-keyservers.net after several lookups, php.net I only allowed a few failures & mit.edu seemed to work fine. 
My device is a Star N9599T with 2GB RAM & 4GB swap. Generally there is ~200MB free on /data & ~500MB free on /sdcard but I didn't check

**Comment by alanthehat** [comment]
If I was trying to debug I would use 'wget' from a looping script & collect the responses, then see how OpenKeychain is set up to report them to the user as the problem that I am reporting is lack of meaning in the error message

**Comment by alanthehat** [comment]
sorry, that was
pool.sks-keyservers.net 
subkeys.pgp.net 
pgp.mit.edu

**Comment by dschuermann** [comment]
Could be bad luck when getting a broken keyserver from the sks-keyservers pool, but I am not sure...

**Comment by alanthehat** [comment]
Is subkeys.pgp.net part of pool.sks-keyservers.net? If so & if pgp.net was faulting that might explain what was happening, but that still leaves the poor error message -- "an error occurred" 
Can the error handler be set to default to relay whatever message it receives unless it has better text itself? Plus, hopefully, a word or more saying where the error came from, possibly 'from remote server' in this instance.

**Comment by dschuermann** [comment]
Should be handled better in newer versions, closing

**Comment by alanthehat** [comment]
Thank you
