### ISSUE TITLE
Feature request: Discover OpenPGP key from YubiKey NEO and download from keyservers

### ISSUE THREAD

**Issue by jas4711** [open-keychain/open-keychain#1028]
For people using a NEO, the step to import a file with your OpenPGP stub shouldn't be strictly necessary.  If you have your OpenPGP key on a keyserver, holding your NEO in front of the app should be sufficient for it to discover what private keys are on it, and download the public key from the keyservers, and you are ready.

Compare with a fresh GnuPG installation: if you do 'gpg --recv-keys 54265e8c' followed by 'gpg --card-status' you end up with a working GnuPG configuration for that NEO.  No need to transfer any secret stubs from an earlier machine.

**Comment by Valodim** [comment]
Yeah this was sort of planned at some point. It's already halfway there actually - there is an activity which reacts to a yubikey but justs reads the fingerprint to the debug log, and we have a mechanism to create stub secret keys from public keys. So what's missing is mostly UI code which says "hey I got this yubikey with fingerprint 0xabc, import and convert?" and then chain an import operation with an editkeyoperation.

**Comment by Valodim** [comment]
I did some backend work to allow promotion of public keys to secret keys by creating stubs, and allowing a restricted subset of key edit operations on keys where no master key is available. Had to figure out that bouncycastle would only read the first half of the IV for divert-to-card secret keys, which should be the length-prefixed serial number. So NOW it's actually only UI code missing which pieces together the backend operations.

Did you have a workflow for this in mind? Where would you have looked for an option to do this?

**Comment by jas4711** [comment]
Thanks for working on it!  I expected it could be a button on the first-start-wizard, either split it up into 'Import Key from memory card', 'Generate Key', and 'Import Key from YubiKey NEO' or make the first screen be 'Import Key' and 'Generate Key' and when you select 'Import Key' there is a way to "import" the key from a NEO.

Or just register an intent so that when a NEO is swiped, the application is started, and if it doesn't know about that OpenPGP key, it is imported.

Just some ideas.

**Comment by Valodim** [comment]
Heh, I sort of forgot this issue existed. I implemented this a while ago on the v/crypto-input-parcel branch together with yubikey certification,  and this was also merged into development ( ce3a1f4c33cef5ce02824b79ca4343f115c4e804)
