### ISSUE TITLE
decode clip board with text in iso-2022-JP 

### ISSUE THREAD

**Issue by goemongit** [open-keychain/open-keychain#1031]
I received encrypted text in Japanese. Copy-Paste via clip board and decode results in wrong charset display, ASCII?

I am using v2.7 at a SGS2+ with Android 4.2.2

This is the begin of the message:

-----BEGIN PGP MESSAGE-----
Charset: iso-2022-jp
...
-----END PGP MESSAGE-----

**Comment by Valodim** [comment]
You are right. We should respect the charset from the ascii armor header, and we don't but assume utf-8 instead. This is a fairly simple fix in our own UI, but requires more thought for the API. We'll see what we can do.

**Comment by goemongit** [comment]
Thanks for the answer. I look forward to see it implemented one day. So far
I am very happy with your software. It makes crypto on tho much easier.

Best wishes
Jürgen
Am 23.01.2015 19:53 schrieb "Vincent" <notifications@github.com>:

**Comment by Valodim** [comment]
This should work internally now, and is respected in the DecryptMessage activity. Not yet in the API though.

**Comment by Valodim** [comment]
As of https://github.com/open-keychain/openpgp-api-lib/commit/edcc61970f24bb3601af26d89f49d384e7a3aff6 this should be passed to an api caller as well
