### ISSUE TITLE
Rewrite input for PgpSignEncrypt

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1032]
I just looked over KeychainIntentService and how the sign encrypt action is handled, and I really don't like it. Getting rid of all program logic from KeychainIntentService has been a long-term goal, and this is the last part that remains, but it's a big one.

Right now, the frontends using PgpSignEncrypt keep state around in a ton of member variables, which are usually put into a bundle of 8 extras in a specific createEncryptBundle function for the service call. Inside the service, those extras are read and fed into a builder. If there are multiple URIs, this happens multiple times, with no properly defined result. Inside PgpSignEncrypt, the builder implicitly assigns a ton of member variables again.

What I would like to do is get rid of the variables->bundle->builder->variables part, but have a SignEncryptParcel which contains all this state, similarly to the EditKeyOperation with its SaveKeyringParcel. This can be used in frontend code, passed to the service, which passes it to the operation untouched, which takes care of the rest.

Just leaving this here for discussion and as a todo for myself

**Comment by Valodim** [comment]
finally done in 7b24ee7b55db99467dd63e631ba55a27d08587d5

Unit tests for this are broken right now, will work on that later. There is also room for optimization concerning cleartext/detached operations, right now there are numerous ways to assign variables in the input which lead to undefined behavior.

**Comment by dschuermann** [comment]
@Valodim can this be closed?

**Comment by dschuermann** [comment]
@Valodim ping?
