### ISSUE TITLE
Development branch: After canonicalize: pub keys gone

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1038]
After canonicalize: pub keys gone

**Comment by Valodim** [comment]
Secret keys are reimported first, after reimport of a secret key the consolidate operation is called... I wonder for how long this has been broken![](http://mugenguild.com/forum/Smileys/mfg/innocent.gif)

**Comment by Valodim** [comment]
found it. 2bb7c3bcef695519c58d33253b74393caf7f14a0 shouldn't be difficult to fix

**Comment by Valodim** [comment]
fixed in 5466d1e9802815726d713bca2aeabaff2861519c
