### ISSUE TITLE
Stuck after entering incorrect Yubikey PIN

### ISSUE THREAD

**Issue by phipolis** [open-keychain/open-keychain#1039]
If one enters the wrong Yubikey PIN when prompted, after placing the Yubikey NEO against the device, Open Keychain flashes the toast "Incorrect PIN!" but doesn't offer a chance to retype it. If you keep trying to use the NEO, it will eventually exceed the tries limit and block the card.

Request: Instead of just showing "Incorrect PIN" toast, invalidate the pin and bring up the pin entry screen to let the user try again.

**Comment by dschuermann** [comment]
Should be fixed in development branch. Please wait for the next OpenKeychain release.
