### ISSUE TITLE
wrong [back] when [advanced] selected from 'no key' dialog

### ISSUE THREAD

**Issue by alanthehat** [open-keychain/open-keychain#1040]
From siacs 'Conversations', in a conversation,  select PGP encryption

OpenKeychain opens with 'select key' dialogue 

Select [create key] then [back] returns you to same dialogue as I expected
however
Select [advanced], then [create key] then [back] puts you in main keys list

**Comment by alanthehat** [comment]
Conversations (XMPP client) - https://f-droid.org/app/eu.siacs.conversations

**Comment by chipset95** [comment]
Can't seem to reproduce the issue, where exactly is the advanced option?

**Comment by alanthehat** [comment]
![screenshot_2015-03-06-14-24-48](https://cloud.githubusercontent.com/assets/7391459/6526784/567691a8-c40d-11e4-9da0-ff52bb5e2242.png)
In purple 2/3 down the screen

**Comment by chipset95** [comment]
@dschuermann , I think the GitHub repo has this fixed already?

**Comment by dschuermann** [comment]
not sure, you have to test this.

**Comment by chipset95** [comment]
@dschuermann this view doesn't exist in the beta in development branch

**Comment by dschuermann** [comment]
@chipset95 follow instructions provided by issue.

**Comment by chipset95** [comment]
@dschuermann issue is in v3.1.2, development is working on 3.2beta1. I cannot reproduce since it does not exist in development.

**Comment by Valodim** [comment]
I think this is fixed. Please reopen if it isn't.

**Comment by alanthehat** [comment]
I've had a system crash & lost Conversations so I can't test, but thank you
