### ISSUE TITLE
API new Actions

### ISSUE THREAD

**Issue by ashh87** [open-keychain/open-keychain#1041]
I have some suggestions for new actions for the API...

I have a backup app which I would like to modify to encrypt the backups using the API. Encryption will be done without interaction, so for this to be one neatly, the app will have to be authorised with OKC beforehand. I'm not sure if a 'do nothing' action would be useful in order to force it to register, or if it would be simplest just to ask the API to do some other action and ignore the result. ('do nothing' rather than 'register', as other providers might not require registering in the same way, and OKC could require it for a 'do nothing' action).

I also need to select recipients non-interactively too - doing it once and saving the result before doing backups. An action to select keys and return their IDs/a string of emails would be useful, rather than relying on the selection screen to come up when an invalid ID is sent to it. This could be wrapped in a (Dialog)Preference in the API. This preference would require registering with OKC, so maybe it makes the 'do nothing' action above slightly redundant. If keys to encrypt to disappeared, apps would then be able to send a notification and have the user select new keys.

Finally, a method to determine if decryption is available for a given selected key would be useful, without trying to decrypt something and checking the result. Apps could then warn (for example) that they can do a backup with a key, but that the corresponding private key needs to imported before restoration is possible. NB restoration would be interactive, asking for a passphrase ;)

**Comment by Valodim** [comment]
Sounds all good to me. That said, both me and Dominik are fairly busy at the current time so it's not likely either of us will find this high on their list of priorities anytime soon. We sure do like to receive pull requests, though. :+1:

**Comment by dschuermann** [comment]
If you want the user to select public keys, you can use
ACTION_GET_KEY_IDS _without specifying EXTRA_USER_IDS.

So, based on the example [0], comment the line like below:

```
public void getKeyIds(Intent data) {
        data.setAction(OpenPgpApi.ACTION_GET_KEY_IDS);
        data.putExtra(OpenPgpApi.EXTRA_ACCOUNT_NAME,
mAccount.getText().toString());
//        data.putExtra(OpenPgpApi.EXTRA_USER_IDS,
mGetKeyIdsEdit.getText().toString().split(","));

        OpenPgpApi api = new OpenPgpApi(this,
mServiceConnection.getService());
        api.executeApiAsync(data, null, null, new MyCallback(false,
null, REQUEST_CODE_GET_KEY_IDS));
    }
```

[0] https://github.com/open-keychain/api-example

**Comment by dschuermann** [comment]
@ashh87 Besides a method for checking if a key for decryption is available, the first two described use cases should already be possible. Or am I missing something?

**Comment by ashh87** [comment]
Yes that seems right :)

**Comment by dschuermann** [comment]
Closing for now, if no objections are made.
