### ISSUE TITLE
use enums instead of int constants

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1042]
so, not using enums is [out of date](http://stackoverflow.com/questions/4822877/why-doesnt-android-use-more-enums) at this point. we should totally get rid of int-constants wherever possible

**Comment by dschuermann** [comment]
yeah, 21. century coding

**Comment by danielnelz** [comment]
Hey,
I skimmed through some of the code today and replaced the magic int constants in the classes CreateKeyActivity.java and KeyFormattingUtils.java.
I created a pull request for this change.
In the next couple of days I'll be on the lookout for further int constants to replace while getting to know the codebase.
Thanks

**Comment by danielnelz** [comment]
Replaced some more ints. Pull request already created.

Thanks!
