### ISSUE TITLE
ask for passphrase on secret key export/deletion

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1045]
Although these operations do not require a passphrase cryptographically, it still makes sense to make sure the user is authorized if they want to use those operations. See #194 for discussion.

**Comment by tdjogi010** [comment]
Hey @Valodim ,
I send a pull request #1108 .
Please check it.

**Comment by Valodim** [comment]
Good so far. This is still missing other places where keys can be deleted though, like the KeyList and AdvancedKeyView.

On the long run, I'd prefer to have the check in the operation code where it really belongs, rather than just the UI. It is the UI code's obligation to inquiry the passphrase for these operations, but the Delete and Export operations should not just trust that this check was already made at an earlier point.

**Comment by manojkhannakm** [comment]
Hello @Valodim

I've planned to solve this issue by creating a DeleteKeyDialogActivity(similar to PassphraseDialogActivity) which would start the PassphraseDialogActivity if the key is not cached and then display the DeleteKeyDialogFragment. Is this approach good?

But I've also found that the above approach cannot not be applied to exporting as it uses a common FileDialogFragment. Can you please suggest something on this.

And what should happen when users try to export multiple secret keys? should they be asked for the passphrases of all keys(which I believe would be a bad UX design) or should they be simply not allowed to export.

**Comment by iseki-masaya** [comment]
Hello @Valodim

I send a pull request #1182.
Please take a look.
