### ISSUE TITLE
openkey-chain fails to build without android-19 platform

### ISSUE THREAD

**Issue by steelman** [open-keychain/open-keychain#1046]
I have prepared my build environment according to the instructions in the README.md. After a few failed builds I had to install

* android-19 platform (required by html-textview)
* Build Tools revision 19.1.0 (required by html-textview)
* Build Tools revision 21.1.1 (required by android-lockpattern)

It appears not only html-textview needs it:

```
find -name build.gradle | xargs grep targetSdkVer 
./OpenKeychain/build.gradle:        targetSdkVersion 21
./extern/TokenAutoComplete/library/build.gradle:        targetSdkVersion 19
./extern/TokenAutoComplete/example/build.gradle:        targetSdkVersion 19
./extern/KeybaseLib/Lib/build.gradle:        targetSdkVersion 19
./extern/html-textview/build.gradle:        targetSdkVersion 19
./extern/SuperToasts/supertoasts/build.gradle:          targetSdkVersion 19
./extern/SuperToasts/demo/build.gradle:         targetSdkVersion 19
```
Please either

* enumerate in the README.md all the versions of platform (API)  and Build Tools that open-keychain and the submodules require for a successful build or
* make everything work with the same (newest) available version.

After installing the older platform and Build Tools packages I managed to build the package.

**Comment by dschuermann** [comment]
We should pick "make everything work with the same (newest) available version.".
Open for pull requests.

**Comment by steelman** [comment]
I am a complete Android noob.

**Comment by dschuermann** [comment]
@steelman No problem :) No need to do it, just leaving it open for others

**Comment by montimaj** [comment]
Check this out! Hope it has resolved this issue
https://github.com/open-keychain/open-keychain/pull/1069

**Comment by dschuermann** [comment]
@montimaj @steelman Can you try if it now builds with build tools 21.1.2 and SDK 21 only? This should be fixed now

**Comment by montimaj** [comment]
Yup it works fine!

On Mon, Mar 2, 2015 at 10:03 PM, Dominik Schürmann <notifications@github.com
> wrote:

> Closed #1046 <https://github.com/open-keychain/open-keychain/issues/1046>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/open-keychain/open-keychain/issues/1046#event-244482704>
> .
>



-- 
*Sayantan Majumdar*

**Comment by steelman** [comment]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':extern:android-lockpattern:code:preBuild'.
> failed to find Build Tools revision 21.1.1
```

**Comment by dschuermann** [comment]
Try git submodule init and git submodule update

**Comment by steelman** [comment]
``` $ git submodule update -f
Submodule path 'extern/KeybaseLib': checked out '9615d90b18d1aee4dad994aa45875adfdcfb3c34'
Submodule path 'extern/StickyListHeaders': checked out '70a2ed80632938540bf07b81270384f4e5a96f9e'
Submodule path 'extern/TokenAutoComplete': checked out '1d6d3882e711c14c93abf73cbcbd28b9e0e2b498'
Submodule path 'extern/html-textview': checked out '9872a73156518fd8df79dd2cd4d24750574b9ac7'
Submodule path 'extern/minidns': checked out '969ffd2951fcaa07f46b441936a0c0fd4502dafd'
Submodule path 'extern/openkeychain-api-lib': checked out '9259075028e0906d0cb085e0c4578e23829dc3c0'
Submodule path 'extern/openpgp-api-lib': checked out '1861415d77f46a466a0ae654ee72f5768f1eed14'
Submodule path 'extern/safeslinger-exchange': checked out '7c84cb54df5b3d5c6780984e48f3e9e4cbc5128e'
Submodule path 'extern/spongycastle': checked out '939914d9ffd1e8cc2710de6c600c9ccfc86aa545'
```

**Comment by dschuermann** [comment]
``extern:android-lockpattern`` is no longer used, that's why I am wondering. You can delete that subdirectory.

**Comment by steelman** [comment]
```
BUILD SUCCESSFUL
```
