### ISSUE TITLE
Replace Holo icons with Material Design icons

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1048]
* Replace all old holo icons with material design icons
* Remove old icons from project
* Use our download script in "Graphics" folder (see https://google.github.io/material-design-icons/ for icon list)
* Special icons on http://materialdesignicons.com/

**Comment by ishan1604** [comment]
@dschuermann I am interested in taking this up. I looked at both the links. But I am not quite sure how to use the downloads script in Graphics folder.

I saw the shell script get-material-icons.sh, could you please guide me by giving one simple example on how to use it to download the icons from the given website.

What I wish to do is?
Learn from your example, implement it in the app to replace all the Holo icons with Material Design Icons and also write a Wiki Document on how this works for future reference of other developers.

Thanks

**Comment by chipset95** [comment]
I have replaced most of the Holo drawbles with Material ones in [this](https://github.com/chipset95/open-keychain/commit/739917b754bb787a9ff8e51c08a55d7275394283) commit.

I wasn't able to use the scripts, but I got all the resources from [Android Asset Studio](http://romannurik.github.io/AndroidAssetStudio) and [Material Icons Index](https://google.github.io/material-design-icons/)

**Comment by vectorijk** [comment]
Fetch icons by script . And I restructured icons and change icon names in layout file. 
All in [this](https://github.com/open-keychain/open-keychain/pull/1090) commit
