### ISSUE TITLE
Key creation: make scrollable

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1049]
On Android 5, the key creation wizard's content is not scrollable. This is especially problematic when entering the passphrase in step 1. Make the content scrollable and pinn the two wizard butons to the bottom.

**Comment by todipratik** [comment]
@dschuermann Are you talking about this ?

![](https://s3.amazonaws.com/pushbullet-uploads/ujAAXGgayiq-zKISF3TaLQIG7DrcXM7hHnhSh0Hmn0qA/Screenshot_2015-03-02-23-02-14.png)

**Comment by dschuermann** [comment]
@todipratik No, the content itself was not scrollable, but I already fixed it in https://github.com/open-keychain/open-keychain/commit/b1c8fa347162825e603e44781efa1446181a1218 . Forgot to close this issue.
