### ISSUE TITLE
Passphrase strength indicator

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1050]
see https://github.com/matt-allen/android-password-strength-indicator

* copy this code over to OpenKeychain
* Integrate into first time wizard

**Comment by the-solipsist** [comment]
Does this use realistic password strength testing, as https://github.com/dropbox/zxcvbn does?

**Comment by dschuermann** [comment]
Nope it does not. If someone wants to do it, go for it!
