### ISSUE TITLE
Show "my keys" even when no secret key is in our database

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1051]
Show "my keys" even when no secret key is in our database. Instead of items show a button to import your key from a file.

**Comment by dschuermann** [comment]
Related: https://github.com/open-keychain/open-keychain/issues/1052

**Comment by imjalpreet** [comment]
@dschuermann, in this you actually a want a change in the key_list_fragment.xml, right?

**Comment by dschuermann** [comment]
I want a change in KeyListFragment.
When no secret key is available in db, but public keys are existing, the "My Keys" header should still be shown and instead of items we should show a button to import keys from a file.

**Comment by imjalpreet** [comment]
So, there should be no change in the key_list_fragment.xml? I thought that when there are no keys and it shows No keys found!!, we should replace that by A button to import keys from file. Is it this way or am I understanding it a bit wrong?

**Comment by Valodim** [comment]
this is about secret keys specifically. if a user has only public keys in his key list, there is no indicator that he has no secret ones because the "My Keys" section is not even shown.

not entirely sure how to handle this correctly. either use a mergecursor and put in a fake item, or use addHeaderView of the list. hmmm.

**Comment by imjalpreet** [comment]
Can you tell how can I create a public key and test this?

**Comment by dschuermann** [comment]
no :)

**Comment by sdipendra** [comment]
Created a pull request for the above at #1145, if you can review it and tell any changes to made.

**Comment by Pushpalanka** [comment]
Is this issue in-progress with you imjalpreet?

**Comment by dschuermann** [comment]
For clarification: This issue higly depends on https://github.com/open-keychain/open-keychain/issues/1052
So no need to work on it until we use the RecyclerView.

**Comment by dschuermann** [comment]
Done in https://github.com/open-keychain/open-keychain/commit/b2d447ab32c3e3327c0b3a89f51c46ede520a6d1 and https://github.com/open-keychain/open-keychain/commit/7004d129a8546977c450bd40931b0b774cd2025e
