### ISSUE TITLE
Support key stubs via K-9 mail for use with YubiKey NEO

### ISSUE THREAD

**Issue by andtentacles** [open-keychain/open-keychain#1055]
On a YubiKey NEO, I added a new encryption subkey to a standard 1024D GPG key. Then I exported a private key stub to my phone. The stub does not contain secret keys, but enables file decryption via NFC and the YubiKeyNEO in the OpenKeychain app, which is working fine.

I would like to use this decryption method for e-mails in K-9 mail. However, in the key selection dialog displayed by OpenKeychain's interface to K-9 mail, my GPG key is grayed out (with an "X" next to it) and I cannot select it. 

The key should be selectable, since the main OpenKeychain app can use it for decryption (provided I swipe the YubiKey, of course).

**Comment by dschuermann** [comment]
It's a limitation of OpenKeychain's API at the moment. It only allows you to select keys capable of signing for K-9. We are aware of that. It will change in a future version.
