### ISSUE TITLE
Scan QR Code from key view: check fingerprint

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1056]
When scanning a QR Code from the key view: The scanned key should be the key you have opened in the key view.
Give mDataUri to the scan QrCodeScanActivity and check the fingerprint against the one in the uri. If it does not fit, abort with an error in our snackbar.

**Comment by Valodim** [comment]
done in 0557e0680e3cdedc32f8ebe35105b772c7b3935b
