### ISSUE TITLE
preselect key for certification if only one is available with certify flag

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1058]
right now in the 'certify' view, a key for certification is only preselected if the user only has a single secret key. if the user has more than one key but only one is actually suitable for certifying, that one should be selected.

this is slightly complex in the class structure because it involves the CertifyKeyFragment, CertifyKeySpinner and KeySpinner. The check for certification suitability should be in CertifyKeySpinner (it's a certification thing after all), but the mechanism for pre-selection should probably be in KeySpinner.

**Comment by tdjogi010** [comment]
Hey @Valodim 
I sent a pull request #1119 
Plz check it.

**Comment by dschuermann** [comment]
@tdjogi010 Please read again: " The check for certification suitability should be in CertifyKeySpinner (it's a certification thing after all), but the mechanism for pre-selection should probably be in KeySpinner."

**Comment by tdjogi010** [comment]
@dschuermann @Valodim 
Made changes #1119 .
I hope this is what is required.

**Comment by dschuermann** [comment]
@tdjogi010 sry, but no. The check for certification suitability should be in CertifyKeySpinner. The mechanism for pre-selection should probably be in KeySpinner.

**Comment by tdjogi010** [comment]
@dschuermann @Valodim 
I sent new pull request #1142 
Maybe this is what is required.

**Comment by tdjogi010** [comment]
Hey, @dschuermann @Valodim 
Plz review pull request #1142 and give your advice about it.
