### ISSUE TITLE
Crash on expiry change

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1059]
1. have key with expiry of today
2. change expiry to yesterday

```
AndroidRuntime  D  Shutting down VM
  8748         AndroidRuntime  E  FATAL EXCEPTION: main
  8748         AndroidRuntime  E  Process: org.sufficientlysecure.keychain, PID: 8748
  8748         AndroidRuntime  E  java.lang.RuntimeException
  8748         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.dialog.EditSubkeyExpiryDialogFragment$2.onClick(EditSubkeyExpiryDialogFragment.java:177)
  8748         AndroidRuntime  E  at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:160)
  8748         AndroidRuntime  E  at android.os.Handler.dispatchMessage(Handler.java:102)
  8748         AndroidRuntime  E  at android.os.Looper.loop(Looper.java:135)
  8748         AndroidRuntime  E  at android.app.ActivityThread.main(ActivityThread.java:5256)
  8748         AndroidRuntime  E  at java.lang.reflect.Method.invoke(Native Method)
  8748         AndroidRuntime  E  at java.lang.reflect.Method.invoke(Method.java:372)
  8748         AndroidRuntime  E  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
  8748         AndroidRuntime  E  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
```

**Comment by montimaj** [comment]
@dschuermann I have compiled the latest version of the app and tested this expiry change activity. The app is crashing after doing the following:
1. Have key without expiry.
2. Set expiry to any date after today
3. Change expiry to any date between today and previous_date_set -1.
  The crash that has been mentioned here was occurring in the apk that is there in Google Play Store.  In the latest version the user cannot set the expiry date to yesterday if the previous_date_ set is today. 
Pull request: #1083

**Comment by dschuermann** [comment]
More info:
It looks Android 5 again allows having older dates selected in the widget.

http://stackoverflow.com/questions/28085786/fix-datepickerdialog-setmaxdate-and-setmindate-on-android-lollipop

**Comment by dschuermann** [comment]
The crash still happens but I was able to get the old spinner back (which in this case makes more sense than the big calendar view): be06c4c

**Comment by dschuermann** [comment]
fixed in https://github.com/open-keychain/open-keychain/commit/7b0e067f63f6f463cd7775347a7bf1c6e3c232c6
