### ISSUE TITLE
Main email in search changes randomly from keybase and keyserver result

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1066]
1. Do many searches for one fingerprint
2. email address randomly changes from keybase.io/dschuermann and the real email

**Comment by jellysheep** [comment]
Hi, I would like to fix this issue, and am currently debugging relevant code.
Would you like to have the real email address instead of the keybase ID shown in case both are found?

**Comment by dschuermann** [comment]
@jellysheep Prefer the email address returned by HKP keyservern over keybase.io ones.

**Comment by jellysheep** [comment]
Ok, thanks. Will it be enough to prefer an ID if it contains a `@` character?
Also there is another issue: when requesting multiple searches, the started threads will continue running for >10s if the server does not respond, even when requesting another search. Should these threads be forced to stop somehow? If needed, should I start another issue on this or just add a commit to this issue?

**Comment by dschuermann** [comment]
No that will not be enough. Please build the view based on the results sorted by HKP keyserver and then keybase.
Create a new issue for the other problem please.

**Comment by jellysheep** [comment]
This commit should fix the issue. For me it constantly shows the correct email from HKP server now.

**Comment by dschuermann** [comment]
Not convinced about this implementation. It adds a lot of code duplicity for differentiating hkp keyserver and keybase entries. I would propose adding an attribute to ``ImportKeysListEntry`` to indicate where they are coming from. Then you can respect this attribute.

**Comment by jellysheep** [comment]
I was not happy about this duplication either. I made all changes inside `CloudSearch.java` to keep interfaces as they are, as e.g. `ImportKeysListEntry` is a Serializable.
So it is ok fo you to add a field `private boolean mFromHkpServer;` to `ImportKeysListEntry`?
Should `serialVersionUID` be changed then?

**Comment by dschuermann** [comment]
I looked into it again and this is also the wrong place^^ There is already a mOrigins ArrayList. So this fix should be easy in ImportKeysList.mergeDupes

**Comment by jellysheep** [comment]
As the current UI displays the first user ID in the `mergedUserIds` map, to prefer HKP server results is simply done by *pre*pending keyserver IDs and *ap*pending keybase IDs, as imlemented above.
The email displayed in the search result is still just a rather random pick out of the available ones, though.

**Comment by dschuermann** [comment]
What do you mean by random pick? Can you point me to the related code?

**Comment by jellysheep** [comment]
In `OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/adapter/ImportKeysAdapter.java` line 142 the *main* user ID is chosen by taking the first entry in the list.
This seems kind of random, as this just depends on the order of email addresses that the keyservers report, if I'm not mistaken.

**Comment by dschuermann** [comment]
OK, but the keybase user ID is never the first one with your commit? Please do a pull request then

**Comment by jellysheep** [comment]
That is correct, the HKP server results will be sorted first, if there are any.
I'm sorry, I just forgot the pull request. Done.
