### ISSUE TITLE
OpenPGP SmartCards (in particular Yubikey NEO)

### ISSUE THREAD

**Issue by dholl** [open-keychain/open-keychain#107]
Has anyone yet offered (or is anyone already working on) support for smartcards in OpenPGP Keychain, such as these:
- OpenPGP SmartCard V2 http://www.g10code.de/p-card.html
- Yubikey Neo http://www.yubico.com/products/yubikey-hardware/yubikey-neo/
- Crypto Stick https://www.crypto-stick.com/

I would like to have OpenPGP-compatible security on my mobile devices, but be able to physically detach my private keys when they're not needed.  (I love that the OpenPGP SmartCard V2 has a signature counter, so that I may keep logs and detect if it is used without my knowlege.  And it supports 4096 bit keys despite the labeling. [1,2,3])

I've started some background digging for existing libraries (such as "seek-for-android"?), but I don't imagine this would be easy.  I would enjoy working with other folks.

-- David

[1] http://comments.gmane.org/gmane.org.fsf.europe.discussion/4221
[2] http://lists.gnupg.org/pipermail/gnupg-announce/2011q3/000312.html
[3] http://www.gossamer-threads.com/lists/gnupg/users/55635#55647

**Comment by brobostigon** [comment]
how does one enable access to the yubikey neo's openpgp card over nfc, there seems basiclly no information on how to do it.

**Comment by dschuermann** [comment]
@brobostigon http://www.openkeychain.org/help/

**Comment by dzhus** [comment]
Are there any OpenPGP-compliant smartcards with NFC interface other than Yubikey?

**Comment by dschuermann** [comment]
There is https://www.sigilance.com/
