### ISSUE TITLE
invoke nfc in advanced key

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1071]

**Comment by dschuermann** [comment]
Add a simple button somewhere that executes the invokeNfc command from the advanced key view. So that also keys that are not yours can be shared via NFC.

**Comment by sdipendra** [comment]
Do you want this button to be visible based on availability of NFC or it should be a permanent?

**Comment by kentnek** [comment]
Do you mean adding a Share via NFC button to the ActionBar of the ViewKeyActivity, to the right of the Encrypt Text button?

**Comment by dschuermann** [comment]
no I mean a button in the advanced key view under the first tab

**Comment by kentnek** [comment]
Oh you mean something like this?

![Screenshot](http://i.imgur.com/PzzyHPh.png)

**Comment by kentnek** [comment]
I have just implemented this feature and made a pull request.

However I'm wondering if both key types (owned and not owned) can be shared via NFC, why not just show the Share via NFC button in `ViewKeyActivity`. Currently its `Visibility` is set to `GONE` if a key doesn't belong to the user.
