### ISSUE TITLE
Dialog shakes when importing many keys

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1076]
OS: Android 5

When importing many keys from a file, the dialog shakes. This maybe due to the way we update the progress.

**Comment by indrora** [comment]
(for future people trying to go at this ticket): what device are you using?

**Comment by dschuermann** [comment]
Sony Z3 with with newest Cyanogenmod nightly.

**Comment by dschuermann** [comment]
Hmmm it is not shaking anymore. Maybe this was a bug in the OS version, not sure. I also had this issue on Android 4.4 on nexus 4...

**Comment by indrora** [comment]
Looks like it's the result of Android trying to auto-fit the text repeatedly.

**Comment by dschuermann** [comment]
Don't see this bug anymore
