### ISSUE TITLE
Edit passphrase of stripped keys

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1085]
Allow passphrase edit of keyrings where the master key has been stripped.
Reference: https://github.com/open-keychain/open-keychain/issues/975#issuecomment-76859607

**Comment by Valodim** [comment]
changing a key's passphrase should be an independent operation from other edits, ui-wise.

**Comment by Diapolo** [comment]
Is this an allowed operation and just currently not supported :)? I was also missing the functionality to change a passphrase without having the master key secret available.

**Comment by dschuermann** [comment]
Just not supported currently. We need to implement this.

**Comment by Tcheutchoua-Steve** [comment]
I will like to fix this ticket but I don't seem to really get what the problem is . I have the app running on my phone and have successfully changed my Passphrase. I don't know if that is the bug in question or it is another one.

**Comment by montimaj** [comment]
You can't change the passphrase if the master key is stripped. That's the issue.

**Comment by Tcheutchoua-Steve** [comment]
OK. Thanks. I get it now

**Comment by Tcheutchoua-Steve** [comment]
This is my approach to solve the ticket
when you select the edit icon , it pops out a list asking you to edit the paraphrase or edit other key items
If you select the " edit passphrase" , you are redirected to another view
The new view requests for the old paraphrase before allowing you to change it.
If you select "edit identities or subkeys " , it asks for the current passphrase and if correctly entered , you are brought to the currently existing view but without the passphrase section (that is change passphrase will not be seen  anymore).
	
Please i need to know if my approach is good so as to solve this ticket. 
Thanks

**Comment by dschuermann** [comment]
@Tcheutchoua-Steve For now, make a "Change passphrase" menu item in the overflow menu that opens a dialog to change the passphrase.

**Comment by Sharad001** [comment]
Hi, sir can i know where can i access the stripped keys functionality. so that i can start working on it !!

**Comment by dschuermann** [comment]
1. Create a new "my key"
2. Edit this key
3. click on your master key (the bold first subkey in the list)
4. select strip key

**Comment by Sharad001** [comment]
So , you want "change passphrase" to be removed from the page and appear on the overflow menu right.

**Comment by Tcheutchoua-Steve** [comment]
I just made a commit of what I did and will like to know if that is what you were talking about. It is on https://github.com/Tcheutchoua-Steve/open-keychain/commit/d2b5969945cd0e0e5cf0bfa490f543666f193c8e

**Comment by Valodim** [comment]
obsolete with considerations in #1541
