### ISSUE TITLE
SHA512 is used instead of SHA256

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1094]
Not sure why but somehow SHA512 is used (I just saw it when testing https://github.com/open-keychain/open-keychain/issues/1093 ) but SHA256 is preferred in my settings (OpenKeychain's default).

**Comment by dschuermann** [comment]
Re-produce:
1. create a key
2. Sign text with this key in Openkeychain and copy into clipboard.
3. Look at clipboard: It says it's a SHA512 cleartext signature.
-> It should be SHA256 like in our preferences

**Comment by Valodim** [comment]
this is related to CanonicalizedSecretKey.getSupportedHashAlgorithms. apparently, we pay no heed to the preferred hashing algorithms specified in a keyring

**Comment by montimaj** [comment]
The selected Hash algorithm will now be displayed!

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/commit/c121657c2cf17ecd3d59809ff86f758b7b1a592c

**Comment by kerlerm** [comment]
Does this commit also close https://github.com/open-keychain/open-keychain/issues/1001 ?
