### ISSUE TITLE
erratic/wrong behaviour when using key with some subkeys on SmartCard

### ISSUE THREAD

**Issue by Diapolo** [open-keychain/open-keychain#1099]
I tried to build a new key, which I can use on my main PC and also on my Android phone:

- create a new key
- add 4 subkeys (2 for PC - sign and encrypt / 2 for Android - sign and encrypt)
- remove private part for the main key from keyring
- move the private part from 2 of the subkeys to an OpenPGP SmartCard (no Yubikey)
- export these 4 private subkeys and transfer to Android
- import them with OpenKeyChain (current version 3.1.2 from F-Droid)
- the new key is correctly recognized, it:
  - doesn't contain the master keys private part (this is shown)
  - shows that 2 of the subkeys are moved to a SmartCard/NFC (the later 2 ones)
  - shows that 2 of the subkeys are available (have the private part with them)

All seems good until I try to use these key with K9-Mail. I can select the correct key, but when first signing (or encrypting for self) with them, the app OpenKeyChain wants me to hold the Yubikey at the back of my Android. That sucks, I want to use the 2 subkeys, for which I HAVE the private part available and I DON'T want to use the ones on a SmartCard (because that's just used on the PC). It also doesn't matter in which order the keys are transferred to the SmartCard (key 1/2 or key 3/4). As long as there are subkeys which are flagged to be on SmartCard/NFC, OpenKeyChain tries to use these.

**Comment by Valodim** [comment]
OpenKeychain uses the first available subkey, prioritizing keys where the secret material is available over yubikeys seems arbitrary. In your scenario, isn't what you actually want to mark all keys as stripped/unavailable to openkeychain except the ones where secret key material exists?

**Comment by Diapolo** [comment]
@Valodim In my first try the 2 stripped subkeys were at index 1 and 2 and the ones where secret key material exists was at index 3 and 4. This did not work, I was asked for a Yubikey (which matches to what you've written above).

Now yesterday I made a mistake, when trying to revert the above situation so that the keys I want to use in OpenKeychain are at index 1 and 2. My mistake (I guess) was that I left the "sign" capability on for the mainkey (which is also stripped). That could have confused OpenKeychain, so it tried to used the mainkey. I need to recreate the keyring so that the master key has just "verify" capability, subkey at index 1 has "sign", index 2 has "encrypt" (both with the secrets available) and then index 3 and 4 as stripped subkeys for my SmartCard.

**Comment by Diapolo** [comment]
This just doesn work like it should, see this TEST key:
![key](https://cloud.githubusercontent.com/assets/1419649/6545696/aa040b10-c594-11e4-9e7f-cca7508113b1.png)

When trying to send signed/encrypted E-Mail I'm queried for a Yubikey :-/.

**Comment by Valodim** [comment]
if you don't want to use the latter keys as nfc keys, why don't you strip them? I fail to see the problem here.

**Comment by Diapolo** [comment]
@Valodim You mean I should delete the 3 SmartCard keys on my main PC, export the keyring for usage on the smartphone and re-import to have a complete keyring on the PC?

But why is OpenKeychain using the NFC keys over the keys at index 1 or 2, that doesn't make sense IMHO. You told me it uses the first key with an available secret above...

**Comment by Valodim** [comment]
essentially yes, although I would guess that this is easier to achieve with the right use of  `gpg --expory-secret-subkeys`

the problem is that there is no well-defined order of subkeys in a keyring. yes there is an order the subkeys appear in in the raw file, but it is still undefined. keyrings are essentially an unordered, append-only file structure. I'm not sure what factors play into the order right now in our queries.

**Comment by Diapolo** [comment]
What about a way to specify the key, which OpenKeychain MUST use in such a case!? IMHO it'd be nice to be able to use the "same" keyring on smartphone and PC without the need to change it or export it in a way that works with OpenKeychain.

**Comment by dschuermann** [comment]
@Diapolo This is a highly advanced use case, I don't see a reason to support this in OpenKeychain. Why not using the suggested way of using the gpg export command?
BTW: How does gpg select the keys?
An implementation would be difficult as it requires to save particular preferred subkey ids for every private key and also from a UI point of view.

**Comment by Diapolo** [comment]
@dschuermann Let me at least ask (because THAT logic must be in the code somewhere), why NFC/Yubikey keys are preferred over the keys, where the secret IT available.

**Comment by dschuermann** [comment]
@Diapolo As far as I know the code, they are not preferred. It's just unordered and thus bad luck ;)
See https://github.com/open-keychain/open-keychain/blob/development/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/CanonicalizedSecretKeyRing.java#L78

**Comment by dschuermann** [comment]
I added the question to http://www.openkeychain.org/faq/.

**Comment by Diapolo** [comment]
@dschuermann Thanks for clarification and for adding it to the FAQ. I'm currently unable to try the thing with just exporting the right subkeys, but will report back, if I get it working ;). Keep up the great work and I'd love to see someone working on Transifex issues, mind taking a look into them?
