### ISSUE TITLE
EmailEditText ToDos

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1106]
Currently the code to verify emails and show an indicator and the code to check the password strength is in CreateKeyInputFragment. The email field is also used in AddUserIdDialogFragment and the password strength indicator should also be used in SetPassphraseDialogFragment (is currently not used there).
We have some code duplication here.
It would be nice to have all code and xml related to the fields in their own classes named PasswordEditText and EmailEditText.

**Comment by chipset95** [comment]
Implemented in pull request #1107. Please have a look! :)

**Comment by dschuermann** [comment]
Still some leftovers:
* Move adapter code from CreateKeyInputFragment into EmailEditText
* Create NameEditText with adapter code for name autocomplete
* Move password strengthview code into PasswordEditText

**Comment by dschuermann** [comment]
* Use hack from AutoCorrectAutoCompleteTextView in EmailEditText and NameEditText

**Comment by chipset95** [comment]
On it!

**Comment by chipset95** [comment]
Since AutoCorrectAutoCompleteTextView is not being used once NameEditText is implemented, should I remove it?

**Comment by dschuermann** [comment]
yes

**Comment by dschuermann** [comment]
Password strengthview code has been merged into PasswordEditText by https://github.com/open-keychain/open-keychain/pull/1111

What is left:
* Move adapter code from CreateKeyInputFragment into EmailEditText
* Create NameEditText with adapter code for name autocomplete
* Use hack from AutoCorrectAutoCompleteTextView in EmailEditText and NameEditText

**Comment by chipset95** [comment]
@dschuermann I already did that in #1109

**Comment by chipset95** [comment]
@dschuermann should I remove PasswordEditText, since we have PassphraseEditText now?

**Comment by dschuermann** [comment]
yes

**Comment by chipset95** [comment]
@dschuermann Does this count in One Patch Rule for GSoC?

**Comment by dschuermann** [comment]
sure
