### ISSUE TITLE
Snackbar cannot be seen in encrypt activies when keyboard is open

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1114]
Snackbar cannot be seen in encrypt activies when keyboard is open, e.g., when no key is selected.

**Comment by Valodim** [comment]
this doesn't seem like a simple one patch... do you have a simple solution in mind for this?

**Comment by dschuermann** [comment]
I thought that it may have something to do with the RelativeLayout or how the layouts are inside of each other, but I am not sure.

**Comment by Sharad001** [comment]
Hi sir could you please elaborate this issue as i don't see any snackbar activity during encrypt activities.

**Comment by dschuermann** [comment]
1 .Click on the "Encrypt to" field, keyboard comes up
2. don't enter anything
3. click on encrypt and share button
4. Snackbar is shown behind the keyboard

**Comment by Sharad001** [comment]
Got it and on it !! :)

**Comment by Sharad001** [comment]
Sir, do we want the snackbar to come above the keyboard or keyboard should get hidden when snackbar activity is there.

**Comment by dschuermann** [comment]
Snackbar above keyboard in all activites.

**Comment by Sharad001** [comment]
Hi sir, sorry for the delay but i'm little busy with my exams and i will get back to you with the solution after 20th when my exam ends.
