### ISSUE TITLE
Rework "Delete after encryption" feature

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1116]
Delete after encryption/decryption is currently implemented very badly.
* If the user chooses to encrypt a file and share it, the dialog is shown behind the share menu of Android, thus the file will never be deleted.
* If multiple files are encrypted the dialog is shown for every file separately, also the files are deleted separately.
* The deletion code is inside the DialogFragment.

Should be:
* Show dialog before sharing the encrypted temporary file and only proceed to sharing if "Delete" is clicked
* Execute deletion after encryption process succeeded
* Allow deletion of multiple files, i.e. show a list of files in the DeleteFileDialogFragment dialog. Also show a list of files in the Toasts, collect files that failed to delete.

**Comment by manojkhannakm** [comment]
Hello @dschuermann 

By "show a list of files in the DeleteFileDialogFragment dialog" do you mean to show the list of files as Checkboxes so as to allow the user to the select the files to delete or just the list of file names.

**Comment by dschuermann** [comment]
Just a list of file names

**Comment by manojkhannakm** [comment]
Pull request: https://github.com/open-keychain/open-keychain/pull/1124

Also while testing I've found a bug. When selecting files for encryption, if a same file is selected multiple times, while deleting it causes a crash of activity. Should this be handled while selecting the files or while deleting.

**Comment by manojkhannakm** [comment]
Also while testing I've found a bug. When selecting files for encryption, if a same file is selected multiple times, while deleting it causes a crash of activity. Should this be handled while selecting the files or while deleting.

**Comment by manojkhannakm** [comment]
@dschuermann Please have a look at the updated pull request https://github.com/open-keychain/open-keychain/pull/1137.
