### ISSUE TITLE
Use contact name instead of user id on linked system contact card

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1126]
see title. right now, the primary user id is shown as contact name, when it should be the merged contact's name

**Comment by Sharad001** [comment]
Sir can you tell me where can i find the contact card code as it is very large code-base so please suggest how to find it.

**Comment by Sharad001** [comment]
Sir can you please tell me where is this linked contact card has been used. It would be helpful if you could give some screenshot for good understanding

**Comment by dschuermann** [comment]
Alread done in https://github.com/open-keychain/open-keychain/pull/1134
