### ISSUE TITLE
Dont display key ids

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1131]
Dont display key Ids anymore. If two keys exist with the same Name show creation date for differentiation?

**Comment by Sharad001** [comment]
hi sir can i know where can i find the list of ids just for start so that i can start working on it.

**Comment by dschuermann** [comment]
@Sharad001 Please stick to the issues labeled with simple-one-patch: https://github.com/open-keychain/open-keychain/issues?q=is%3Aopen+label%3Asimple-one-patch
