### ISSUE TITLE
Feature: Search keys for each contact

### ISSUE THREAD

**Issue by sedrubal** [open-keychain/open-keychain#1140]
A function to automatically search avaylable keys on keyserver for each contact person.

**Comment by dschuermann** [comment]
A functionality has already been implemented last year and is currently disabled: https://github.com/open-keychain/open-keychain/blob/development/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/ContactSyncAdapterService.java

We just don't know currently how to do this UI wise. So this is on hold until we find a proper way of doing this. Maybe it is even better to not do it and download keys automatically when receiving a signed email.
On the other hand, this sort of import could encourage people to use OpenPGP.

**Comment by sedrubal** [comment]
But I think it's better if the user can decide, when he wants to download the keys.

**Comment by dschuermann** [comment]
Yes sure, I laid out my concerns: It is difficult to implement from a UI standpoint and the gain of such a mass import is maybe not high enough to annoy the users.

**Comment by tcitworld** [comment]
Hi, has this evolved ?

**Comment by Valodim** [comment]
Not really, no. Our plan is to automate most public key management at least for the e-mail use case with [autocrypt](autocrypt.org). Hopefully this will remove the need to upload keys to public keyservers, and the headache of dealing with them.

**Comment by tcitworld** [comment]
Perfect, thanks !
