### ISSUE TITLE
Application ignore expiration date of master key

### ISSUE THREAD

**Issue by bmalkow** [open-keychain/open-keychain#1141]
I found a problem with expiration date. It seems application ignore expiration date of master key (it displays only expiration dates of subkeys). Application also shows expired key as valid.

Check it on key:

    gpg -k 0x0664A76954265E8C
    pub   3744R/0x0664A76954265E8C 2014-06-22 [expires: 2015-08-19]
    uid                 [ unknown] Simon Josefsson <simon@josefsson.org>
    uid                 [ unknown] Simon Josefsson <simon@yubico.com>
    sub   2048R/0x860B7FBB32F8119D 2014-06-22 [expires: 2015-08-19]
    sub   2048R/0x9535162A78ECD86B 2014-06-22 [expires: 2015-08-19]
    sub   2048R/0xAF6608D736BA8F9B 2014-06-22 [expires: 2015-08-19]

**Comment by dschuermann** [comment]
@Valodim can you look into this?
The key in question is shown in OpenKeychain:
![device-2015-03-12-143952](https://cloud.githubusercontent.com/assets/321888/6618782/ad32c31a-c8c5-11e4-8917-2721cec09268.png)

**Comment by bmalkow** [comment]
Look at this [0x0664A76954265E8C](https://pgp.mit.edu/pks/lookup?op=vindex&search=0x0664A76954265E8C)

**Comment by dschuermann** [comment]
@bmalkow thanks for the details.

**Comment by Valodim** [comment]
Hm, I'm pretty sure I did consider key expiration during import. I didn't look at the other side of that query in a long time though. I'll look into it.

**Comment by Valodim** [comment]
it was an implementation bug, concept was fine. fixed.
