### ISSUE TITLE
Please add a feature: exporting/sharing private and public key using another public key

### ISSUE THREAD

**Issue by Foxdelmar** [open-keychain/open-keychain#1150]
thx for all your great work on open-keychain.
Today I was asking how to export my private key from my mobile device. In the FAQ/Help it is recommended to save the keys on the SD-Card with a strong passphrase. 

But I would be really happy if you could add the feature to share/send the private and public key (*.asc) directly to open-keychain itself to encrypt the key with another public key to send it via e-mail without saving and deleting it on the file system.

With this alternative I would not have to store the private key on my file system which I would like to avoid.

I would like to donate for this feature or for a nice recommendation for an easier way.

best regards

**Comment by Valodim** [comment]
You can do this already, just generate a key and encrypt a file to it. Specialized support sounds like a niche thing

**Comment by Foxdelmar** [comment]
Hi Valodim,
sorry that I haven't answered earlier.

I tried and testet a lot but It does not work.

I want to export my private key in openKeyChain. But it should not be saved on my local storage. I dont want to use a strong passphrase.

I want to encrypt my private key with another public key in my key list before this private key leaves the app openKeyChain. Could this feature please be added?

**Comment by Valodim** [comment]
a better thought out "key backup" feature is planned at some point, but not currently a point of priority. for the moment you are stuck with using a strong passphrase, or encrypting after the key was written to local storage. sorry.

for the record though, if you encrypt your data with a very strong passphrase, it is just as difficult to crack as if it was encrypted with a public key. data is encrypted with AES-128 in both cases.
