### ISSUE TITLE
API EXTRA_PASSPHRASE parameter does not work

### ISSUE THREAD

**Issue by jsawaya** [open-keychain/open-keychain#1157]
Setting the EXTRA_PASSPHRASE parameter does not effect the process as the open-keychain app always prompts for the pass-phrase (with or without the EXTRA_PASSPHRASE parameter).
It does not even fail with a bad pass-phrase (when it should fail).  

Simple test case:
	public void cleartextSignClickHandler()
	{
		Intent data = new Intent();
		data.setAction(OpenPgpApi.ACTION_CLEARTEXT_SIGN);

		data.putExtra(OpenPgpApi.EXTRA_SIGN_KEY_ID, signKeyIdLong);
		data.putExtra(OpenPgpApi.EXTRA_PASSPHRASE, passCode);

		String inputString = cleartextEditText.getText().toString();
		InputStream is = getByteArrayInputStreamFromString(inputString);

		ByteArrayOutputStream os = new ByteArrayOutputStream();

		OpenPgpApi openPgpApi = getOpenPgpApi();
		openPgpApi.executeApiAsync(data, is, os, new OpenkeychainCallback(openPgpCameraActivity, REQUEST_CODE_CLEARTEXT_SIGN, os, ciphertextEditText, null));
	}

Log:
03-17 13:42:30.421: D/dalvikvm(555): Debugger has detached; object registry had 1 entries
03-17 13:42:30.441: D/dalvikvm(575): Debugger has detached; object registry had 1 entries
03-17 13:42:30.441: D/dalvikvm(32276): Debugger has detached; object registry had 1 entries
03-17 13:44:59.239: W/InputEventReceiver(575): Attempted to finish an input event but the input event receiver has already been disposed.
03-17 13:44:59.450: E/ViewRootImpl(575): sendUserActionEvent() mView == null
03-17 13:44:59.590: W/IInputConnectionWrapper(575): getTextBeforeCursor on inactive InputConnection
03-17 13:44:59.590: W/IInputConnectionWrapper(575): getCursorCapsMode on inactive InputConnection
03-17 13:44:59.680: W/IInputConnectionWrapper(575): getCursorCapsMode on inactive InputConnection
03-17 13:44:59.680: W/IInputConnectionWrapper(575): getSelectedText on inactive InputConnection
03-17 13:44:59.680: W/IInputConnectionWrapper(575): getTextBeforeCursor on inactive InputConnection
03-17 13:44:59.690: W/IInputConnectionWrapper(575): getTextAfterCursor on inactive InputConnection
03-17 13:44:59.700: W/IInputConnectionWrapper(575): showStatusIcon on inactive InputConnection
03-17 13:45:00.261: D/dalvikvm(555): Debugger has detached; object registry had 1 entries
03-17 13:45:00.271: D/dalvikvm(575): Debugger has detached; object registry had 1 entries
03-17 13:45:00.471: D/dalvikvm(32276): Debugger has detached; object registry had 1 entries
03-17 13:45:04.775: D/Keychain(555): isPackageAllowed packageName: com.sawaya.openpgpapi.openpgpcamera
03-17 13:45:04.775: V/Keychain(575): query(uri=content://org.sufficientlysecure.keychain.provider/api_apps, proj=null)
03-17 13:45:04.785: D/Keychain(555): allowed: [org.sufficientlysecure.keychain.demo, com.sawaya.openpgpapi.openpgpcamera]
03-17 13:45:04.785: D/Keychain(555): Package is allowed! packageName: com.sawaya.openpgpapi.openpgpcamera
03-17 13:45:04.795: V/Keychain(575): query(uri=content://org.sufficientlysecure.keychain.provider/api_apps/com.sawaya.openpgpapi.openpgpcamera, proj=[package_signature])
03-17 13:45:04.805: D/Keychain(555): Package signature is correct! (equals signature from database)
03-17 13:45:04.805: D/Keychain(555): currentPkg: com.sawaya.openpgpapi.openpgpcamera
03-17 13:45:04.905: D/Keychain(575): uri: content://org.sufficientlysecure.keychain.provider/api_apps/com.sawaya.openpgpapi.openpgpcamera
03-17 13:45:04.926: D/AbsListView(575): Get MotionRecognitionManager
03-17 13:45:04.946: D/AbsListView(575): Get MotionRecognitionManager
03-17 13:45:04.946: V/Keychain(575): query(uri=content://org.sufficientlysecure.keychain.provider/key_rings/unified, proj=[_id, master_key_id, user_id, is_expired, is_revoked, has_encrypt, verified, has_any_secret, has_duplicate_user_id, creation])
03-17 13:45:05.006: D/ProgressBar(575): updateDrawableBounds: left = 0
03-17 13:45:05.006: D/ProgressBar(575): updateDrawableBounds: top = 0
03-17 13:45:05.006: D/ProgressBar(575): updateDrawableBounds: right = 152
03-17 13:45:05.006: D/ProgressBar(575): updateDrawableBounds: bottom = 152
03-17 13:45:07.138: D/Keychain(575): allowedKeysUri: content://org.sufficientlysecure.keychain.provider/api_apps/com.sawaya.openpgpapi.openpgpcamera/allowed_keys
03-17 13:45:07.138: D/Keychain(575): insert(uri=content://org.sufficientlysecure.keychain.provider/api_apps/com.sawaya.openpgpapi.openpgpcamera/allowed_keys, values=key_id=3391992614177110942)
03-17 13:45:07.138: D/Keychain(575): Constraint exception on insert! Entry already existing?
03-17 13:45:07.138: D/Keychain(575): android.database.sqlite.SQLiteConstraintException: columns key_id, package_name are not unique (code 19)
03-17 13:45:07.138: D/Keychain(575): 	at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
03-17 13:45:07.138: D/Keychain(575): 	at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:972)
03-17 13:45:07.138: D/Keychain(575): 	at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
03-17 13:45:07.138: D/Keychain(575): 	at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
03-17 13:45:07.138: D/Keychain(575): 	at android.database.sqlite.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1603)
03-17 13:45:07.138: D/Keychain(575): 	at android.database.sqlite.SQLiteDatabase.insertOrThrow(SQLiteDatabase.java:1499)
03-17 13:45:07.138: D/Keychain(575): 	at org.sufficientlysecure.keychain.provider.KeychainProvider.insert(KeychainProvider.java:743)
03-17 13:45:07.138: D/Keychain(575): 	at android.content.ContentProvider$Transport.insert(ContentProvider.java:220)
03-17 13:45:07.138: D/Keychain(575): 	at android.content.ContentResolver.insert(ContentResolver.java:1195)
03-17 13:45:07.138: D/Keychain(575): 	at org.sufficientlysecure.keychain.provider.ProviderHelper.addAllowedKeyIdForApp(ProviderHelper.java:1554)
03-17 13:45:07.138: D/Keychain(575): 	at org.sufficientlysecure.keychain.remote.ui.SelectSignKeyIdListFragment$1.onItemClick(SelectSignKeyIdListFragment.java:118)
03-17 13:45:07.138: D/Keychain(575): 	at android.widget.AdapterView.performItemClick(AdapterView.java:308)
03-17 13:45:07.138: D/Keychain(575): 	at android.widget.AbsListView.performItemClick(AbsListView.java:1495)
03-17 13:45:07.138: D/Keychain(575): 	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3453)
03-17 13:45:07.138: D/Keychain(575): 	at android.widget.AbsListView$3.run(AbsListView.java:4816)
03-17 13:45:07.138: D/Keychain(575): 	at android.os.Handler.handleCallback(Handler.java:733)
03-17 13:45:07.138: D/Keychain(575): 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-17 13:45:07.138: D/Keychain(575): 	at android.os.Looper.loop(Looper.java:146)
03-17 13:45:07.138: D/Keychain(575): 	at android.app.ActivityThread.main(ActivityThread.java:5487)
03-17 13:45:07.138: D/Keychain(575): 	at java.lang.reflect.Method.invokeNative(Native Method)
03-17 13:45:07.138: D/Keychain(575): 	at java.lang.reflect.Method.invoke(Method.java:515)
03-17 13:45:07.138: D/Keychain(575): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
03-17 13:45:07.138: D/Keychain(575): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
03-17 13:45:07.138: D/Keychain(575): 	at dalvik.system.NativeStart.main(Native Method)
03-17 13:45:07.598: D/AbsListView(575): onDetachedFromWindow
03-17 13:45:08.830: D/Keychain(555): isPackageAllowed packageName: com.sawaya.openpgpapi.openpgpcamera
03-17 13:45:08.830: V/Keychain(575): query(uri=content://org.sufficientlysecure.keychain.provider/api_apps, proj=null)
03-17 13:45:08.840: D/Keychain(555): allowed: [org.sufficientlysecure.keychain.demo, com.sawaya.openpgpapi.openpgpcamera]
03-17 13:45:08.840: D/Keychain(555): Package is allowed! packageName: com.sawaya.openpgpapi.openpgpcamera
03-17 13:45:08.850: V/Keychain(575): query(uri=content://org.sufficientlysecure.keychain.provider/api_apps/com.sawaya.openpgpapi.openpgpcamera, proj=[package_signature])
03-17 13:45:08.860: D/Keychain(555): Package signature is correct! (equals signature from database)
03-17 13:45:08.950: D/AbsListView(575): Get MotionRecognitionManager
03-17 13:45:08.960: V/Keychain(575): query(uri=content://org.sufficientlysecure.keychain.provider/key_rings/unified, proj=[_id, master_key_id, user_id, is_expired, is_revoked, has_encrypt, verified, has_duplicate_user_id, creation])
03-17 13:45:09.000: D/ProgressBar(575): updateDrawableBounds: left = 0
03-17 13:45:09.000: D/ProgressBar(575): updateDrawableBounds: top = 0
03-17 13:45:09.000: D/ProgressBar(575): updateDrawableBounds: right = 152
03-17 13:45:09.000: D/ProgressBar(575): updateDrawableBounds: bottom = 152
03-17 13:45:12.323: D/AbsListView(575): onDetachedFromWindow
03-17 13:45:59.294: D/Keychain(555): isPackageAllowed packageName: com.sawaya.openpgpapi.openpgpcamera
03-17 13:45:59.304: V/Keychain(575): query(uri=content://org.sufficientlysecure.keychain.provider/api_apps, proj=null)
03-17 13:45:59.314: D/Keychain(555): allowed: [org.sufficientlysecure.keychain.demo, com.sawaya.openpgpapi.openpgpcamera]
03-17 13:45:59.314: D/Keychain(555): Package is allowed! packageName: com.sawaya.openpgpapi.openpgpcamera
03-17 13:45:59.324: V/Keychain(575): query(uri=content://org.sufficientlysecure.keychain.provider/api_apps/com.sawaya.openpgpapi.openpgpcamera, proj=[package_signature])
03-17 13:45:59.334: D/Keychain(555): Package signature is correct! (equals signature from database)
03-17 13:45:59.334: D/Keychain(555): nfcSignedHash: null
03-17 13:45:59.334: D/Keychain(555): nfcCreationTimestamp: -1
03-17 13:45:59.344: V/Keychain(555): log: LogEntryParcel{mLevel=DEBUG, mType=MSG_PSE, mParameters=null, mIndent=0}
03-17 13:45:59.344: D/Keychain(555): enableSignature:true
03-17 13:45:59.344: D/Keychain(555): enableEncryption:false
03-17 13:45:59.344: D/Keychain(555): enableCompression:false
03-17 13:45:59.344: D/Keychain(555): enableAsciiArmorOutput:true
03-17 13:45:59.344: V/Keychain(575): query(uri=content://org.sufficientlysecure.keychain.provider/key_rings/3391992614177110942/unified, proj=[has_any_secret, verified, privkey_data])
03-17 13:46:01.686: V/Keychain(575): query(uri=content://org.sufficientlysecure.keychain.provider/key_rings/find/subkey/3391992614177110942, proj=[master_key_id])
03-17 13:46:01.706: D/Keychain(555): PassphraseCacheService.getCachedPassphrase() for masterKeyId 3391992614177110942, subKeyId 3391992614177110942
03-17 13:46:01.706: D/Keychain(32276): PassphraseCacheService.onStartCommand()
03-17 13:46:01.706: D/Keychain(32276): PassphraseCacheService.getCachedPassphraseImpl() for masterKeyId 3391992614177110942, subKeyId 3391992614177110942
03-17 13:46:01.726: V/Keychain(575): query(uri=content://org.sufficientlysecure.keychain.provider/key_rings/3391992614177110942/keys, proj=[has_secret])
03-17 13:46:01.736: D/Keychain(32276): PassphraseCacheService: masterkey passphrase not (yet) cached, returning null
03-17 13:46:01.736: V/Keychain(555): log: LogEntryParcel{mLevel=INFO, mType=MSG_PSE_PENDING_PASSPHRASE, mParameters=null, mIndent=2}
03-17 13:46:02.107: V/Keychain(575): query(uri=content://org.sufficientlysecure.keychain.provider/key_rings/find/subkey/3391992614177110942, proj=[has_any_secret, verified, privkey_data])
03-17 13:46:02.117: V/Keychain(575): query(uri=content://org.sufficientlysecure.keychain.provider/key_rings/find/subkey/3391992614177110942, proj=[master_key_id])
03-17 13:46:02.127: V/Keychain(575): query(uri=content://org.sufficientlysecure.keychain.provider/key_rings/3391992614177110942/keys, proj=[has_secret])
03-17 13:46:02.217: D/ProgressBar(575): updateDrawableBounds: left = 0
03-17 13:46:02.217: D/ProgressBar(575): updateDrawableBounds: top = 0
03-17 13:46:02.217: D/ProgressBar(575): updateDrawableBounds: right = 96
03-17 13:46:02.217: D/ProgressBar(575): updateDrawableBounds: bottom = 96

The open-keychain UI prompts for passphrase - even though it was passed as parameter.

**Comment by dschuermann** [comment]
Please try out the version from our development branch. It should be fixed now with https://github.com/open-keychain/open-keychain/commit/9e668eadcb5dc5737f3df94339a1fa1e8662f0ea
