### ISSUE TITLE
Passphrase cache not clearing

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1169]
Cached pass at 15:30
Still cached at 21:15

Setting: 3 min cache time

Maybe we are using imprecise alarm settings. This needs more investigation. At most times, it is working.

**Comment by Sharad001** [comment]
Sir , i have tried to cache the passphrase almost 10 times but i didn't found any kind of error. But still as you said there is some problem with alarm settings so i am trying to find the bug in the implementation and i will get back to you when i resolve the issue .!!

**Comment by Sharad001** [comment]
Sir , please tell me whether i have done it correctly or not so that i should move forward with another bug and then for proposal !!
