### ISSUE TITLE
All my contacts disappeared

### ISSUE THREAD

**Issue by niklasni1** [open-keychain/open-keychain#1175]
I installed OpenKeychain from F-Droid on my Nexus 5, which has the latest Cyanogen Mod 11 snapshot installed. No Google apps, no other forms og contact sync.

I opened the app and the Create key wizard. I got an SMS and switched to the Conversations app, and noticed that all my SMSes were listed by phone number, not by contact name. Switching to the People app, all my contacts except four had disappeared. 

I think, but cannot confirm, that those four contacts are the ones that have been added manually to this phone, the others were imported from vCards when I got it.

**Comment by dschuermann** [comment]
Can you try to install the beta version as explained here: http://www.openkeychain.org/help/
And then try to reproduce the problem? Is it still happening with the beta version?

**Comment by niklasni1** [comment]
Not if it requires Google Play, unfortunately.

**Comment by dschuermann** [comment]
Could you try the new release and re-open this issue if it still happens?
