### ISSUE TITLE
Keyserver LDAP protocol support

### ISSUE THREAD

**Issue by qw3ry** [open-keychain/open-keychain#1195]
It seems that I cannot connect to ldap-keyservers. As far as I can tell e.g. keyserver.pgp.com does not offer a hkp connection, but I would like to add it to my keyservers.

Tbh it is not really easy to verify the keyserver URLs. It would be much easier if the keyservers entered could instantly be verified by some kind of test routine.

**Comment by kwirk** [comment]
:+1:

**Comment by dschuermann** [comment]
second feature request separated into https://github.com/open-keychain/open-keychain/issues/1202

**Comment by Sekanato** [comment]
Would like ldap support too! Is it still considered?

**Comment by dschuermann** [comment]
@Sekanato Nobody is working on this feature right now, but we are open for pull requests to add this.

**Comment by Valodim** [comment]
Is this widely used somewhere? I thought hkps had established itself as the one true protocol for this purpose, except for PGP Global Directory (which, last I checked, nobody uses?)

**Comment by dschuermann** [comment]
For now we will not implement LDAP. User base is too small. Also, key exchange must move away from keyservers.

**Comment by canary5** [comment]
Why key exchange must move from keyservers? Any security issues?

**Comment by dschuermann** [comment]
Most users no longer prefer to publish their email addresses on keyservers due to privacy and spam concerns.
