### ISSUE TITLE
Snackbars again behind layout

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1196]
Hey @manojkhannakm 
you did some great work with your pull request https://github.com/open-keychain/open-keychain/pull/1168
Unfortunatly, we did some big internal changes leading to have the issue again with snackbars behind the keyboard.
Do you have some spare time to look into it. Especially the encrypt/decrypt activities.

**Comment by manojkhannakm** [comment]
I'm a bit busy with my exams now. I'll try to fix it during the weekend.

**Comment by dschuermann** [comment]
thanks

**Comment by dschuermann** [comment]
@manojkhannakm any progress updates? Don't want to push you, just asking :)

**Comment by manojkhannakm** [comment]
Fixed. Sorry for being quite inactive lately, got really stuck due to exams.

I'm right now experimenting some UI testing using the Espresso framework. If possible I'll try to push some update on on it today :)

**Comment by dschuermann** [comment]
@manojkhannakm thanks again. Looking forward for Espresso tests ;)
