### ISSUE TITLE
Signing crash with YubiKey

### ISSUE THREAD

**Issue by bmalkow** [open-keychain/open-keychain#1201]
When I try to sign or encrypt&sign message in K-9:

	04-17 15:44:27.588: E/AndroidRuntime(9502): FATAL EXCEPTION: main
	04-17 15:44:27.588: E/AndroidRuntime(9502): Process: org.sufficientlysecure.keychain, PID: 9502
	04-17 15:44:27.588: E/AndroidRuntime(9502): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.PassphraseDialogActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	at android.os.Handler.dispatchMessage(Handler.java:102)
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	at android.os.Looper.loop(Looper.java:135)
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	at java.lang.reflect.Method.invoke(Native Method)
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	at java.lang.reflect.Method.invoke(Method.java:372)
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
	04-17 15:44:27.588: E/AndroidRuntime(9502): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	at org.sufficientlysecure.keychain.ui.PassphraseDialogActivity.onCreate(PassphraseDialogActivity.java:105)
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	at android.app.Activity.performCreate(Activity.java:5933)
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
	04-17 15:44:27.588: E/AndroidRuntime(9502): 	... 10 more

Used revision b440456acc1e846f19f663a2987cb1bc292f14bd

**Comment by dschuermann** [comment]
Yeah, development branch is broken right now.
What K-9 version are you using?

**Comment by bmalkow** [comment]
K-9 5.004

**Comment by Valodim** [comment]
Hmm, I checked it out and this looks like a bug which shouldn't happen anymore indeed.

**Comment by dschuermann** [comment]
Please test with new version and re-open if still present

**Comment by bmalkow** [comment]
Does it builds for you? I see many test failures.

**Comment by dschuermann** [comment]
Yes it builds: https://travis-ci.org/open-keychain/open-keychain/builds/61456498

**Comment by bmalkow** [comment]
Still exactly the same error.
I added some debug, and I can confirm that for sure `requiredInput.getSubKeyId()` returns `null`.

**Comment by dschuermann** [comment]
Do you have a key for re-producing the issue or could you at least point to the public key?

**Comment by bmalkow** [comment]
This is my private key.
I have master key (unattached) with three keys on Neo. keyid:0x0C3137AF49766002

**Comment by dschuermann** [comment]
What do you mean by unattached?
So the three subkeys of your PGP key are on the NEO while the master key is not?

**Comment by bmalkow** [comment]
I have offline master key and subkeys of NEO.
As described [here](http://blog.josefsson.org/2014/06/23/offline-gnupg-master-key-and-subkeys-on-yubikey-neo-smartcard/).

**Comment by deermo** [comment]
Same error here. OpenKeychain 3.2. Yubikey Neo with Offline Master Key and two Subkeys on the NEO. OpenKeychain crashes when signing. Decryption works perfectly.

**Comment by ghostroute** [comment]
I'm also seeing this (or at least, I'm seeing #1275 - not sure how to get a backtrace out of OpenKeychain).

k9 mail 5.005
OpenKeychain 3.2 (both from f-droid)

For me this happens with a key living completely on the yubikey (main key and two subkeys), generated using a host gpg 1.4.18. As this is a test key, I could PM you the secret key file. (And possibly hand over the yubikey if really necessary.)

Let me know how I can help debugging.

**Comment by Valodim** [comment]
does it crash before or after you touch the yubikey to the device?

Either way, the test key would be extremely helpful indeed, please send via mail when you have the time (look@my.amazin.horse)

**Comment by ghostroute** [comment]
Before. The first time it asked me which key to use for that outgoing email address.

Will do.

**Comment by bmalkow** [comment]
Reproduced on this [key](https://gist.github.com/bmalkow/960cd9028cafcb6eff96).
Have fun!

**Comment by segler-alex** [comment]
This bug is still there with 3.2.2
i have the same configuration, also detached master key

**Comment by Valodim** [comment]
sorry this is taking a while. we both don't have a lot of time at the moment, so we decided to release 3.2.2 with the fixes we had at that point, so this issue didn't make it into the milestone.

**Comment by dschuermann** [comment]
Please try again with version 3.3 that has just been released (will appear in some hours on Google Play and F-Droid). If this issue is still present, re-open this issue report.

**Comment by bmalkow** [comment]
Still problems:
When I try to sign: "signing subkey not found!"
When I try to encrypt: "Missing key for encryption: %s"

**Comment by dschuermann** [comment]
@bmalkow Are you sure that you tried 3.3?

**Comment by bmalkow** [comment]
Yes. I'm sure.
Double checked.

**Comment by dschuermann** [comment]
@bmalkow thanks. So Openkeychain doesn't crash but shows these errors now? At least it has improved in error handling...

**Comment by bmalkow** [comment]
K-9 ver 5.006

Yes: doesn't crash but show error message in Toast.
Hehe! Right: error handling is better :-)

**Comment by Valodim** [comment]
related to #1402, should be fixed by revoking and re-creating k9 account (or wait for next bugfix release)

**Comment by bmalkow** [comment]
Works perfect!
Thank you!

**Comment by steelman** [comment]
Android: 6.0.1
CyanogenMod: 13.0-20160205-NIGHTLY-peregrine
OpenKeychain: 3.9.2 (from F-Droid)
K9-Mail: 5.008 (F-Droid as well)

I am trying to send encrypted message, I've got public keys for both sender and recipient, no private key for sender though. I get the "Missing key for encryption: %s" message, meanwhile logcat shows

```
03-14 21:08:59.729  3888  5239 W Keychain: You are using a deprecated service which may lead to truncated data on return, please use IOpenPgpService2!
03-14 21:08:59.930 11761 11761 E k9      : OpenPGP Error ID:0
03-14 21:08:59.930 11761 11761 E k9      : OpenPGP Error Message:Missing key for encryption: %s
```

Both keys are valid and haven't expired. I can encrypt a message for those keys in OpenKeychain.

**Comment by dschuermann** [comment]
@steelman please open a new issue
