### ISSUE TITLE
Verify the keyserver URLs

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1202]
Check if keyserver urls work on add

from https://github.com/open-keychain/open-keychain/issues/1195#issuecomment-94056797:
> Tbh it is not really easy to verify the keyserver URLs. It would be much easier if the keyservers entered could instantly be verified by some kind of test routine.

**Comment by adithyaphilip** [comment]
This doesn't sound like a sustainable solution to me, but would running a search op for a key we know will exist (say, openpkg, the default query on https://hkps.pool.sks-keyservers.net/) work? This would have the downside on not working with private/internal keyservers (edge case?).

Alternatively, when a new keyserver is added, we could ask the user to enter a search for a key he is sure will exist, and if we get any results, we decide the keyserver works.

**Comment by qw3ry** [comment]
I do not know how the various protocols work, but I guess you'll get at least something like "no keys found" if you search on the server - this would at least make sure there is _something_ listening at the other side.
OTOH a search would be a workable solution as well in my opinion. Maybe search list of keys until a key is found? The list could be configured somewhere in the advanced settings?

**Comment by dschuermann** [comment]
Searching for a specific key doesn't seem like a viable solution.
Actually, I looked into http://tools.ietf.org/html/draft-shaw-openpgp-hkp-00 and tested some things, and I don't see any good solution to check if it is working keyserver.
Checking for "no keys found" is error prone when a keyserver is implemented differently and does not reply with this string, and yes there are servers that do that (see HkpKeyserver.java).
The problem is that the standard defines 404 as a result when no keys were found which is bad practice in my opinion.

Conclusively, I would only try to connect to the server with HttpURLConnection.connect() and catch the IOException. This should at least say: "No Internet connection _or_ no responding server on the other end".
