### ISSUE TITLE
Ask for passphrase on delete of secret keys from KeyListFragment

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1206]
Asking for the passphrase for delete/export in KeyView and on multi-export in KeyListFragment has already been implemented. Only passphrase asking for secret key delete operation in KeyListFragment is missing.

see https://github.com/open-keychain/open-keychain/issues/1045 for existing work.

**Comment by dschuermann** [comment]
No longer sure if we should do this.
What if you forget the passphrase of a key? You can not delete it...

**Comment by Valodim** [comment]
another thought is, a malicious person who has access to your phone can simply clear application data

**Comment by dschuermann** [comment]
K Let's move back with this decision and put up an FAQ entry that explains this with our thoughts...

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/commit/1ffcffae150806ceb970230f34dc53a49b6a0594 and https://github.com/open-keychain/open-keychain.github.io/commit/8f838a2e16be660952a83e3e3d9bf67bc5bb226f
