### ISSUE TITLE
Better handling of devices without NFC

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1211]
Currently just silently ignoring it in https://github.com/open-keychain/open-keychain/commit/555b0bf7573a9273bdd5e8c7870cabd8cd0e2186

Maybe throw an exception and handle this via a dialog that informs the user?

**Comment by rohands** [comment]
Not sure if this is what you wanted when you meant better handling?
![screenshot from 2015-09-20 22 36 34](https://cloud.githubusercontent.com/assets/8949393/9981917/5c5d5742-5fe8-11e5-9f4e-1504af55a8d8.png)
Also, if you could tell me what the context would be in that case for the builder?

**Comment by rohands** [comment]
I have included exception classes and tested it on Moto E(2nd Gen)

**Comment by dschuermann** [comment]
Please do a proper pull request with commits, I can't evaluate your changes based on a screenshot.

**Comment by rohands** [comment]
I've commited the changes, please check.

**Comment by dschuermann** [comment]
Please do a separate pull request for the NFC changes. Normally, each pull request should fix a different bug. You can make separate branches for this.

**Comment by rohands** [comment]
#1542 
This commit is dedicated to Better handling of devices without NFC

**Comment by rohands** [comment]
Hi, can someone kindly monitor this issue?
