### ISSUE TITLE
Can't import key with yubikey

### ISSUE THREAD

**Issue by bmalkow** [open-keychain/open-keychain#1215]
Can't import my own key with Yubikey (I have key with master key, so signature key isn't cert key).
It located key (by signature key) and during import I see 

    Fingerprint of fetched key didn't match expected!

Revision: b0c87e2372681d4f2de547b73d41b98d86bd564e

**Comment by Valodim** [comment]
Thanks for the report, I'll look into it

**Comment by Valodim** [comment]
91d500b20dba3d83085e4cca8836a4eaff24f113
