### ISSUE TITLE
Yubikey NFC operation

### ISSUE THREAD

**Issue by mikecardwell** [open-keychain/open-keychain#1217]
When using the Yubikey Neo as a smartcard with OpenKeychain, I assume it works as a normal smartcard? I.e, OpenKeychain never gets access to the raw key material at any point, it just passes the data to decrypt/sign over NFC to the Yubikey, which performs the crypto operations on-board, and then sends the result back? Am I right? I assumed this is how it works, but somebody who seems to have a decent level of knowledge about how NFC works, recently suggested that might not be possible with the NFC hardware in the Yubikey...

**Comment by Valodim** [comment]
Yes it is possible, and we delegate all crypto operations to the Yubikey as you expected. There is no way to obtain the private key material from a Yubikey, that is the whole point of having a hardware token in the first place :+1:

**Comment by mikecardwell** [comment]
Thanks for the confirmation. FWIW, my query was prompted by a comment somebody left on a blog post I wrote about OpenKeychain yesterday - https://grepular.com/An_NFC_PGP_SmartCard_For_Android

**Comment by Valodim** [comment]
Nice writeup, thanks! closing this issue now
