### ISSUE TITLE
Key shared via bluetooth is encoded in HTML

### ISSUE THREAD

**Issue by wfaulk** [open-keychain/open-keychain#1223]
When I tried to copy my key to my Mac via Bluetooth, the Mac received a file named "bluetooth_content_share.html" with contents that looked like this:

    <html>
    <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    </head>
    <body>
    -----BEGIN PGP PUBLIC KEY BLOCK-----<br>
    <br>
    gVMEc6PwyOL63szYP1idG6G2k93azdbrczHK5xDNAxCjYRdZDfYsTEO7s<a href="tel:118">118</a>uEhA<br>
    jzBKVNFQD/B00js83AG97sOHsboc39liyxG8PE4jgiuHIYYSmy2BAJoG8YDxvpuy<br>
    F6E5dBlUCYMDQXF9TqluF1aXDpenYKVr6W4Rckvu1fhB6CM4LIjBuDdQju5EIfJT<br>
    ⋮
    XgwNH97I58vNgTtwueVnM96w2AXGMrfQRMPluGm22GBeF1LxcAJAUiHjvE8VQomZ<br>
    jI/BG0y5OQqsq+GzTNkqtg<br>
    -----END PGP PUBLIC KEY BLOCK-----<br>
    </body>
    </html>

The data presented here is bogus, but the html structure is the same, except that the actual file had no newlines in it, not even a trailing one.  Note that any sequence of 3 or more decimal digits got converted to a "tel" url-scheme link.

I doubt that OpenKeychain is creating this HTML version; I'm guessing it probably needs to tell the Bluetooth sharing facility in Android not to mangle the file like this.

**Comment by wfaulk** [comment]
I've been trying to fix this, but nothing seems to work.  The relevant code seems to be [here](https://github.com/open-keychain/open-keychain/blob/91b774d22334b91c1867b867c515d1fcd31e34da/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyAdvShareFragment.java#L212-L222).

I've created a [question on StackOverflow](http://stackoverflow.com/q/29907030/147202) related to this bug.

**Comment by wfaulk** [comment]
[This change](https://github.com/wfaulk/open-keychain/commit/42d789e7f76e1cbee2194322669ee2dae747d5fa) works, but at the cost of creating temporary files that will have to be cleaned up.

**Comment by dschuermann** [comment]
see my comment here: https://github.com/open-keychain/open-keychain/pull/1230#issuecomment-97247545

**Comment by wfaulk** [comment]
This fix was implemented using the `EXTRA_REPLACEMENT_EXTRAS` method you suggested in #1230.
