### ISSUE TITLE
Link to search from AutoTextComplete on empty result set

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1228]

**Comment by advaita13** [comment]
Isn't there a search button just beside the AutoCompleteTextView field?

**Comment by daquexian** [comment]
Hi :) Does this issue still need work? It seems that there is already a search button on empty result set.

**Comment by Valodim** [comment]
I think this issue refers to what was attempted in #1765, i.e. a link to search from the dropdown that appears in the "Encrypt to" field.

Thinking about this now, I'm not so sure that there is a nice way to do this, breaking out into a full dialog from a dropdown seems messy. Thoughts @dschuermann ?

**Comment by dschuermann** [comment]
I am no longer sure if this is an important issue worth pursuing. We should focus on different aspects in OpenKeychain. I will close this for now. If you think otherwise @Valodim please re-open.
