### ISSUE TITLE
Tutorial for openkeychain.org

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1232]
I would like to have a HowTo on our website openkeychain.org. It has also been requested by Guardianproject several times in the past (they will then link to us)

See for examples: https://guardianproject.info/howto

You can find the tutorial code here:
https://github.com/guardianproject/tutorial-orbot-orweb
https://github.com/guardianproject/Gibberbot-Tutorial

**Comment by nuntius35** [comment]
@dschuermann I have done something: https://github.com/nuntius35/openkeychain-tutorial 

I am sorry that it is not very professional.

**Comment by dschuermann** [comment]
@nuntius35 Already a great start.

I think we should strip some screens and change some texts, but I will do that.

Could you provide me with the following changes:
* 06_setup_create.png : Please make this screenshot again, but with the "Synchronize with the cloud" checkbox enabled
* 09_export_key.png : Please make this screenshot again, but with the "Also export secret keys" checkbox enabled
* Step 6 misses a step how to copy the public key into the email.

For verification via QR Code, fingerprint etc we should add a different tutorial.

**Comment by dschuermann** [comment]
Also, @Valodim and I were confused by the navigation. We should better switch to a linear navigation with only right and left without down/up.

**Comment by nuntius35** [comment]
@dschuermann Thanks for your feedback. I fixed the screenshots and added some more screeshots to show how to share the key with K-9 from whitin OpenKeychain. (When I did the screenshots for the first time, I didn't miss this step but I actually pasted the key from the export.asc file. But you are right, that's not a good way for a beginner.)

Also I linearized the layout.

There's still too much text, but you said you will remove some of it.

**Comment by dschuermann** [comment]
@nuntius35 Tutorial is now here: https://github.com/open-keychain/open-keychain.github.io/tree/master/howto
I simplified some things and changed the text. I am okay with this version now. We would really like to have a simpler configuration and export methods, but that's the current state of OpenKeychain...
It will definitely help people getting started.

**Comment by Valodim** [comment]
"We recommend to use F-Droid as an alternative to Google Play." I'm not sure we need to explicitly advertise F-Droid in this tutorial, other than mention we're available there. This will make people feel uninformed for using the play store (it is not recommended by a crypto tutorial, after all).

**Comment by dschuermann** [comment]
done

**Comment by Valodim** [comment]
I like the Rejewski and Turing touch, but can we use a neutral domain name rather than posteo.de?

typo in step 3: "safe place"
sentence on next screen as double "also" (and "save place" again)

is "share with" really the primary way we want people to encrypt? just typing the address as usual should feel a lot more familiar to the user

last step should say "de"cryption is automatic

**Comment by Valodim** [comment]
oh wait the "share with" is actually meant to share the key... huummmm if I didn't understand that from the description, I'm not sure the user will. I thought these were meant to be the steps to simply send an encrypted e-mail.

**Comment by dschuermann** [comment]
Yeah, we should use example.com. @nuntius35 can you provide new Screenshots? (Hope this is the last Version)

**Comment by nuntius35** [comment]
I will provide screenshots with example.com tomorrow. 

@Valodim I am also not too happy with the "share with" dialog but the problem is that you cannot tell Adele to download your key from a keyserver but you have to find some way to include it in your mail.

@dschuermann I like your simplifications of the text.

**Comment by dschuermann** [comment]
@nuntius35 Awesome!

@nuntius35 @Valodim I fixed the minor issues you mentioned Valodim, and changed some texts again (especially the [start](http://www.openkeychain.org/howto/#/) and [end](http://www.openkeychain.org/howto/#/theend). My personal opinion is that we can release this after getting the updated screenshots.

**Comment by dschuermann** [comment]
Ok guys,
I am fine with the current version of this HowTo at http://www.openkeychain.org/howto
Any objections against publishing it more prominently?
@Valodim

**Comment by martinjdavidson** [comment]
Spelling (in the sub-header).

On June 10, 2015 7:05:35 PM EDT, "Dominik Schürmann" <notifications@github.com> wrote:
>Ok guys,
>I am fine with the current version of this HowTo at
>http://www.openkeychain.org/howto
>Any objections against publishing it more prominently?
>@Valodim 
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/1232#issuecomment-110942060

——Martin J… D… <mjd@alum.rpi.edu>

**Comment by dschuermann** [comment]
@martinjdavidson Thanks for your feedback. Can you be more specific? I don't see a spelling mistake. Do you mean the first slide?

**Comment by martinjdavidson** [comment]
The sixth (6th) screen heading, "A friendly welcome screen"
has a subheading "Just press Creaty My Key." (I attached a screen image.)
Thought "Just press <…>Create My Key<…>" was intended.

**Comment by dschuermann** [comment]
@martinjdavidson Thanks, done.

**Comment by dschuermann** [comment]
now on http://www.openkeychain.org/
