### ISSUE TITLE
OpenKeyChain crashes while decrypting messages

### ISSUE THREAD

**Issue by vanitasvitae** [open-keychain/open-keychain#1236]
Hi!
I have a problem with openkeychain on my nexus 5. I use K9 with openkeychain, but when I try to decrypt a message, openkeychain crashes twice after entering the password.
It also crashes twice if I copy some encrypted text and use the function "decrypt from clipboard" (crashing twice means there are two popups saying openkeychain stopped working).
Also I found that openkeychain may not recognize encrypted messages when I copy the the first paragraph of an encrypted email. However it works if I start copying from the first "-". 
This wont work:
"
-----BEGIN..."
This will work:
"-----BEGIN..."

Im using openkeychain v3.1.2 from fdroid.
If I use APG to decrypt the same message, everything works.
How can I help you? Do you need more information?

**Comment by vanitasvitae** [comment]
PS: Im on Mahdi ROM Android 4.4.4

**Comment by vanitasvitae** [comment]
edit: I was wrong abot the decryption from clipboard. Its working, but openkeychain still crashes without closing the app. Decrypting from mail still doesnt work.

**Comment by dschuermann** [comment]
This bug is on hold until we publish a new version of OpenKeychain, please stay tuned. If you could use Google Play, follow http://www.openkeychain.org/help/ to get a beta version and report back if this fixes your problem.

**Comment by vanitasvitae** [comment]
Unfortunately I don't use Google Play, but I will wait for the next release ;)

**Comment by vanitasvitae** [comment]
I think the Bug is gone in tge newest release. Everything works now. Thanks for fixing ;)
