### ISSUE TITLE
bad NFC response code: 6982

### ISSUE THREAD

**Issue by allrandomdude** [open-keychain/open-keychain#1243]
Hi

My old YubyKey was affected by this issue: https://developers.yubico.com/ykneo-openpgp/SecurityAdvisory%202015-04-14.html (version 1.0.8). 
Now i have a new YubyKey without this problem (version 1.0.10).
But the new key does not work with OpenKeyChain/NFC/Android?!?

The error message is: bad NFC response code: 6982

______________________________________________
![bad_nfc_response_code-6982](https://cloud.githubusercontent.com/assets/7827495/7457932/65902b66-f290-11e4-80e9-ab79ee9be6e5.gif)

**Comment by dschuermann** [comment]
This is already fixed in our development branch, please wait until we publish a new OpenKeychain version.

**Comment by allrandomdude** [comment]
ok, thx

**Comment by dschuermann** [comment]
More information here: https://github.com/open-keychain/open-keychain/pull/1200
