### ISSUE TITLE
error handling in decrypt fragment

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1244]
After the recent change in decrypt ui (96853a15ee535860fd789bc5be4979f2205e959c), error handling is broken and needs to be redone. From a quick glance, the TextDecryptFragment shows a snackbar for success/error, the FileDecryptFragment doesn't.

The snackbar, and a case for !result.success(), should all be in loadVerifyResult in DecryptFragment

**Comment by dschuermann** [comment]
This should be fixed now, please re-test
