### ISSUE TITLE
wrong key for decryption/signing verify

### ISSUE THREAD

**Issue by HacKanCuBa** [open-keychain/open-keychain#1250]
It works fine for encrypting, but decryption / signing verify always fails because it looks in my keychain for a specific subkey and doesn't realise its a subkey!  So it always says that the key hasn't been found.

Android 4.4.2 with up-to-date open-keychain.

Checked against my thunderbird+enigmail to see if everything was ok, and it was.

**Comment by dschuermann** [comment]
Are you using a YubiKey? Can you tell us your key fingerprint? How exactly is your key composed?

**Comment by HacKanCuBa** [comment]
Hello! Thanks for replying, this bug seems to be fixed now, somehow... Two updates happened since, and now works.
Cheers!
