### ISSUE TITLE
Always show YubiKey card view

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1252]
The YubiKey card view should be always visible for keys bound to YubiKeys

**Comment by Valodim** [comment]
This is not so simple actually. The Yubikey serial is stored in the s2k dummy data of the secret key, but it is not available from the content provider at this point, and neither do we store other information from the yubikey such as owner name. This reduces available information for a yubikey card to pretty much only its presence, not what is usually shown.

**Comment by Valodim** [comment]
with the key status card, this is no longer necessary
