### ISSUE TITLE
Bad NFC response code:  6982

### ISSUE THREAD

**Issue by mohlerm** [open-keychain/open-keychain#1253]
Hi,

I receiving a replacement key from yubico because of that vulnerability: https://developers.yubico.com/ykneo-openpgp/SecurityAdvisory%202015-04-14.html running their OpenPGP applet v.1.0.10.
The new key can't be used to encrypt anymore, decrypting works though.
It says: "bad nfc response code: 6982" as soon as my key touches the back of the phone (Sony Z3C).

Same error happens on my Nexus 7, I already tried reimporting the keys.
Encrypting/decrypting via the Yubikey works on my computer flawlessly.

Thanks

**Comment by dschuermann** [comment]
See https://github.com/open-keychain/open-keychain/issues/1243
