### ISSUE TITLE
handling of unknown keys in decryptactivity

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1254]
also introduced in 96853a15ee535860fd789bc5be4979f2205e959c, the handling of unknown keys is bogus.

if a key is not known, we can't check if a signature is valid. in the ui, this shows up as "signed by unknown key". once a lookup is done this data is immediately refreshed, and shows "signature ok" but *without* checking again if the signature is actually valid.

**Comment by dschuermann** [comment]
@Valodim Is this still true?

**Comment by Valodim** [comment]
hmmm no, the sign/decrypt status in DecryptActivity is not updated on a key refresh. this had too many problems.

**Comment by Valodim** [comment]
no longer true but not truly fixed either. see #1564
