### ISSUE TITLE
Enhancement: On-Card Key Generation

### ISSUE THREAD

**Issue by josecastillo** [open-keychain/open-keychain#1256]
Opening this issue because I want to implement this, but I'm unsure whether it's desired functionality. As it stands currently, users can generate an OpenPGP identity within OpenKeychain, but if they want to use a Yubikey or NFC smart card, they must first configure it on a PC. I would like to be able to support people generating their keys securely on a Yubikey or a smart card, using nothing but OpenKeychain. I've started a branch to implement the commands necessary to do this on the card, but have run into some challenges understanding how I can fit these changes into the broader application. 

https://github.com/open-keychain/open-keychain/compare/development...josecastillo:oncardkeygen

On-card key generation works by issuing a GENERATE ASYMMETRIC KEYPAIR command for the correct slot (sign/decrypt/auth). The card generates this key, and then returns TLV data with the public exponent and modulus. From there, OpenKeychain would craft a public key packet with this data, and go about making the certification and subkey binding signatures with the usual nfcCalculateSignature commands. Finally, OpenKeychain would need to set the fingerprint and key generation timestamps on the card, and optionally change the user's PINs from the default. So far I've added commands to handle all of these tasks. 

The challenge is in incorporating this into the broader architecture of identity generation in OpenKeychain. I had imagined adding a parameter to the SubkeyAdd constructor, indicating whether the key should be generated on the card, and then firing off the required NFC operations in PgpKeyOperation. But looking into it further, the PgpKeyOperation creates the key using JcaPGPKeyPair, which always seems to want a private key. With on-card key generation, we won't have that, because the card never discloses private key data. 

Anyway, apologies for the wall of text, but after looking into this for a while I'm wondering whether this is even an enhancement that you would like to see in OpenKeychain. Personally I think it would be a huge usability win — especially for NFC-only tokens that cannot be easily configured on a PC.

**Comment by Valodim** [comment]
This is on our agenda, albeit not with a very high priority (#875). It is definitely a desirable enhancement, if you get it into a working state we will merge for sure.

Have you given just sending the command a shot? Is it reasonably usable via NFC, in terms of required time for key generation etc?

The data flow is indeed complicated for this issue, and I have no advice from the top of my head. I will try to think about this some more when I have the time and come back with a better answer.

**Comment by josecastillo** [comment]
Oh awesome — I hadn't seen that item, sorry for not searching more thoroughly. Good to know that it's something that's on the radar screen. 

I have tested the commands with both a Yubikey and an NFC smart card; there's no way around it, key generation is SLOW. It's also very unpredictable, ranging from as short as 15 seconds to as long as a minute-plus; the average is around 30-35 seconds per key. To be usable, it would definitely require some specific instructions to the user, like "Lay your [smartphone | tablet] on top of the token until key generation is complete". 

I will continue to work at this, but your comment from September does sound right: this change would absolutely mess with the key editing data flow. Still if you do have thoughts about it in the future, I'd welcome any guidance!

**Comment by Valodim** [comment]
30 seconds is a huge deal.... hmm. did you try how long import of a secret key to the yubikey takes for comparison?

**Comment by josecastillo** [comment]
I'll add commands for this and see how it works. It'll almost certainly be a lot faster since it's just a couple of PUT DATA calls. And it would work with the existing processes for key generation. I'll close this issue for now and follow up in #875.
