### ISSUE TITLE
hide scrollbar 

### ISSUE THREAD

**Issue by agrajaghh** [open-keychain/open-keychain#1257]
Current the scrollbar is shown even if there are just a few elements displayed: ![tmp_18985-openkeychain-485389994](https://cloud.githubusercontent.com/assets/5296073/7512324/82d9319a-f4ac-11e4-8a36-b198c7f32ace.jpg)

I think it would be best to hide the scrollbar when it's not necessary. The standard Android scrollbar is also hidden some seconds after scrolling. 

Btw, congratulations for the new version! It looks really nice!

**Comment by indrora** [comment]
This is by design, as the Android contacts ux does the same thing

**Comment by agrajaghh** [comment]
The scrollbar is still too intrusive IMHO and it feels weird to be able to move the scrollbar when there is just one key...

**Comment by dschuermann** [comment]
Yeah, for a future release we want to get the design of Android's Contacts app, which is a smaller scrollbar with these "bubbles" to indicate the character section. This somehow depends on https://github.com/open-keychain/open-keychain/issues/1052 and related issues.
Thus, it was low priority to fix the scrollbar using the old ListView.

**Comment by petmue** [comment]
Now it has been almost a year since this topic was closed. Have you wasted some thoughts about the scrollbar in the meantime? 
I stumbled on it recently and it feels like you have a stair though there's no second floor.

**Comment by Valodim** [comment]
This issue has very low priority for us. It is not simple, and brings little to the table while we have heaps of serious issues to work on. If anyone feels strongly about this, pull requests are welcome.
