### ISSUE TITLE
Cannot modify keys (java.lang.AssertionError: Unhandled SecretKeyType (should not happen))

### ISSUE THREAD

**Issue by abs7ERGO** [open-keychain/open-keychain#1259]
Since the latest materials design release (3.2), the app crashes every single time I try to edit or update any of my keys.

**Comment by abs7ERGO** [comment]
This may be part of the reason: most of my keys are imported from file.

**Comment by Valodim** [comment]
can you tell me the fingerprint of your key? if you say it happens during key update, maybe I can find something in your key.

**Comment by abs7ERGO** [comment]
Unfortunately, I can't do that.

Looking at the stack trace in the report (I've already submitted several via Google), I get the following:

java.lang.AssertionError: Unhandled SecretKeyType (should not happen)

If there's something else I can provide beyond that, let me know.

**Comment by Valodim** [comment]
this is likely the same issue as #1262. we have some data on that one so we should be able to handle this for the next bugfix release and see if it fixes your problem. thanks for reporting!

**Comment by dschuermann** [comment]
I don't see this bug anymore on 3.4.1 in Google Play's developer console. Anyone still having this problem?
