### ISSUE TITLE
"Decryption of messages with Conversations fails"

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1269]
G Play review:
"Was god.. Now decryption of messages with Conversations fails... Please fix this!"

I have tested this and it worked for me. We should investigate.

**Comment by dschuermann** [comment]
Maybe this bug is also related to https://github.com/open-keychain/open-keychain/issues/1268

**Comment by mar-v-in** [comment]
I guess this might be only due to Conversations not being restarted after the update which is (at least sometimes) required as service connection is lost. Suggest the user to swipe away conversations from the recent screen and check back if decryption works after opening it again

**Comment by Valodim** [comment]
is this one still valid?
