### ISSUE TITLE
Keychain may cause k9 to hang if files are shared encryptedly

### ISSUE THREAD

**Issue by balert** [open-keychain/open-keychain#1271]
Reproduce:
- From gallery app share photo to k9 and select encyption

What happens: 
- k9 activity on send disappears, phone goes back to gallery, k9 says it would send message but Keychain passphrase activity is not shown.
- (attachment is not encrypted, I assume this happens on purpose, i.e. is not implemented yet?!)

How to workaround: 
- kill k9 hard, and resend message from outbox

**Comment by dschuermann** [comment]
K-9 Mail related bug reports are now tracked at https://github.com/k9mail/k-9/milestones/PGP/MIME
If no corresponding bug report exist under https://github.com/k9mail/k-9/milestones/PGP/MIME, please open a new one.

Also read our announcement at https://www.openkeychain.org/k-9/
