### ISSUE TITLE
Yubikey NEO PIN is not cached

### ISSUE THREAD

**Issue by deermo** [open-keychain/open-keychain#1272]
Just updated to OpenKeychain 3.2 on an CM 12.1 Nightly Android using K9-Mail. Since then, the PIN for the Yubikey is not cached anymore (However, the notification claims that the password is cached). Happens when decrypting. The setting to save the PIN for subkeys individually does not alter this behavior. 

Happy to provide follow-up information, just let me know. And, BTW: Great app! Enables safe communication on the phone! Thanks!

**Comment by mikecardwell** [comment]
Same thing happened to me. I'm on CM 12, Android 5.0.2 on a OnePlus One. Before the last update, key caching worked fine.

**Comment by Valodim** [comment]
this feature was lost in a rewrite and generalization of yubikey control flow. reintroduced in 007bbdda2bd310d7141a4d1c2125c781bf8aabef :+1:
