### ISSUE TITLE
Feature Request: Decrypt to Text Viewer

### ISSUE THREAD

**Issue by ReubenM** [open-keychain/open-keychain#1274]
Request for option to decode to a built in text viewer. Lots of times I just need to copy text from an encrypted file to the clipboard without actually saving the decrypted file. Decrypting the file to a text buffer, and then discarding it from memory once I'm done viewing it would be very handy.

Maybe put pragmatic limits on the size (and possibly type) of a file to decrypt to a text viewer.

**Comment by Valodim** [comment]
the decrypt screen is scheduled for a rewrite at some point anyways, this feature will surely be included

**Comment by Valodim** [comment]
see #1297
