### ISSUE TITLE
Signing Mail with PGP on Yubikey Neo and K9-mail causes Open Keychain to crash

### ISSUE THREAD

**Issue by stevesbrain** [open-keychain/open-keychain#1275]
Version of software used:
K-9 Mail: 5.005
Android: 5.1 (Nexus 5, 3.4.0-franco.Kernel, Pure White LMY47D 3-11-2015 ROM)
OpenKeychain: 3.2.1 (32100)

Problem:
Composing an email in K9-mail, attempting to "Sign" the email via a PGP key stored on a Yubikey Neo (which works absolutely fine for decrypting in K9-mail, and GNU Password Store). Ticking "Sign" works fine, typing email works fine, but as soon as you hit "Send" (which should then prompt for key details), the message "Unfortunately, OpenKeychain has stopped" appears.

I would be glad to fetch some logs for OpenKeychain - just let me know where to find them :)

**Comment by Valodim** [comment]
This is likely the same as #1201, where a stack trace is available. we'll try to have a bugfix release in a couple days, see if that fixes your problem. thanks for reporting :+1:

**Comment by hyper3xpl0iter** [comment]
Can confirm that I too am have the same issue both on my Nexus 5 (5.1) and Nexus 7 (4,4,4)

**Comment by stevesbrain** [comment]
Appreciate the information :) I'll look forward to the update :D
