### ISSUE TITLE
subkeys stored on yubikey confuse ViewKeyActivity

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1280]
reported in irc: if the fingerprints from the yubikey refer to a subkey rather than a master key, the import works fine but ViewKeyActivity gets confused and shows an empty screen.

http://i.imgur.com/04w4mgi.png

**Comment by hyper3xpl0iter** [comment]
I can confirm that I'm having the same issue.

**Comment by Valodim** [comment]
partial fix in a81474b7a5b179d29776f2c652609d13dec74536, the activity now works correctly. binding the yubike does *not* work correctly yet.

**Comment by Valodim** [comment]
updated promote key operation in c1e7fcf02455b7a03c86bb78efe39684396c15f8, it now specifically marks those keys as 'divert to card' which are available on the yubikey, but identifes the key by the master key id of the displayed public key

**Comment by Valodim** [comment]
fix confirmed and rebased on master
