### ISSUE TITLE
open-keychain hangs after imputting PIN for Yubikey and touching the phone with it

### ISSUE THREAD

**Issue by mezinster** [open-keychain/open-keychain#1286]
Looks like the YubiKey can't be read or some issue happens while reading it...

How can i help you to track that down ?

Cyanogenmod 10.2
Google Nexus 4
Openkeychain 3.2.1

**Comment by dschuermann** [comment]
Please try again with version 3.3 that has just been released (will appear in some hours on Google Play and F-Droid). If this issue is still present, re-open this issue report.

**Comment by mezinster** [comment]
Reproduced on 3.3.

Bug report sent from mezinster@gmail.com about 40 mins ago

**Comment by dschuermann** [comment]
Please try to reproduce with 3.4.1 and report back. I made improved the error handling in this version.

**Comment by mezinster** [comment]
3.4.1 "Keep the Yubikey on the Back" and nothing happens next.... 
What is the maximum time for "encrypt and sign" operation?

**Comment by mezinster** [comment]
![screenshot_2015-07-15-20-36-43](https://cloud.githubusercontent.com/assets/10500786/8705350/afbc56e0-2b31-11e5-9f09-58633ef61eb1.png)
![screenshot_2015-07-15-20-37-14](https://cloud.githubusercontent.com/assets/10500786/8705354/b371d346-2b31-11e5-84a2-6c4b28706d03.png)

**Comment by mezinster** [comment]
I was holding the key at the back approx for 40 seconds

**Comment by mezinster** [comment]
Relates to 
"yubikey decrypt taking minutes #1525"

Workaround is to turn On and Off NFC support in Android settings. 
(in 70% of cases that helps from the first attempt)

It's a pity, but that has to be done each time when 
trying to do something with a help of your Yubikey
