### ISSUE TITLE
Q: Is OpenKeychain PGP/SMIME ready?

### ISSUE THREAD

**Issue by Diapolo** [open-keychain/open-keychain#1287]
This is likely a question which is easy to answer for the devs, but I just want to be sure ;). I'm using K9 with OpenKeychain and received a PGP/SMIME mail, which doesn't work (it's not displayed, just 2 attachments I can't open). So is K9 limited in displaying PGP/SMIME mails or is OpenKeychain not ready for the PGP/SMIME standard (in comparison to Inline-PGP which is working of course)?

**Comment by dschuermann** [comment]
OpenKeychain 3.2 includes API calls, such as verification of detached signatures, that are required for PGP/MIME. We don't do MIME parsing in OpenKeychain; this is an explicit design decision.

So, yes OpenKeychain is ready, more work is needed in K-9 Mail to improve its MIME parsing and decryption/verification using these API calls.
