### ISSUE TITLE
GSoC 2015: Tor/Proxy Support

### ISSUE THREAD

**Issue by adithyaphilip** [open-keychain/open-keychain#1289]
We'd like to introduce Tor(via Orbot)/Proxy support, for privacy while connecting to keyservers.
https://github.com/guardianproject/NetCipher looks like it can handle both.

NetCipher comes with OrbotHelper, a class which checks for the existence of Orbot, whether it's been enabled, etc.
We would use it to perform these checks when:
a) The user first selects the Tor proxying option - we check if Orbot is installed, and ask him to install it otherwise.
b) The user has enabled Tor suport, but Orbot is not installed/not enabled when we attempt a background/manual key sync/key import.

We would also require a new preference - Proxy Support, allowing the user to choose between Tor or another proxy server. The menu could have three radio buttons:
* None
* Use Tor
* Use other proxy (with EditText for entering proxy host with port)

**Comment by adithyaphilip** [comment]
Confirmed that NetCipher is used with Orweb (https://github.com/guardianproject/Orweb).

**Comment by dschuermann** [comment]
Closing this one because you did it

**Comment by Valodim** [comment]
:tada:
