### ISSUE TITLE
"Manage my keys" can only create keys

### ISSUE THREAD

**Issue by Yoshi64Bit** [open-keychain/open-keychain#1294]
menu/key_list.xml:

    <item
        android:id="@+id/menu_key_list_create"
        android:title="@string/menu_manage_keys"
        app:showAsAction="never" />

This menu items got the title "Manage my keys" but it launchs (KeyListFragment.java):

    private void createKey() {
        Intent intent = new Intent(getActivity(), CreateKeyActivity.class);
        startActivityForResult(intent, REQUEST_ACTION);
    }

This Activity can only create keys. As a result, this menu item should be renamed to something like "create a key" and/ or should be moved to to FAB.

**Comment by dschuermann** [comment]
It also imports keys, and allows to use yubikeys. The internal naming does not really reflect its current status. The fab is only used for the - more often executed - operation of adding public keys
