### ISSUE TITLE
Can't sign files

### ISSUE THREAD

**Issue by Yoshi64Bit** [open-keychain/open-keychain#1295]
It is possible to sign a text by leaving the receiver field empty, but at the file encryption screen this results in a message which says that at least one key should be chosen for encryption.

**Comment by Valodim** [comment]
this is intentional. signing a file would only work as a detached signature, which is a) completely different from an encrypt+sign operation in the same dialog, and b) we have no verify operation for at this point.

**Comment by dschuermann** [comment]
This is now part of https://github.com/open-keychain/open-keychain/issues/1297
