### ISSUE TITLE
File decryption UI

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1297]
This was a GSoC 2015 task that has not been assigned. If someone wants to work on it, we are happy to guide them through the process of implementing this. It is also possible to do small subsets of this task, we are happy for every contribution!

 - [x] **General decryption UI**
Currently the file decryption screen in OpenKeychain only allows to decrypt one file at a time and only allows saving of decrypted files into the filesystem. While this is okay for simple scenarios. The decryption process could result in many files being decrypted. Either when multiple files are shared together using Android's [ACTION_SEND_MULTIPLE](http://developer.android.com/training/sharing/receive.html#handling-content) or when the OpenPGP data structure contains many parts. Thus, the screen should be extended for multiple files. A list of files should be displayed like done in the encryption screen that with the options save/open per file item. To get the right content type and decrypt the filename the new internal DECRYPT_METADATA functionality of OpenKeychain should be used. The real payload should be decrypted when save/open is clicked. Furthermore the recipient's key user id should be displayed inside the item.

 - [ ] **Hidden receipients**
A related problem are [hidden recipients](https://github.com/open-keychain/open-keychain/issues/626): The OpenPGP standard allows to prevent the disclosure for whom a file/message is encrypted for. This feature has already been implemented for encrypt but is currently commented out. It must be implemented for decryption (try decryption with all keys) to be done.

 - [ ] **Detached signatures**
Also "detached signatures" should be supported by the new decryption screens. An internal method has already been done during the work on PGP/MIME. This can be used, but needs a carefully designed UI. This method also needs a UI for the encrypt screen.

 - [ ] **Full error overlay**
If a key is not valid anymore a big overlay is shown in decrypt text UI. This should also be implemented for a new file decryption UI. See https://github.com/open-keychain/open-keychain/commit/0d6d4653b43fcf1389b470afd7364854505d96c2

Issues included in this task:
https://github.com/open-keychain/open-keychain/issues/731
https://github.com/open-keychain/open-keychain/issues/557
https://github.com/open-keychain/open-keychain/issues/950
https://github.com/open-keychain/open-keychain/issues/626

**Comment by Valodim** [comment]
related implementation detail: display of the file structure and actual decryption of the files are separate cryptographic operations. the DecryptFragment should internally cache the CryptoInputParcel, to make sure the user doesn't have to input his password or yubikey twice for what is perceived as a single operation in the ui.

**Comment by crosser** [comment]
I was going to open a feature request about the file decryption UI but now I'd just leave it as a comment here:

The screen shown after decryption (and encryption?) uses largely the same layout as the screen on which you enter the file do decrypt. This is confusing, because it is not instantly apparent that the job was done. After-decryption screen should clearly tell the user where the decrypted file is stored, perhaps suggest what the user can do with it (browse etc.), and _should not_ have the "Decrypt, verify, and save file" at the bottom.

**Comment by dschuermann** [comment]
This issue has again be externalized into seperate ones.
