### ISSUE TITLE
Passphrase Alternatives

### ISSUE THREAD

**Issue by Hiperzone** [open-keychain/open-keychain#1299]
Currently OpenKeyChain only supports one kind of key unlock method which is the Passphrase. By taking advantage of new security features currently present in many smartphones, OpenKeyChain will allow users to choose new security options which will be available by displaying a Key Unlocking Method Wizard to the user.

Security methods may range from the already known Passphrase method to NFC, Fingerprint, QRCode, LockPattern  or combinations of two security methods.

A complete redesign of the Create Key UI flow will be done to accommodate the new changes with a new UI design.
Implementation of Android UI components for each unlock method so they are reusable for all situations.

**Comment by thetaeo** [comment]
It would be interesting to work on fingerprint sensors using the Android 6.0 API (I have a Nexus 5X for testing, and have gotten used to the extremely painless unlock procedure). It appears that the API is based off of creating a private key, then requiring a fingerprint to perform operations with it (see [this sample](https://github.com/googlesamples/android-FingerprintDialog/blob/master/Application/src/main/java/com/example/android/fingerprintdialog/MainActivity.java#L103-L138)). I would be willing to work on this.

**Comment by dschuermann** [comment]
@thetaeo Our new plans are to replace individual key protection with a full app lock mechanism with sqlcipher. Thus, before adding protection mechanisms, we need to implement app lock. Please read and comment at https://github.com/open-keychain/open-keychain/issues/1541 for more information.

**Comment by Valodim** [comment]
Superseded by #1541
