### ISSUE TITLE
PGP/MIME API

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#130]
As per discussed on guardian-dev mailinglist:
- namespace: ``org.openintents.openpgp.mime``
- k9mail implementation (old pull request: see k9mail/k-9#4)

**Comment by Ph1b** [comment]
Any news on this?

**Comment by dschuermann** [comment]
@Ph1b yes, we (Valodim, cketti, and I) are working on it ;) still takes time...

**Comment by dschuermann** [comment]
Closed because API is done, rest needs to be implemented in K9
