### ISSUE TITLE
NFC Error: Bad NFC Response code: 6985

### ISSUE THREAD

**Issue by nlcampos** [open-keychain/open-keychain#1301]
Hi there!!!

  I had received my new Yubikey 1.0.10 in substitution of previous one 1.0.8.
  1.0.8 works fine, but it has a security issue and mustn't be used. With 1.0.10 I receive the error - NFC Error: Bad NFC Response code: 6985 as can be see below.

![screenshot_2015-05-25-16-53-14](https://cloud.githubusercontent.com/assets/12600491/7801896/a6eaed80-0302-11e5-90c2-933eb3e70890.png)

  Open-keychain version is 3.2.2 (32200)
  Thanks!!

Kind regards,

Nelson Campos, PMP
GPG id 67C63C6C

**Comment by Valodim** [comment]
Huh. I would have expected #1200 to fix this one. No time to look into it in detail at the moment, but we should definitely get this fixed if it breaks compatibility with new yubikeys.

@josecastillo Any thoughts?

**Comment by nlcampos** [comment]
@Valodim if you need some tests, please, let me know.

Regards,

Nelson Campos, PMP
GPG id 67C63C6C

**Comment by josecastillo** [comment]
Is this happening when you attempt to sign or decrypt? Are you using the default PIN option?

**Comment by nlcampos** [comment]
@josecastillo signing the text, but I have figured out that my key don't have signature key:

mac-leah:~ nlcampos$ gpg2 --card-status
Application ID ...: D2760001240102000006036319700000
Version ..........: 2.0
Manufacturer .....: Yubico
Serial number ....: 03631970
Name of cardholder: Nelson Campos
Language prefs ...: en
Sex ..............: male
URL of public key : https://dl.dropboxusercontent.com/u/17367785/67C63C6C_public.key
Login data .......: [not set]
Signature PIN ....: forced
Key attributes ...: 2048R 2048R 2048R
Max. PIN lengths .: 127 127 127
PIN retry counter : 3 3 3
Signature counter : 0
Signature key ....: [none]
Encryption key....: 2B78 26DA 2F8A 926F 86D3  1674 59DB BD55 5D9C 13FF
      created ....: 2015-05-13 02:37:41
Authentication key: 3AE2 5075 7E1F 362C 4061  9FC5 14FF 5E49 BFD7 45D1
      created ....: 2015-05-13 02:41:49
General key info..: pub  2048R/5D9C13FF 2015-05-13 Nelson Campos <nlcampos@gmail.com>
sec   2048R/67C63C6C  created: 2015-05-11  expires: 2019-05-11
ssb>  2048R/5D9C13FF  created: 2015-05-13  expires: 2019-05-12
                      card-no: 0006 03631970
ssb>  2048R/6F6E5861  created: 2015-05-13  expires: never     
                      card-no: 0006 03631970
ssb>  2048R/BFD745D1  created: 2015-05-13  expires: never     
                      card-no: 0006 03631970

  Is it the problem?

Regards,

Nelson Campos, PMP
GPG id 67C63C6C

**Comment by josecastillo** [comment]
Yes, this explains the message. If your signature key is not initialized on the Yubikey, it will respond with the "Conditions not satisfied" status, which is 6985. To sign with OpenKeychain, you'll need to either follow steps to move your master key to the Yubikey, or add a signing subkey to put onto the Yubikey, depending on your needs. 

Still, this is expected behavior from OpenKeychain; your Yubikey is correctly reporting an error status, which OpenKeychain is relaying in the UI.

**Comment by nlcampos** [comment]
@josecastillo thanks for the explanation. I'm closing this issue, ok?

Kind regards,

Nelson Campos, PMP
GPG id 67C63C6C

**Comment by Valodim** [comment]
Hmm, might be worth giving better error messages if we know them for specific states

**Comment by josecastillo** [comment]
@Valodim Totally agree. We could throw a more specific IOException in the sign / decrypt methods, although it's technically not really an IO issue. Also, all these error messages will need to be localized eventually. 

Would it make sense to create a class of exception to encapsulate these card error conditions (there's a list of them on page 51 of the spec), and then determine the appropriate error message in ```handleNfcError```? I can work on that if you think this direction makes sense.

**Comment by dschuermann** [comment]
@josecastillo https://github.com/open-keychain/open-keychain/issues/1303
