### ISSUE TITLE
Loop at key-confirmation with yubikey.

### ISSUE THREAD

**Issue by pingu8007** [open-keychain/open-keychain#1302]
When I try to confirm a key by fingerprint with yubikey neo, it repeat asking for yubikey's PIN and the key never truely certified. It occurred even when the option to use default PIN is checked, just become ask once rather than twice. I haven't tried to confirm keys by QR code but I guess the result will be the same.

I have another yubikey to play around, so if there are any question just let me know what to do.

**Comment by crosser** [comment]
Same here. It continues to ask for PIN (despite it's cached) and requesting to touch yubikey repeatedly. Version 3.2.3

**Comment by dschuermann** [comment]
confirmed with 3.2.3

**Comment by Valodim** [comment]
on it

**Comment by Valodim** [comment]
fixed in dd94c70fbe92e8b2f578b93da428dc9c7d728d84
