### ISSUE TITLE
descriptive nfc error messages

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1303]
this is a follow-up of issue #1301

nfc error messages are at this point just "bad nfc response code NNNN". IOException is an appropriate class, since it represents a failed or interrupted IO operation, but it should be parameterized with the error response code.

the exception's getMessage() can return the same message as displayed right now for compatibility, but an additional getMessage(Context context) method could be introduced to return localized and better descriptive error messages. the mapping can probably not be done much nicer than a large switch statement, but maybe I'm missing something.

error messages on p51 of the [openpgp card spec](http://g10code.com/docs/openpgp-card-2.0.pdf)

**Comment by dschuermann** [comment]
closed with https://github.com/open-keychain/open-keychain/pull/1338
