### ISSUE TITLE
setting to disable passphrase cache notification

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1307]
just got a feature request via irc for a preference to disable the notification of cached passphrases, to keep the notification area for "things to act upon" only.

I remember something about services being required to display a notification or otherwise they are easily destroyed, but I don't know how much of a problem this really is. any thoughts @dschuermann?

**Comment by crosser** [comment]
I suggest to rather add "things to act upon" to the notification widget, namely a button to open the app, and a button to forget the cached key. The same way as is done in OISafe.

**Comment by Valodim** [comment]
that is what we are doing now isn't it

**Comment by crosser** [comment]
No.
![img_9575](https://cloud.githubusercontent.com/assets/1404921/7879250/7918f6c0-05f7-11e5-91b6-52bdad62cc38.JPG)

**Comment by dschuermann** [comment]
Hold the OpenKeychain notification and swipe gently down.

**Comment by crosser** [comment]
Right.
But it's hidden, and tapping does nothing. I think it would be more user-friendly if tapping did something "obviously right", like opening the main activity or a dialogue to clear cache/open the app.

**Comment by dschuermann** [comment]
@crosser Thanks for your valuable feedback.
I just looked at other apps, like Android Wear which also has a long running notification.
Actually there are sort of two views: small and big. The big view, which contains the list of keys and the clear cache button is fine, but the small view is improvable. I looked at Android Wear which also uses a long running notification, and based on that I came up with this change for the small view:

Instead of:
OpenKeychain
OpenKeychain has cached 1 passwords

we could do:
OpenKeychain
1 password cached. Touch to clear cache.

@crosser @Valodim feedback?

**Comment by crosser** [comment]
@dschuermann that sounds reasonable to me :)

**Comment by dschuermann** [comment]
Externalized design decision into https://github.com/open-keychain/open-keychain/issues/1313

**Comment by dschuermann** [comment]
@Valodim I implemented #1313, and I think this issue can also be closed as it is now a "thing to act upon". It is now similar to "USB debugging connected - Touch to disable debugging" and "Connected as a media device - Touch for other USB options". We are: "X passwords cached - Touch to clear password cache." Not sure if we really want a preference to hide this notification.
What do you think?

**Comment by Valodim** [comment]
isn't that even technically problematic because the service might be closed if it doesn't have a notification?

**Comment by dschuermann** [comment]
Could happen, but I don't think it will in 5 minutes caching time...

**Comment by dschuermann** [comment]
Addendum: In IBR-DTN we tried several ways to have a long running service and it seemed pretty stable even without a notification, although the Android docs say you should display one to have a long running service that's not killed.

**Comment by crosser** [comment]
FWIW, I think it is useful to have a notification (with reasonable action, as it is now) as a security reminder that the key is "unlocked" and thus more vulnerable at the moment.

**Comment by dschuermann** [comment]
I would say: Let's not consider this feature request and leave it as it's now. We solved it partly by introducing something to act upon.
