### ISSUE TITLE
additional privacy-respecting version of open-keychain

### ISSUE THREAD

**Issue by ka-ba** [open-keychain/open-keychain#1308]
Pls consider offering a second version of the app, that doesn't need (and consequently doesn't request) permissions to contacts and to internet communication (this additional version should always have the same codebase as the current version).
That way every user has the chance to choose between the full-blown full-featured version and a more privacy-respecting 'secure' version while resigning some comfort.
(The app QRDroid already offers such a version, for example.)

**Comment by dschuermann** [comment]
I don't think that this makes much sense. In contrast to QRDroid, OpenKeychain is open source. Thus, everyone can verify that the permissions are indeed required for the described purpose. Soif you don't like certain features, simply don't use them.
