### ISSUE TITLE
Decrypting a file requests yubikey TWICE

### ISSUE THREAD

**Issue by crosser** [open-keychain/open-keychain#1309]
Once you select a file (ascii armored pgp) to decrypt, it asks for the pin and to touch yubikey. Then it lets you select the file to save, it asks you to touch yubikey _again_. Prior to 3.2.3, it also asked for the PIN second time, now it does not.

**Comment by Valodim** [comment]
Hmmm this sort of follows from design right now, since the data is first decrypted for metadata extraction, and then again for saving the data stream. for the ui flow it obviously makes sense to only ask once though, and cache the session key. I'll look into it.

**Comment by nlcampos** [comment]
Hi there!!!

  I do confirm this issue. First of all, I thought that OpenKeyChain has a bug that is preventing it to decrypt files, but after I have read this post, I have tested it and I have confirmed this issue.

[]'s,

Nelson Campos, PMP
PGP 67C63C6C

**Comment by dschuermann** [comment]
Please try again with version 3.3 that has just been released (will appear in some hours on Google Play and F-Droid). If this issue is still present, re-open this issue report.

**Comment by crosser** [comment]
Confirming fixed.
