### ISSUE TITLE
Crash on key deletion

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1311]
OpenKeychain crashes when deleting my own key, after entering the passphrase.
When the passphrase is cached it works.

**Comment by dschuermann** [comment]
also from google+:


I have one issue remaining: OpenKeyChain crashes when I want to delete one of my keys. It ask for the passphrase to unlock it, and crashes when I enter it. The key remains unlocked though, so I can delete it once the program restarts.﻿

**Comment by Valodim** [comment]
fixed in a91fc1c0c9a1c1558e6783a6ea1406aaaaa54ba0, and not using cache for delete/export operation anymore

**Comment by Valodim** [comment]
it's also noteworthy that deletion of secret keys works without a passphrase from multi-select in the key list...

**Comment by dschuermann** [comment]
https://github.com/open-keychain/open-keychain/issues/1415
