### ISSUE TITLE
sticky preferences

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1316]
so one review in the play store complained that we changed the behavior of encrypt files to also "encrypt filenames". he obviously missed the option to change that behavior, but if it's his default use case it's still annoying to select it every time.

We got rid of all related preferences and I think we should avoid introducing them. the pattern I have in mind is when one such option is selected, we show a snackbar with text like

>  Filenames will not be encrypted.
>  Save as default?

with a SAVE button to the right, which does just that

**Comment by Valodim** [comment]
implemented in v/sticky-prefs 4c9c63fa69cff3de04ef234a6b3b808f559e0a15. what do you think?

**Comment by dschuermann** [comment]
I think it's a good idea, but:
The model I have in my mind is that these settings are only specific for the screen, so they are not global settings in a sense like the ones we had before.
Thus, I would save the settings differently for file vs. text encrypt, i.e., make two different compression settings, one for text and one for files, internally.

**Comment by Valodim** [comment]
merged 7cfc0d80d0b4318ce1ae027536d70c2cda4c8605
