### ISSUE TITLE
Error when sharing fingerprint

### ISSUE THREAD

**Issue by pingu8007** [open-keychain/open-keychain#1325]
When press the share fingerprint button, I got a "Error processing key!" message. It happen to both my key and others' key.
In my memory, this button should call out the app list to share the fingerprint string.

**Comment by Valodim** [comment]
it's a regression we just noticed yesterday. will fix, thanks for the heads up.

**Comment by dschuermann** [comment]
fixed in https://github.com/open-keychain/open-keychain/commit/c43e29b621d5a0d2071a10d4033df25251b3ea23
