### ISSUE TITLE
Database migration potentially happening after key creation

### ISSUE THREAD

**Issue by thialfihar** [open-keychain/open-keychain#1334]
I noticed that the database migration + subsequent consolidation might happen at an awkward time, potentially resulting in data loss or an unrecoverable state.

Basically by having a version that didn't know about the `isFirstTime` preference, creating some keys in it, then upgrading to a current version, which shows the first time screen in MainActivity and allows the creation or import of a key or multiple keys, because there was no database access up to that point.

Creation or import of a key involves a progress dialog and when the app attempts to save the key the migration is triggered, which finally starts the consolidation, also trying to use the progress dialog.

This froze the app for me and the database wasn't in a usable state afterwards.

Putting this in MainActivity's `onCreate` works:
```java
    // force DB migration
    new KeychainDatabase(this).getReadableDatabase();
```
Because it triggers the migration as the first thing. It doesn't seem to be the cleanest solution, however, and I'm not sure what the best way would be.

**Comment by dschuermann** [comment]
Hm maybe we should put this into KeychainApplication.
@Valodim What do you think?

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/commit/136397667a1c740578081a990882a18149a6b686
