### ISSUE TITLE
MaterialDrawer upgrade

### ISSUE THREAD

**Issue by thialfihar** [open-keychain/open-keychain#1335]
`com.mikepenz.materialdrawer:library:3.0.6@aar` is available and with it, apparently `com.mikepenz.iconics:library:0.9.1@aar` won't be needed anymore.

Changes in code are minimal and I'd happily upgrade it and possibly other libraries to the latest versions, unless there are policies about library upgrades in place.

Furthermore, `MaterialDrawerTheme.Light.ActionBar` can be used as parent for `KeychainTheme.Base`, as it itself extends `KeychainTheme.Base`'s current parent `Theme.AppCompat.Light`. This would allow tweaking of the color scheme of the Drawer by overriding `material_drawer_*` colors.

**Comment by dschuermann** [comment]
Do a pull request and we will happily merge it :)
