### ISSUE TITLE
Re-enable jacoco support

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1339]
Jacoco support is gone due to this big change: https://github.com/open-keychain/open-keychain/commit/d16b09b2a6be41319b993c27e69b85067a7f1c46

@Valodim Do we need Jacoco? If it's not important for us, we can leave this out for now as it introduces much build file complexity.

**Comment by Valodim** [comment]
yes, I would like to keep it. in fact, we might want to add coveralls as well to give test coverage reports some more exposure

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/commit/b856d82ae2080dd5c35a8d71c069490a87b14d8f
