### ISSUE TITLE
Yubikey: No support for non-numeric pins

### ISSUE THREAD

**Issue by James-TR** [open-keychain/open-keychain#1350]
I don't have a numeric pin on my Yubikey and found it a rude shock when I updated OpenKeychain, and couldn't find an easy way to make it present the proper keyboard rather than numeric-only.

EDIT: I won't take "Change your Yubikey's pin to numbers" as a solution.

**Comment by Valodim** [comment]
Hi, thanks for your report!

There is a preference "Use number keypad for YubiKey pin" under "Password cache" settings, which is enabled by default. From the word "pin", most people don't realize that it is actually any string, so it's the default to make pins easier to type.

The consideration here is that the yubikey has a "three attempts" mechanism, so even a five digit pin is already quite safe (i.e. ten times as safe as your EC card), unlike secret key passphrases where an offline attacker has as many attempts as he has cpu time.

**Comment by James-TR** [comment]
Thanks, completely missed the setting there (was half asleep at the time and had just set the app back up on myphone) Thanks for that, serves me right for not checking the documentation :P
