### ISSUE TITLE
Fix crash when using icon theme with mask for unknown icons

### ISSUE THREAD

**Issue by twouters** [open-keychain/open-keychain#1356]
I've experienced crashes in openkeychain when using the icon theme provided by [TwelF](https://gitlab.com/xphnx/twelf_cm12_theme).

```
[snip]
W/StatusBarIconView(2244): Icon not found in 2130837623: 7f020077
W/StatusBarIconView(2244): No icon for slot org.sufficientlysecure.keychain/0x1
W/StatusBar(2244): removeNotification for unknown key: 0|org.sufficientlysecure.keychain|1|null|10101
D/NotificationService(954): onNotification error pkg=org.sufficientlysecure.keychain tag=null id=1; will crashApplication(uid=10101, pid=27442)
D/AndroidRuntime(27442): Shutting down VM
E/AndroidRuntime(27442): FATAL EXCEPTION: main
E/AndroidRuntime(27442): Process: org.sufficientlysecure.keychain:passphrase_cache, PID: 27442
E/AndroidRuntime(27442): android.app.RemoteServiceException: Bad notification posted from package org.sufficientlysecure.keychain: Couldn't create icon: StatusBarIcon(pkg=org.sufficientlysecure.keychainuser=0 id=0x7f020077 level=0 visible=true nu
m=0 )
E/AndroidRuntime(27442):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1484)
E/AndroidRuntime(27442):     at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(27442):     at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(27442):     at android.app.ActivityThread.main(ActivityThread.java:5289)
E/AndroidRuntime(27442):     at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(27442):     at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(27442):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
E/AndroidRuntime(27442):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
E/AndroidRuntime(27442):     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
```

This seems to be a rather common issue on mostly - if not only - cyanogenmod devices:
- [CYAN-6506](https://jira.cyanogenmod.org/browse/CYAN-6506)
- [BACON-2897](https://jira.cyanogenmod.org/browse/BACON-2897) (more clues here)

Apparently this is a known issue which has been reported on the TwelF issue tracker and a workaround(?) has been [provided](https://gitlab.com/xphnx/twelf_cm12_theme/issues/66):

> So you only have to change in the most common situation/for example
> ```
> .setSmallIcon(R.drawable.ic_launcher)
> ```
> to
> ```
> .setSmallIcon(R.drawable.ic_stat_notify)
> .setLargeIcon(Helpers.getBitmap(R.drawable.ic_launcher, getBaseContext()))
> ```
> and add a simplified white icon as "ic_stat_notify.png".

**Comment by ribmo** [comment]
Ah, this would explain the endless crashes I've been experiencing! I'm running CM12 with TwelF.

I've just disabled TwelF and OK is now usable again.

Out of interest, where do you get those logs @twouters?

**Comment by twouters** [comment]
@ribmo I've used [catlog](https://github.com/nolanlawson/Catlog) to catch those logs

**Comment by moparisthebest** [comment]
Workarounds include disabling TwelF which isn't great, or applying my patch and building your own version of OpenKeychain.  You can also install the [apk I built/signed here](https://www.moparisthebest.com/OpenKeychain-release.apk) but I wouldn't trust some random binary with my pgp key, so I wouldn't recommend you do that either.

**Comment by dschuermann** [comment]
Fixed by https://github.com/open-keychain/open-keychain/issues/1360
