### ISSUE TITLE
Visual element to verify if the rewritten password matches.

### ISSUE THREAD

**Issue by ishit** [open-keychain/open-keychain#1357]
What are your thoughts on this?

**Comment by dschuermann** [comment]
Please provide a clear description about what you have in mind. I will then reopen this issue.

**Comment by ishit** [comment]
During the signup phase, when the user is asked to choose a password and retype that password, we can provide a visual indication(like a green tick) that the retyped password matches the original password.

**Comment by dschuermann** [comment]
Great idea. I tagged this with help-wanted, if anyone wants to work on this.

**Comment by ishit** [comment]
Shall I send a pull request for this issue? Seems like workable for first contribution.

**Comment by dschuermann** [comment]
yes

**Comment by ishit** [comment]
@dschuermann Can we close this?
