### ISSUE TITLE
K-9 Mail: Encrypt attachments

### ISSUE THREAD

**Issue by knoy** [open-keychain/open-keychain#1363]
Currently in K-9 attachments are not encrypted and a toast pops up warning the user of the situation if they try to attach something to an encrypted email. 

This should be fixed considering OpenKeychain already has the functionality to encrypt binary files.

**Comment by bnvk** [comment]
The modal is actually not reported if a user has to navigate the following path when attaching:

- Select file in Other App -> Select Send (via K-9 Mail) -> Specify Encryption & Signing

This is the case in many apps which do not properly implement intents & file selection such as the "Sound Recorder" on CyanogenMod as I just discovered to learn that attachments are sent in the clear :open_mouth:

**Comment by dschuermann** [comment]
Unfortunately, K-9 Mail needs a lot of work. We will make an announcement on openkeychain.org if we pick up development of K-9 - OpenKeychain integration.

**Comment by bnvk** [comment]
@dschuermann Cool. Looking forward to that :+1:

**Comment by dschuermann** [comment]
K-9 Mail related bug reports are now tracked at https://github.com/k9mail/k-9/milestones/PGP/MIME
If no corresponding bug report exist under https://github.com/k9mail/k-9/milestones/PGP/MIME, please open a new one.

Also read our announcement at https://www.openkeychain.org/k-9/
