### ISSUE TITLE
crashes on approve by fingerprint

### ISSUE THREAD

**Issue by quantenschaum** [open-keychain/open-keychain#1364]
When I select "approve key by comparing fingerprint" (über fingerabdruckvergleich bestätigen), then "fingerprints match", uncheck "sycn with cloud", "approve", I get "openkeychain crashed"

**Comment by Valodim** [comment]
for all keys? or a specific one? what key do you certify with?

**Comment by quantenschaum** [comment]
It crashes for all keys I tried to certify.
My key is a key that was generated by openkeychain itself.

**Comment by quantenschaum** [comment]
Interesting, I just generated a new key in openkeychain. Certifying other keys with this new key works.

**Comment by Valodim** [comment]
what's the key id of the non-working key?

**Comment by quantenschaum** [comment]
Sorry, I generated the key for testing some time ago, it was never actually used or uploaded to a server. I just trashed it.

**Comment by Valodim** [comment]
so the key was broken in some way. too bad you trashed it, if you used it for testing only it would have been helpful for bugtracking. can't really reproduce this now
