### ISSUE TITLE
Bug: Cannot add some PGP key from browser

### ISSUE THREAD

**Issue by debaal** [open-keychain/open-keychain#1365]
- Using Firefox 38.0.5
- https://www.ibr.cs.tu-bs.de/users/schuerm/
- Long Press onto link to PGP signature
- Click "Mit App 'Schlüssel importieren mit OpenKeychain' öffnen"
- App finds key correctly on server
- Press the download button in lower right corner
- Import fails
- Log says:
   Schlüssel wird importiert
      Schlüsselserver hkps.pool.sks-keyserver.net wird verwendet
         Von einem Schlüsselserver abrufen: 0x...
            Schlüsselabruf erfolgreich!
         Fingerabdruck des abgerufenen Schlüssels entspricht nicht dem Erwarteten!
      Importieren fehlgeschlagen!

**Comment by dschuermann** [comment]
@debaal Will be fixed in the upcoming OpenKeychain release.
