### ISSUE TITLE
OpenKeychain asks **twice** for key (password) when decrypting a file with symmetric encryption

### ISSUE THREAD

**Issue by Wikinaut** [open-keychain/open-keychain#1368]
* OKC version 3.2.3 (323000)
* HUAWEI P8 LITE smartphone with Android 5.0

I wanted to decrypt a <file.txt> which I encrypted previously with ```gpg -c <file.txt>``` . Then I stored ```file.txt.gpg``` on the Smartphone

OKC behaviour was:
* I was prompted to enter the key.
* OKC showed the original filename ```file.txt``` and created it.
* filesize is 0 bytes
* **BUG: OKC now prompts a second time for the key.**
* Only now the file is correctly decrypted and stored as ```file.txt``` with the original data.

**Comment by Valodim** [comment]
thanks for your report!

the encrypt and decrypt dialogs are being rewritten, chances are bugs like this will not carry over. will re-evaluate this bug in the next version :+1:

**Comment by dschuermann** [comment]
Please try again with version 3.3 that has just been released (will appear in some hours on Google Play and F-Droid). If this issue is still present, re-open this issue report.
