### ISSUE TITLE
Key menu: allow local signing, or locally assign trust value (confirm fingerprint locally)

### ISSUE THREAD

**Issue by Wikinaut** [open-keychain/open-keychain#1370]
As an OKC user, when I imported a public key, I can manually (or with QR code) check the fingerprint of the imported key.

I wish to preserve (store) this "yes, I have confirmed that the fingerprint of this key is correct" information **locally**, i.e. without the step of signing the public key with my key and retransmitting/updating the public key on the key servers.

### Problem
The current OKC software does not allow to store a local trust (fp confirmation information).

### Proposal
Allow to add a "local fingerprint confirmation" or similar trust value information, without the need to resend to keyservers.

**Comment by dschuermann** [comment]
We explicilty don't implement a local trust db. This overcomplicates the current security design and has been decided against also due to usability concerns. We also have an FAQ entry for this: http://www.openkeychain.org/faq/

> Can I mark public keys as trusted without certifying them with my own key?

> No. You can, however, simply create a new key just for certification, which will essentially be the same thing.
