### ISSUE TITLE
When Yubikey responds with "NFC Error: bad PIN", OpenKeyChain offers no PIN Dialog.

### ISSUE THREAD

**Issue by phryneas** [open-keychain/open-keychain#1371]
Tapping the Yubikey again will try the same wrong PIN, which will quickly lead to the key being locked.

**Comment by phryneas** [comment]
The only way of entering a new PIN seems to be

* force stopping the app or
* waiting for the key caching time windows

**Comment by Valodim** [comment]
you can clear the cache from the notification, too. but the cache *should* be cleared on a wrong pin. I just tested and it works for me, so it's likely just broken in current release.

we have quite a few things in the pipeline, looking to release soon :+1:

**Comment by Valodim** [comment]
for reference: https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/NfcOperationActivity.java#L199

**Comment by phryneas** [comment]
Ah, I see, it was added in c694d73 - now all I have to do is reset my pin and wait for the next release xD

**Comment by Valodim** [comment]
Not quite as far behind, our latest release was May 28th, so this is a regression. We are planning a release very soon though. :+1:

**Comment by phryneas** [comment]
looking forward to it - thanks so far :+1:
