### ISSUE TITLE
Multi decrypt: File cannot be opened after certain actions

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1375]
1. Encrypt 2 files and share with "Decrypt with OpenKeychain"
2. Click on the overflow menu of one file and select "Save file"
3. abort this by clicking back until you are back in OK
4. File cannot be opened anymore

While other files are being decrypting you also cannot already click on a finished file, maybe this is related. Haven't looked into the code yet.

**Comment by Valodim** [comment]
cannot reproduce anymore, likely fixed along the way when I redid the context menu
