### ISSUE TITLE
K-9 Mail: Sign emails

### ISSUE THREAD

**Issue by knoy** [open-keychain/open-keychain#1379]
PGP emails sent using K9 + OpenKeychain do not appear signed in other email clients.

**Comment by dschuermann** [comment]
This is due to missing PGP/MIME support in the current K-9 Mail release.

**Comment by knoy** [comment]
Thanks, I've offered a bounty at K9 that will hopefully speed things alone:

https://github.com/k9mail/k-9/issues/572
