### ISSUE TITLE
YubiKey creation: PIN/Admin PIN

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1382]
Create a screen for the create key wizard that shows a random PIN + Admin PIN (first numbers of Admin PIN = PIN).
Next screen: User needs to type in these PINs to prove that she has remembered them.

Add PIN/Admin PIN back end functionality for SaveKeyringParcel to apply them after moving the keys to the card.

Assigned to myself.

**Comment by Valodim** [comment]
no reason to move the pin/admin pin through the backend via SaveKeyringParcel, the dataflow is a lot simpler if this is just done in the activity.

**Comment by dschuermann** [comment]
Not sure if I can get a nice program flow when I want to execute this together with moving the keys to the card. That's the reason I thought to do it this way.

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/commit/195508ed92434197d0d6ab2d3ef6e0b4bd0780b6
