### ISSUE TITLE
open-keychain hangs after imputting PIN for Yubikey and touching the phone with it (from #1286)

### ISSUE THREAD

**Issue by mezinster** [open-keychain/open-keychain#1386]
continuation of an "open-keychain hangs after imputting PIN for Yubikey and touching the phone with it #1286"
reproduced on ver. 3.3
 
crash report sent from mezinster@gmail.com

**Comment by dschuermann** [comment]
Thanks, I reopened https://github.com/open-keychain/open-keychain/issues/1286
