### ISSUE TITLE
Caching symmetric encryption passwords does not work

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1401]
We actually have something implemented here: https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/service/PassphraseCacheService.java#L236
But the password is not retrieved correctly when decrypting.
Not sure if we actually want to fix this or get rid of this functionality.

**Comment by Valodim** [comment]
I think we can keep it, if the decryption fails we can still ask for the password again.
