### ISSUE TITLE
Allow any operation without any private key

### ISSUE THREAD

**Issue by sedrubal** [open-keychain/open-keychain#1404]
As discussed in #947 there is no reason why you should need a private key on your mobile to do things like encrypt and verify sigs. (Reasons, why you should't even import a key are discussed in #975). And there is no reason, why you should need a key which apts to your sender email address to sign the mail or receivers email address to decrypt a mail (K9 mail).

Please remove these false dependencies.

**Comment by dschuermann** [comment]
There are already removed in current K-9 Mail master.

**Comment by sedrubal** [comment]
ok thanks.

Did you release them already?

**Comment by dschuermann** [comment]
No, there is still much more work to do. Please look into the K-9 Mail bug tracker for info.
