### ISSUE TITLE
PGP files not correctly linked from Total Commander to OpenKeychain?

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1408]
As part of a mail conversation:
A user was not able to decrypt *.pgp files opened from the file manager "total commander". As far as I understand only the key import is shown. From OpenKeychain decryption works.

**Comment by francwalter** [comment]
This might be a really minor bug.
The stock file-manager in CM12 (on SGS4) does send the encrypted file correctly to OpenKeychain. 
It might be only the file-manager-App "Total Commander", which sends the symmetric encrypted file wrongly to OpenKeychain.
Must be something with the intent filter.
The stock file-manager (com.cyanogenmod.filemanager - Version 3.0.0) even asks me about different apps, which I would like to send the pgp-file. Total Commander does not, it just opens OpenKeychain.
Don't know where the mistake is, but anyway, this is not a problem.

**Comment by wiktor-k** [comment]
Is this still an issue?

I'm using Total Commander and when clicking on `gpg` or `pgp` file I see both options -> Import key and decrypt using OpenKeychain.

I think it should be closed.

**Comment by dschuermann** [comment]
@wiktor-k thanks for testing
