### ISSUE TITLE
Crash on initial setup, key generation

### ISSUE THREAD

**Issue by briansteven** [open-keychain/open-keychain#1410]
App closes with no error (just vanishes) during initial setup when generating a new key.  When opening the app again, it allows you to go through the initial setup again, but with the same result.  This is on a Samsung Galaxy S6.

**Comment by Valodim** [comment]
I changed a couple of stuff around in the createfinalkeyfragment, which should make it more resisilent to activity state changes. please reopen or file a new issue if this happens with the upcoming 3.4.1 release.
