### ISSUE TITLE
Database error on export of keys

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1417]
1. Multi select some keys
2. export
-> database error

**Comment by dschuermann** [comment]
This could have happended due to the operations pr. Could you also look into this one @adithyaphilip ?

**Comment by dschuermann** [comment]
working on it...

**Comment by adithyaphilip** [comment]
This happens before the operations pr too, if that helps

**Comment by dschuermann** [comment]
closed with https://github.com/open-keychain/open-keychain/commit/15cee8e7e995afe1c435004c3abba521439e4e0b
