### ISSUE TITLE
Backup feature

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1419]
Result of discussions:

* Remove "export to file" from public key view, add this option to extended information
* Rename "export to file" to "backup to file" in secret key view
* Remove "select all" from multi select
* Remove "export to file" from multi select
* Add new fragment in menu drawer: "Backup"
* new fragment can: Backup all keys and Backup all keys (including yours) (with warning)

**Comment by dschuermann** [comment]
Done in https://github.com/open-keychain/open-keychain/commit/d4fbaf9397da725489c6b86341d9eb9db6c14bdb

Much can be improved from this point on, but it's better than before...

**Comment by Valodim** [comment]
well... so much for "bugfix release" ;)

**Comment by dschuermann** [comment]
:grin: It wasn't much effort actually, just moving some code around...
