### ISSUE TITLE
Problem with Confirming Fingerprints and Decrypting Files

### ISSUE THREAD

**Issue by ajay340** [open-keychain/open-keychain#1423]
Whenever I try to confirm someone's fingerprint, it just loads at 0/100 and never continues when "building key." 
Screenshot: https://mega.nz/#!WlcmxarZ!fO0wPTtONlo5qglYdzofWayPGsSwNGbIZ9fpw8duNh

Whenever I try to decrypt a .gpg file it crashes the app.
Video: https://mega.nz/#!qhdWiJRT!zftd-asCbRSrYrIAurpYQC1MG-BXeZQafbKnL0Dwjs

USING: GALAXY S6

**Comment by Valodim** [comment]
is there anything special about your key, i.e. is it a yubikey, partially stripped, or anything like that?

**Comment by ajay340** [comment]
Nothing at all, it was generated on keybase.io.

**Comment by dschuermann** [comment]
@ajay340 Which OpenKeychain version are you using?

**Comment by ajay340** [comment]
I just updated to the newest version, the fingerprints now confirm properly and the files now decrypt but it won't share the file to clouds and such and I can't save the files to my storage.
