### ISSUE TITLE
Scanning with Barcode Scanner hangs at import

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1425]
1. Scan with Barcode Scanner
2. Gets URI with fingerprint and Imports in OpenKeychain
3. Import hangs

Needs more investigation.

**Comment by adithyaphilip** [comment]
Looking into it.

**Comment by Valodim** [comment]
we'd like to push out a bugfix release today, should we wait for this one?

**Comment by adithyaphilip** [comment]
I'm almost done, just testing. Half an hour?

**Comment by dschuermann** [comment]
sure np

**Comment by Valodim** [comment]
no rush, I'll need more time than half an hour myself for a bunch of nitpickings before the release ;)

**Comment by adithyaphilip** [comment]
Does this issue still persist?
