### ISSUE TITLE
Decrypt from clipboard not working on older Androids?

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1427]
On the mailinglist someone has a problem to decrypt from clipboard. Looks like he is using an older version of Android.
-> We should test this on older Versions

**Comment by Valodim** [comment]
I removed a lot of compatibility cruft from the clipboard access code, but that was all < minApi 15. but yeah, we should test this somehow

**Comment by adithyaphilip** [comment]
Works great on API levels 15 (Kindle Fire - 4.0.3) and 16 (Sony Xperia J - 4.1.2).
