### ISSUE TITLE
Small UI glitches

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1428]
Just testing and noticing some UI glitches:
* If there are two keys inside the key adapter the creation date is displayed. It should also be grey if the key is revoked.
* In encrypt text: "Encrypt and copy text" shows the Notify behind my keyboard. Same is true for encrypt files with "Encrypt and copy text"
* When going to a fragment from the nav drawer and then pressing back on Android's footer navigation, the title is not changed.

**Comment by Valodim** [comment]
- a74d86c3d810267393207fca24c482f24f299a15
- d7a7c7310adeac2ceb513af7662307a669e5f821
- e51d443154d02734faa56d9beb058a7f60735830
