### ISSUE TITLE
Need an option to not encrypt file name by default

### ISSUE THREAD

**Issue by bingoUV** [open-keychain/open-keychain#1430]
When encrypting a file by sharing it with Openkeychain, as of 3.1.2, file names were not "encrypted" I.e. replaced by 1.gpg, 2.gpg etc. unless a checkbox was selected. In releases after that, this behavior reversed. There should be an option in settings to choose the default behavior so that every time this doesn't have to be selected.

**Comment by Valodim** [comment]
this already exists, use the checkbox in the encryption dialog context menu

**Comment by bingoUV** [comment]
Yes, that's why I said that "every time this doesn't have to be selected". If one doesn't want filename encryption, one needs to use that check box in the encryption dialog context menu every time when encrypting a file. Also make it difficult to automate with tasker.

So there should be one global setting about disabling filename encryption.

**Comment by dschuermann** [comment]
In the snackbar that's popping up from the bottom you can select this choice as a default.
