### ISSUE TITLE
illegalstateexception for dialog show during onResume()

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1431]
I changed PassphraseDialogActivity at some point to re-initialize the dialog fragment in onResume() at some point. turns out this doesn't work in the support library (but it does natively, apparently)

there's a discussion here: http://code.google.com/p/android/issues/detail?id=23096#c4

**Comment by Valodim** [comment]
turns out this is easier than expected, just use onResumeFragments rather than onResume, let's see how that turns out :+1: 

3c239bfb34e67f78ea1a50374045ca5a50b84e9c

**Comment by Valodim** [comment]
@adithyaphilip this one is related to your code: 7f9cc445fba937c5ae9ea1891ee1227bd68628b0

a fragment may be recreated under some conditions (see [here](https://raw.githubusercontent.com/xxv/android-lifecycle/master/complete_android_fragment_lifecycle.png)), at which point the new fragment object will also create a new CryptoOperationHelper object. the fragment restores its state, but the cryptooperationhelper does not, losing the mRequestedOperation variable.

scenario where this happened: in decryptactivity, some passphrasedialog pops up. navigate somewhere else, navigate back to the activity, the fragment is recreated -> the passphrasedialogactivity returns an onActivityResult, but is disregarded by the new CryptoOperationHelper object.

**Comment by adithyaphilip** [comment]
Thank you, I'll make sure to include it in other relevant places. Might be an issue in fragments with multiple OperationHelpers though, since they would overwrite the mRequestedOperation in outState. Should we introduce an id for each OperationHelper being created so it writes to a unique location in outState (by just appending that id to the string used as key) for such situations?

**Comment by Valodim** [comment]
I thought about this some more, and I think the best solution is to assign unique identifiers to each operationhelper from its caller. I'll work something out

**Comment by Valodim** [comment]
done, check out 96dbb9e60c7f1e057d90be5925167619de31ab55

**Comment by adithyaphilip** [comment]
Looks like the perfect solution. No more `mRequestedCode` at all. Yay ^^
