### ISSUE TITLE
OpenKeychain App crashes when looking up for missing key

### ISSUE THREAD

**Issue by SignorMacchina** [open-keychain/open-keychain#1440]
When I get a signed email in K9 Mail from somebody, that's key is unknown and push the button to "Look up missing key", the app immediately crashes.
I'm using a Sony Xperia Z3 Compact with Android 5.0.2

**Comment by dschuermann** [comment]
Thanks for your report. We will investigate.

**Comment by dschuermann** [comment]
@adithyaphilip can you look into this if it's related to proxy methods?

**Comment by adithyaphilip** [comment]
yup, will do.

**Comment by adithyaphilip** [comment]
Same cause as https://github.com/open-keychain/open-keychain/issues/1412, fixed with https://github.com/open-keychain/open-keychain/commit/be6b7ff89993de4eff1eb2499f7537ab74a6d8c8.
@SignorMacchina updating to the latest version of OpenKeychain (v3.4.1) should solve this issue.
