### ISSUE TITLE
Folder encryption.

### ISSUE THREAD

**Issue by Disarate** [open-keychain/open-keychain#1446]
Being able to encrypt folders as well would be really nice.

**Comment by Valodim** [comment]
there is no support for this in the openpgp standard, so there is no easy way to make this work in a way other applications (like gnupg) would understand. there is probably more we can do in this way, but I'm not exactly sure what.

can you describe the workflow you would expect for what you had in mind more?

**Comment by Disarate** [comment]
S.S.E. app in Android has the ability to encrypt folders which works pretty good. But if there is no easy solution in okc then may be a batch operation where output files retain respective file names except for file extension, could give similar benefits. UI can offer more customizations like specifying default input and output directories.

**Comment by dschuermann** [comment]
@Disarate This is already possible. You can add many files and disable "Encrypt filenames" in the overflow menu.
