### ISSUE TITLE
Problem with importing a key

### ISSUE THREAD

**Issue by Sapsality** [open-keychain/open-keychain#1451]
Hi there
I try to import my private+public key using this guide: https://github.com/open-keychain/open-keychain/issues/975
I follow it to the word
And the message pops up telling me that "no valid keys have been found in flle/clipboard".
Can you please help me figure out how to do it properly?

**Comment by Sapsality** [comment]
And while I'm at it
If this method ultimately fails and I would decide to import my key pair to openchain through some keyserver, is it ok to post my PRIVATE+public key at any of them?
I read that even if someone gets my private key, it's completely useless without the passphrase.

So is it secure to post my key pair on mit.edu for instance to import it to my android device?

**Comment by Valodim** [comment]
this is not a lot of information to diagnose your issue. so you have an .asc file which you expect to contain your key on your phone now, but OpenKeychain can't open it?

**Comment by dschuermann** [comment]
Not enough info, closing

**Comment by ArchieT** [comment]
Well, I will provide some more info:

```
 mf  ~  uname -r
4.1.5-1-ARCH
 mf  ~  gpg --version
gpg (GnuPG) 2.1.7
libgcrypt 1.6.4
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: ~/.gnupg
Obsługiwane algorytmy:
Asymetryczne: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Symetryczne: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256,
             TWOFISH, CAMELLIA128, CAMELLIA192, CAMELLIA256
Skrótów: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Kompresji: Nieskompresowany, ZIP, ZLIB, BZIP2
 mf  ~  gpg -a --export-secret-keys 88A50062 > impossible
gpg: key 88A50062/D35C60AE: error receiving key from agent: Nie można przydzielić pamięci - skipped
gpg: key 88A50062/65A62995: error receiving key from agent: Nie można przydzielić pamięci - skipped
 mf  ~  
```

Also tried Keys–>Backup in GPA.

For both files, I get `No valid keys found in file/clipboard!`.

**Comment by dschuermann** [comment]
@ArchieT Please open a new issue for your import problem
