### ISSUE TITLE
What does OpenKeychain sync?

### ISSUE THREAD

**Issue by owaro** [open-keychain/open-keychain#1457]
What data is sent by OpenKeychain when system sync is enabled? 

Does it ask the server about gpg contact keys only? 

Does it upload personal keys? 

Does it search the keyserver for keys against every single Android contact that are not listed in OpenKeyChain?

Syncing should be opt-in for privacy.

**Comment by Valodim** [comment]
at this point, OpenKeychain:
- does not update any keys unless asked to (refresh button in key view, "refresh all" option in key list)
- does not upload any keys to keyservers unless asked to (checkbox during creation and confirmation of keys, "upload to keyserver" button in extended view)
- does not download new keys non-interactively at any point
- associates contacts with confirmed keys by e-mail address

this seems to be a common doubt though, we might want to specify it in our FAQ. some of these behaviors are planned to change at some point, too, in particular @adithyaphilip is working on an automatic update of keys from the keyservers as a recurring background operation.

**Comment by owaro** [comment]
bump

**Comment by adithyaphilip** [comment]
As @Valodim had mentioned, OpenKeychain links contacts to confirmed keys if they have the same email address. The "all contacts synced" should refer to this. As of now, no automatic background download/upload happens with respect to contacts or keyservers. 

We're currently working on adding a regular download of existing keys from keyservers based on an opt-in preference provided at startup (and modifiable later from settings) to keep keys up to date. Privacy is definitely a concern, and we have an issue at https://github.com/open-keychain/open-keychain/issues/1337 to discuss it. We would be glad to hear any insights you had on the same.

**Comment by dschuermann** [comment]
We now have text under OpenKeychain's account on Android that explains the current behaviour.
