### ISSUE TITLE
cannot search online

### ISSUE THREAD

**Issue by alanthehat** [open-keychain/open-keychain#1458]
I see no way to find online a public key for a new destination. APG can do this although the option is buried in menus. 
I do not want to use APG to obtain the key, export from there then import to OpenKeychain

**Comment by Valodim** [comment]
I'm not sure what you want to do. Do you mean searching keyservers?

**Comment by alanthehat** [comment]
Yes, I do mean searching keyservers. 
I often compose emails where I have patchy internet connection. If, at the moment of sending, I have no internet there is confusion unless I already have the key (I which case the message just sits in the 'outbox' until internet returns)

**Comment by Valodim** [comment]
Are you talking about sending messages from K-9?

You can search keyservers in OpenKeychain, it's the "Search Cloud" option from the large "+" button in the key list.

**Comment by alanthehat** [comment]
Ah, missed that, thank you :-)
