### ISSUE TITLE
Yubikey: "Unknown key, hit next to import" despite already imported

### ISSUE THREAD

**Issue by crosser** [open-keychain/open-keychain#1460]
When I touch Yubikey with PGP key to a "cold" phone, and select OpenKeyChain to handle it, it says "Unknown key, hit next to import". In reality, the key is "imported" long ago and is shown in the key management interface. If I touch the key when OpenKeyChain is running, it shows "Yubikey matches and is bound to key". Looks as if the message is shown before the check has a chance to complete.

https://goo.gl/photos/GZjtATGW4Cbv8PGB7

As an aside, the wording "hit _next_ to import" is incorrect: there is no "next" button, the button is called "IMPORT".

**Comment by Valodim** [comment]
are you on current master, or 3.4.1? this behavior changed very recently

**Comment by crosser** [comment]
Current Play Store, it says 3.4.1 (34100)

**Comment by GekkePrutser** [comment]
I also get this error when trying to import a new Yubikey. Also on 3.4.1

**Comment by Valodim** [comment]
probably fixed with #2157

**Comment by crosser** [comment]
Probably fixed. I cannot reproduce it now anyway.
