### ISSUE TITLE
Read from Clipboard fails with PGP Message v1

### ISSUE THREAD

**Issue by UndeadKernel** [open-keychain/open-keychain#1467]
In the current version of open-keychain from the Android market in a Nexus 4 with Android 5.1.1, it is not possible to decrypt PGP messages utilizing the clipboard.

This is the use-case where I've found the problem:
1) Receive an email encrypted with Enigmail (Thunderbirth plugin) which utilizes gpg 2.1.6
2) Open the GMail app and copy the email into the clippboard
3) Select the option "Read from clipboard"
Outcome: Error message "Encountered an error reading input data!"

If I save the encrypted message into a file and then try to decrypt the file via the option "Select input file", everything works fine.

**Comment by Valodim** [comment]
Hmmm yeah the decrypt from clipboard mechanism (or generally decrypt from ascii-armored text) is *way* too picky about its input at this point. Issue duly noted, we'll see what we can do.

**Comment by UndeadKernel** [comment]
I was wondering if it is possible to implement this feature by creating a temporary file with the contents of the clipboard and then just doing a standard file decryption. I envision the following:

1) The user selects to decrypt from the clipboard.
2) The application takes the contents of the clipboard and creates a temporary file with these contents.
3) The function to decrypt a file is invoked with the contents of the temporary file.
4) The results are displayed to the user as normal.

Maybe this is too trivial and there is something else I'm actually missing.

**Comment by Valodim** [comment]
that's actually already how it works, more or less. the problem is with the actual data, some newlines getting added or removed or something like that. we just need to make the parser more flexible in this regard

**Comment by dschuermann** [comment]
@UndeadKernel We just released version 3.5, it will be available in the next hours on Google Play and tomorrow on F-Droid.
Can you re-test with this version?

**Comment by UndeadKernel** [comment]
@dschuermann I have tested with the new version and I'm pleased to report that everything is working as expected! Thank you for taking a look at this, your efforts are much appreciated.
