### ISSUE TITLE
Unusable signing key not properly disabled

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1468]
Revoked and expired keys are disabled in the signing key spinner. Unusable keys (missing signing subkey) are not properly disabled, they can still be selected by click.

**Comment by Valodim** [comment]
Hm. At first I thought I probably forgot to implement this, but the check is there and looks valid to me. Weird. Will look into it

**Comment by 007durgesh219** [comment]
Please see #1818

**Comment by Valodim** [comment]
thanks!
