### ISSUE TITLE
Rename "YubiKey NEO" to "Security Token"?

### ISSUE THREAD

**Issue by jgoerzen** [open-keychain/open-keychain#1471]
Hello,

I have obtained a JavaCard on which I have installed the OpenPGP applet.  This is not a Yubico card in any way, but is the same applet that they forked theirs from.  OpenKeyChain works with it (so it might be time to stop calling it "Yubikey" and call it "OpenPGP applet" support.)

I also have the GnuPG  OpenPGP card v2.0 with Mifare support, as well as the SmartCard-HSM with Mifare support.  Both are seen by the NFC reader on Android, but OpenKeychain just gives an NFC initialization error on both.

I suspect that minor changes would be all it takes to get it working with these cards.  The GnuPG card is quite popular and is described here:

http://wiki.fsfe.org/FellowshipSmartCard

http://g10code.com/p-card.html

**Comment by crosser** [comment]
FWIW, on g10 card, JavaCard functionality is inaccessible over NFC. Mifare chip with antenna is completely separate from the JavaCard chip that can run OpenPGP applet. (FSFE apparently has no NFC at all.)

I would love to see alternatives to Yubikey NEO, but so far I did not find any.

**Comment by Valodim** [comment]
neither the fellowshipsmartcard nor the openpgp card actually support access to the openpgp applet via NFC.

relevant part from here: http://shop.kernelconcepts.de/

```
Please notice that the OpenPGP card function is not accessible via RFID interface! The MiFAR-1k chip is an additional chip implanted into the same card but completely independant of the OpenPGP chip.
```

It is also worth mentioning that no part of our code is YubiKey specific, it is 100% specs of the openpgp applet, accessed via ISO-DEP (ISO 14443-4) nfc communication.

**Comment by dschuermann** [comment]
@crosser There is https://www.sigilance.com

**Comment by crosser** [comment]
@dschuermann  :+1:
(perhaps worth a mention in openkeychain docs?)

**Comment by dschuermann** [comment]
We could rename the functionality, but I am not sure what name we would use then. OpenKeychain's main goal is usability and YubiKey is quite a popular product now, so hopefully average people directly know: "Ah nice I can use these YubiKey NEOs with OpenKeychain". Then they google YubiKey NEO and buy one. If we name it "OpenPGP applet", they google it and are extremly confused and give up. "OpenPGP card" is also misleading as in my opinion YubiKeys don't look like cards.

Maybe we should call it something like "Security token" and after clicking on the option in the first time wizard show the "OpenKeychain approved" ones (currently YubiKey NEO and Sigilance). I don't want to encourage users to use blank cards.

**Comment by Valodim** [comment]
Indeed. I would hate to get one-star reviews because people order an "OpenPGP Card" and are disappointed because "we don't support it" when their card doesn't actually support NFC. As this issue proves, it's not at all clear to users what type of card they would require.

**Comment by jgoerzen** [comment]
I think a simple name of "Yubikey or OpenPGP Java Applet" might work.  I can vouch that it works for non-Yubikey OpenPGP Java Applet cards.

**Comment by dschuermann** [comment]
@jgoerzen Which card exactly did you use and where did you buy it?

**Comment by jgoerzen** [comment]
This one, from this vendor: http://www.smartcardfocus.us/shop/ilp/id~709/javacos-a22-dual-interface-java-card-150k/p/index.shtml

**Comment by Valodim** [comment]
"Yubikey or OpenPGP Java Applet" is *not* a simple name. I would also argue that buying a card like the one you linked and installing the openpgp applet is only a viable option for expert users, since it is not backed by vendor support like Yubikeys are.

As a compromise, we could add an entry to the FAQ which clarifies that the implementation is not actually YubiKey-specific and is compatible with any nfc-enabled OpenPGP java applet as an expert option.

**Comment by dschuermann** [comment]
I added an FAQ entry for now with https://github.com/open-keychain/open-keychain.github.io/commit/a052931a2b2fc789b5aaeb525c6c9a2b180beef9
We can still think about renaming/redesigning the wizard later

**Comment by slomo** [comment]
I liked the idea of it been called 'security token'. (Disclaimer: I am working for [Fidesmo](http://fidesmo.com), we over a card with an OpenPGP cardlet, that just works fine with Open-Keychain)

**Comment by dschuermann** [comment]
Under manage my keys -> "Use Security Token", add subtilte "YubiKey NEO, Fidesmo, SIGILANCE"

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/commit/0fd5b45df913d1524aa400a644c48dc91044d9bf
