### ISSUE TITLE
Dead Link in FAQ

### ISSUE THREAD

**Issue by RichJeanes** [open-keychain/open-keychain#1475]
Simple issue. Just looks like Yubico changed their site's directory structure a bit.
FAQ -> How to import an existing key onto the YubiKey?
Current link: https://developers.yubico.com/ykneo-openpgp/KeyImport.html
Proper link: https://developers.yubico.com/PGP/Importing_keys.html

I would open up a PR to fix it, but I have no clue where to even start looking for that. Haha

**Comment by Valodim** [comment]
fixed,thanks ;)

for the record, website is here:
https://github.com/open-keychain/open-keychain.github.io

**Comment by RichJeanes** [comment]
Oh look at that. That makes sense that the app just pulls its help pages from the site.
