### ISSUE TITLE
Missing security checks

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1476]
priority: Check binding signatures for requirements on import! throw out binding signatures with insecure
 signatures (bit length, hash algo)
- fix insecure key test in PgpEncryptDecryptTest
- put checks for curve OIDs and algorithm tags into import instead of PgpDecryptVerify?
- check signingRing in PgpDecryptVerify?
- ECC checks https://tools.ietf.org/html/rfc6637#section-13 , https://github.com/open-keychain/open-keychain/issues/1353
- check encryption algo used for encrypting secret keys?
- check S2K security on import?
- check for min rsa/dsa/elgamal/ecc requirements in key creation backend

Insecure todo:
- show warnings after import that certain keys are invalid? (also see H's master thesis) How to do this properly?
- Also check insecure keys when used via API? In PgpSignEncrypt?

**Comment by dschuermann** [comment]
- show imported keys with insecure asymmetric key length as invalid inside OpenKeychain's list (requires the new state INSECURE for database)
- show warnings after import that certain keys are invalid? (also see H's master thesis) How to do this properly?

**Comment by dschuermann** [comment]
Do we have all these checks?

**Comment by Valodim** [comment]
Uh, most of them at least. We also have insecure reporting during decryption/verification, key checks during import, and the key health card. I found it hard to see what this ticket specifically entailed, if you are still missing something please make individual tickets.
