### ISSUE TITLE
yubikey neo with subkeys?

### ISSUE THREAD

**Issue by petervnv** [open-keychain/open-keychain#1478]
Hi all,

Running K9 (5.106) and Openkeychain (3.4) on Sony Z3 compact with stock 5.1.1.

I have a very recent yubikey NEO with the OpenPGP applet. I have moved my subkeys to the NEO in a setup like the one here https://www.esev.com/blog/post/2015-01-pgp-ssh-key-on-yubikey-neo/

Now this setup works as expected with thunderbird and enigmail on my desktop. But when I try to decrypt an email in k9, I get the popup asking for my yubikey PIN, I enter it, I then get the dialog to "Hold Yubikey against the NFC marker...", I can feel NFC working as normal and then I get the "Take away the yubikey now" dialog, which I do. Now I would expect the email to be decrypted just like it does with thunderbird/enigmail, but unfortunately the imgae "Hold Yubikey against the NFC marker..." pops up again and K9 freezes/crashes. The only way to get k9 working again is to kill the process in Settings.

Anyone else have any success with subkeys on the Neo and openkeychain with k9?

I have posted the logs from k9 and openkeychain here http://pastebin.com/2fR1mhbj

Cheers,
Peter

**Comment by mohlerm** [comment]
I'm using the exact same setup (K9, OKC, Z3C 5.1.1) and it works for me.
However, sometimes I experience similar issues, especially if I rotate the device while the NFC popup is visible. But usually disabling/enabling NFC and restarting the decrypt process solves it.

**Comment by petervnv** [comment]
Thanks mohlerm,

Unfortunately it still isn't working for me. Further debugging shows an error message with the OpenPGP API.
I wonder if this maybe due to the version of the OpenPGP applet in my Neo? My neo is using OpenPGP applet version 1.10.9.

Any ideas?


D/k9      (14742): MessageView displaying message MessageReference{accountUuid='ced649f2-7f10-4f36-9933-f84b7c1b2956', folderName='INBOX', uid='1184', flag=null}
V/WindowManager(  861): Adding window Window{27200aee u0 org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.NfcOperationActivity} at 8 of 16 (before Window{190b6c31 u0 org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.NfcOperationActivity})
V/WindowManager(  861): Adding window Window{2d2fbe1c u0 com.fsck.k9/com.fsck.k9.activity.MessageList} at 7 of 17 (before Window{28f0518d u0 org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.NfcOperationActivity})
W/SurfaceFlinger(  272): couldn't log to binary event log: overflow.
D/PullToRefresh(14742): First Visible: 0. Visible Count: 0. Total Items:3
I/art     (  861): Explicit concurrent mark sweep GC freed 52879(2MB) AllocSpace objects, 8(688KB) LOS objects, 30% free, 36MB/52MB, paused 1.448ms total 81.102ms
V/WindowManager(  861): Adding window Window{1a85e7fa u0 org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.NfcOperationActivity} at 8 of 17 (before Window{27200aee u0 org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.NfcOperationActivity})
I/Timeline(  861): Timeline: Activity_windows_visible id: ActivityRecord{1aa111b8 u0 com.fsck.k9/.activity.MessageList t3910} time:974727
D/k9      (14742): OpenPGP API decryptVerify result code: 2
E/k9      (14742): Internal error on starting pendingintent!
E/k9      (14742): android.content.IntentSender$SendIntentException
E/k9      (14742): 	at android.app.Activity.startIntentSenderForResultInner(Activity.java:3954)
E/k9      (14742): 	at android.app.Activity.startIntentSenderForResult(Activity.java:3925)
E/k9      (14742): 	at android.app.Activity.startIntentSenderForResult(Activity.java:3892)
E/k9      (14742): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.handleUserInteractionRequest(MessageCryptoHelper.java:386)
E/k9      (14742): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.handleCryptoOperationResult(MessageCryptoHelper.java:365)
E/k9      (14742): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.onCryptoOperationReturned(MessageCryptoHelper.java:347)
E/k9      (14742): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.access$400(MessageCryptoHelper.java:49)
E/k9      (14742): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper$2.onReturn(MessageCryptoHelper.java:215)
E/k9      (14742): 	at org.openintents.openpgp.util.OpenPgpApi$OpenPgpAsyncTask.onPostExecute(OpenPgpApi.java:318)
E/k9      (14742): 	at org.openintents.openpgp.util.OpenPgpApi$OpenPgpAsyncTask.onPostExecute(OpenPgpApi.java:299)
E/k9      (14742): 	at android.os.AsyncTask.finish(AsyncTask.java:636)
E/k9      (14742): 	at android.os.AsyncTask.access$500(AsyncTask.java:177)
E/k9      (14742): 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
E/k9      (14742): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/k9      (14742): 	at android.os.Looper.loop(Looper.java:211)
E/k9      (14742): 	at android.app.ActivityThread.main(ActivityThread.java:5373)
E/k9      (14742): 	at java.lang.reflect.Method.invoke(Native Method)
E/k9      (14742): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/k9      (14742): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
E/k9      (14742): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
D/k9      (14742): OpenPGP API decryptVerify result code: 2
I/ActivityManager(  861): START u0 {cmp=org.sufficientlysecure.keychain/.ui.NfcOperationActivity (has extras)} from uid 10008 on display 0
W/ResourceType(  861): Found multiple library tables, ignoring...
V/WindowManager(  861): addAppToken: AppWindowToken{31ec3a1 token=Token{288a008 ActivityRecord{3d0e21ab u0 org.sufficientlysecure.keychain/.ui.NfcOperationActivity t3910}}} to stack=1 task=3910 at 5
I/Timeline(14742): Timeline: Activity_idle id: android.os.BinderProxy@39f7b968 time:974753
I/Timeline(  861): Timeline: Activity_windows_visible id: ActivityRecord{1a65b7fd u0 org.sufficientlysecure.keychain/.ui.NfcOperationActivity t3910} time:974802
I/Timeline(  861): Timeline: Activity_windows_visible id: ActivityRecord{2fc2e066 u0 org.sufficientlysecure.keychain/.ui.NfcOperationActivity t3910} time:974805
I/Timeline(  861): Timeline: Activity_windows_visible id: ActivityRecord{20c53c56 u0 org.sufficientlysecure.keychain/.ui.NfcOperationActivity t3910} time:974808
I/WindowManager(  861): Screen frozen for +381ms due to Window{190b6c31 u0 org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.NfcOperationActivity}
V/WindowManager(  861): Adding window Window{6457c52 u0 org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.NfcOperationActivity} at 11 of 17 (after Window{190b6c31 u0 org.sufficientlysecure.keychain/org.sufficientlysecure.keychain.ui.NfcOperationActivity})
D/NfcAdaptation(10105): NfcAdaptation::HalDeviceContextDataCallback: len=20
I/BrcmNfcNfa(10105): NFC received ntf gid:1
I/BrcmNfcNfa(10105): nfa_dm_disc_discovery_cback (): event:0x4002
I/BrcmNfcNfa(10105): nfa_dm_disc_sm_execute (): state: DISCOVERY (1), event: DISCOVER_NTF(2) disc_flags: 0x1
I/BrcmNfcNfa(10105): nfa_dm_disc_new_state (): old_state: DISCOVERY (1), new_state: W4_ALL_DISCOVERIES (2) disc_flags: 0x1
D/BrcmNfcJni(10105): nfaConnectionCallback: event= 2
D/BrcmNfcJni(10105): nfaConnectionCallback: NFA_DISC_RESULT_EVT: status = 0
D/BrcmNfcJni(10105): NFA_DISC_RESULT_EVT success

**Comment by petervnv** [comment]
OK, I think I've figured out part of the problem.
I was actually testing on a recent K9 dev (5.106) branch I compiled instead of stable (5.006) from the play store.

So with 5.006 indeed the yubikey works as expected and as mohlerm reported.

So I believe this bug is introduced in the dev unstable branch.

Not sure if this is the right place to report a bug in dev branch or if I should close the issue here.
Thoughts?

**Comment by Valodim** [comment]
changes in k9 dev branch are substantial compared to current master, it's almost entirely untested and is just not in a stable state at all. I'm not sure reporting this is worth it at the moment, since there it's pretty much just the default use case for yubikey decryption
