### ISSUE TITLE
After key creation, OpenKeychain closes

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1479]
Mentioned in Google Play and reproduced by @Valodim 
1. create a new key using the first time wizard
2. after key creation is done, OpenKeychain closes.

It should go to the main list instead

**Comment by Valodim** [comment]
this is an important issue, it really ruins our first time setup experience

**Comment by dschuermann** [comment]
fixed in https://github.com/open-keychain/open-keychain/commit/94683607d64b004e58983d0eb7788fd3f0ba877b
