### ISSUE TITLE
Back button dead

### ISSUE THREAD

**Issue by Just1Number** [open-keychain/open-keychain#1482]
The back button in 'Settings/cloud search/Select OpenPGP keyservers'  doesn't work. You can still get back with the hardware keys.

**Comment by Valodim** [comment]
Hmm. Seems to work for me. What OpenKeychain version are you on, and what type of Android?

**Comment by Just1Number** [comment]
OpenKeychain 3.4.1
Android 5.1.1 stock on Nexus 5

**Comment by Valodim** [comment]
Cannot reproduce, reopen if this persists in the next release please

**Comment by dschuermann** [comment]
Does not work for me. It's the back button inside the keyserver list.

**Comment by Valodim** [comment]
Oh, that one. Sorry, I didn't get that.
