### ISSUE TITLE
"Transceiver failed" error with Note 3 using NFC Yubikey

### ISSUE THREAD

**Issue by jtl999** [open-keychain/open-keychain#1484]
Hello

I have a Note 3 LTE (SM-N900W8) running Android 4.3 stock ROM and I have a YubiKey Neo setup with PGP that works over USB with my computer.  I imported my public key into Openkeychain, works fine for encrypting things to other public keys and when I have the Openkeychain app open I can bump my Yubikey for the summery (public private key linked screen). However when I'm in K-9 Mail (as an example) or in general when I'm trying to decrypt a PGP encrypted file I get "tranceiver error" almost immediately.

Yubikey works most of the time with Authenticator app (sometimes requires a few tries, but I only recall Yubikey working with Openkeychain only one time for decryption)
![image](https://cloud.githubusercontent.com/assets/1234670/9292413/5051576c-43ac-11e5-92cb-85f01adb44bb.png)

Any help is appreciated.

**Comment by jtl999** [comment]
Interestingly I tried with another Yubikey I had where I didn't care about losing the private key and I tried one invalid PIN and then I get the "retry counter, 2 attempts remaining" message

**Comment by Valodim** [comment]
So this happens in K-9 as well as file (or message) decryption in OpenKeychain directly?

**Comment by jtl999** [comment]
Yes

**Comment by dschuermann** [comment]
We have a related issue here: https://github.com/open-keychain/open-keychain/issues/990
Not sure if your problem is the same...

**Comment by jtl999** [comment]
Sounds similar, tried all sorts of distance things and no dice.

**Comment by jtl999** [comment]
Noticed an update on GooglePlay that came out very recently for OpenKeychain (<48hr old)

Issue still happens

**Comment by dschuermann** [comment]
Have you tried: http://forum.yubico.com/viewtopic.php?f=26&t=1297 ?

**Comment by jtl999** [comment]
Yes

NFC antenna is on the battery with Note 3, tried removing back cover just having it over battery as well, no change.

**Comment by jtl999** [comment]
What's also interesting is that the YubiKey Authenticator app also has intermittent communication errors. I fear this is not a bug with Openkeychain but how my device communicates with the Yubikey. Here is a screenshot of NFC TagInfo showing problems communicating with the device (The NDEF section just has the 44 character one time password, as usual with the validation URL.)

https://imgur.com/a/LlxOM

**Comment by jtl999** [comment]
I just made a huge discovery. 

Using the NXP Taginfo app with my brothers Nexus 5 (running 5.1.1) I scanned my YubiKey and it was successfully detected every time, not matter what.

I'm so angry but feel dumb at the same time, why can't my $600 Note 3 can't read my Yubkey NFC tag reliably? (as in Yubico Authenticator works almost every time with intermittent issues, and the Openkeychain app never works for encryption decryption), any Openkeychain/NFC library developers want the data, contact me

Thanks

**Comment by Valodim** [comment]
I'm not sure what the authenticator app does, but openpgp sign/decrypt are operations which require a lot of power on the yubikey, so simpler operations might work just because they require less power.

either way, there is not a lot we can do about this. I wonder if we should keep a list of devices with known issues, in the FAQ maybe

**Comment by jtl999** [comment]
Yeah. I understand.

I tested with my mothers Galaxy S4 and that works fine actually even through very thick otterbox case. I think the issue is the battery because that contains much of the NFC chips and stuff. Ordering a replacement tonight, was very hard to find. Shame on you Samsung for not selling batteries in Canada for my almost two year old phone...

**Comment by jtl999** [comment]
Ordered a new battery for Note3 as it was running down anyway and the NFC antenna is in the battery. Picked express shipping, we will see.

**Comment by jtl999** [comment]
New battery didn't solve the problem, express shipping my butt. However battery life is much better :)

**Comment by dschuermann** [comment]
@jtl999 sry that it didn't work out for you. I started a wiki page about NFC problems: https://github.com/open-keychain/open-keychain/wiki/NFC-devices

Unfortunatly, we can't do much more at this point

**Comment by bashrc** [comment]
I've also been testing with a yubikey neo and samsung galaxy S4. I can only describe the user experience as "hostile". On the rare occasions where I can get the yubikey in *exactly* the right position and orientation, which involves a lot of fiddling about, I just get the error: "transceive length too long". This could indeed be some sort of battery issue with low signal/noise causing delays in transmission.

**Comment by jtl999** [comment]
Oh, what model of S4?

**Comment by bashrc** [comment]
GT-I9505

**Comment by weissjeffm** [comment]
FWIW I have the same issue with a Galaxy Note 3.
