### ISSUE TITLE
revoke key as a whole, not every part of it individually

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1485]
I just noticed that a revocation operation revokes all user ids and subkeys.

What really should be done is revocation of only the primary key. Unlike subkey and user id revocations, this operation cannot be undone, and it revokes use of the key as a whole, which is precisely what we want.

**Comment by adithyaphilip** [comment]
We actually shifted from revoking only the master key to also revoking all subkeys and user ids during the discussion on the PR: https://github.com/open-keychain/open-keychain/pull/1435#issuecomment-120381188, primarily to prevent other PGP implementations from erroneously letting the user sign with an unrevoked subkey, besides following the precedent set by Engimail.

**Comment by Valodim** [comment]
Oh, ok. I didnt follow that discussion. Hmm. Not really sure about this, it clashes with our decision of hiding revoked user ids in the identity list, AND all revocations besides the primary one are reversible, so it is *imperative* that other clients handle *this* revocation correctly.

**Comment by dschuermann** [comment]
As @adithyaphilip said, Enigmail does it this way and we decided to follow this to prevent bad PGP implementations (and we all know there are some...) to accept subkeys/user ids.
Why does it clash with our decision to hide user ids? It shouldn't really matter if we display user ids for revoked keys or not.

**Comment by dschuermann** [comment]
Maybe it's a good idea to precisely state this decision inside the RevokeOperation...

**Comment by Valodim** [comment]
I'm not convinced. Unless you have a concrete example of a misbehaving implementation, this seems like an arbitrary decision. I'll look up enigmail's reasoning when I have some time.

**Comment by dschuermann** [comment]
I checked Enigmail again and they only revoke the master key. I was confused because they indicate a revocation for all subkeys and user ids in their UI.
BTW: Enigmail has like zero comments in their code :/
So ack, we can revert this decision, sry @adithyaphilip

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/commit/a3395112e091eca4d3efafc1b9f29d782298b588
