### ISSUE TITLE
Missing check if YubiKey is the right one

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1490]
NfcOperationActivity should check if the yubikey used for a operation is really the right one using RequiredInputParcel's values. If it's the wrong one, we should show an error inside the dialog.

**Comment by dschuermann** [comment]
Else this will result in an invalid signature or in corrupt data on decryption.

**Comment by nmikhailov** [comment]
I belive this was fixed in #1835

**Comment by Valodim** [comment]
yup
