### ISSUE TITLE
Transifex: for better translation quality please fix / review all issues there

### ISSUE THREAD

**Issue by Diapolo** [open-keychain/open-keychain#1497]
@dschuermann I saw you recently were working on the translations of your project and started fixing / reviewing some of the open issues in Transifex (see https://www.transifex.com/dominikschuermann/open-keychain/translate/#issues). IMHO you should start fixing / reviewing all of them so we can improve the overal quality of the translations.

Also I'd love to apply as a reviewer or perhaps even coordinator for the german language of the project.

**Comment by dschuermann** [comment]
Hi @Diapolo ,
the simple problem here are time constraints ;)
I added you as a coordinator, but please open an issue here if you have doubts about something.
I started adding some notes to https://github.com/open-keychain/open-keychain/wiki/Language-Conventions . For cosistency, we should follow these notes and you are invited to add more terminology to this wiki.

**Comment by Diapolo** [comment]
Thanks, I'll do my best to improve our translation quality and will consult you in terms of controversial things :).
