### ISSUE TITLE
Encryption Algorithm

### ISSUE THREAD

**Issue by shahideh** [open-keychain/open-keychain#1499]
Add an option for change encryption algorithm
(For example camelia algorithm)

**Comment by Valodim** [comment]
why?

**Comment by dschuermann** [comment]
We decided what algorithms should be used to have a secure communication based on modern ciphers. We follow recommendations from security experts.

**Comment by shahideh** [comment]
Thanks
May i know what algorithm and hash you use?

**Comment by dschuermann** [comment]
The asymmetric algorithm depends on the key you use. Hash algorithm is currently SHA-512. Symmetric is AES 256. You can find all defaults here: https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSecurityConstants.java
