### ISSUE TITLE
OK gets unresponsive when opening large decrypted text file

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1503]
If you decrypt a large text file and then opens it with OKs internal viewer, OK slows extremly down and eventually does not respond.

**Comment by Valodim** [comment]
made a [trace](http://valodim.stratum0.net/ddms8026011857650774456.trace). almost 100% of the time is sent in android methods for text layouting.

not sure how to handle this. we can either find a widget more optimized for displaying larger amonts of text, or we could simply limit the supported use case and truncate after a couple of kilobytes.

**Comment by Valodim** [comment]
done in d149bfd3dbc1010d661b81e72e442c4d4f7b9fa0

**Comment by numericOverflow** [comment]
@Valodim - can you tell me what version these changes will be released under?

**Comment by Valodim** [comment]
this is in version 3.6, which was released in the play store last thursday (but not yet on fdroid due to build problems)
