### ISSUE TITLE
When using the OpenPGP API library, data _returned_ from the OpenKeychain app is through the ParcelFileDescriptor stream is likely to get truncated!

### ISSUE THREAD

**Issue by mgeier63** [open-keychain/open-keychain#1504]
This is because the TransferThread doesn't necessarily read all available data back from the OpenKeychain service, because it is stopped immediately after the "execute" call has returned (it's stopped by  input.close();)

The obvious solution of simply waiting for (joining) the TransferThread  unfortunately does not work, because the TransferThread can not detect remote stream close/end  due to the way the pipe FileDescriptors are set up.

This is because the  FileDescriptors are "dup"ed when going through parcels, the input ParcelFileDescriptor never realises that the FileDescriptor at the service side has been closed. It works though if the return pipe gets set up on the service side.

Note: The testcase OpenPgpServiceTest doesn't really test IPC as it runs in the same process! I've therefore created a standalone test app

For details [see this pull request](https://github.com/open-keychain/openpgp-api/pull/3)
and  [this pull request](https://github.com/open-keychain/open-keychain/pull/1505)

To reproduce build and run [this app](https://github.com/mgeier63/demo-openpgp-api-bug)

**Comment by dschuermann** [comment]
Thanks for your work! Looks like it was hard to debug.
I will look into this next week and then get back to you.

**Comment by dschuermann** [comment]
Thanks again for this hard work. Your changes will be released with the next OpenKeychain version.
Out of curiosity: Are you working on something or why have you encountered this problem?
It's rare to find people debugging these kind of unpredictable stuff...

**Comment by mgeier63** [comment]
Don't worry, I got paid for it;-) - I'm setting up a secure communication
environment for a client,  using OpenKeychain, Conversations and K9.  I've
encountered this problem in "Conversations" first - it happens pretty often
there when sending PGP encrypted images (for attachments it stores the
stream returned from OpenKeychain in a file and immediately reads the file
length after the service call has returned - but the transfer thread hasn't
even processed the final buffer yet), but in hindsight it may have been
responsible for a couple of  corrupted images in K9 email attachments as
well!


2015-08-28 17:49 GMT+02:00 Dominik Schürmann <notifications@github.com>:

**Comment by dschuermann** [comment]
Released in OpenKeychain 3.6
