### ISSUE TITLE
Merge Linked Identities

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1506]
Merge Linked Identities branch into master and show UI when experimental feature setting is enabled (https://github.com/open-keychain/open-keychain/commit/ec7a3a704701537eda24afe16081b18b34497928)

Assigned to @Valodim

**Comment by Valodim** [comment]
merged, and fixed a couple bugs along the way.

still missing the switch as an experimental feature, but this should be easy since there are effectively only two entrypoints

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/commit/bff302f80865a89a46e2c111bb2f3c99986bc285
