### ISSUE TITLE
Non-clearsigned signatures generated by GPG are not recognized as valid

### ISSUE THREAD

**Issue by petschekr** [open-keychain/open-keychain#1507]
Generating a signature of the text `Hello world` with GPG by running `echo Hello world | gpg --sign --armor -u "DB85C154"` produces the following signature:

```
-----BEGIN PGP MESSAGE-----
Version: GnuPG v2

owEBRAG7/pANAwAIAWNWMDfbhcFUAcsUYgBV30yESGVsbG8gd29ybGQgDQqJARwE
AAEIAAYFAlXfTIQACgkQY1YwN9uFwVRonwf/bv6t2EeepoDC8wAsEVZAoRApqkx7
0QIkYRc0MdIytbVU3KRhSPeF/V/z9Sn0vx/AOFMug9vMAfGw+klQuK9YS4Bj/y8o
zoToQ9BA8HP1U9lMWhAp9U8emlaMyCmmFJJHXLIZZtgOY7uxS6c/nlZTn2oBkucO
shZYkwVWmuYgRm28eu1psFx4fS92sXWzn1xdP42EMR2czZSbCQUxN5yDgzMdLn2U
XP4VeItInv21QXvrV9sMNOFurFVO8Yxb68KqRaORZY80+0oxEIZezBvgw0tBMRtp
XBpPrO70hIlP+tqLXSuwGVNxNWxBinREdYfoFRqnBXvLSiXUy0ameeei6g==
=3nXP
-----END PGP MESSAGE-----
```

signed by [this](https://pgp.mit.edu/pks/lookup?op=vindex&search=0x63563037DB85C154) key. Verifying by running `gpg --verify` works flawlessly:

```
gpg: Signature made 08/27/15 13:47:01 Eastern Daylight Time using RSA key ID DB85C154
gpg: Good signature from "Ryan Petschek (YubiKey) <petschekr@gmail.com>" [ultimate]
```

However, when I try to decrypt/verify this signature, OpenKeychain fails with the message `Encountered an error reading input data!` and nothing else in the log. OpenKeychain does seem capable of verifying clearsigned messages generated by `echo Hello world | gpg --clearsign --armor -u "DB85C154"` which produces:

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Hello world
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQEcBAEBCAAGBQJV30/zAAoJEGNWMDfbhcFUmfwIAICav/5w2A1pelWGBorOURq8
Jcg3JA08f2wUWLg/TZfBLF8HIY1xqfmk4hmzPzEuV6ncG/LKlpeYbzOUpJ8Fl5pT
PcHYlBH6L1wOj6qKqwjP2i5ulViXKUhpalTreAFA0V/M/IHdBk/ZUVT3AhiT49Bv
eQLLEi3ljMEmGK8k0WHNzTv+iSTTiKkUh3zobjtyXi9+NOCaWm6dMBxoo5vJ20Nt
19+g3pfqAVkc2e0bxBC30qkTnmFIZjdRsfNzIfeaNsI+d6CBL8kMh3P9/RWVC83U
v01X9jGSVKlGcEg6d29G08UH//K79XFhIbaZZw2wTPcKdgx21tLvpsyuYNvCwFg=
=gGEe
-----END PGP SIGNATURE-----
```

Is there a specific reason that support for the first type of signature doesn't appear to be supported by OpenKeychain?

**Comment by dschuermann** [comment]
No there is no specific reason.
It's simply not a format that we took into consideration, because the use cases are quite small.
We are open for pull requests to fix this :)

**Comment by Valodim** [comment]
There is a quite specific reason, actually: verifying detached signatures requires input of the signature data and also the file to check, which is a very different ui flow than all other decrypt/verify operations we support. Even before implementing it, coming up with a good ui flow for this is not easy.

**Comment by dschuermann** [comment]
@Valodim This isn't a detached signature. The data is inside the PGP MESSAGE

**Comment by Valodim** [comment]
Oh! Mixed that up. Ok, that's an easy fix then.

**Comment by hirschrobert** [comment]
Hello, I seem to have the same problem. Signatures from GpgOl are not recognized in k9/openkeychain. There is also no option to decript if the signature is in a message. Am I getting it wrong? How does it work?Thanks

**Comment by Valodim** [comment]
alright, I think this works now - at least your test case does :+1:

out of curiosity, do you actually use this type of file for anything? also, how do you extract the signed data? `gpg --verify --output` only seems to work for detached signatures?

**Comment by petschekr** [comment]
@Valodim
Running `gpg --verify` will only verify the message while `gpg --decrypt` will output the message and verify it.

**Comment by Valodim** [comment]
ah, interesting. still not sure what the use case is supposed to be, but support just required moving a couple of parts around, so why not. will be in the next release.

**Comment by petschekr** [comment]
Great, thanks a lot! It's probably not a very popular use case but this type of signature seems to be the only one that Keybase.io's [kbpgp.js](https://github.com/keybase/kbpgp) supports so I just wanted them to be interoperable.
