### ISSUE TITLE
DNS linked identity not ready

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1511]
Adding a DNS linked identity is not ready.
Strings linked_create_dns_2_2 and linked_create_dns_2_3 contain "bla".

Disable DNS support for now?

**Comment by Valodim** [comment]
Yes. This was planned anyways because without DNSSEC it is not secure.

**Comment by Valodim** [comment]
huh, I'm sure I had this disabled before but somehow the commits are gone. weird. anyways, done in 8152f265146e0d51a1b51a34e376c960be46869e
