### ISSUE TITLE
Github Linked Identity: Post gist not working

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1512]
Link "Post Gist" doesn't insert text, check Github API

**Comment by Valodim** [comment]
uugghhh. yes well, this doesn't work anymore, and I can't find a different parameter.

the flow was a stand-in for a proper gist-api based post flow anyways. but that's not a small amount of work

**Comment by Valodim** [comment]
halfway there. new interface gon be slick like you won't believe 8)
