### ISSUE TITLE
Linked Identity comments from transifex

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1514]
String: msg_lv_error_twitter_handle: This string as an odd ring to it. What do you actually mean? Dito next string.

String: linked_create_https_1_3: Should rather read &quot;Please enter the URL of a site where you are able to place a text file for proof.&quot

**Comment by Valodim** [comment]
I'm in the process of redesigning these dialogs, a ton of these strings will hopefully be out by release. If you can add a comment, maybe say that these don't need translation for now

**Comment by dschuermann** [comment]
thx
