### ISSUE TITLE
import text from qr code

### ISSUE THREAD

**Issue by mofosyne** [open-keychain/open-keychain#1516]
Would be nice if small encrypted or signed messages could be stored on paper.

**Comment by Valodim** [comment]
even small encrypted messages yield huge qr codes, I'm not sure this is possible

**Comment by dschuermann** [comment]
If you want to transmit data via QR codes between two devices consider https://f-droid.org/repository/browse/?fdfilter=qr+code&fdid=com.github.xloem.qrstream

Closing this issue, because it's out of scope.
