### ISSUE TITLE
On initial setup, Unkown key

### ISSUE THREAD

**Issue by sjug** [open-keychain/open-keychain#1517]
Hello there,

Wanted to start signing & encrypting my email via K-9 mail with OpenKeychain. However when I open the app (3.5.1) using the setup, select 'use Yubikey NEO,' then I place it on the back.

I get the correct serial number, a blank key holder, and "Unknown key, hit next to import" and "No keys found!"

However when I plug it into my laptop and check the output of 'gpg --card-status' I see all the correct information. Why is it not detecting any keys?

**Comment by Valodim** [comment]
The information on the yubikey itself is not sufficient to reconstruct the entire key. For that reason, we try to fetch the key from keyservers. If your public key is not on the keyservers, import it as a public key then try the yubikey import again.

**Comment by sjug** [comment]
It worked after a few tries. Thanks!
