### ISSUE TITLE
YubiKey: support key URL

### ISSUE THREAD

**Issue by rdoeffinger** [open-keychain/open-keychain#1521]
The YubiKeys can store a URL with the public key.
It would be nice if OpenKeychain could use that instead or in addition to relying on key servers, particularly for cases where the public key does not need to be public otherwise.

**Comment by Valodim** [comment]
sounds like a helpful feature, though not a high priority one. we are planning to rewrite secret key import in the near future, might do it then.

may I inquire though, did you put the url on the yubikey manually? also, does the url serve any other purpose besides this? "Put your key on a website, then use gpg to put the uri in the yubikey" sounds like an awful lot of manual work, if all it would do is facilitat automatic import in OpenKeychain if the key is not available from keyservers.

**Comment by crosser** [comment]
AFAIK "URL of public key" is part of OpenPGP Card standard. If you care to put your keys to an OpenPGP card, you might care supply the the URL as well. I did :)

If you rely on some app (like Openkeychain) to put the secret keys on the card, and that app publishes the public key somewhere (sks-keyservers/keybase/...), that app could also put the URL of that place to the card. This way you make it transparent for the "normal user", and flexible enough for people with special requirements.

Sidenote: one potential use case for the URL on the card is, when you meeting someone in person, you can let them scan your OpenPGP card and subsequently fetch your public key from the URL. (If you want to accept the risk of them covertly using your card for decryption/signing at that moment. They'd need to know your PIN for that of course.)

**Comment by rdoeffinger** [comment]
I won't claim this is a even remotely important feature, but a few comments as to why I would prefer that approach:
1) Putting your key on a website is trivial if you have one, e.g. one scp command. And you should do something like that anyway to have a backup. Even if you don't have a website, any cloud storage with public folders will do. Plus the fact that some email addresses are flooded with fake keys on the key servers is a good reason to have the key on a web site anyway. Also, most web sites have better uptime than the key servers (used to?).
2) As mentioned for compatibility with less intelligent programs it is useful to do. And it seems like GnuPG is one such, at least I have always uses "gpg --card-edit" "fetch" which uses this URL. In theory you could use a key server http query URL, but my last experience with that is that they are broken about as often as they are working.
3) I haven't tried lately, but in the past key servers did not like keys without (valid) email addresses. Not all keys are connected to some email address (e.g. because they are only used for ssh/VPN login), and thus key servers are problematic to use.

Aside:
> They'd need to know your PIN for that of course
Considering the security track record and how many of the YubiKeys out there are vulnerable to that one attack, no, probably they won't need your PIN for that.

**Comment by Valodim** [comment]
just general comments:

on 1) "one scp command" is *not* trivial. also, a uri to download from is just as unique as a fingerprint to use from keyservers, so there is no difference in security

on 3) at least one user id packet is required in the openpgp standard, although a user id can be anything, doesn't need to be an e-mail address

**Comment by Valodim** [comment]
superseded by #1587
