### ISSUE TITLE
YubiKey NEO decrypt taking minutes

### ISSUE THREAD

**Issue by marix11** [open-keychain/open-keychain#1525]
Hi,
Sometimes its working fast. Sometimes it takes minutes to hold yubikey. Preparing steams takes ages. What i am doing wrong

**Comment by dschuermann** [comment]
This depends on factors we can not really influence:
* NFC chipset
* NFC antenna placement of your smartphone manufacturer
* firmware blob
* Android version (simplified: higher Android version -> better NFC stack)

**Comment by Valodim** [comment]
what do you mean by "Preparing streams"? is that the progress message which takes a long time?

also, does this happen when you decrypt from k-9, or in OpenKeychain itself?

**Comment by marix11** [comment]
Its in openkeychain itself. It happens after you enter yubikey pin and you hold yubikey. Sometimes its just few seconds, sometimes its taking few minutes. "Preparing streams" and some circle rotating that time. Galaxy s4, latests cm12.1 nightlies

**Comment by dschuermann** [comment]
@marix11 Just to make sure: This happens after the yubikey dialog is closed? Does it depend on the size of the encrypted file?

**Comment by marix11** [comment]
It happens after you enter pin code for yubikey. And doesnt depend on size, just small text encrypted

**Comment by dschuermann** [comment]
@marix11 Sry, but I am still confused by your statement. There are two rotating circles. One is inside the Dialog that is shown **while** you hold the yubikey against the device. And the other one is shown **after the dialog is closed**. At which point does it take time?

**Comment by marix11** [comment]
While you hold the yubikey. At first i thought my nfc not working, but it works after one or two minutes

**Comment by crosser** [comment]
I don't know if it's related or not, but sometimes when communication fails when I take the key away too fast, or touch too far away from the sensor, the device stops responding to NFC for a few minutes, with any NFC-aware program. In [this log](https://drive.google.com/open?id=0ByShPJfR4k84cUxqNmJQVHRIZlE) I first make a good contact, and then a "bad" one. By the end of the log, the device is not responding to the touch of the key.

**Comment by Valodim** [comment]
actually, I think "Preparing streams" shows up only after the yubikey dialog is closed, so something is still wrong here

**Comment by dschuermann** [comment]
"Preparing streams" is shown in the background even when the Dialog is still in displayed.

**Comment by dschuermann** [comment]
Now that we found out we are talking about NFC problems: which device, android version and ROM are you using?

**Comment by marix11** [comment]
Mine s4 9505, cm12.1 latest

**Comment by crosser** [comment]
Mine is Sony z3 w/vendor ROM (Android 5.1.1), Openkeychain 3.5.1. (But what I reported is probably unrelated. I don't see any "preparing streams".)

**Comment by mezinster** [comment]
GoogleNexus4
CM 10.2.1-mako
Android 4.3.1
Android Core 3.4.0
OKC 3.5.1

Tested that when it takes a lot of time to perform an operation with Yubikey
it's fairly enough to re-enable NFC support in android settings [on and off] (sometimes it's necessary to do a couple of times).

**Comment by mezinster** [comment]
Reflashed my Nexus 4 to the latest Official 5.1.1 (LMY48M).
Works like a charm!
So it's definitely related to a Driver\NFC stack issue in a firmware

**Comment by marix11** [comment]
Hi, me back to this issue. Cm12.1 i can use yubikey like 1/10 times succesfully. Just hear sound it trying to do smth but nothing.  Cm11 working very good. Same phone, i was testing different cm versions
