### ISSUE TITLE
Install from Google Play: Error 504

### ISSUE THREAD

**Issue by Thijxx** [open-keychain/open-keychain#1527]
When I try to install this app I get unknown error 504.

My connection is not slow or poor. Of 164 apps, this is the only app I cannot install and the error occurs at installation, not at download. I cannot stress this enough, it is not a connection problem.
This device is completely wiped, it didn't make the error go away.

Ulefone Be Touch 2
Android 5.0
Kernel 3.10.61
Build: 20150803_2210

I've installed the app on an other device without a problem. So it's not my aura :D

**Comment by dschuermann** [comment]
You are the first to encouter such a problem with OpenKeychain. In which country are you currently and which provider are you using for Internet access? Have you tried to download via wifi?

**Comment by dschuermann** [comment]
Try this:
Method 1:

Go to Settings>> Application Manager or Apps>> open "All" apps

From the list find Google Play Store >> clear data and clear cache

Find Google Service framework(Google Play Services) from the list>> clear data and clear cache

Now install or, update app from Play Store

Method 2:

Navigate to System Settings>> Accounts>> Google>> Remove gmail account

From Settings>> Apps>> All> Force Stop then clear data and cache from Play store, google service framework (google play services) and download manager (like in method 1)

Again go to Settings>> Accounts>> Google>> add your gmail account

Restart your Android device then accept all Google terms and setup Google settings

Re-run Google Play Store and update or, install app.


from http://www.ibtimes.co.uk/how-fix-google-play-store-errors-android-device-list-issues-fixes-1447208

**Comment by dschuermann** [comment]
Got this via Google Play comments:
>  Why oh why can't I install this app. Error 504 all the time. Connection is perfect and it's the only app not installing.  Gateway errors for multiple days and only for a single application do not exist. It does not install via desktop browser, I have enough free space (40GB), re-adding Google account and clearing caches did not provide a solution. Complete device wipe and re-install didn't work. Even ripped the apk and tried manual installation, did not fly. Only app I cannot install.  May be an Android bug and not the developers fault, made it 3 stars to ease the pain.

**Comment by dschuermann** [comment]
> Complete device wipe and re-install didn't work. Even ripped the apk and tried manual installation, did not fly. Only app I cannot install.  Networks I used, in the Netherlands are: KPN, Ziggo and some fiber company. May be an Android bug and not the developers fault, made it 3 stars to ease the pain.

**Comment by Valodim** [comment]
ask google play support, maybe?

**Comment by dschuermann** [comment]
Considering the last information from his reviews, it's definitely Google's fault. Not our, not his providers. Thus, closing

**Comment by santosh7788** [comment]
Even i have same problem ...all apps are installing except one app...that to while installing.......

**Comment by dschuermann** [comment]
@santosh7788 Please try to install OpenKeychain using F-Droid: https://f-droid.org/
