### ISSUE TITLE
How to delete key to which I have forgotten password 

### ISSUE THREAD

**Issue by countesscvs** [open-keychain/open-keychain#1532]
Pardon my ignorance.
I am only an end userqof the app, not a developer.

I have forgotten the password to this key:
a81bfa146a90c62d0a740280677ec7a617ff39ed
And now I cannot delete & upload.

Any suggestions?

New my already generated,  but would like o remove this from my linked contact card.

Thanks in advance, everyone.

**Comment by adithyaphilip** [comment]
If you've forgotten the password to your key, you will not be able to revoke and upload, since revocation requires it. If you simply want to delete the key from your device (and the linked contact) but not revoke it on keyservers (people who search for your key will still think it's valid, until it say, expires), you may proceed with:
* Tap on a key, and select delete from the menu like you did earlier.
* Click on the spinner which says "Revoke and Upload" and select "Delete Only" from the drop down box. Now click on the "DELETE ONLY" button.
* This will open a new dialog, click on "DELETE". This removes the key from both your device and the linked contact.

Please note, this is only a last resort. If you happen to have made a revocation certificate for your key, you can still export the key from your device, apply the revocation certificate on the key on a desktop/laptop using a program like `gpg`, and then upload it to a keyserver from there.

However, if you haven't made a revocation certificate and are sure you won't be able to retrieve the password, deleting the key is the way to simply remove it from your device.

**Comment by countesscvs** [comment]
Also, I do hope deletion keeps my current messages in my device available. Unfortunately, I am a Countess who just communicated with these keys to various royalty and nobility worldwide. 

The perpetrators of this type of cyber attack are attempting to make it appear as if I am unorganized, forgetful, incompetent, hysterical and/or in need of medical or psychiatric care. (None of which are true.) I guess they do not understand that I am not in line for the throne of the Queen of England. 

Sad, but true.

Sincerely, Christina von Siebenbürgen 

On Sep 16, 2015, Adithya Abraham Philip <notifications@github.com> wrote:
>If you've forgotten the password to your key, you will not be able to
>revoke and upload, since revocation requires it. If you simply want to
>delete the key from your device (and the linked contact) but not revoke
>it on keyservers (people who search for your key will still think it's
>valid, until it say, expires), you may proceed with:
>* Tap on a key, and select delete from the menu like you did earlier.
>* Click on the spinner which says "Revoke and Upload" and select
>"Delete Only" from the drop down box. Now click on the "DELETE ONLY"
>button.
>* This will open a new dialog, click on "DELETE". This removes the key
>from both your device and the linked contact.
>
>Please note, this is only a last resort. If you happen to have made a
>revocation certificate for your key, you can still export the key from
>your device, apply the revocation certificate on the key on a
>desktop/laptop using a program like `gpg`, and then upload it to a
>keyserver from there.
>
>However, if you haven't made a revocation certificate and are sure you
>won't be able to retrieve the password, deleting the key is the way to
>simply remove it from your device.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/1532#issuecomment-140682114

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by countesscvs** [comment]
Thank you very much for your help. I do not relish the delete only option as that allows 3rd party use until I revoke and upload. And I no longer have a working computer. It is a long story. But let me paraphrase simply for your entertainment while I impart a modicum of information. I have ascertained that there is someone who likes to toy with me and my device on a personal level. Why? Just today I awoke to find that my password on this device (not the one which my question pertains to) had mysteriously become "incorrect ". This one I did not forget. I went to PgP signatures due to 5 years of password hijacking by keyloggers and remote team viewers and remote accesses. Now they have progressed to my 16 digit pin encrypted screen lock and my pgp passwords. These are things reputable developers would never stoop to. Unfortunately, my "fans" (and I use that term loosely in a quite sarcastic way), do not know when a one-time prank turns into cybercrime. Five years is more than enough,
don't you think? It feels like I am a remote digital pseudo toy for a development team composed of only obessive-compulsive, autistics and... (whatever that psychiatric condition is where the person attempts to kill everyone around you because you do not return their affections). And that, my hard-working developer friends, is what being a popular poet, photographer, music journalist and fine artist is like when you are active on social media linked to RSS Graffiti. Over 5 years, my contacts in my industry have all been lost to me, my online blogs and magazine messed with until offline, and personal financial accounts bothered repeatedly. Fame, hard-worked-for and backed up by natural talent, oftentimes brings out the worst in people. Thanks for understanding and helping me with your instructions. Sincerely, Christina von Siebenbürgen 

On Sep 16, 2015, Adithya Abraham Philip <notifications@github.com> wrote:
>If you've forgotten the password to your key, you will not be able to
>revoke and upload, since revocation requires it. If you simply want to
>delete the key from your device (and the linked contact) but not revoke
>it on keyservers (people who search for your key will still think it's
>valid, until it say, expires), you may proceed with:
>* Tap on a key, and select delete from the menu like you did earlier.
>* Click on the spinner which says "Revoke and Upload" and select
>"Delete Only" from the drop down box. Now click on the "DELETE ONLY"
>button.
>* This will open a new dialog, click on "DELETE". This removes the key
>from both your device and the linked contact.
>
>Please note, this is only a last resort. If you happen to have made a
>revocation certificate for your key, you can still export the key from
>your device, apply the revocation certificate on the key on a
>desktop/laptop using a program like `gpg`, and then upload it to a
>keyserver from there.
>
>However, if you haven't made a revocation certificate and are sure you
>won't be able to retrieve the password, deleting the key is the way to
>simply remove it from your device.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/1532#issuecomment-140682114

-- 
Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by Valodim** [comment]
Um actually, deletion does not keep the messages available. The entire idea of encryption using keys is that a message can't be read without the correct key, so if you delete it the message will be unreadable...

**Comment by countesscvs** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

It's okay then. I only signed it, not encrypted it.

On Sep 16, 2015, Vincent <notifications@github.com> wrote:
>Um actually, deletion does not keep the messages available. The entire
>idea of encryption using keys is that a message can't be read without
>the correct key, so if you delete it the message will be unreadable...
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/1532#issuecomment-140923216

- -- Sent with K-@ Mail - the evolution of emailing.
-----BEGIN PGP SIGNATURE-----

iQI5BAEBCgAjHBzCqUN2Uy4xIDx0YWIuY3ZzQGdtYWlsLmNvbT4FAlX5+esACgkQ
UNn+7xEB6XH+MQ/9Gk2ypUIq5Eb4QRnDkPkje9BU/pISpdQ5q95Tvp2thtF20Pef
e8qR7zKHdKiX0d7uov4GC35Q5Lwf9nFmQvMhehY1Sxr63KwdfFSQvT0P7ct8Ofjb
ueLbxA620LSUt1rYfEeh9OKX4PM5mjiydYiZu+kjjtuAXbVnsVgIb8V02C7T31Fv
TfzUpaHeOLPLTj/sOmsNHGVQGH91IPwy44fA7+0VT8adTHBG+uCuXtI/EAtenWXu
Ne6gozM0q/z8BfOjhJCRhRjN4DX5Ock0/mDnapLBNQyYbvkqs85peZUWSZ5FERH9
hddyqJ+qF/7r6eYxC/nqt0HXCE1AK9BS3RfMq5sAAQk4bkdV9JFDAauL5kphejmz
kgDAuVnIltM8rlYD00K/dG8lzEgJGxz0sEevfBa0i/xZTJu0+IPHIHycfExr7RaY
MbBEhnnq/Yf+KxieljbXqvjYezdGrjENzkKkCJpHCTPZW/rOYFsV6dSw9dPThbGg
827BCrbmYsBv+ULrNnlcuya1Amr1FVuiCgKdI4P7+7TSzOcYhRUoyqsSgt5NpweJ
E817Dl6krSrkcw98P401SGtyGKU+v1EgmrSBfxs2vbl8P2bYHnTz0fnAcbnFxsV0
08qR1cqkVIvm0ULuhejpnA0O0IsCvvuH/ovX8iEWcyWchSmv+LUauSzylAU=
=K6VE
-----END PGP SIGNATURE-----
