### ISSUE TITLE
Support Ed25519/EdDSA

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1533]
Unfortunately, the EdDSA GSoC project didn't make it, but there is some code left to pick up development for others:

Old GSoC code:
- https://github.com/open-keychain/spongycastle/tree/eddsa
- https://github.com/open-keychain/open-keychain/tree/eddsa

Issues:
- https://github.com/open-keychain/open-keychain/issues/1283
- https://github.com/open-keychain/open-keychain/issues/1279

**Comment by Valodim** [comment]
This was finished in #2053 a while ago
