### ISSUE TITLE
RSA key no longer working in open-keychain, unable to send gpg mail

### ISSUE THREAD

**Issue by linkp** [open-keychain/open-keychain#1537]
Expectation:
K9 signs & encrypts email like it used to

Reaility:
K9 throws the following error:
OpenPGP Error: Attempt to invoke virtual method 'org.spongycastle.openpgp.PGPPublicKey org.spongycastle.openpgp.PGPSecretKey.getPublicKey()' on a null object reference

Examining the subkeys of my key in open-keychain appears to indicate that some expected properties are missing from the imported key.

![screenshot_2015-09-17-18-01-45](https://cloud.githubusercontent.com/assets/3360118/9949062/7cfc3e34-5d66-11e5-9797-fc3a60fc5deb.png)

**Comment by Valodim** [comment]
the flags of the key are 0x23, which is cert+sign+auth, and there doesn't seem to be a bad cert on it which could lead to this behavior. I'll investigate.

**Comment by Valodim** [comment]
yet another manifestation of #996, #1026 and #1003, this was solved with a fresh export from a more recent version of gpg

**Comment by linkp** [comment]
Re-exporting the key (Thunderbird 38.2.0/Enigmail 1.8.2/gnupg2  2.0.22-3ubuntu1.3) and copying it to my Android for re-import resolved this for me.
