### ISSUE TITLE
Can't import Key from GPG Keychain

### ISSUE THREAD

**Issue by villabacho1982** [open-keychain/open-keychain#1545]
Hi, I just downloaded the latest version of GPG Toolkit and created two keys for my email accounts.
When I export these keys to .asc files, transfer them to my phone via usb and try to import them to open keychain, I get a message that there are no keys there.
I can select the file but nothing happens when I hit import..

I read about issues with older gpg versions but I think I have the latest version..

**Comment by Valodim** [comment]
hmm, this is not a lot of info for diagnosis.

I assume you are talking about your secret key. can you try exporting your public key and see if that one can be imported from file? if that doesn't work just like for your key, you can send us the public key so we can investigate what's wrong with the data.

**Comment by Valodim** [comment]
had a similar case in IRC, it boiled down to line ending incompatibiliy

**Comment by dschuermann** [comment]
I assume this is the same as https://github.com/open-keychain/open-keychain/issues/1409 , closing.
