### ISSUE TITLE
Open-Keychain is not detected as a cryptography provider by Kaiten Mail

### ISSUE THREAD

**Issue by cajuntechie** [open-keychain/open-keychain#1551]
When going to the cryptography section of Kaiten Mail (supposedly the same as K-90), only APG is seen as a cryptography provider. I'm not sure if this is an integration problem with OKC or Kaiten so I'm reporting the issue to both.

**Comment by dschuermann** [comment]
It's a problem for Kaiten, which is closed source, thus closing here.
