### ISSUE TITLE
warn when stripping master key

### ISSUE THREAD

**Issue by muzirian** [open-keychain/open-keychain#1554]
Stripping master key renders tge key chain useless, cant revoke the keys or even modify anything for that keypair on openkeychain. So users should be warned when stripping master key. Warning may give option to revoke the keypair before the action, like the app does when deleting keypairs. creating another key if it make any sense :p

**Comment by Valodim** [comment]
makes sense. iirc, we don't even explain what stripping does in the first place...

**Comment by vhazali** [comment]
Hello, I see the tdjogi010 is no longer working on this issue, if it's alright I'll pick up from where he left off? It's actually only left with the refactoring of the case statement?
