### ISSUE TITLE
option to selectively import/export subkeyes

### ISSUE THREAD

**Issue by muzirian** [open-keychain/open-keychain#1555]
Feature request for selective import and export of subkeyes.
For example encryption key alone can be exported and then imported to another machine for encryption,without saving master key in that machine.

Also option to list included keys when importing so only needed keys can be imported, keeping unnecessary keys away/ofline from the phone.

**Comment by Valodim** [comment]
first off, it's important to note that we don't expect regular users to deal with subkeys at all. that is why these things are somewhere deep in the "extended" dialogs.

about the feature request itself, I'm not convinced of either scenario. to seriously "keep keys offline", they should not be transferred to the phone in the first place. it's also possible to strip subkeys, just not as part of the import process. the other direction seems like an even less common use case, exporting *from* the phone *to* a different machine which isn't supposed to have the whole key?

**Comment by muzirian** [comment]
It seems that there is slight difference between importing selectively than stripping keys after importing.
Anyways it was just a suggestion.
Thnx for the reply. :)
