### ISSUE TITLE
App crash when backup

### ISSUE THREAD

**Issue by muzirian** [open-keychain/open-keychain#1556]
aspp crashes when tries to backup keyring with a stripped masterkey

**Comment by Valodim** [comment]
are you using a play store/fdroid version, or current development?

**Comment by muzirian** [comment]
playstore now.
will try the fdroid version and update

**Comment by muzirian** [comment]
Tried fdroid version, it crashes too

**Comment by Valodim** [comment]
this behavior is already fixed in the backup activity (35b9dabc), but I did indeed overlook this problem in ViewKeyActivity. fixed in 3316cb6, thanks for your report!
