### ISSUE TITLE
SpongyCastle build failure

### ISSUE THREAD

**Issue by YodaTheMagistr** [open-keychain/open-keychain#1557]
Hello,

i'm trying to compile Openkeychain from source with libs downloaded from source e.g. spongycastle:
https://github.com/rtyley/spongycastle

So. Clone rtyleys git repo, copy spongycastle to open-keychain/extern/spongycastle, compile.

When i'm trying to compile with ./gradlew assembleDebug i have this error:

```
...
...
Creating configuration testReleasePublish.
Creating configuration testReleaseProvided.
Creating configuration testReleaseWearApp.
Evaluating project ':extern:spongycastle:core' using build file '/home/administrator/apps/open-keychain_clean/extern/spongycastle/core/build.gradle'.
Evaluating project ':extern:spongycastle:pg' using build file '/home/administrator/apps/open-keychain_clean/extern/spongycastle/pg/build.gradle'.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/administrator/apps/open-keychain_clean/extern/spongycastle/pg/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':extern:spongycastle:pg'.
> Project with path ':core' could not be found in project ':extern:spongycastle:pg'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 8.137 secs
Stopped 0 compiler daemon(s).

```

What's the difference between spongycastles? Yours and rtyleys?

Thank you.

**Comment by dschuermann** [comment]
Our spongycastle is at https://github.com/open-keychain/spongycastle . Just look at the commits to see the difference. There is no need to clone it manually. Follow step 2 of https://github.com/open-keychain/open-keychain#build-with-gradle
