### ISSUE TITLE
Cannot decrypt messages generated by gpg4usb

### ISSUE THREAD

**Issue by pguizeline** [open-keychain/open-keychain#1565]
Hello,

First let me apologize if this issue is not related to OpenKeychain and it's a gpg4usb problem.

When trying to decrypt emails encryoted via gpg4usb I get the following error:
"OpenPGP Error: Encountered an error reading input data!"

**Comment by Valodim** [comment]
hi, thanks for reporting!

can you send me the data, or an encrypted test message via mail? that would be tremendously helpful -> look@my.amazin.horse

**Comment by Valodim** [comment]
received your mail. the data contains extra newlines, but otherwise looks ok.

can you describe exactly how you processed the mail? these extra newlines shouldn't be there, and I'm curious how they got in. did you maybe copy/paste the data, or open them with an editor at some point?

**Comment by pguizeline** [comment]
Hi Vincent, 

I used gpg4usb composer to write the message, then encrypted it, copied and pasted onto Gmail web interface composer. Maybe that's what's generating those extra lines that you've detected 

Thanks for all the help!

**Comment by Valodim** [comment]
same issue as #1409. these newlines shouldn't be there, but I suppose it makes sense after more than one report that we change our parser to handle this case.

**Comment by dschuermann** [comment]
closed due to duplicate in  #1409.
