### ISSUE TITLE
Translation - German - Notifcation Message

### ISSUE THREAD

**Issue by schmitt-stefan** [open-keychain/open-keychain#1566]
Notification displayed:
>1 Passwort gemerkt
>Berühren um Passwörter zu lehren

Notification as should be:
>1 Passwort gemerkt
>Berühren um Passwörter zu leeren

"lehren" means to teach,
"leeren" means to empty
The function is to empty the stored passphrases.

**Comment by Valodim** [comment]
if you'd like to contribute, you can directly improve translations at our transifex project:

https://www.transifex.com/sufficientlysecure/open-keychain/

all improvements will be included in the next release :+1:

**Comment by schmitt-stefan** [comment]
Ok. Just found the translation and it was already changed.
