### ISSUE TITLE
Feature Request: Decrypt PGP Message with already decrypted Session Key

### ISSUE THREAD

**Issue by TheRealDashu** [open-keychain/open-keychain#1569]
I would like to use Openpgp Api with a smartcard in which i hold private keys. The Smartcard will decrypt
the Session Key and the Android device will decrypt the rest of the Message.

**Comment by Valodim** [comment]
this should be fairly easy, if we allow passing a map of encrypted->decrypted session keys as parameter, as is already done internally in CryptoInputParcel

**Comment by Valodim** [comment]
feature requester didn't get back to me about some clarifications. without someone actively requesting it for a particular purpose, I don't think we should implement the feature
