### ISSUE TITLE
Remove org.apache.http dependencies in LinkedTokenResource etc.

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1570]
org.apache.http has been deprecated in SDK 23. We currently use a legacy dependency for this support, see https://github.com/open-keychain/open-keychain/commit/67a51cdfe3f6fb7982b27eb2b6d4b1b5d49f69aa

**Comment by Valodim** [comment]
what's the recommended alternative?

**Comment by dschuermann** [comment]
UrlConnection

**Comment by Valodim** [comment]
ah, yes. I already did that in the relatively new code in `LinkedIdCreateGithubFragment`, the code where I used apache stuff is older. will update at some point.

**Comment by dschuermann** [comment]
You could also use OkHttp btw.

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/pull/1748
