### ISSUE TITLE
Check Android 6 permissions

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1571]
We are now targeting SDK 23, thus we need to handle runtime permissions on our own.
There are some libraries with helper classes/annotations but I am not sure yet if we should use them.

**Comment by dschuermann** [comment]
We need to handle the following permissions:

* CAMERA: Done in https://github.com/open-keychain/open-keychain/commit/ccdfd55f61456baf11bcc0cf30460b75cd699403 . I don't think we need an explanation here. When the user wants to scan QR Codes, this is expected.

* Storage group (WRITE_EXTERNAL_PERMISSION): In my tests on Android 6, OpenKeychain still fully works with this disabled. I think we only need this one on Android < 4.4 for saving backups. On Android >= 4.4 we always use the ACTION_OPEN_DOCUMENT everywhere. Is this right???

* Contacts group: Needs to be handled. My proposal is to ask the user to enable automatic key update and contact linking on OpenKeychain's first start with both switches disabled (https://github.com/open-keychain/open-keychain/issues/1492). When the user switches the controls, we should directly ask for the permissions. If the user revokes these later, we can detect this on start of the service. If they are revoked we can simply disable automatic key sync and contact linking in the preferences. Maybe showing a notification that redirects the user to the preferences screen similar to the first start screen. Comments/Feedack?

@Valodim @adithyaphilip

**Comment by dschuermann** [comment]
* If we still want to support ``file://`` Uris, we need to request the READ_EXTERNAL_PERMISSION permission. See details at https://commonsware.com/blog/2015/10/07/runtime-permissions-files-action-send.html

**Comment by dschuermann** [comment]
Support for ``file`` scheme in decryption implemented in https://github.com/open-keychain/open-keychain/commit/c6ea0b6a07df0c509183e4c664b5749a264954f8
Still needs to be handled for:
* VIEW and SEND action in import
* SEND action in encrypt

**Comment by dschuermann** [comment]
BTW: All file browsers I tested (CM File Manager, OI File Manager, Amaze) are doing ACTION_VIEW with a ``file`` Uri so this is quite important.

**Comment by Valodim** [comment]
About the contacts group: Looking at #989, I'm actually leaning towards disabling contacy sync until we know what is going on there. This is not a feature of central importance, but there seems to be a bug in it which *wipe all contacts* on installation. This is not commonly reported, but also not a single freak accident we can just dismiss, and the effect is *very* serious for the affected user.

**Comment by dschuermann** [comment]
I don't see any real indicators that we are responsible for the issues described in #989. The delete operations we are doing seem to be completely okay.

**Comment by Valodim** [comment]
I don't see how this happens either, but for all we know it could be a bug in some version of android which we trigger. Either way, it was reported multiple times, and for every user who observed this behavior, connected it to the installation of OpenKeychain and filed a bug report, there are probably several more who didn't. We might be past the point where "I looked at the code really hard and can't explain the behavior" is an acceptable argument to dismiss this.

As a compromise, to mitigate the android bug theory, we could disable the feature on earlier versions of android?

**Comment by dschuermann** [comment]
Permission handling implemented for SEND action in encrypt in https://github.com/open-keychain/open-keychain/commit/0eac49775484daf9319f5982e818f9223f0adf23

**Comment by dschuermann** [comment]
Permission handling implemented for VIEW and SEND in import key in https://github.com/open-keychain/open-keychain/commit/e1b54137aae5bd7454af1c1f4ea0d43f1fe79d22

**Comment by dschuermann** [comment]
Permission handling for sync service done in https://github.com/open-keychain/open-keychain/commit/dc631e5c1542b09e1359a861e98a2c03b93e05cd and https://github.com/open-keychain/open-keychain/commit/c5bcbce28fa45d8d1e5714d111f3cc24a2c99d0e

Last TODO in other issue: https://github.com/open-keychain/open-keychain/issues/1492
