### ISSUE TITLE
"Wrong data type, expected text" when sharing from OI Notepad

### ISSUE THREAD

**Issue by aperomsik** [open-keychain/open-keychain#1574]
Before version 3.6, Open Keychain was working well with text shared from OI Notepad. Now I get the "wrong data type, expected text" toast message.

**Comment by Valodim** [comment]
Issue confirmed. I'll try to get it into a bugfix release soon :+1:

**Comment by Valodim** [comment]
forgot to mention, this was fixed in 64a09a89451b09aaa54090c2e6373814edb5d0eb
