### ISSUE TITLE
NullPointerException in OperationLog from execute

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1575]
```
java.lang.NullPointerException: Attempt to invoke virtual method 'org.sufficientlysecure.keychain.operations.results.OperationResult$SubLogEntryParcel org.sufficientlysecure.keychain.operations.results.OperationResult$OperationLog.getSubResultIfSingle()' on a null object reference
	at org.sufficientlysecure.keychain.operations.results.OperationResult.getLog(OperationResult.java:108)
	at org.sufficientlysecure.keychain.operations.results.OperationResult$OperationLog.add(OperationResult.java:924)
	at org.sufficientlysecure.keychain.operations.CertifyOperation.execute(CertifyOperation.java:234)
	at org.sufficientlysecure.keychain.operations.CertifyOperation.execute(CertifyOperation.java:66)
	at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:143)
```

**Comment by Valodim** [comment]
@adithyaphilip question about your code: you used null as a value for "no proxy", right? Was there a reason not to use `Proxy.NO_PROXY`?

**Comment by Valodim** [comment]
Regarding my previous question, I changed this to Proxy.NO_PROXY in a665dd60fbf52eccb04980bb040569967a617ebe. can you check out the code to see if I missed anything about that data flow? if you had a good reason to use null we can also revert, but I think it's cleaner this way.

**Comment by Valodim** [comment]
oh, the issue reported here is fixed in a1330f78e499840b386ea92e4280e9cdff9407f6. operations should never return null (annotated as NonNull, too), and always return their correct type (I fixed EditKeyOperation in this regard, too 1c83c33d35ae68a301c18d94c155d3bb7ddf3dd0)

**Comment by adithyaphilip** [comment]
@Valodim nope, you're right, null was used to mean "no proxy" and it's better if we use `Proxy.NO_PROXY` for it. Will go through the code to see if it's still checked against null anywhere else.

**Comment by Valodim** [comment]
aight :+1:
