### ISSUE TITLE
encrypted text is decrypted in APG but not in open-keychain

### ISSUE THREAD

**Issue by solekiller** [open-keychain/open-keychain#1582]
# i have encrypted this message:
-----BEGIN PGP MESSAGE-----
Version: 10.3.0 (Build 9060)
Comment: www.cisco.com
Charset: us-ascii
 
qANQR1DBwEwDt67c8DUIQ28BCAC24dgjVkT+07zIXOz7RPhm5pGWuIJmrzUyF59g
VTFiiykDCw0pb/YcZs8bo7blZKm4uVE7meej8EIx6AGSsnf69QB9mpz47g5VYAs/
pEfbKVA6IHx4/JpjfLp7dQlKwLeauw0a9vKPdsbytGpzBRLCdQSpRckOr2u82NqX
LcASg7JZvNrPJtmMyZG2JbsDTY7cq3N7/xuD7LjYEyK7z/8V34C+boPwwJYMZEG3
BgtlEmu5YYziUHQLwHeFL0SmSSi82N8deErMtMlUnLBx19Kr4AtkiTqegVOZaXk0
X5yEXK6I9qROschNt+wtERwGGrYbAaubYAEG1aQkYh30B0rk0kYB8ur9QmLadedj
tAbjrLGXE608mJ6FDRUur6aX5/6cbxetwELTlewfeBP73ABH9P1NMpglQRLXFUBl
ob33v8vUR3nhO+Ek
=6c7H
-----END PGP MESSAGE-----

# after removing the headers and feeding it to APG (like so) it worked:
-----BEGIN PGP MESSAGE-----
 
qANQR1DBwEwDt67c8DUIQ28BCAC24dgjVkT+07zIXOz7RPhm5pGWuIJmrzUyF59g
VTFiiykDCw0pb/YcZs8bo7blZKm4uVE7meej8EIx6AGSsnf69QB9mpz47g5VYAs/
pEfbKVA6IHx4/JpjfLp7dQlKwLeauw0a9vKPdsbytGpzBRLCdQSpRckOr2u82NqX
LcASg7JZvNrPJtmMyZG2JbsDTY7cq3N7/xuD7LjYEyK7z/8V34C+boPwwJYMZEG3
BgtlEmu5YYziUHQLwHeFL0SmSSi82N8deErMtMlUnLBx19Kr4AtkiTqegVOZaXk0
X5yEXK6I9qROschNt+wtERwGGrYbAaubYAEG1aQkYh30B0rk0kYB8ur9QmLadedj
tAbjrLGXE608mJ6FDRUur6aX5/6cbxetwELTlewfeBP73ABH9P1NMpglQRLXFUBl
ob33v8vUR3nhO+Ek
=6c7H
-----END PGP MESSAGE-----

#but it does not work in open keychain for some reason.
#(could it be because of the \r?)

**Comment by Valodim** [comment]
Huuhh. That data contains a marker packet. We used to ignore that, but now we don't for some reason? This is actually breaking a MUST of the rfc, definitely gonna fix ASAP. Thanks for the report.

**Comment by solekiller** [comment]
a marker packet? can you explain please? is it some kind of whitespace?

**Comment by Valodim** [comment]
related crash report:

```
java.lang.ClassCastException: org.spongycastle.bcpg.MarkerPacket cannot be cast to org.spongycastle.bcpg.InputStreamPacket
	at org.spongycastle.openpgp.PGPEncryptedDataList.<init>(PGPEncryptedDataList.java:52)
	at org.spongycastle.openpgp.PGPObjectFactory.nextObject(PGPObjectFactory.java:147)
	at org.sufficientlysecure.keychain.pgp.PgpDecryptVerify.decryptVerify(PgpDecryptVerify.java:332)
	at org.sufficientlysecure.keychain.pgp.PgpDecryptVerify.executeInternal(PgpDecryptVerify.java:162)
	at org.sufficientlysecure.keychain.pgp.PgpDecryptVerify.execute(PgpDecryptVerify.java:122)
	at org.sufficientlysecure.keychain.pgp.PgpDecryptVerify.execute(PgpDecryptVerify.java:81)
	at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:142)
```

**Comment by mezinster** [comment]
I cannot decrypt the message below :(
The error: Error processing OpenPGP data (No Valid OpenPGP encrypted or signed data found!)

Is it the same issue ?

-----BEGIN PGP MESSAGE-----
Version: Encryption Desktop 10.3.2 (Build 16127)
Charset: utf-8

qANQR1DBwEwD1FB1xQQt3osBB/9DR9Z3NnwI3tUQ4DOcR+vkx6ZJzCjx9Yq/i9cB
e2b9/aEya2SjLJOE9Ae6B4i7Ri+5PjxX9x9Fu4mmNWy2vK0+ysm5KOxAWt3t0VKK
Jb+xQrkBy1GCq9V64Mw1gR4o30WSyuUbBheB38xFpoN+WVIQY1w8kxrue/MnVQwj
ui+I6FTZdSC5MX3tv2f4bVa8wFCXnS0+5qBMhy49zAig8phCB/YaQxa2ywNs4wKs
C+7pKCSQ35FehsRiMOT093kDJXW6qIBxezcdffSXMjhMNG1UJQg2gg54JByy1UbT
CZiuveZ2gCWgZXBYzBj3onxPKogfPqiTf2qp1k00BSUnxeNY0lABGxkykWULU7vT
VQ/c14Jhzz/p9XtBhTQ3CtoaUe1lUkDVEF1OPiAjXDvCFYSQdmbw6rMWo30ZSQYZ
8ED0HJWYRNwh9JpyaTv9srRA6VEmHw==
=M2hk
-----END PGP MESSAGE-----

**Comment by Valodim** [comment]
yup, same issue.

@solekiller how's the fix coming along?

**Comment by mezinster** [comment]
Anybody's trying to fix the issue ?
I am not urging in any way, but if it is really important - it would be nice to know that at least some developer's attention is attracted.

**Comment by Valodim** [comment]
Solekiller said he wanted to take a shot at it, but since he didn't reply in a couple of days I'm gonna do it. we will try to get a bugfix release out sometime this week.

**Comment by Valodim** [comment]
done

**Comment by solekiller** [comment]
oh sorry, I didn't get the chance, too busy at work.
i will test your solution though and report back.

**Comment by solekiller** [comment]
once i figure out how to build this thing.

**Comment by Valodim** [comment]
the readme has a step-by-step :)
