### ISSUE TITLE
Blackberry Q10: "Tag does not support ISO-DEP"

### ISSUE THREAD

**Issue by singpolyma** [open-keychain/open-keychain#1590]
Using Openkeychain on my Blackberry Q10, when I try to use my new yubikey neo it says

    Tag does not support ISO-DEP (ISO 14443-4)

What does that mean?

**Comment by dschuermann** [comment]
Looks like Blackberry does not implement the full NFC stack.
This error is shown when ``IsoDep`` is null. See http://developer.android.com/reference/android/nfc/tech/IsoDep.html#get(android.nfc.Tag)

This should obviously work with the YubiKey NEO, thus I guess it's the Blackberry.

**Comment by singpolyma** [comment]
I've asked about this in the dev forums: https://rim.i.lithium.com/t5/Android-Development/IsoDep-support/td-p/3145919

**Comment by Valodim** [comment]
perfect, thanks a lot! we will add a warning about this if it turns out that it's actually a blackberry problem. could just be a quirk of the system that we need to do something differently there. we don't have a blackberry development device though so we can't test for compatibility outselves

**Comment by Valodim** [comment]
well that first answer wasn't particularly helpful. let's hope for a reply to your follow-up

**Comment by dschuermann** [comment]
We can not do much about this problem, so I will close this issue. The Blackberry Q10 is also a rare device to be used with OpenKeychain.

**Comment by Valodim** [comment]
no response from the blackberry devs, either.
