### ISSUE TITLE
First Line of Text Followed by Empty Line is Swallowed After Decryption

### ISSUE THREAD

**Issue by smaragd** [open-keychain/open-keychain#1592]
I have reproduced this on multiple devices running OpenKeychain 3.6.1:
* Google Galaxy Nexus on Cyanogenmod 11
* Google Nexus 7 on Cyanogenmod 12.1

It does not matter how the text was encrypted, but for reproducing this problem, I take the following steps, all within OpenKeychain:

### 1. Enter several lines of text

In OpenKeychain's encrypt mode, select the ```Encrypt text``` option. Enter the following lines of text, leave a blank line between each text line:
```
Line One

Line Two

Line Three
```

### 2. Encrypt and sign to clipboard
Pick your own GPG key and encrypt and sign it.

### 3. Decrypt and display text
Go back to decrypt mode and select ```Read from clipboard``` to verify and decrypt what you have just encrypted. The signature validation is successful, but the shown decrypted text is missing the first line of text and the first blank line. Instead, it shows this:
```
Line Two

Line Three
```

It seems to be important that there is a blank line after the first line, because if you have no blank lines in the plain text, as in
```
Line One
Line Two
Line Three
```
then it works as expected and shows all three lines after encrypting and decrypting.

This is particularly annoying if an encrypted email response is just one line long, followed by a blank and the original quoted mail. All you get to see after decryption is the quoted mail, but the one-liner reply cannot be read. Decrypting the same ciphertext in a different tool shows that first line just fine.

### Screenshots
The following screenshots show the entered text just before encryption, and the immediately decrypted text with the first line missing.

![openkeychain_1](https://cloud.githubusercontent.com/assets/2957772/11161397/75bd1f0c-8a49-11e5-8eaf-ce4289af75f8.jpg)

![openkeychain_2](https://cloud.githubusercontent.com/assets/2957772/11161398/81111368-8a49-11e5-9752-0efbd8b3f88e.jpg)

**Comment by Valodim** [comment]
first guess, this happens when the first line is wrongly recognized as a MIME header. will look into it, thanks for reporting!

**Comment by Valodim** [comment]
should work now :+1:

**Comment by smaragd** [comment]
Awesome! :clap:

**Comment by piater** [comment]
Why does OpenKeychain have to take guesses about whether "the data we get is actually MIME"? OpenKeychain cannot know and should not have to care. It should just decrypt the data it is asked to decrypt.

I keep my passwords in GPG-encrypted files, and OpenKeychain does a wonderful job for this use case (thanks and kudos!) - but these files happen to be formatted in a way that in most (but not all) cases, OpenKeychain drops all leading lines up to and including the first blank line.

If, for some reason, OpenKeychain must take care of what I think is the caller's business, can this behavior be made configurable? I'd simply turn it off.

**Comment by dschuermann** [comment]
@piater OpenKeychain does this to be able to decrypt and parse "attachments" from email apps that do not support OpenPGP themselves, such as GMail. Can you please open a new issue about your problem with an example? This issue here is old and closed
