### ISSUE TITLE
In Backup UI, add link to in-app help: "How to import this?"

### ISSUE THREAD

**Issue by JasperWeiss** [open-keychain/open-keychain#1595]
Backed up keys can not be imported on other systems. Why can one not simple export the private key and import it somewhere else as opposed to a openkeychain compatible only backup?

**Comment by Valodim** [comment]
The key backup is simply encrypted with pgp - nothing OpenKeychain specific about it. You can decrypt and import it in gpg. Check out `How to import an OpenKeychain backup with gpg?`

**Comment by JasperWeiss** [comment]
Sorry for that, the password in openkeychain is entered in blocks with - in between. How should the encryption key be entered in the terminal?

**Comment by Valodim** [comment]
Just like that, with - inbetween.

Hmm. I wonder how this can be made clearer, I can see how it is not entirely obvious...

**Comment by JasperWeiss** [comment]
I do think it's a great idea to encrypt it with a password before exporting it. I especially like how you have to retype it to make sure you actually wrote it down. The - in between makes it way more convenient to copy aswell.
It's just that it isn't really clear how to import it. But it should be kept this way though, way more secure this way. People will just have to use their brain and check the faq :)

**Comment by Valodim** [comment]
I'm thinking about adding a shortcut to the relevant FAQ entries to the activity. We do have the FAQ available in-app already, it's just not very accessible. Maybe with a `?` icon in the top right?

Thoughts @dschuermann?

**Comment by JasperWeiss** [comment]
More obvious would be a link that says "how do Import this backup on gpg?" Or something along those lines.

**Comment by Valodim** [comment]
we'll see what we can do about this. thanks for your feedback :+1:

**Comment by dschuermann** [comment]
@Valodim what about adding a link/button into the last Fragment with the title "How to import this in my Desktop PC?" linking to in-app help. I think a "?" will not be enough.

**Comment by Valodim** [comment]
sounds good

**Comment by JasperWeiss** [comment]
@dschuermann that'd be great, kind of what I meant actually.

**Comment by TedaLIEz** [comment]
I think I can do some help with this, but I couldn't find *How to import an OpenKeychain backup with gpg?* in-app and I found it in the web page.Does the faq text in-app not complete?

**Comment by rohands** [comment]
Why is the issue open yet? Does the patch need more working on it  or has it not been reviewed yet?

**Comment by dschuermann** [comment]
@rohands has now been reviewed

**Comment by TedaLIEz** [comment]
Somehow I failed the CI build, and I have no idea about the result.What should I do about that?

**Comment by dschuermann** [comment]
@TedaLIEz Not your fault, we need to fix the CI build, haven't found time to do it.

**Comment by TedaLIEz** [comment]
@dschuermann All right.And I want to know whether using openJDK is necessary, I have some problem to get openJDK on my mac OS X :)
