### ISSUE TITLE
Openkeychain didn't return any key on ACTION_GET_KEY

### ISSUE THREAD

**Issue by Polynomdivison** [open-keychain/open-keychain#1596]
Hi,
I tried the pgp-mime support of k9-mail with OpenKeychain 3.6.1.
Everything works except: attach my public key.

Error message:

    OpenPGP Error: Your Openpgp Provider didn't return any key on ACTION_GET_KEY, contact them.
    Uncheck "Attach my public key" to proceed.

https://github.com/k9mail/k-9/pull/884

**Comment by Polynomdivison** [comment]
Sorry.
See:
 open-keychain/open-keychain@89d016c

**Comment by Valodim** [comment]
yup, that commit is only seven days old. bleeding edge openkeychain for a bleeding edge k-9 :+1:
