### ISSUE TITLE
wrong signature for own key

### ISSUE THREAD

**Issue by minges** [open-keychain/open-keychain#1601]
On my Samsung S4 mini (Android 4.4.2) I experienced the following issue:

After setting up open-keychain and importing my keys from the PC I sent out a signed test e-mail from my smartphone to one of my accounts using K-9 Mail and open-keychain.

The e-mail ended up in my PC-account and was read with Thunderbird and Enigmail running on Windows 7.

The signature was recognised as valid. So at first glance everything seemed fine.

The copy of the same message in the outbox of K-9 Mail was diagnosed of having a wrong signature!

Sending a signed e-mail from the PC to the smartphone is again recognised as validly signed by Thunderbird / Enigmail and diagnosed wrongly signed on K-9 Mail. All with the same account information and using the same keys.

I would really appreciate any hint on how to make this one way street into a truly working two way communication.

Thanks!
Roland

**Comment by Valodim** [comment]
can you send a signed message to me? I might be able to see what's up if the signature is broken for me as well. -> look@my.amazin.horse

**Comment by minges** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

this is the requested signed test-e-mail.

You should find my public key on one of the key servers in the web.

Thanks!

Roland


- --
___________________________________________________
Prof. Dr. Roland Minges Tel: +49 (1 71) 752 8848 Raiffeisenstrasse 8 Fax: +49 (1 71) 13 - 752 8848 D-73527 Schwäbisch Gmünd skype: roland.minges www.RolandMinges.de mail: 42@RolandMinges.de PGP Key ID (DH/DSS): 0xA4681B0F

Am 19. November 2015 15:34:07 MEZ, schrieb Vincent <notifications@github.com>:
>can you send a signed message to me? I might be able to see what's up
>if the signature is broken for me as well. -> look@my.amazin.horse
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/1601#issuecomment-158074215
-----BEGIN PGP SIGNATURE-----

iGoEAREKACojHFJvbGFuZCBNaW5nZXMgPDQyQHJvbGFuZG1pbmdlcy5kZT4FAlZN
4nEACgkQZ2UQhKRoGw+CuwCgqNy96dBHFOWJKDbETstflO3rYCcAoN6W9K5cqx3Z
dS+tTnApilTThvq7
=w70d
-----END PGP SIGNATURE-----

**Comment by Valodim** [comment]
Phew, ok here we go: The signature is valid, but doesn't pass the check if the crypto is still considered secure. More specifically, it is a DSA 1024 bit key, where we [require at least 2048 bit strength](https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSecurityConstants.java#L123) to consider the signature secure.

It was a tough decision, but DSA 1024 keys are long past their due date (check out [keylength.com][keylength.com], dsa 1024 is roughly in the category "ok to use until 2010"), so we really don't feel comfortable displaying their signatures as secure anymore. An obvious bug is that this is not yet displayed in a good way in K-9, where it just shows up as a bad signature.

Unfortunately, there is no remedy to your situation but to create a new key with stronger parameters. We recommend RSA 4096 keys, for maximum compatibility and just the right amount of overkill in bitsize to last a couple of decades.

**Comment by minges** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi,

thanks a lot! That really helps in understanding the situation.

Regarding the key length I see, that I'm getting old... :-(

I will generate a new, longer key and am really grateful for this
"wake up call".

Regarding the misleading error message:

Is this something you could fix at some point in the future, or should
I give this information to the K-9-team?

Kind regards
Roland


- -- 
___________________________________________________________
Prof. Dr. Roland Minges    Tel:   +49 (1 71) 752 8848
Raiffeisenstrasse 8        Fax:   +49 (1 71) 13 - 752 8848
D-73527 Schwäbisch Gmünd   skype: roland.minges
www.RolandMinges.de        mail:  42@RolandMinges.de
PGP Key ID (DH/DSS): 0xA4681B0F

Am 19.11.2015 um 16:27 schrieb Vincent:
> Phew, ok here we go: The signature is valid, but doesn't pass the
> check if the crypto is still considered secure. More specifically,
> it is a DSA 1024 bit key, where we require at least 2048 bit
> strength 
> <https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSecurityConstants.java#L123>
>
> 
to consider the signature secure.
> 
> It was a tough decision, but DSA 1024 keys are long past their due
> date (check out [keylength.com][keylength.com], dsa 1024 is roughly
> in the category "ok to use until 2010"), so we really don't feel
> comfortable displaying their signatures as secure anymore. An
> obvious bug is that this is not yet displayed in a good way in K-9,
> where it just shows up as a bad signature.
> 
> Unfortunately, there is no remedy to your situation but to create a
> new key with stronger parameters. We recommend RSA 4096 keys, for
> maximum compatibility and just the right amount of overkill in
> bitsize to last a couple of decades.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/open-keychain/open-keychain/issues/1601#issuecomment-158089567>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (MingW32)

iEYEARECAAYFAlZN9mwACgkQZ2UQhKRoGw+TmQCfelOL6gWJyvSglmjY97OK6tZi
WCMAnRyPASZVeJpiyS7AO5B7wkwJMmRR
=rKk3
-----END PGP SIGNATURE-----

**Comment by Valodim** [comment]
glad I could be of assistance.

we got the issue covered, it's just not a very simple issue to fix because there is a lot of more important things to do on K-9
