### ISSUE TITLE
unintentionally hidden reply

### ISSUE THREAD

**Issue by minges** [open-keychain/open-keychain#1604]
I sent a signed message from my Windows 7 PC using Thunderbird/Enigmail.
I received an unsigned reply to this message with my initial message including its signature at the end of the reply.
I can fully view this reply (unsigned reply and signed initial message) on my PC.
On K-9 Mail with open-keychain on my Samsung S4 mini (Android version 4.4.2) I tried to read the reply. In this reply I can see only my initial signed message. The text of the unsigned reply, which is everything before the "BEGIN PGP SIGNED MESSAGE" of my initial message is not visible on K-9.
Thanks for any hint!
Regards
Roland

**Comment by Valodim** [comment]
This is a bug (as in "only partially implemented feature") in current K-9. For PGP/INLINE it just looks for the BEGIN PGP SIGNED MESSAGE markers and then shows only the signed part.

The problem is that it's not trivial to tell exactly what to show. Obviously, we can't just show the unsigned data as part of the signed text (because it's not signed!), but showing both and marking the signed parts leads to very convoluted and confusing UI.

A larger redesign of K-9 is planned and funded, so this will hopefully be solved in the future. In the meantime, sorry for the inconvenience.

**Comment by minges** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi,

thanks for the information.

Is there any chance for the meantime to bypass the problem or does
this mean I will have to deactivate the OpenPGP-Provider when I want
to see the part befor BEGIN PGP...?

Kind regards
Roland


- -- 
___________________________________________________________
Prof. Dr. Roland Minges    Tel:   +49 (1 71) 752 8848
Raiffeisenstrasse 8        Fax:   +49 (1 71) 13 - 752 8848
D-73527 Schwäbisch Gmünd   skype: roland.minges
www.RolandMinges.de        mail:  42@RolandMinges.de
PGP Key ID (DH/DSS): 0xA4681B0F

Am 23.11.2015 um 12:28 schrieb Vincent:
> This is a bug (as in "only partially implemented feature") in
> current K-9. For PGP/INLINE it just looks for the BEGIN PGP SIGNED
> MESSAGE markers and then shows only the signed part.
> 
> The problem is that it's not trivial to tell exactly what to show. 
> Obviously, we can't just show the unsigned data as part of the
> signed text (because it's not signed!), but showing both and
> marking the signed parts leads to very convoluted and confusing
> UI.
> 
> A larger redesign of K-9 is planned and funded, so this will
> hopefully be solved in the future. In the meantime, sorry for the
> inconvenience.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/open-keychain/open-keychain/issues/1604#issuecomment-158909728>.
>
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (MingW32)

iEYEARECAAYFAlZS+uIACgkQZ2UQhKRoGw/dYQCfan1rO3Ukh4f7oxWEdo1Ahppd
erEAn1ONwYVHRGmpdqbXH3o4d+OygJCh
=ZW2v
-----END PGP SIGNATURE-----

**Comment by Valodim** [comment]
Until a new version of K-9 is released, I'm not aware of a good workaround.
