### ISSUE TITLE
Crash on sharing empty log

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1605]
Reproduce:
- Have no keys
- Update all keys
- Open log
- Share log -> crash

**Comment by TedaLIEz** [comment]
Hi dschuermann:
   I just read the code and I think I have solved it, simply because the log stringbuffer uses substring without checking the log's length.

**Comment by dschuermann** [comment]
@TedaLIEz Great, we would love to see a pull request for this
