### ISSUE TITLE
Crash on cloud search

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1606]
Looks like I have missed one runtime permission check:
- disable contacts permission
- search cloud -> crash

**Comment by Valodim** [comment]
related minor thing: the notification doesn't go away when changing the setting

**Comment by dschuermann** [comment]
See https://github.com/open-keychain/open-keychain/issues/1607

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/commit/e7c9be955630a763a4d67a00fd8dbc195b2675b9
