### ISSUE TITLE
QR Code not displayed

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1608]
Not sure if it's just my device, but the QR Code in my keys is not immediately displayed for me.

**Comment by Valodim** [comment]
in ViewKeyActivity?

**Comment by dschuermann** [comment]
yup

**Comment by Valodim** [comment]
ok. at first I thought it was my change in 7f3f802c4b9c1c5d70cf45d04f3f45de2cd5589e which changes the way qr codes are loaded and displayed, but that branch is not yet merged. no idea.

**Comment by dschuermann** [comment]
Is it displayed on your device?

**Comment by Valodim** [comment]
yup. not particularly quickly, but it shows up after < 1s

**Comment by dschuermann** [comment]
strange, could be a cyanogenmod update on my z3 that causes this. After clicking on it, it is displayed properly and then also viewed in the new activity.

**Comment by Valodim** [comment]
does this happen in extended view as well? if so, try cherry-picking my commit above, see if that fixes it

**Comment by dschuermann** [comment]
It started working again after swiping away OpenKeychain and restarting it. Not sure what was happening...

**Comment by Valodim** [comment]
that thing is animated, I would guess that the animation was interrupted somehow
