### ISSUE TITLE
signing subkey not found

### ISSUE THREAD

**Issue by minges** [open-keychain/open-keychain#1612]
Hi,
platform is Samsung S4 mini with Android 4.4.2.
Mailer is K-9 and open-keychain manages the keys.
Following the recomendation you gave, I generated a new, longer key.
I did this in my pc (Thunderbird / Enigmail) and transfered the new key to the phone.
Sending a signed message from the PC results in a successful verification on the phone.
Trying to reply results in "signing subkey not found!".
Help!
Regards
Roland

**Comment by Valodim** [comment]
I suspect that either you still have your old key lying around and that one is still set in K-9 as the one to use, or this is a bug from the old API (new one isn't supported by K-9 yet). Please try the following:
- in OpenKeychain, open the drawer and select "Apps"
- select K-9 in the list
- revoke access
- go into K-9, you should be asked to setup a key anew

**Comment by minges** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi,

thanks a lot!

I already deleted the old key, but it didn't help.

The important step was revoking access for K-9 in open-keychain and re-confirming it in K-9 again. Only in this step the new key could be selected.

This signed message proves, that it works now ;-)

Regards
Roland


- --
___________________________________________________
Prof. Dr. Roland Minges Tel: +49 (1 71) 752 8848 Raiffeisenstrasse 8 Fax: +49 (1 71) 13 - 752 8848 D-73527 Schwäbisch Gmünd skype: roland.minges www.RolandMinges.de mail: 42@RolandMinges.de PGP Key ID (DH/DSS): 0xA4681B0F

Am 27. November 2015 00:43:35 MEZ, schrieb Vincent <notifications@github.com>:
>I suspect that either you still have your old key lying around and that
>one is still set in K-9 as the one to use, or this is a bug from the
>old API (new one isn't supported by K-9 yet). Please try the following:
>- in OpenKeychain, open the drawer and select "Apps"
>- select K-9 in the list
>- revoke access
>- go into K-9, you should be asked to setup a key anew
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/1612#issuecomment-160006336
-----BEGIN PGP SIGNATURE-----

iQJABAEBCgAqIxxSb2xhbmQgTWluZ2VzIDw0MkByb2xhbmRtaW5nZXMuZGU+BQJW
V/9cAAoJEN0+B3DQot9naLEP/1L0H6KGRXfGJ+l9dlYnn9rNZlZNh4NHaYGLu4mL
/v6/S9VRtvtLnDi9odR36EgQjXkYg7nTJcA3vd8vB6jXnc8iz0f28DoPQzhEvx8F
trgIlhM5UQqcLHIQluVg7Ch7MT9rmXOnj70++0WLq61LFSr25tQ1cCJHl3eSfYGk
uElgO7mvgevuQFIc2MUiyeJrHNbejpRjy6j9U0oCSNHUL5GXQ7mU79ZCrQZShjxz
qg+2c1Zl99oirPX48mAUHgHj6SVaCKm5jmgs4ORwh+FnzX/9AdCw2EuQ5OuuqENG
6X9H1YwMgc8jANk6XSBqgEZZh2eraMQejAdsiYHrIdYKe68/uWDkb3Y7oqfQoJ6K
+/r3Ypw9J+dHnd7zfuGY85bvzamzUnAS9USkmCmYG/bklG8MBptlvC017AOGbiXi
QigizhKkTLFjz1rqF+t4LIV/lO49gFVzb+G8DrTWh3jwulZYE5MTNxFUo0SirnbT
02EbbG/uH3hyvLWrVYiLHpRk4kQphJeahdocAz6O8bFMJCKQByd2Ubtso6huEWnJ
HRmtTvpt9W2zs2XhDrUwVIPbgNYy7pbaogG/DRJQua8jflupEbf5KGbmrtjErN6i
U4qPm5uXap3UVCUJgEDBpxRTBKY4twySm6EL01O+ZZ/uD0gfh811DKcOtOLgs0rw
nEJH
=fig/
-----END PGP SIGNATURE-----

**Comment by Valodim** [comment]
This sounds like a bug in the old API, then. Assumed way to reproduce: select secret key for old api use, delete, experience bug. Thanks for your report!

@dschuermann
