### ISSUE TITLE
signature valid on PC, invalid on phone

### ISSUE THREAD

**Issue by minges** [open-keychain/open-keychain#1613]
On my PC (Win 7, Thunderbird, Enigmail) I wrote an e-mail with an attachment (a pdf-file). I signed the message, but not the attachment.

Thunderbird displays the signature as valid.

On my Samsung S4 mini (Android 4.4.2, K-9, open-keychain) this messsage was diagnosed as having an invalid signature.
I do suspect, this has something to do with the unsigned attachment, so the error message is at least misleading.

Maybe this helps improving user experience ;-)

Kind regards
Roland

**Comment by dschuermann** [comment]
Currently, K-9 Mail is using an old version of our API, which displays insecure signatures as invalid among other problems. See our blog post how that will improve in the future: https://www.openkeychain.org/k-9/
