### ISSUE TITLE
Decrypting message of multiple keys fails

### ISSUE THREAD

**Issue by openbrian** [open-keychain/open-keychain#1616]
When following these instructions (https://www.openkeychain.org/faq/) to import a private key, especially

gpg --armor --export-secret-keys YOUREMAILADDRESS | gpg --armor --symmetric --output mykey.sec.asc

the decryption in OpenKeychain fails.  This is likely due to me having multiple private keys.  Some have expired.

However this does work:

gpg --list-secret-keys
gpg --armor --export-secret-keys deadbeef | gpg --armor --symmetric --output mykey.sec.asc

I'm confused why the decryption fails.  I can understand the import failing.

**Comment by Valodim** [comment]
I suspect the encrypted data is just empty. You did replace YOUREMAILADDRESS with your email address in the above example?

I wonder if we should just leave that out, most people have only one key anyways.

**Comment by dschuermann** [comment]
> I wonder if we should just leave that out, most people have only one key anyways.

Good idea, if they have multiple they are advanced users and probably know how to export only single ones.

**Comment by openbrian** [comment]
They may know how to export only one, but they expect OpenKeychain to import multiple keys without an issue.

**Comment by dschuermann** [comment]
@openbrian Importing multiple private keys should work. Can you please try again and after the failed import, please click on "Show Log" inside the small popup on the bottom and and paste the result here? There is a share button on top of the log screen where you can send yourself the log via email.
