### ISSUE TITLE
OpenKeychain does not return the algorithm used to sign data

### ISSUE THREAD

**Issue by Diagoras** [open-keychain/open-keychain#1619]
To implement [RFC 3156](https://tools.ietf.org/html/rfc3156) (aka PGP/MIME) in K-9 Mail, the "micalg" header value must be set to identify the signing algorithm used by the sender. However, OpenPgpApi.ACTION_DETACHED_SIGN doesn't seem to return the algorithm used, either as an extra or as part of the ASCII armoured signature. However, if I read the OpenKeychain source code correctly, it look as if the signing algorithm is fixed to SHA-512 for the time being.

Should applications implementing PGP/MIME just statically set the "micalg" value to SHA-512, and assume that's guaranteed to never change? Or should the detached signing operation return the algorithm used?

**Comment by dschuermann** [comment]
Thanks for reporting. Indeed, OpenKeychain always uses SHA-512 currently. I would propose setting it statically for now. For future proofness, we will implementiert a New extra to return it.

**Comment by Valodim** [comment]
This is part of what I'm working on at the moment, I got this. :+1:

**Comment by dschuermann** [comment]
Has been added here: https://github.com/open-keychain/open-keychain/commit/e32c1a9ced4c3409d4cf581dc1206968b6c86ef4
