### ISSUE TITLE
Edit subkeys

### ISSUE THREAD

**Issue by ephexeve** [open-keychain/open-keychain#1620]
More of a question than an issue, when I import a GPG subkey, I cannot edit this key, is this a sort of "confirmation" that the current key I am willing to edit is a subkey?

**Comment by Valodim** [comment]
If I'm getting your question right: I think so. The primary key is required to edit subkeys, because under the hood what happens during editing is that the primary key signs the new information about the subkey.

**Comment by ephexeve** [comment]
You are right. I tried making a new key from open-keychain, and in fact I could edit the key (since the private was store on the device). This is a nice feature. Thanks.
