### ISSUE TITLE
Unable to checkout in submodule path 'extern/spongycastle'

### ISSUE THREAD

**Issue by TedaLIEz** [open-keychain/open-keychain#1629]
Hi:
&nbsp;&nbsp;&nbsp;&nbsp;I clone the repo just now and run the command `git submodule update --init --recursive` but come with an error:
`fatal: reference is not a tree: b0acac5821e3cc58549c76ecc16df147796e08e1
Unable to checkout 'b0acac5821e3cc58549c76ecc16df147796e08e1' in submodule path 'extern/spongycastle'`
Does someone have the same problem with me?Any ideas?

**Comment by dschuermann** [comment]
@Valodim I don't see the commit in openkeychain-master on https://github.com/open-keychain/spongycastle . Can you push it please.

**Comment by Valodim** [comment]
cherry-picked to openkeychain-master and updated ref: https://github.com/open-keychain/spongycastle/commit/b8387f22a9f20d1bd186a377e1ec9208c6eae3e5
