### ISSUE TITLE
openkeychain fails to import public key

### ISSUE THREAD

**Issue by tomsam-de** [open-keychain/open-keychain#1632]
Someone sent me his pgp public key, which i could successfully import into enigmail (thunderbird).
I was also able to decrypt and validate his message.

After that I installed openkeychain on my android device, and got an error message when importing that  key, whilst my own keys were imported without any problems.

The error message says 
**Unterschlüssel 0xaaf8a22aa36581cd kommt zweimal im Schlüsselbund vor.
Schlüsselbund ist fehlerhaft und wird nicht importiert**

That translates more or less to something like:
**Subkey 0xaaf8a22aa36581cd found twice in the keyring.
Keyring is faulty and will not be imported.**
 

Questions: 
Whats wrong with that key?
How can I validate that key? (linux commands preferred)

See below the "key properties" of the key in question:
![x](https://cloud.githubusercontent.com/assets/16363102/11913776/d0281ac2-a66f-11e5-8298-f21e87536558.png)

If you need more information, let me know.

**Comment by Valodim** [comment]
That's an interesting case, I've only seen it once before. Do you now what software was used to generate the key in question?

**Comment by tomsam-de** [comment]
The armored file  says

**-----BEGIN PGP PUBLIC KEY BLOCK-----**
**Version: OpenPGP totemomail**
**Comment: totemomail OpenPGP - http://www.totemo.com**

so at least the "e-mail client" is known. 

It's not for sure that the e-mail client itself has  OpenPGP built-in,
as they (totemo) offer a transparent way for their customers, see

http://www.totemo.com/products/mail/encryption-gateway/overview/

The person who sent me the key doesn't know how that key was generated
He said  his IT department did it ...

**Comment by dschuermann** [comment]
I sent an email to support@totemo.com referencing this issue. It's definitely a fault on their side.

**Comment by tomsam-de** [comment]
I did the same, was waiting for their answers.

**Comment by dschuermann** [comment]
The important part of their answer:

> the PGP keys in totemomail 4.0  are created/exported that way, however we changed
> this for totemomail 5.0 (released in August 2015), so that keys generated by totemomail
> can be also imported successfully into PGP on Android.

So this has been fixed in their software. Now their customers must update.

**Comment by Valodim** [comment]
I would like to point out that this behavior in the totemo pgp implementation makes no sense, not only the export but generating a subkey binding from a primary key to itself in the first place. We correctly reject these keys, in fact, we have a unit test to check that we reject this particular type of malformed key.

either way, nothing more we can do about this, closing the issue. thanks for reporting.
