### ISSUE TITLE
Verify public key with YubiKey

### ISSUE THREAD

**Issue by ghost** [open-keychain/open-keychain#1634]
I have an unconfirmed public key and I try to "Confirm with fingerprint"
After manually confirming the fingerprints match and moving on to the
next screen I select my key and press "Confirm key" and it says
"Certification of 0 keys failed!" with the full error log containing

```
Certifying keyrings
  Fetching certifying master key
    Unlocking master key
      Error unlocking master key!
```

This is because I'm using my YubiKey paired with OpenKeychain and it
didn't give me any option to use it. I think it just assumes that the
private key is stored on the phone and tries to access it and fails.

**Comment by dschuermann** [comment]
Are all keys on your YubiKey? Which tutorial did you follow to prepare your YubiKey? Were you able to select your YubiKey-based OpenPGP key from the dropdown?

**Comment by shancat** [comment]
My only public/private pair is my YubiKey. Yes I was able to select my
YubiKey based key from the dropdown. I've recorded this video to show
you what happens.

https://gfycat.com/YoungAdolescentFrigatebird

If you need any more information I will do my best to be as detailed as
possible :) Thanks

**Comment by dschuermann** [comment]
Closing this very old issue as it is probably no longer true for current versions.

**Comment by gonzalob** [comment]
I'm facing the same issue with the current version: 5.3
