### ISSUE TITLE
Highlighter crashes on brackets

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1637]
1. Press search in OpenKeychains main key list
2. Enter "(" -> crash

```
  7749         AndroidRuntime  E  java.util.regex.PatternSyntaxException: Incorrectly nested parentheses in regexp pattern near index 7:
  7749         AndroidRuntime  E  (?i)(()
  7749         AndroidRuntime  E  ^
  7749         AndroidRuntime  E  at java.util.regex.Pattern.compileImpl(Native Method)
  7749         AndroidRuntime  E  at java.util.regex.Pattern.compile(Pattern.java:411)
  7749         AndroidRuntime  E  at java.util.regex.Pattern.<init>(Pattern.java:394)
  7749         AndroidRuntime  E  at java.util.regex.Pattern.compile(Pattern.java:381)
  7749         AndroidRuntime  E  at org.sufficientlysecure.keychain.ui.util.Highlighter.highlight(Highlighter.java:46)
```

**Comment by adithyaphilip** [comment]
@dschuermann This crashes for me in the release build, but not in the current master.

**Comment by dschuermann** [comment]
Hmmm, I think it depends on the available keys inside the list. It crashes for me on current master with all my keys imported but not if the list is empty.

**Comment by adithyaphilip** [comment]
At first glance it looks like an issue with unsanitized input for regex, does https://github.com/open-keychain/open-keychain/commit/90aa4f55cb83385498109626e06fcc31aa4c8f71 fix it?

**Comment by TedaLIEz** [comment]
@adithyaphilip I also found this crash entering "(", how about using <a href="http://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html#quote-java.lang.String-">Pattern.quote()</a> to solve it?
