### ISSUE TITLE
Crash when encrypting through contact key: kgpg problem?

### ISSUE THREAD

**Issue by bigdrew** [open-keychain/open-keychain#1641]
Openkeychain crashes when using the contact key dialog.  To reproduce:

1-Select a contact's key from the main app screen.
2-Select the encrypt file icon.  This also happens with the encrypt text icon, however the app crashes only after selecting the text box to type.

Encryption is successful when using the encrypt dialog from the side menu or an intent.

**Comment by Valodim** [comment]
cannot reproduce on current master. does this still happen? if it does, does it happen for specific keys only?

**Comment by bigdrew** [comment]
You're right.  It was the key.  I created dummy keys with kgpg to test and
got the same problem but gnupg command line works fine so something is
wonky with kgpg.

**Comment by dschuermann** [comment]
Can you generate a test key with kgpg for us that has this problem and then put it in a comment here on github using ascii armor?

**Comment by bigdrew** [comment]
I generated a test key pair with kgpg but I'm having trouble reproducing
the problem now.  You may want to mark this issue as resolved for now.
I'll request it to be reopened of I can get a key to not work.

Can you generate a test key with kgpg for us that has this problem and then
put it in a comment here on github using ascii armor?

—
Reply to this email directly or view it on GitHub
<https://github.com/open-keychain/open-keychain/issues/1641#issuecomment-168313888>
.
