### ISSUE TITLE
Key search: show if key is already imported

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1646]

**Comment by 007durgesh219** [comment]
@dschuermann how do we show that??.  In my suggestion, we can add a textview written (Already Imported). Should I proceed with that ??

**Comment by Valodim** [comment]
The code structure of key import is not very well suited for this kind of addition at the moment. This feature is part of the [improved key search ui](https://github.com/open-keychain/open-keychain/wiki/Google-Summer-of-Code-2016#improved-key-search-ui) gsoc task, which involves a rewrite of the entire dialog.
