### ISSUE TITLE
Result private keyserver not showing

### ISSUE THREAD

**Issue by evdbovenkamp** [open-keychain/open-keychain#1650]
I have setup a private keyserver and made this my default (and only) server.
When I create a key (with OpenKeychain) , and try to upload this, it works!!
When I try to retreive a key (search with OpenKeychain), it fails.

When I capture the session with Wireshark, I can see that the response on the query is correct.
The search of keys work, with the same settings, on my windows computer and trough the web interface.

What am I doing wrong? Or is this a bug?

**Comment by dschuermann** [comment]
Difficult to debug without any access to your server, thus closing. It works with all public keyservers

**Comment by sharvadharma** [comment]
hi , 
i m beginner for this encryption decryption 
i used openkeychain and k9 mail 
i create a private sks server by the following link
https://njh.eu/keyserver
and then i add my key server in openkeychain as following
hkp://myserverip:11371
and i uploaded my key to the server through openkeychain 
and i checked the key in server through web interface browser
http://myserverip:11371
server returns the keydetail 
i tried to search the key from the openkeychain
i recieved mesage no keys found

what i need to do for search import keys in open keychain
from my private server

if you need  server details i will mail you 

thanks in advance
