### ISSUE TITLE
Warning when entering the "extended information" screen

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1657]
* I would like to rename the "Extended information" menu item to "Expert settings". I know, we already used "expert" in the past, but I no longer like "extended". It sounds like normal options, instead these are really expert options, no normal user should use.
* Then I would like to add a warning dialog when entering the screen that needs to be acknowledged. Like 

```
Expert setting should only be utilized for special use cases.
Misusing them can break the OpenPGP key!

Cancel      I know what I am doing
```

Feedback?

**Comment by dschuermann** [comment]
Outcome of internal discussion:
* rename to "Advanced"
* new first fragment tab contains info about these advanced options

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/commit/cc917857b00ea8bf6328f351eb051e7e5313e60b

@Valodim Please review the text

**Comment by Valodim** [comment]
text looked ok to me. I added some padding to the icon though
