### ISSUE TITLE
Don't expose CertifyActivity

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1661]
* remove exposing of CertifyActivity by removing intent filter on openpgp4fpr.
* this should only be executed using OpenKeychain

**Comment by Valodim** [comment]
Do we do this? I think openpgp4fpr is linked to ImportActivity

see https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/AndroidManifest.xml#L515

**Comment by Valodim** [comment]
yeah ImportKeysProxyActivity goes directly to certification. I'll change it.

**Comment by Valodim** [comment]
Hm. I changed this to ImportKeysActivity now, but I'm not sure if that's really better behavior. Is showing the certify dialog really a problem?

**Comment by dschuermann** [comment]
The issue I have with this that a Barcode Scanner is a non-trusted third-party app, which could change the fingerprint on it's way from the paper with the QR Code to OpenKeychain. That's why I would propose not encouraging direct certification based on this.

**Comment by Valodim** [comment]
Hm. Maybe we could check if the barcode scanner app is a well-known one? Not accepting scanned qr codes from barcode scanner apps with millions of installs feels like treading on paranoid terrain, and this *will* break the workflow of people who are used to, well, scanning codes using their barcode scanner app.

**Comment by dschuermann** [comment]
If it's a targeted attack, it will show the expected information, but is a different key.

Checking if it's a well known scanner app means we must check the apk certificate, not sure if we want to introduce this complexity. Most QR Code scanner apps on Google Play have the same intent filter as "Barcode Scanner" btw.

In general, I think it's a bad security design to expose certification UI without requiring the user to go into OpenKeychain first. It would be only okay to expose this registered API apps. Currently any app can start an intent with "openpgp4fpr" to start certification process, this could also be done from the background via FLAG_NEW_TASK to interrupt an on-going certification btw...

**Comment by Valodim** [comment]
Maybe display an extra activity "You scanned a fingerprint with App X, please scan with openkeychain directly to be safe (click here)"?

**Comment by dschuermann** [comment]
Great idea, yep!

**Comment by Valodim** [comment]
Sounds like a straightforward implementation, and with the whole android intent handling experience to boot :+1:

**Comment by LuboViluda** [comment]
Hi,
I implemented changes, with small difference in showed text (by another app instead of app XY), becauce I was not sure how to obtain name of app with fired the intent (it is possible with ActivityManager and getCurrentTasks, but the method is deprecated now)

Please let me know, if some additional changes/fixes are required :)

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/pull/1795
