### ISSUE TITLE
[Feature request] A second export method in OpenKeychain's log view

### ISSUE THREAD

**Issue by Olf0** [open-keychain/open-keychain#1663]
This was tested with OpenKeychain v3.7 (3700) under AlienDalvik / AOSP 4.1.2:

When hitting the "Share" button in the log view of the key import function, the system mail client is opened with the mail body containing solely a single "null".  Exactly the same happens, when I try to "share" an actual public key in a key's "extended information". 
But when "sharing" a key's fingerprint its "extended information" this works well: The system mail client is opened with the mail body containing "openpgp4fpr:...". 
"Sharing" text selections in K9-Mail yields the same result: The system mail client is opened with the mail body containing the selected text (truncated to roughly one KByte). 
Side note: Other Android applications, which do not exhibit a triangular "Share" button, but a "share" entry in their pull down menu (e.g. Amaze file manager, Turbo Editor), open a list of suitable Android applications. 

The awkward behaviour of the "Share" button in OpenKeychain and K9-Mail in general must be attributed to the fact that these tests were carried out under AlienDalvik as part of SailfishOS 2.0.0. 
But I wonder, why sharing a key's fingerprint works reliably (and so does sharing text selections in K9-Mail), but sharing a proper key or a key import log just outputs a "null"? 

If this works well under native Android and you have no idea what OpenKeychain may do differently when sharing fingerprints (and K9 sharing text selections) in contrast to actual keys and key import logs, please do not bother about that specifically. 

The real issue IMO is, that OpenKeychain offers no alternative to "Sharing" when trying to save a key import log.  In contrast to this, in a key's "extended information" dialogue a clipboard function is offered for both, the key's fingerprint and the actual key.  Hence my feature request is:

Please do offer a clipboard button (along with the existing share button) in the log view of OpenKeychain's key import function.
## 

Kudos for your excellent work,
Olf0

**Comment by Valodim** [comment]
I didn't look into this in detail, but both of these actions launch an `ACTION_SEND` intent with mimetype "text/plain". The difference between them is that "share fingerprint" delivers the data in an `EXTRA_TEXT` extra containing the fingerprint data as text. In the other cases, the data is written to a file and passed as a uri in `EXTRA_STREAM`.

The difference in semantics is roughly the same as content-disposition inline and attachment for MIME. I believe that this is correct behavior for a number of reasons:
* thinking about the recipient side, both public keys and logs *should* be treated like "attachments to share", not like "text to share", i.e. should show up as an attachment in an e-mail client or as a file to send in a messaging app, not as actual text.
* if the EXTRA_TEXT field is used, the text is limited to the intent filesize limit. at 1MB, this limit is actually in a relevant order of magnitude for log sharing
* some applications mangle the data of the EXTRA_TEXT field. for example, bluetooth sharing converts it to HTML for display, doing things like converting longer sequences of numbers into telephone number links - which obviously breaks shared public key material.
* data can be passed as ClipData objects in newer android versions which offers some more flexibility. these objects also contain a uri and a plain text field, and if you look at the coerceToText method which can be ued to retrieve the contained text, this will read the text from the uri if there is no text attribute provided (see [here](http://developer.android.com/reference/android/content/ClipData.Item.html#coerceToText(android.content.Context) and [here](https://android.googlesource.com/platform/frameworks/base/+/23fdaf6fb62a9b5154b2508916a21c678462c5d0/core/java/android/content/ClippedData.java)).

Now I'm aware that, even if this is correct behavior, this insight is unhelpful if every other App doesn't think so and consequently treats the intent incorrectly. We will look into this and see how some apps behave, and maybe adapt our behavior.

As for the showing or not of the chooser dialog, for the case of view log this is indeed not enforced where it maybe should be. It *is* enforced in the extended information share public key dialog (see [here](https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ViewKeyAdvShareFragment.java#L270)) though, so it's puzzling that this does not show up for you. Can you double-check this? Or are we maybe not talking about the same button?

**Comment by Olf0** [comment]
> I didn't look into this in detail, but both of these actions launch an
> `ACTION_SEND` intent with mimetype "text/plain". The difference
> between them is that "share fingerprint" delivers the data in an
> `EXTRA_TEXT` extra containing the fingerprint data as text. In the
> other cases, the data is written to a file and passed as a uri in
> `EXTRA_STREAM`.

Thank you, that is sufficient information for filing a bug WRT the AlienDalvik integration in SailfishOS2.0.0.  The content of the `EXTRA_TEXT` arrives, the "file with its uri passed in `EXTRA_STREAM`" mechanism fails.
The fact that I have no Apps to choose from (i.e. the system mail client opens immediately) is also caused by this special operating environment (AlienDalvik in SailfishOS2.0.0), correct?

> The difference in semantics is roughly the same as content-disposition
> inline and attachment for MIME. I believe that this is correct
> behavior for a number of reasons:
> [...]
(IMO absolutely valid reasons omitted for brevity.)

> * data can be passed as ClipData objects in newer android versions
> which offers some more flexibility. 

As this requires at least API level 11 (Android 3.0), this is a no-go as long as you intend to maintain support for Android 2.x (Android market share still at high single digit percentage), hence currently still good for many.
And for me personally, I suspect newer mechanisms not being better supported than traditional ones by AlienDalvik in SFOS2.0.0, although it is based on AOSP 4.1.2.

> [...]
> Now I'm aware that, even if this is correct behavior, this insight is
> unhelpful if every other App doesn't think so and consequently treats
> the intent incorrectly. 

As all these sharing mechanisms as well as the clipboard / cut&paste-buffer are neither stable nor anywhere near feature complete between Applications on the "Android side" (running under AlienDalvik) and the "Jolla side" (native SailfishOS applications), I pay a lot of attention how apps behave (mostly ones from f-droid) in this area and I observe quite some variation in details, although most of them work even in my special setup.
The current behaviour of OpenKeychain to use an `ACTION_SEND` intent with mimetype "text/plain" for sharing is not unique, but some apps use different mechanisms.  But I remember only once before having just 'null' transmitted (obviously by using `EXTRA_STREAM` and not `EXTRA_TEXT`).  But AFAIR there was a way around (clipboard, file export etc.) that time, so unfortunately I cannot remember in which app that happened.

> We will look into this and see how some apps behave, and maybe 
> adapt our behavior.

Well, while I would love to see some improvement for me, spending significant effort on issues, which presumably only occur under a special operating environment used by a couple of 10000 people, may be better invested elsewhere.

> As for the showing or not of the chooser dialog, for the case of view
> log this is indeed not enforced where it maybe should be. It *is*
> enforced in the extended information share public key dialog 
> though, so it's puzzling that this does not show up for you. Can you
> double-check this?

Checked again all three of them, "share fingerprint" and "share public key" in extended information share dialogue, as well as in the view log window.  All immediately open the system mail client.

> Or are we maybe not talking about the same button?

Attachmed file <key_extended-information_share_2016-01-08-edit.png> depicts the for me dysfunctional "share public key" button encircled in red and the (awkwardly for me) working "share fingerprint" button encircled in green.


But on to easy solutions! ;-)
Most other data exports in OpenKeychain offer two or three mechanisms (share, clipboard, file export), why not offering a clipboard button in the the view log window? 
Attachment <key-operation_log_2016-01-08-edit.png> shows that window, with the (awkwardly for me) working "share log" button encircled in yellow and the spacious room for another button (e.g. clipboard) encircled by blue (although I think "share" and "clipboard" button should be ordered the other way around then, as they are in other places in OpenKeychain).

**Comment by Olf0** [comment]
The aforementioned severe flaw in SailfishOS's Clipboard functionality for Android applications has been mitigated in SailfishOS 2.0.1 (after years): It is still somewhat awkward to use, but at least it seems to work consistently, finally. 

> [...]
> But on to easy solutions! ;-)
> Most other data exports in OpenKeychain offer two or three mechanisms
> (share, clipboard, file export), why not offering a clipboard button
> in the the view log window? 
> Attachment <key-operation_log_2016-01-08-edit.png> shows that window,
> with the (awkwardly for me) working "share log" button encircled in
> yellow and the spacious room for another button (e.g. clipboard)
> encircled by blue (although I think "share" and "clipboard" button
> should be ordered the other way around then, as they are in other
> places in OpenKeychain).

Although the specific issue for SailfishOS (Jolla Phone & Tablet) users has been mitigated, I still believe a second, alternative method of exporting a log in OpenKeychain makes sense for ...
... consistency, as other places in OpenKeychain offer at least two methods of exporting.
... ease of use, as the "share" functionality may be problematic on the receiving side: As that was the case for SailfishOS < 2.0.1, it may still hold true for certain applications or OS / application combinations.

That second, alternative method does not have to be a "Copy to clipboard" function. 
Rereading this thread and reconsidering the subject, "Save to file" may be a better fit than "Copy to clipboard" as an alternative to "Share" under a couple of aspects (generality, some security aspects, non-dependent on OS functionality, etc.).

-- 
Best regards, 
   Olf

**Comment by dschuermann** [comment]
Closing as this is an issue in SailfishOS
