### ISSUE TITLE
No valid OpenPGP block found

### ISSUE THREAD

**Issue by petmue** [open-keychain/open-keychain#1665]
Hi!

I am not sure, whether this is an openkeychain issue or a k9 mail issue, that's why I'd like to post it here again: https://github.com/k9mail/k-9/issues/1008

 I use K9 5.007 and OpenKeyChain 3.7 on my Android with CM 12.1.

When I reply a mail, K9 mail adds the old message quoted like this:
> This is the reply mail followed by the quotation of the original mail:
>> -----BEGIN PGP MESSAGE-----
>> Charset: utf-8
>> Version: GnuPG v2
>>
>hQIMA324sfl24ltklwqfl2tl2gw

However, K9 mail cannot decrypt my sent message then and Thunderbird tells me that no valid OpenPGP block could be found. This is how the sent mail looks then:

> -----BEGIN PGP MESSAGE-----
>
>hQIMAypJd8s8JCpBAQ//fWrPkSHfvGyh9YPbIn9OhQCOKCQM2yUusUiGbOxYPxbZ

When I compare it to a working encrypted mail 
> -----END PGP MESSAGE-----

is missing here at the end of the mail. So only a part of the encrypted messages seems to be sent!

###### How can I help you to narrow down the problem?

**Comment by dschuermann** [comment]
This is a K-9 Mail issue, it will be handled on their issue tracker, thx for reporting!
