### ISSUE TITLE
Remove SingleTop from ImportKeysActivity

### ISSUE THREAD

**Issue by adithyaphilip** [open-keychain/open-keychain#1669]
Allows multiple instances of ImportKeysActivity to exist, one for each intent. Follow up on PR https://github.com/open-keychain/open-keychain/pull/1666.

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/commit/5e3e6e2d62159eac6fb0e2c9d6f30afe941407d4

**Comment by dschuermann** [comment]
sry :P

**Comment by adithyaphilip** [comment]
Oh, my bad. Sorry :/

**Comment by dschuermann** [comment]
np, will do a release soon :dancers:

**Comment by adithyaphilip** [comment]
I see it's been done. Yay ^^
