### ISSUE TITLE
handle encrypted files in "import key" file selection

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1673]
When the user selects an encrypted file for import, they currently get an error. Since we export encrypted keys, importing it back via the import from file dialog seems like a workflow users might want to use, so we should support that.

**Comment by Valodim** [comment]
I noticed this is actually quite important, since right now there is no good way to restore from a backup from our first time dialog.

**Comment by Juaanma** [comment]
Hi, I would like to contribute to this issue. After @runnerway's solution, it's still needed to incorporate his idea to the first time dialog, right?

**Comment by Valodim** [comment]
Not really, the first time dialog simply links to the ImportKeysFragment, so that should already work :)

**Comment by rhari991** [comment]
@dschuermann Seems this issue has been solved ?

**Comment by dschuermann** [comment]
@rhari991 you are right. this has already been done.
