### ISSUE TITLE
Synchronize with internet always activated

### ISSUE THREAD

**Issue by petmue** [open-keychain/open-keychain#1674]
I updated to OpenKeychain 3.8 via F-Droid on CM 12.1
In the key editing dialog there's a checkbox saying "Synchronize with the internet" being checked.
When I uncheck it and press save, OpenKeyChain tells me that there's "nothing to do". So when I close the dialog and open it again, the checkbox is checked again.

Why is it activated by default anyway? I don't want to share my key. I'd prefer the option to be opt-in and not opt-out, because there's usually not opt-out on the keyservers, once it got synchronized... :-(

**Comment by dschuermann** [comment]
The key is only uploaded to a keyserver when you actually change identities and press save. If nothing is changed OpenKeychain will show "nothing to do".

We should change the text on that checkbox to say "Synchronize with the Internet on Save" or something like this and maybe move it into the Toolbar.
Long term solution is to make a global preference if keys should be uploaded or not or a way to flag keys which should be uploaded and which not.

**Comment by petmue** [comment]
> Long term solution is to make a global preference if keys should be uploaded or not or a way to flag keys which should be uploaded and which not.

That sounds fair to me! Thanks for the clarification.

**Comment by dschuermann** [comment]
Thanks for raising this issue. I bundled the discussion about this here: https://github.com/open-keychain/open-keychain/issues/1847
