### ISSUE TITLE
Switch from Spongy Castle to Bouncy Castle?

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1676]
According to the Book Android Security Internals, the bouncycastle packages have been renamed to "com.android.org.bouncycastle" starting with Android 3.0. If I understand this correctly, we could switch back to bouncy instead of spongy.

See also https://android.googlesource.com/platform/libcore/+/0ac85ead96f1ba7d35f3acadd154de4ef0a8fd87^!/

I will test this in a branch when I get time.

**Comment by dschuermann** [comment]
@rtyley do you know something about this?

**Comment by rtyley** [comment]
> @rtyley do you know something about this?

Not much beyond what you've already seen - it's a good change in Android, it's what they should have done in the first place! I think it's possible that _some_ post-3.0 devices by ill-behaved manufacturers may still bundle `org.bouncycastle.*` in their system class library, making it a little unpredictable as to whether a user will hit a problem or not - a Nexus device is probably fine, but for a non-vanilla Android there's no guarantees :crying_cat_face: I'd be interested to know the results of your tests.

For the time being at least, I'll continue to repackage Bouncy Castle as Spongy Castle, on the grounds that there are still plenty of pre-Android-3.0 devices out there that need decent cryptography.

**Comment by dschuermann** [comment]
@rtyley Thanks for your answer. Will try to find some Samsung devices and test if they still include ``org.bouncycastle`` or if it's safe to migrate.

**Comment by rtyley** [comment]
Cool, let me know how you go!

**Comment by dschuermann** [comment]
@rtyley I did some tests and it looks ok, so we now switched to bouncycastle on git master.

I tested on the following devices with Amazon Device Farm:

Top 5 amazon devices:
Amazon Kindle Fire HDX 7 (WiFi)
4.4.3
LG G Pad 7.0 (AT&T)
4.4.2
Samsung Galaxy S5 (T-Mobile)
4.4.2
Samsung Galaxy S6 (Verizon)
5.0.2
Samsung Galaxy Tab 4 10.1 Nook (WiFi)
4.4.2

And I selected some older devices/Android versions:
ASUS Nexus 7 - 1st Gen (WiFi)
4.2.1
Samsung Galaxy Note (AT&T)
4.1.2
Samsung Galaxy S4 (AT&T)
4.4.4
Samsung Galaxy S4 (AT&T)
4.2.2

**Comment by dschuermann** [comment]
@rtyley We now released v3.9 and everything works, I don't see reports related to this switch :) A change that was required in addition was: https://github.com/open-keychain/open-keychain/commit/c9018e1844293eb2c47f642c5940531a3496dce5
