### ISSUE TITLE
App crashes when importing exported keys

### ISSUE THREAD

**Issue by turion** [open-keychain/open-keychain#1678]
I recently switched phones and I used the encrypted export function from OpenKeychain on my old phone to upload the keys to owncloud and downloaded them on the new phone and tried to import them. I enter the password to decrypt the file and as soon as I'm finished and I click "Entsperren" (unlock or decrypt in english I guess), the app crashes. How can I submit some debug information?

**Comment by vanitasvitae** [comment]
I guess this is #1677

**Comment by turion** [comment]
Probably. How do I read the debug logs?

**Comment by vanitasvitae** [comment]
have you tried adb logcat?

**Comment by vanitasvitae** [comment]
Wenn du ein Linux System zum Debuggen nutzen willst kannst du (mit installiertem Android SDK) "adb logcat" in ein Terminal eingeben und erhälst logs über alles was auf deinem Handy passiert. Alternativ kannst du eine App wie "aLogcat Root" auf deinem Handy verwenden (falls dein Handy gerootet ist)

**Comment by turion** [comment]
Ich habe aLogcat laufen, aber muss es aLogcat Root sein um diese Exception auch zu sehen?

**Comment by vanitasvitae** [comment]
Warscheinlich. Kannst es ja versuchen. Ich meine aber gelesen zu haben, dass aLogcat nur seine eigenen logs lesen kann, wenn es nicht mit root rechten ausgeführt wird.

**Comment by turion** [comment]
Ok, vielen Dank, aber ist mir im Moment zu viel Aufwand nur um wahrscheinlich rauszufinden, dass es der gleiche Bug ist... ;) ich warte einfach auf die nächste Version und schau, ob es dann gefixt ist, und wenn nicht, installier ich mir das SDK

**Comment by Valodim** [comment]
It's the same one. I looked at it earlier and I'm pretty sure I figured it out. Bugfix release soon, tomorrow if we can make it. Thanks for your report! :+1:
