### ISSUE TITLE
Hilarious FAQ typo

### ISSUE THREAD

**Issue by turion** [open-keychain/open-keychain#1679]
Not sure whether you want FAQ bugs here as well, but this one is really sweet:

3.4 I have more than one subkey capable of _singing_.

Well, that's a really special subkey you have there if it's able to sing. And I agree that you are right to "consider [...that...] an advanced usecase". :D

(Actually I was considering not reporting this because it's too funny)

**Comment by Valodim** [comment]
funny typo indeed. thanks for reporting :)
