### ISSUE TITLE
One thought about tor

### ISSUE THREAD

**Issue by vanitasvitae** [open-keychain/open-keychain#1680]
Hi
I just again stumbled about the option to synchronize keys over tor and that made me thinking:
How are the keys downloaded over tor? Does the app tell the keyserver (through tor) that it needs a copy of key A,B,C,D...? If it does it in this way, the keyservers can obviously generate a profile of the tor user based on the set of requested keys (ignoring the fact that the user also synchronizes its own key).

If keys are synchronized that way, wouldn't it be better, to request the keys one after another always through a new tor identity? That way, the key servers couldn't track the user as easy as they otherwise can, because all it sees is that (tor)user X requests key A, (tor)user Y wants B and Z wants C... Additionally there could be a delay between the keys. 

Is this even possible with Orbot? And does it make sense at all?

**Comment by Valodim** [comment]
This is already taken into consideration, see #1337 :+1:

**Comment by vanitasvitae** [comment]
Oh nice :)
