### ISSUE TITLE
export Sec Key

### ISSUE THREAD

**Issue by beli3ver** [open-keychain/open-keychain#1690]
Hi,

my computer crashed, so I lost my keys.
But in OpenKeychain they still exists.
Is there a way to export them to use them on my computer again?

Thanks

**Comment by beli3ver** [comment]
Now I find the way, but every time I make it, I get the message wrong password:

"XXXXXX-XXXXXX-XXXXXX-XXXXXX"
XXXXXX-XXXXXX-XXXXXX-XXXXXX
"XXXXXXXXXXXXXXXXXXXXXXXX"

none of this way is working, and yes the code is right

**Comment by dschuermann** [comment]
Which application are you using on your desktop to decrypt the backup?

**Comment by beli3ver** [comment]
First I tried it with gpg under Debian.
Then with GPG4Win, that work.
I don't know where the error was.

**Comment by Valodim** [comment]
So the data was encrypted with the expected backup code after all. Works as expected then :+1:
