### ISSUE TITLE
Verify .pgp signatures 

### ISSUE THREAD

**Issue by JasperWeiss** [open-keychain/open-keychain#1691]
Would it be possible for OpenKeychain to verify signatures from seperate files.
For example, I have a developers public key imported and I download an .iso aswell as the corresponding .iso.pgp. When I try to verify the signature OpenKeychain says it hasn't found data to verify, It should look for the a file in the same directory with the same name except the .pgp extension.

**Comment by dschuermann** [comment]
duplicate of https://github.com/open-keychain/open-keychain/issues/1380
