### ISSUE TITLE
PIN set as numpad only after update (3.8.2)

### ISSUE THREAD

**Issue by fcartegnie** [open-keychain/open-keychain#1698]
Can only revert to passphrase by checking/unchecking numpad only in prefs

**Comment by Valodim** [comment]
Is this a recurring problem, or did you only have to do it once?

**Comment by Valodim** [comment]
It is also worth mentioning that THE biggest advantage of using a yubikey is that your password is hardware brute-force protected. Since it is practically impossible to guess a six-digit pin in three tries, we *strongly* recommend using a pin over a password for increased usability!

**Comment by fcartegnie** [comment]
That happened just after the update to 3.8.2 and persisted until setting prefs.

**Comment by Valodim** [comment]
I'm not sure why the setting changed with the update, but I'm not sure I see the problem here. You changed it back and it works as expected now, doesn't it?
