### ISSUE TITLE
NFC bug, Unhelpful error message, Yubikey NEO

### ISSUE THREAD

**Issue by sc-perth** [open-keychain/open-keychain#1700]
Setup: K-9 mail, OpenKeychain, Yubikey NEO w/ 3 subkeys (master key is stripped & stored offline).

Issue: Decrypt (& verify?) operations fail with error message "OpenPGP Error: Data is corrupt!". Does not matter if decryption operation occurs from K-9 or OpenKeychain app.
Encryption & signing operations work without issue.
```
[START] Processing input data
 [DEBUG] Attempting to process OpenPGP data
 [DEBUG] Starting decrypt operation???
  [DEBUG] Found block of asymmetrically encrypted data for key 0xb8855e5234ffe589
  [DEBUG] Encountered trailing, asymmetrically encrypted data for key 0xb8855e5234ffe589
   [INFO] Unlocking secret key
   [ERROR] Data is corrupt!
```
[screenshots.zip](https://github.com/open-keychain/open-keychain/files/100103/screenshots.zip)

Fix: Toggle NFC off and on (I'm 90% certain that I tried rebooting to fix this, and it did not fix it.)

Phone: Note 4 (SAMSUNG-SM-N910A)
OS: Samsung's Android 5.1.1 (Kernel: 3.10.40-5613584 Build: LMY47X.N910AUCU2DOI2)

**Comment by sc-perth** [comment]
Due to the ease of fix, this bug report is intended mainly as searchable documentation for others experiencing this issue & as an FYI to the devs. If this is not (reasonably) fixable, I will not be offended if this issue is closed.

Thank you,

**Comment by Valodim** [comment]
I'm afraid that this is a bug we can't do a lot about. The error message suggests that we get bad data about the decryption from the yubikey - not malformed, but incorrect - so this is likely a bug somewhere deeper in the nfc stack.

If we are lucky, this is fixed with #1614, I doubt it though.

**Comment by sc-perth** [comment]
Hi Valodim,

Thank you for your response, it's more than I was expecting since I'm guessing this bug originates in the OS's NFC stack. If I'm understanding correctly after [#1614](https://github.com/open-keychain/open-keychain/pull/1614) you're going to (functionally) replace the NFC stack with Nordpol? That actually sounds promising to me. Let me know if there's anything I can do (read: testing;) to help.

**Comment by Valodim** [comment]
No, apps don't have nearly that level of access on Android. In fact, we can't even restart the nfc module to the same effect as what you do manually.

Nordpol just streamlines the access process in code and is better tested on various devices than what we have right now.

**Comment by ahippo** [comment]
I have a similar problem (at the first glance).
I also use OpenKeychain with Yubikey NEO storing 2 subkeys with master key stripped.

Decrypting a GPG-encrypted file with OpenKeychain gives "Data is corrupt".
Toggling NFC and rebooting the phone doesn't help.
Decrypting of other files (including of the same size, 361 bytes) works fine.
The file itself is not corrupted and is decrypted using the same Yubikey (connected via USB) on my Windows laptop just fine.

OpenKeychain version 3.9.5 (39510)
Sony Xperia Z1 Compact (D5503)
Android 5.1.1, build number 14.6.A.1.236, kernel 3.4.0-perf-gd26777b-00851-ga8b7b55

Please, let me know, if I can do anything useful to help investigate the problem.
