### ISSUE TITLE
encrypted txt by 8192 bits rsa cannot to be decrypted

### ISSUE THREAD

**Issue by pkchust** [open-keychain/open-keychain#1703]
app said that cannot found the key in the stream
could you let the app support 8192 rsa ?

**Comment by Valodim** [comment]
OpenKeychain supports 8192 rsa, the error is something else.

If the precise error message is "No encrypted data with known secret key found in stream!", then the data is encrypted to a secret key which is not available to openkeychain.

**Comment by pkchust** [comment]
yes 👍 . you're right. 
thanks.

从我的android设备发送。

-----Original Message-----
