### ISSUE TITLE
OpenKeychain on Chrome

### ISSUE THREAD

**Issue by jzbz** [open-keychain/open-keychain#1704]
Hi, I have converted the OpenKeychain apk to a Chrome app using ARC Welder. It has a few bugs but works well for my intended purpose (symmetric text encryption).

Many core functions such as key creation, importing keys, and signing messages work flawlessly.

There seems to be an issue with the ability to write files as well as some minor GUI issues. Are there any plans by the project to release OpenKeychain on Chrome? I am willing to submit it myself to the Chrome store for my own convenience however I would hold off if an official release is in the works as it would be much more desirable to have a package from upstream since we are dealing with security software.

Thanks.

![c1](https://cloud.githubusercontent.com/assets/4731927/12592568/ffb6737c-c43a-11e5-85d9-1ed9d08bfcfe.png)
![c2](https://cloud.githubusercontent.com/assets/4731927/12592570/ffbdcbea-c43a-11e5-8a47-091867c048f7.png)
![c3](https://cloud.githubusercontent.com/assets/4731927/12592569/ffb74194-c43a-11e5-9b6c-eee58a6f14ad.png)

**Comment by ajay340** [comment]
Cool but don't really see the point of this.

**Comment by dschuermann** [comment]
Funny that this works. In my experiment with ARC Welder on Linux I was not able to produce a chrome app. It keeps spinning and never ends...
But nevertheless, currently we don't have plans to support Chrome, but that could change in the future. I leave this open for now...

**Comment by jzbz** [comment]
@dschuermann Yes I had the same problem when trying to build it using Chromium in Debian. I was unable to solve the issue so I just used ARC Welder on Chrome OS and it completed without issue.
