### ISSUE TITLE
Can't enter Alphanumeric Key for Yubikey

### ISSUE THREAD

**Issue by metabubble** [open-keychain/open-keychain#1710]
Hi,

i have setup my yubikey with some other method and now I am failing to decrypt a message with open-keychain.

What do I do?
- Open The App
- Decrypt from paste
> It asks for pin.

My "pin" is a 18 letter alphanumeric string. However I can only enter a number. Any letter is ignored, just the numbers of my "pin" are accepted.

My setup works fine on windows and linux. Please enable all characters for the pin.

Thank you.

**Comment by dschuermann** [comment]
In OpenKeychain's preferences you can disable "Use number keypad for Security Token".

**Comment by metabubble** [comment]
Tip for users experiencing the same problem:

Disabled (was default setting) -> didn't work
enabled, disabled again -> now it works.

**Comment by Valodim** [comment]
please also note that your key is hardware-protected so an attacker has only 3 guesses. a 6 digit pin is engirely sufficient for this attack scenario.

**Comment by metabubble** [comment]
In my opinion, with people looking over your shoulder from time to time, I fancy a longer more complex one. But that's personal preference :)

**Comment by dschuermann** [comment]
@metabubble Thx for the bug report. Fixed in https://github.com/open-keychain/open-keychain/commit/cbf6f15d91f53f460584d959fcd16440c9309be1

**Comment by metabubble** [comment]
Thank you for this great project! Have a nice day.
