### ISSUE TITLE
Spreadshirt Shop 

### ISSUE THREAD

**Issue by UdoKifferbrehl** [open-keychain/open-keychain#1711]
Hey there, 
do you have a Spreadshirt shop? It is an awesome possibility to collect supporters. 
Thanks.

**Comment by dschuermann** [comment]
Not planned right now. But you can support us via Bitcoins or PayPal at https://www.openkeychain.org/

Our logo is also available in high quality here: https://github.com/open-keychain/open-keychain/tree/master/Graphics/drawables/material-launcher So you can print your own shirt if you like! If you really do this, it would be awesome to send us a photo ;)
