### ISSUE TITLE
Crash when using a key over 1MB (edward-en@fsf.org)

### ISSUE THREAD

**Issue by pixelrust** [open-keychain/open-keychain#1714]
OpenKeychain 3.8.2. (38200) regularly crashes on Android 4.4.4 when I try to visualize details of a certain contact. It also crashes when in K-9 email client I try to open messages signed or encrypted by this contact.

The app doesn't crash with other contacts.

The contact is edward-en@fsf.org aka "Edward the GPG Bot" (it's a [public email service](https://emailselfdefense.fsf.org/en/#section3) mentioned in a FSF guide to GPG). 
I don't know much about this but I note that, unlike my other OpenKeychain contacts, this User ID of this key includes many international characters:
http://pgp.mit.edu/pks/lookup?search=edward-en%40fsf.org&op=index

**Comment by dschuermann** [comment]
Very interesting failure case. After looking at the key and the database blob (3134521 byte), I suspect that it can't be displayed because Android's Cursor implementation is limited to 1 MB. Also see http://stackoverflow.com/questions/12716859/retrieve-large-blob-from-android-sqlite-database . We need to think about a solution to this problem...

**Comment by dschuermann** [comment]
@Valodim Not sure how this compares to Android, but: http://www.sqlite.org/intern-v-extern-blob.html

Maybe we should store the key blobs using files with their long key id as the filename?

**Comment by dschuermann** [comment]
I am not sure if we should support such big keys. If we allow unlimited key blobs, a simple keyserver import (or later automatic import from autocrypt) can blow up OpenKeychain. Still, it is an issue that we cannot import this key.

What if:
* if key is > 1 MB throw away all certificates and then save as blob
* if key is still too big fail with clear error message that such huge keys are unsupported

@Valodim What do you think?

**Comment by Valodim** [comment]
I was about to write pretty much the same thing :) Although I don't think it's that big an issue that we can't import this key, at least not if our error reporting was a little more helpful about what's wrong.

Any ideas for a heuristic on what certs to drop? Oldest?

**Comment by gloomytrousers** [comment]
If I understand correctly, certs also indicate the level of trust the signer has in the key/level of verification performed. So start by throwing away the ones with the weakest levels?

**Comment by dschuermann** [comment]
This should be fixed in 4.3. Please try again. If there are still problems we can re-open this issue.
