### ISSUE TITLE
Autorename while Encrypting File

### ISSUE THREAD

**Issue by scopeInfinity** [open-keychain/open-keychain#1718]
If we encrypt a file and provide a filename which already exists. It automatically renames it to `<filename> (1)`, `<filename> (2)`, `<filename> (3)`, ... and so on without notifying user.

**Comment by scopeInfinity** [comment]
For the fix, a prompt before auto rename should be there or a simple message notifying with Exported filename.

**Comment by dschuermann** [comment]
I think this is done by Android's storage access framework, so we can't handle this in our own.
