### ISSUE TITLE
When trying to import a key using the Yubikey NEO no key is found

### ISSUE THREAD

**Issue by materechm** [open-keychain/open-keychain#1719]
Am currently running Android version 6.0.1 and OpenKeychain version 3.8.2

**Comment by dschuermann** [comment]
Not enough information to debug, but it's certainly an area we like to improve, see https://github.com/open-keychain/open-keychain/wiki/Google-Summer-of-Code-2016#security-token-improvements

**Comment by materechm** [comment]
Below is a screenshot of the actual error

**Comment by materechm** [comment]
Here is a screenshot of the error 
![screenshot_20160223-172939](https://cloud.githubusercontent.com/assets/2557870/13278755/bac985de-da87-11e5-855a-7d04791d2ebf.png)

**Comment by dschuermann** [comment]
Have you uploaded the key to a keyserver? This import works only if the public part of the key is available on a keyserver.

**Comment by Valodim** [comment]
another one of these little wording things. "Search key on the internet" instead of "Import key" would make it clear what's going on.

**Comment by materechm** [comment]
resolved, thanks

**Comment by pnorton** [comment]
I disagree with closing this issue.  There is a valid security model where people do not upload their keys to public key servers.  I would like to have the option to select one of the following methods.
~ Public Key Server
~ Keybase.IO
~Providing a file.

**Comment by dschuermann** [comment]
@pnorton You are commenting on a closed issue, please look into https://github.com/open-keychain/open-keychain/issues/1587
