### ISSUE TITLE
Contact synchronization notification

### ISSUE THREAD

**Issue by ghost** [open-keychain/open-keychain#1720]
On Android 6.0 Openkeychain keeps asking me to allow contact synchronization. It seems it'll keep bothering me until I allow permission to my contacts. It should only appear once if at all (if contact synchronization is disabled there's no point to ask for contact access)
To be clear, it's not an Android permission dialogue, it's notification from the app itself that links to the settings page for synchronization.

Besides, I don't see the point in syncing openkeychain to my contacts since it will only create duplicated contacts.

**Comment by clawoflight** [comment]
It will not create duplicate contacts. It will link the openkeychain contact with any existing system contact, like you may be used to from whatsapp or similar.

**Comment by Valodim** [comment]
Yeah that way you have a link from contact details to their keys.

Either way, it is certainly a bug that this dialog keeps coming up. If the user said no once (or maybe twice), it should not come up again.

**Comment by akoul** [comment]
Is it possible to test this bug on emulator? I do not have android 6.0

**Comment by dschuermann** [comment]
@akoul sure, why shouldn't it be reproduced in an emulator?

**Comment by advaita13** [comment]
I have a fix in mind. Before that I'm trying to reproduce the bug so I can later understand if the fix is working as expected. Should be fairly straightforward.

**Comment by tdjogi010** [comment]
@dschuermann I am able to reproduce the bug. The notification comes from the ContactSyncAdapterService class, do you want to stop the service after the user has ignored it several times (number of times ignored can be stored in sharedpreferences) OR let the service be running and just don't publish the notification? I think the former one suits the best.

**Comment by advaita13** [comment]
@dschuermann I too was considering using SharedPreferences to store how many times the notification has been generated. Let's see if that works.

**Comment by dschuermann** [comment]
This notification should not come up because the automatic sync is turned of when before the notification is shown, so it should only come up once. BUT: I think requestContactsSync() ignores if automatic sync is turned on or off, maybe this method needs to check before syncing if automtic sync is turned on. But this is just a guess. This needs to be tested thoughtfully.

**Comment by advaita13** [comment]
True. The issues seems to stem from the requestContactsSync() method. I've implemented the fix using SharedPreferences and it seems to work. I tracked the usages of the ContactSyncAdapterService class and used this information to test the app against every situation that might cause the notification to resurface. It hasn't reappeared so far :)

**Comment by dschuermann** [comment]
@advaita13 Would it be possible to fix this without introducing a shared pref? Can't we check if an account is set to automatic sync before requestContactSync?

**Comment by advaita13** [comment]
@dschuermann Certainly. Introduced a check in the requestContactSync method that checks if the user has disabled automatic sync by accessing the ContentResolver class. Tested it, works so far.

**Comment by dschuermann** [comment]
@advaita13 please make a pull request :)

**Comment by advaita13** [comment]
@dschuermann @adithyaphilip Sorry for the confusion guys. There was some issue with my Git. Had to redo.

https://github.com/open-keychain/open-keychain/pull/1743

**Comment by kratz00** [comment]
I am still seeing these notifications "Access to contacts required. Touch to configure linking to contacts".
They keep coming, as I did not enable the "Link keys to contacts" feature.

- Nexus 5 (Android 6.0.1)
- OpenKeychain 4.2 (installed via F-Droid)

How can I help to pinpoint the problem?

**Comment by dschuermann** [comment]
@kratz00 Please open a new issue
