### ISSUE TITLE
Importing private key fails: no valid user IDs!

### ISSUE THREAD

**Issue by JasperWeiss** [open-keychain/open-keychain#1726]
When importing my private key, the following error occurs:

`Importing secret key xxxxx`
`canoncializing secret keyring xxxxxx`
`processing master key`
`removing bad self certificate for user ID xxxxx`
`removing invalid user ID xxxxxx`
`removing bad self certificate for user ID xxxxx`
`removing invalid user ID xxxxxx`
`Keyring has no valid user IDs!`
`merging in self-certificates data from public keyring`

GPG key created on Ubuntu 15.10, GnuPG  1.4.18
Key size 4096 bit RSA
Key ID 9B747005

I changed the digest preference to SHA512, this may be causing the bad self certificate error?

**Comment by dschuermann** [comment]
Sounds like you are running into the GPG bug: https://www.openkeychain.org/faq/#importing-your-own-key-from-gnupg-fails

**Comment by JasperWeiss** [comment]
Aha, I see. Is there any way I can fix the key? I no longer have the original one

**Comment by JasperWeiss** [comment]
Hmm it seems I can't. So I guess I'll have to start with a fresh key.

**Comment by Valodim** [comment]
exporting it with gpg 2.X usually fixes that problem

**Comment by JasperWeiss** [comment]
Will that still work with the already 'broken' key?

**Comment by Valodim** [comment]
yes

**Comment by JasperWeiss** [comment]
Great, thanks
