### ISSUE TITLE
API: ACTION_GET_KEY_IDS always returns user interaction

### ISSUE THREAD

**Issue by rivalsolutions** [open-keychain/open-keychain#1729]
Hi,

calling `getKeyIds(new Intent())` on the following code results in requiring user interaction but the key for the specified email is already imported into open-keychain app.
```
public void getKeyIds(Intent data) {
        data.setAction(OpenPgpApi.ACTION_GET_KEY_IDS);
        data.putExtra(OpenPgpApi.EXTRA_USER_IDS, "afftrader@rival.work");
        Log.i("test", data.getExtras().toString());

        OpenPgpApi api = new OpenPgpApi(this, mServiceConnection.getService());
        api.executeApiAsync(data, null, null, new MyCallback(false, null, REQUEST_CODE_GET_KEY_IDS));
    }
```
Doing something wrong or am i just misunderstanding how it should work?
any advise is welcome!

**Comment by dschuermann** [comment]
What activity is shown for this user interaction?

**Comment by rivalsolutions** [comment]
it says: "Please select the recipients!"
then a search field and the list of keys that are available.
the one i'm looking for is there as wel, when i select it and press "OKAY" all works as expected.

**Comment by dschuermann** [comment]
``EXTRA_USER_IDS`` expects an array of strings ``String[]``. It should work if you change that.

**Comment by rivalsolutions** [comment]
Thank you very very much!
For correcting my stupid mistake and all your work on this project!
