### ISSUE TITLE
Discover public key not on keyserver (its on symantec pgp server)

### ISSUE THREAD

**Issue by rivalsolutions** [open-keychain/open-keychain#1731]
Hi,

I created a app that uses OpenKeychain and it works great!
Now i got some contacts from which i only have a email address and there is no public key found on the keyserver for that email address.

I now the contacts use PGP and the reason i cant find the public key i believe is because they use PGP trough the Symantec universal PGP server. Is there any way to get the public key from the symantec server?

Thanks in advance

**Comment by Valodim** [comment]
if the keyserver has a hkps interface, you can add it to your list of keyservers. we do not support ldap, though. you can also open a dialog to import keys by launching an intent with action `org.sufficientlysecure.keychain.action.IMPORT_KEY`, or various types of urls which point to keys (openpgp4fpr, keyserver-uris, *.asc uris)

**Comment by rivalsolutions** [comment]
thanks!
