### ISSUE TITLE
Use Rfc822Tokenizer instead of Regex?

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1732]
I just discovered Rfc822Tokenizer, which could be used to parse User IDs. Maybe this works better than our regex.

This must be tested!

**Comment by Valodim** [comment]
sounds like a simple fix

**Comment by rohands** [comment]
@dschuermann I'll give it a shot

**Comment by ludwwwig** [comment]
@rohands Have you made any progress? I would be interested to help with this!

**Comment by dschuermann** [comment]
@ludwwwig go ahead, rohands comment is old enough.

**Comment by Valodim** [comment]
rfc822tokenizer is [not the most thoroughly tested class](https://android.googlesource.com/platform/cts/+/e86ece2/tests/tests/text/src/android/text/util/cts/Rfc822TokenizerTest.java), but I suppose it'll do.

**Comment by fiaxh** [comment]
Using Rfc822Tokenizer would lead to a few problems. As emails are an obligatory component of the user ID for the Rfc822Tokenizer, some cases of PGP UIDs are not parsed correctly:
*  A user ID of the form "Name (Comment)" would be interpreted as email: Name, comment: Comment.
* "Name" would be parsed as email: Name
* " (Comment)" wouldn't be parsed at all
The first two cases could be solved by pattern-matching the result from Rfc822Tokenizer. But on the other hand, the regex results could be improved by checking some side cases, too. And by doing this "manually", it's more flexibly adaptable to actually occurring PGP UID formats. (See PR)

**Comment by dschuermann** [comment]
@fiaxh thanks for your tests and your pull request.
