### ISSUE TITLE
Increase API version for 3.9

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1735]
Increase API version and write API changelog before release

**Comment by Valodim** [comment]
Do keep the experimental features undocumented, please. If something ever changes there, we definitely don't want the hassle of staying backward compatible with that.

**Comment by dschuermann** [comment]
ACK :)

**Comment by dschuermann** [comment]
Please push changes in openpgp-api git to master and also increase version check in OpenPgpService to include 11

**Comment by Valodim** [comment]
huh, I thought I had pushed that. weird.
