### ISSUE TITLE
Save split user ids in database

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1745]
This is a follow-up of #1536. We want to be able to disambiguate user ids in the key list even if they have comments, so we can't simply compare user id strings for this (cf. [here](https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/provider/KeychainProvider.java#L311)) without completely destroying search index performance.

As a first step, the split user ids should be saved in the database in addition to the full user id string. This is redundant, but user ids are short so it's no big deal.

**Comment by Valodim** [comment]
I have a concrete need for this, if someone gave this a go I would appreciate it. (I'll probably do it myself sometime next week otherwise)

**Comment by fjodorver** [comment]
First step is done in pull request #1745

**Comment by fjodorver** [comment]
pull request is updated

**Comment by fjodorver** [comment]
Updated HAS_DUPLICATE_USER_ID in KeychainProvider

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/pull/1763
