### ISSUE TITLE
Dark theme no longer works in main screen on android 5

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1746]
By mail:
```
Hello. The latest version the dark theme no longer applies to the main screen
on android 5.5.1 on my sony experia z5. It does apply in the menu and options
settings. Previous version had no issues. Thanks.
```

On Android 6 it works. I assume it has to do with the changes in the support lib 23.2, see http://android-developers.blogspot.de/2016/02/android-support-library-232.html

**Comment by 007durgesh219** [comment]
It's because initTheme() is called before super.onCreate in BaseActivity.  Calling it after will solve this problem. See #1750

**Comment by dschuermann** [comment]
thanks @007durgesh219
