### ISSUE TITLE
K-9 stable: "OpenPGP: Unknown compression algorithm" 

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1752]
When encrypting a mail with current K-9 Mail it shows a toast "OpenPGP: Unknown compression algorithm" 

Reproduce:
1. Open K-9 Mail
2. Create new mail and check "encrypt" and "sign"
3. On sending mail, I see the OpenKeychain dialog that asks for the allowed keys. After saving, a toast comes up "OpenPGP: Unknown compression algorithm" and the mail is not send
4. After this first error, it works. This toast is only shown this one time for me.

I can't remember that this happened with 3.8, must be new. There is also a Google Play review about this.

We should better also test this with the other client apps.

**Comment by mouse07410** [comment]
For me this bug is not triggered on **sending new** mail, but fails on **reply**. Also, it fails consistently - no matter how many times I try, reply with "Sign" and "Encrypt" fails with the above error message.

I'm on Android 5.5.1, perhaps that makes a difference???

**Comment by 007durgesh219** [comment]
This is because of following in OpenPgpService.java:291
```
int compressionId;
            if (enableCompression) {
                compressionId = PgpSecurityConstants.OpenKeychainCompressionAlgorithmTags.USE_DEFAULT;
            } else {
                compressionId = PgpSecurityConstants.OpenKeychainCompressionAlgorithmTags.UNCOMPRESSED;
            }
```
OpenPgpService.java:330
```
pseInput.setEnableAsciiArmorOutput(asciiArmor)
                    .setVersionHeader(null)
                    .setCompressionAlgorithm(compressionId)
                    .setSymmetricEncryptionAlgorithm(PgpSecurityConstants.OpenKeychainSymmetricKeyAlgorithmTags.USE_DEFAULT)
                    .setEncryptionMasterKeyIds(keyIds)
                    .setFailOnMissingEncryptionKeyIds(true);
```
Here value of USE_DEFAULT is -1. According to PgpSecurityConstants.java:228 we should use ZIP as default algorithm.

Please see #1757

**Comment by dschuermann** [comment]
thanks @007durgesh219
