### ISSUE TITLE
Import From File: Import from multiple files not working

### ISSUE THREAD

**Issue by 007durgesh219** [open-keychain/open-keychain#1762]
In Import from the file if we first open file then open another file without import this one then it will replace it.  I will be better to allow import both. @dschuermann was it intended or can be improved ??

**Comment by 007durgesh219** [comment]
![2016_03_07_07_17_39 2](https://cloud.githubusercontent.com/assets/7701929/13559285/8c8be454-e438-11e5-9c9e-28d0d51a423c.gif)

**Comment by 007durgesh219** [comment]
![2016_03_07_07_17_39 2](https://cloud.githubusercontent.com/assets/7701929/13559361/72a1ee98-e439-11e5-84d6-e3677c5ef154.gif)

**Comment by dschuermann** [comment]
superseeded by new import screen
