### ISSUE TITLE
None of the allowed keys is able to decrypt the content.

### ISSUE THREAD

**Issue by tastytea** [open-keychain/open-keychain#1768]
Hi,
since 3.9.2 I can't decrypt chat messages in Conversations(Jabber client) anymore. Error message is: "None of the allowed keys is able to decrypt the content."
I deleted OpenKeychain and reinstalled it, same error. I downgraded to 3.9 and it works again.

**Comment by Valodim** [comment]
In the Apps -> Conversations fragment, is your key marked as allowed?

**Comment by tastytea** [comment]
I found the error. I use a Jabber-client on my PC which encrypts only with the public key of the recipient. These messages are transferred via carbons to Conversations and are, of course, not decryptable by me.
