### ISSUE TITLE
Add button "Get it on F-Droid"

### ISSUE THREAD

**Issue by PanderMusubi** [open-keychain/open-keychain#1770]
Please, upgrade the "Get it on F-Droid" on your website https://www.openkeychain.org/ with a PNG file from https://commons.wikimedia.org/wiki/File:Get_it_on_F-Droid.svg Also add a button in your README.md file on GitHub. Both buttons please with the appropriate link to the page of your app on F-Droid.

**Comment by dschuermann** [comment]
Done for https://www.openkeychain.org/
On Github no badge for installation is needed IMHO

**Comment by PanderMusubi** [comment]
Thanks.

On GitHub it is more and more common. Some apps do not have a homepage other than GitHub repo and the README.md comes a bit more to life. See as example https://github.com/PanderMusubi/android-galaxyzoo/commit/2a4aa02a4bac722f1cd02e69771b135589344f95

**Comment by dschuermann** [comment]
Yup, but we have a homepage :)
