### ISSUE TITLE
Use white icons in Settings for dark theme

### ISSUE THREAD

**Issue by PanderMusubi** [open-keychain/open-keychain#1773]
Please, use white icons in Settings for dark theme.

**Comment by dschuermann** [comment]
The dark theme is an experimental Feature. We accept pull request for it but we will not put our own effort in it, because there are much more important issues.

**Comment by PanderMusubi** [comment]
FYI: This particular issue comes from a bug in the dark theme from Cyanogen. Nothing expected from open-keychain from me regarding this.
