### ISSUE TITLE
Migrate to OkHttp3

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1775]
We should migrate from OkHttp2 to OkHttp3. See https://github.com/square/okhttp/blob/master/CHANGELOG.md#version-300-rc1 for migration notes.

**Comment by dschuermann** [comment]
Hey @kepuss , you did great work in https://github.com/open-keychain/open-keychain/pull/1748 replacing the apache client with okhttp. Do you also like to tackle this migration to okhttp3 ?

**Comment by kepuss** [comment]
Hi, 
Ok, I can handle it

**Comment by kepuss** [comment]
Hi
I've got one question. Interface KeybaseUrlConnectionClient has method openConnection. Implementation of this interface is OkHttpKeybaseClient which uses depricated OkUrlFactory. So I've changed it to OkHttpClient and also interface and the usages. Should I do something with another implementation DefaultKeybaseUrlConnectionClient which is never used, or it should be deleted?

**Comment by dschuermann** [comment]
Sounds good. If it's never used you can delete it.

**Comment by dschuermann** [comment]
fixed by https://github.com/open-keychain/open-keychain/pull/1783
