### ISSUE TITLE
Missing key for encryption: %s in K9-Mail

### ISSUE THREAD

**Issue by steelman** [open-keychain/open-keychain#1781]
Android: 6.0.1
CyanogenMod: 13.0-20160205-NIGHTLY-peregrine
OpenKeychain: 3.9.2 (from F-Droid)
K9-Mail: 5.008 (F-Droid as well)

I am trying to send encrypted message, I've got public keys for both sender and recipient, no private key for sender though. I get the "Missing key for encryption: %s" message, meanwhile logcat shows

```
03-14 21:08:59.729  3888  5239 W Keychain: You are using a deprecated service which may lead to truncated data on return, please use IOpenPgpService2!
03-14 21:08:59.930 11761 11761 E k9      : OpenPGP Error ID:0
03-14 21:08:59.930 11761 11761 E k9      : OpenPGP Error Message:Missing key for encryption: %s
```

Both keys are valid and haven't expired. I can encrypt a message for those keys in OpenKeychain.

If you want more debug information please give me a step-by-stap for I am not an Android developer.

**Comment by Valodim** [comment]
This is a database inconsistency, not sure why it happened in your case. Try revoking access for k9 in `OpenKeychain -> Apps`, you should be asked to set it up again when you send an email after that.

**Comment by steelman** [comment]
It helped.

**Comment by Valodim** [comment]
These inconsistencies can have multiple reasons, mostly when keys are deleted after they have been associated with "accounts" used by apps. This whole issue goes away when apps no longer use the deprecated, account-based api. Not sure if it's worth investing into this at this point, the issue seems to occur relatively rarely

**Comment by steelman** [comment]
I suppose this issue may serve as a reference when properly indexed by search engines.

BTW. Is it (going to be) possible with the new API, to use openkeychain with k9 without any secret keys on a device?

**Comment by dschuermann** [comment]
Yes it is

**Comment by mathemaphysics** [comment]
And the same thing happens now years later but with PassworStore. I already revoked access and tried again.

Everything works (including decryption of passwords in the database for any length of time) except new password creation.

There is literally nowhere in either OpenKeyChain or PasswordStore where you set a single PGP key to encrypt with. There's the key authorization in OpenKeyChain, but that's permission to use keys (plural), not one.

And I've scoured PasswordStore and can find nowhere to specify the PGP ID.

**Comment by minikN** [comment]
> And the same thing happens now years later but with PassworStore. I already revoked access and tried again.
> 
> Everything works (including decryption of passwords in the database for any length of time) except new password creation.
> 
> There is literally nowhere in either OpenKeyChain or PasswordStore where you set a single PGP key to encrypt with. There's the key authorization in OpenKeyChain, but that's permission to use keys (plural), not one.
> 
> And I've scoured PasswordStore and can find nowhere to specify the PGP ID.

I have the same issue.

**Comment by scobiehague** [comment]
> > And the same thing happens now years later but with PassworStore. I already revoked access and tried again.
> > Everything works (including decryption of passwords in the database for any length of time) except new password creation.
> > There is literally nowhere in either OpenKeyChain or PasswordStore where you set a single PGP key to encrypt with. There's the key authorization in OpenKeyChain, but that's permission to use keys (plural), not one.
> > And I've scoured PasswordStore and can find nowhere to specify the PGP ID.
> 
> I have the same issue.

Same. Just installed off F-droid.

**Comment by jakechv** [comment]
> > > And the same thing happens now years later but with PassworStore. I already revoked access and tried again.
> > > Everything works (including decryption of passwords in the database for any length of time) except new password creation.
> > > There is literally nowhere in either OpenKeyChain or PasswordStore where you set a single PGP key to encrypt with. There's the key authorization in OpenKeyChain, but that's permission to use keys (plural), not one.
> > > And I've scoured PasswordStore and can find nowhere to specify the PGP ID.
> > 
> > 
> > I have the same issue.
> 
> Same. Just installed off F-droid.

Having this issue as well. Updated the application, created a new key and I'm now unable to create passwords associated with the new key.

**Comment by zachdoestein** [comment]
Same issue with passwordStore 1.13.1 and openkeychain 5.5. Both installed from F-Droid.

Can't create new passwords. 

Error: Failed to locate .gpg-id. Is your store set up correctly?

Do we need to create a new bug issue?

**Comment by jakeisnt** [comment]
@zachdoestein Yeah, looks like the best way to proceed is to create a new issue and link this one on it.

**Comment by thatwist** [comment]
I will post here as well as this issue pops in google while searching the problem - this [fix ](https://github.com/open-keychain/open-keychain/issues/2588#issuecomment-778886913) helps - just removing .gpg-id and letting password-store/openkeychain recreate it

**Comment by akiva** [comment]
This problem remains in other tools, see #2588
