### ISSUE TITLE
Import key from clipboard causes force close

### ISSUE THREAD

**Issue by sjug** [open-keychain/open-keychain#1786]
Hey guys,

Having issues with the import from clipboard functionality.

Steps to reproduce:

Load https://xmpp.is/pgp.asc.txt in chrome.
Select all, copy.
Load OpenKeychain.
Press plus action button on bottom right.
Press import from file.
Press clipboard icon to the right of the folder icon on the open button, top right.
"Unfortunately, OpenKeychain has stopped."

Logcat error looks like this:

> 03-15 14:02:39.344 15332-15332/? E/AndroidRuntime: FATAL EXCEPTION: main
>                                                    Process: org.sufficientlysecure.keychain, PID: 15332
>                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getScheme()' on a null object reference
>                                                        at org.sufficientlysecure.keychain.ui.ImportKeysListFragment.checkAndRequestReadPermission(ImportKeysListFragment.java:271)
>                                                        at org.sufficientlysecure.keychain.ui.ImportKeysListFragment.loadNew(ImportKeysListFragment.java:338)
>                                                        at org.sufficientlysecure.keychain.ui.ImportKeysActivity.loadCallback(ImportKeysActivity.java:331)
>                                                        at org.sufficientlysecure.keychain.ui.ImportKeysFileFragment$2.onClick(ImportKeysFileFragment.java:89)
>                                                        at android.view.View.performClick(View.java:5204)
>                                                        at android.view.View$PerformClick.run(View.java:21155)
>                                                        at android.os.Handler.handleCallback(Handler.java:739)
>                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                        at android.os.Looper.loop(Looper.java:148)
>                                                        at android.app.ActivityThread.main(ActivityThread.java:5422)
>                                                        at java.lang.reflect.Method.invoke(Native Method)
>                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Valodim** [comment]
Hi!

This issue was already fixed, and a fixed version (3.9.3) is uploaded to the play store. you should see an update sometime this day. Thanks for your report :+1:

**Comment by sjug** [comment]
Cool thanks, will it be updated on F-droid as well?

**Comment by Valodim** [comment]
You "bought" the app? OpenKeychain doesn't cost anything.

Yes, there will be an update on F-Droid as well.
