### ISSUE TITLE
Update to 3.9.4 removes any existing key

### ISSUE THREAD

**Issue by bpepple** [open-keychain/open-keychain#1789]
Upgrading to 3.9.4 causes my existing public/private key to be no longer available. Unable to determine if it was overwritten or just no longer accessible.

**Comment by Valodim** [comment]
Can you be more precise about "available"? Did they vanish from the key list? We specifically tested the migration path and that worked from two different intermediate states for us :(

**Comment by Valodim** [comment]
luckily, this issue seems to have occurred very rarely, and the problem existed in 3.9.3 only where the migration path was broken. nothing to do here, closing the issue.
