### ISSUE TITLE
Update NetCipher to get rid of "Tor appears not to be running"-message

### ISSUE THREAD

**Issue by vanitasvitae** [open-keychain/open-keychain#1792]
Hi!
On AOSP>=Android N and also on CopperheadOS the flag hidepid=2 is set, which prevents apps from detecting, whether Tor is running or not. The GuardianProject fixed this in the latest version of NetCipher. Could you please update NetCipher, to make Key Synchronization via tor possible again?

**Comment by vanitasvitae** [comment]
Edit: See this issue on CopperheadOS:
https://github.com/copperhead/bugtracker/issues/197#issuecomment-196945201

**Comment by dschuermann** [comment]
I tagged this as help-wanted. Should be fixed, yes!

**Comment by Litun** [comment]
@dschuermann Could u review my pull request?

**Comment by vanitasvitae** [comment]
I'll try to implement this.

**Comment by vanitasvitae** [comment]
@dschuerman I think I fixed this. Can you review my pull request?

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/pull/1865
