### ISSUE TITLE
Request the storage read permissions when it is not granted.

### ISSUE THREAD

**Issue by czchen** [open-keychain/open-keychain#1794]
I have a problem importing my new key. The app crashes with `open failed: EACCES (Permission denied)`. After some googling, I found that the permission is not granted in my Android 6 phone. I changed the permission and everything works fine now.

I think the app needs to implement [Requesting Permissions at Run Time](https://developer.android.com/training/permissions/requesting.html#handle-response) so that app won't crash when the storage permission is not granted.

**Comment by dschuermann** [comment]
What OpenKeychain Version are you using?

**Comment by czchen** [comment]
3.8.2

**Comment by czchen** [comment]
It is fixed in 3.9.4.
