### ISSUE TITLE
Backup of key not working

### ISSUE THREAD

**Issue by dimpfelmoser** [open-keychain/open-keychain#1799]
Android 4.4.2, Samsung Galaxy S4 mini, OpenKeyChain 3.9.4

Created new key pair. Now I am trying to export the thing.
Menu -> backup key -> entered password -> wrote down Backup-code -> pressed "OK, I have it..." -> entered the same Backup code (why???) -> nothing, no button to confirm this, no message, it just sits there showing me the code I just entered

**Comment by Valodim** [comment]
you likely missed a character in the code. the dialog should proceed when all characters are filled.

we ask to input the code again to make sure the user actually wrote it down correctly. yes it's a hassle, but believe me it's more of a hassle when people don't write it down or have a typo or anything like that and only notice when they try to restore the backup but can't.

**Comment by coupeborgward** [comment]
Same here. Once entered no button. 100% sure code is correct

**Comment by nbm077** [comment]
backup not working, tried deleting dashes and crashes app

**Comment by Valodim** [comment]
Thanks for the feedback. We will change the ui widgets used in the backup dialog to the previous way in the next release, that should hopefully provide more stable behavior.

**Comment by Valodim** [comment]
tracking issue in #1815
