### ISSUE TITLE
Crashes when being a protected app of Cyanogenmod

### ISSUE THREAD

**Issue by rugk** [open-keychain/open-keychain#1801]
OS: `CM-13.0-20160325-NIGHTLY-jfltexx`

Reproduce:
1. [Protect](http://androidcommunity.com/cyanogenmod-adds-protected-apps-teases-cmhome-20140622/) OpenKeychain with a pattern.
2. Try to open an (PGP/MIME) encrypted mail with K9 mail (this means you basically open an `.asc` file): [screencast.mp4.zip](https://github.com/open-keychain/open-keychain/files/192163/screencast.mp4.zip)

After unlocking the app it crashes. Note that this does _not_ happen when the app is not a hidden/protected app.

**Comment by 007durgesh219** [comment]
I am running cm13 on oneplus one and its working fine

**Comment by pbeckmann** [comment]
Hello,

i can reproduce it. After the protection is enabled and i open a  pgp/mime mail, (means .asc attachment), I'll get a notification which says: "OpenKeychain was unable to start. Tipp to authenticate and to start the app." (Translated from german).

If I tap on the notification, then i have to enter the pattern. After that there is the decryption view shortly visible, before the app crashes.

Logcat:

`03-31 22:16:08.619  3413  5766 E DatabaseUtils: Writing exception to parcel
03-31 22:16:08.619  3413  5766 E DatabaseUtils: java.lang.SecurityException: Permission Denial: reading com.fsck.k9.provider.AttachmentProvider uri content://com.fsck.k9.attachmentprovider/5dbd3d2e-403b-47af-a3bd-ae6214ceb795/829/VIEW from pid=11042, uid=10070 requires com.fsck.k9.permission.READ_ATTACHMENT, or grantUriPermission()
03-31 22:16:08.619  3413  5766 E DatabaseUtils: 	at android.content.ContentProvider.enforceReadPermissionInner(ContentProvider.java:605)
03-31 22:16:08.619  3413  5766 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceReadPermission(ContentProvider.java:480)
03-31 22:16:08.619  3413  5766 E DatabaseUtils: 	at android.content.ContentProvider$Transport.enforceFilePermission(ContentProvider.java:471)
03-31 22:16:08.619  3413  5766 E DatabaseUtils: 	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:416)
03-31 22:16:08.619  3413  5766 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:313)
03-31 22:16:08.619  3413  5766 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:453)
03-31 22:16:08.621 11042 11057 E AndroidRuntime: FATAL EXCEPTION: Thread-332
03-31 22:16:08.621 11042 11057 E AndroidRuntime: Process: org.sufficientlysecure.keychain, PID: 11042
03-31 22:16:08.621 11042 11057 E AndroidRuntime: java.lang.SecurityException: Permission Denial: reading com.fsck.k9.provider.AttachmentProvider uri content://com.fsck.k9.attachmentprovider/5dbd3d2e-403b-47af-a3bd-ae6214ceb795/829/VIEW from pid=11042, uid=10070 requires com.fsck.k9.permission.READ_ATTACHMENT, or grantUriPermission()
03-31 22:16:08.621 11042 11057 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)
03-31 22:16:08.621 11042 11057 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
03-31 22:16:08.621 11042 11057 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
03-31 22:16:08.621 11042 11057 E AndroidRuntime: 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:692)
03-31 22:16:08.621 11042 11057 E AndroidRuntime: 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1107)
03-31 22:16:08.621 11042 11057 E AndroidRuntime: 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:944)
03-31 22:16:08.621 11042 11057 E AndroidRuntime: 	at android.content.ContentResolver.openInputStream(ContentResolver.java:664)
03-31 22:16:08.621 11042 11057 E AndroidRuntime: 	at org.sufficientlysecure.keychain.pgp.PgpDecryptVerifyOperation.execute(PgpDecryptVerifyOperation.java:101)
03-31 22:16:08.621 11042 11057 E AndroidRuntime: 	at org.sufficientlysecure.keychain.operations.InputDataOperation.execute(InputDataOperation.java:110)
03-31 22:16:08.621 11042 11057 E AndroidRuntime: 	at org.sufficientlysecure.keychain.operations.InputDataOperation.execute(InputDataOperation.java:69)
03-31 22:16:08.621 11042 11057 E AndroidRuntime: 	at org.sufficientlysecure.keychain.service.KeychainService$1.run(KeychainService.java:146)
03-31 22:16:08.621 11042 11057 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
03-31 22:16:08.625  2277  4486 W ActivityManager:   Force finishing activity org.sufficientlysecure.keychain/.ui.DecryptActivity`

Greetings

**Comment by Valodim** [comment]
I have an older nightly of cyanogen and cannot reproduce this error.

Looking at the stack traces, my guess is that this happens because the uri permission granted by k9mail for the activity to access this particular attachment via the contentprovider is lost, as a side effect of cyanogen's protection mechanism. If that is the case, there is nothing we can do about that on our side

**Comment by rugk** [comment]
Okay, I reported it [over there](http://forum.cyanogenmod.org/topic/123572-protected-app-issue-with-openkeychain/).
