### ISSUE TITLE
Possible error

### ISSUE THREAD

**Issue by philipwhiuk** [open-keychain/open-keychain#1802]
Should you really be checking this in?

https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/build.gradle#185
https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/build.gradle#201

            // Github API
            buildConfigField "String", "GITHUB_CLIENT_ID", "\"c942cd81844d94e7e41b\""
            buildConfigField "String", "GITHUB_CLIENT_SECRET", "\"f1dd17e70a0614abbd9310b00a310e23c6c8edff\""

> First, you'll need to register your application. Every registered OAuth application is assigned a unique Client ID and Client Secret. The Client Secret should not be shared! That includes checking the string into your repository.

https://developer.github.com/guides/basics-of-authentication/

**Comment by Valodim** [comment]
Yes. We don't approve the use of snakeoil. The secret is also worthless without session tokens, other than to troll the api key itself.
