### ISSUE TITLE
PIN not rerequested in case it is wrong with fidesmo privacy card

### ISSUE THREAD

**Issue by languitar** [open-keychain/open-keychain#1803]
I am using openkeychain with a fidesmo privacy card. If I entered a wrong PIN for the card and connect it via NFC I see two things happening:

* the error message does not indicate that the PIN is wrong but instead only states: "Security Token reported invalid data. Take away the Security Token now and touch TRY AGAIN"
* there is no new dialog asking for a new PIN. Instead, attempts are repeated with the old PIN, easily wasting the three iterations before the admin PIN is required.

Both things sound as if they should be solved according to #1039 but apparently are not in 3.9.4.

Additionally, I couldn't even find a way to unblock the card using openkeychain with the admin PIN.

**Comment by dschuermann** [comment]
Thanks for your report.
Indeed unblocking a card with an Admin PIN is not supported right now.

I will try to reproduce your problem when I am back in the office where I have a Fidesmo card and some time. I thought that this problem has been fixed. Maybe it is a regression bug. At which point has this happened? When creating a new key or when signing/decrypting?

**Comment by dschuermann** [comment]
Looks like the same problem like reported in https://github.com/open-keychain/open-keychain/issues/1848
Should be fixed in the next version of OpenKeychain. If not please re-open this issue.
