### ISSUE TITLE
Make keyserver upload non-default

### ISSUE THREAD

**Issue by morth** [open-keychain/open-keychain#1811]
This is related to #1674 and #1127.

Up to now the keyserver upload checkboxes (when creating a new key pair or updating identities) are checked by default. Reasons why I think they shouldn't be:

- The checkbox on the identity edit activity can be overlooked very easily, especially when you unchecked it the last time you were editing that key.
- Data protection: As personal information will be published, this should require an Opt-in rather than an Opt-out.

**Comment by dschuermann** [comment]
Thanks for raising this issue. I bundled the discussion about this here: https://github.com/open-keychain/open-keychain/issues/1847
