### ISSUE TITLE
GoogleHandwritingInput breaks backup key input

### ISSUE THREAD

**Issue by AlexFJW** [open-keychain/open-keychain#1814]
Found this out while testing the MaskedEditText fix I wrote. The bug is present in the original MaskedEditText.

Characters entered from GoogleHandwritingInput do not seem to checked by the InputFilter used by MaskedEditText. The total EditText length increases as characters are entered and the input mask breaks.

**Comment by Valodim** [comment]
ok that's it, we are ditching maskedinputtext. it is just too unreliable.

**Comment by Valodim** [comment]
see #1815
