### ISSUE TITLE
ditch MaskedEditText

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#1815]
We moved to using the MaskedEditText library in 713f3076f4ee1b94f1a1a133fba32a396c0d1039. However, this  has lead to a lot of problems, even after fixing various crashes and usability misbehaviors it's still not working *good*, and apparently for some users not at all in a way we haven't managed to reproduce (#1799).

So, back to the linked EditText views it is. This worked fine actually, we just need to be careful about the width-specific variants in the resource files.

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/commit/f7654af00b510aa91badc52eeacb09bf3d0b24e5

**Comment by dschuermann** [comment]
Released in 3.9.5 on Google Play and F-Droid
