### ISSUE TITLE
error : no such remote ref 7c84cb54df5b3d5c6780984e48f3e9e4cbc5128e Fetched in submodule path 'extern/safeslinger-exchange'

### ISSUE THREAD

**Issue by norani** [open-keychain/open-keychain#1820]
I want to run this apg app on Android Studio. I follow the steps provided. In step 2 which is 

`git submodule update --init --recursive `

I got error : 

> error : no such remote ref 7c84cb54df5b3d5c6780984e48f3e9e4cbc5128e  Fetched in submodule path 'extern/safeslinger-exchange', but it did not contain 7c84cb54df5b3d5c6780984e48f3e9e4cbc5128e . Direct fetching of that commit failed.

**Comment by dschuermann** [comment]
You are on the wrong issue tracker, this is not APG

**Comment by norani** [comment]
oh my god sorry. but it gives issues link directly to this webpage

**Comment by dschuermann** [comment]
OpenKeychain is the successor of APG, but we can't help you with old compile errors in APG.

**Comment by norani** [comment]
Thanks, now I'm fork OpenKeyChain instead of apg.
