### ISSUE TITLE
Cannot use i2p Email address

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1825]
We prevent the usage of test@mail.i2p. We should fix our regex or simply don't hard-fail if a non-conforming Email address is added. I favor the second option.

**Comment by Valodim** [comment]
Second option seems good. We also might want to support email address only user ids, for posteo

**Comment by 007durgesh219** [comment]
Can't we allow numbers after . (dot) in regex. That should fix it.
