### ISSUE TITLE
Decrypt strips data before first ... BEGIN PGP ...

### ISSUE THREAD

**Issue by ejhuff** [open-keychain/open-keychain#1826]
Decrypted a symmetric message that contains a PGP public key among other things.  Gpg on linux decrypts it correctly.  Open-keychain on android M strips data before the key block, including the armor header and blank line.

**Comment by Valodim** [comment]
"among other things"? can you be more precise?

or, ideally, provide a file for us to test :)

**Comment by ejhuff** [comment]
Working on it.  First attempt to create a sanitized example failed.

**Comment by ejhuff** [comment]
Okay.  I have a file encrypted with a passphrase I'd rather not divulge, that gpg on linux decrypts correctly, and open-keychain strips some of the leading lines.  But I reencrypted it with a different passphrase and open-keychain decrypts correctly.  I also reencrypted it with the same passphrase and again open-keychain decrypts correctly.  I checked the sha1sum of the encrypted data.  It is the same input file.  Trying a few more ideas.

**Comment by ejhuff** [comment]
Okay, I reencrypted the same file with a different passphrase same length.  The new encrypted file fails in the same way.  The bug is very sensitive to data.  Different length passphrase or changes to the file eliminate the bug.

**Comment by ejhuff** [comment]
Okay, try decrypting this:

-----BEGIN PGP MESSAGE-----

jA0ECQMCns1uG1WFsJRg0ukBOrrZ9H3UHM0T68xEIAQ/7AwR/esnHsny+ylXfE+v
mIema3yY5XBfKLRw3Gptshu3Vk+u98OqXeeL38uJJAN/ib4r4M2Gk4wPHgud39b1
xu1FabWveU05yLNq4/tRQ2E0cCgzZm1tQ+3g00xAKfgJCkC5L9s06YWxaHwm3coh
1x8ydXrEcQrrfjND5rq4uCuOvoNRXBSPDh+4n9P0qS4y8aORSA4NnSvDWtM08Rjf
MHWCuDguCC19bhUjyj0fJPaQUU+WFdjuZ21RkCfk3MJbTCbPY6EAP7lun7L+jomD
a0VfufGNrgIUtCi/ch77WYm95mnzGcUaeWeKQCZiwY6grwbaFk4nWEpZ5nMWbVH2
wovSGgdIE2FpB8AoPWdxy8dQZxoxyk5ShLvMQy+fxP9yc+n0thOnpI+uRHH6dMvT
METHY7C50yvx3Z31KXSfkQfz6wneClVGPqyXz/re73wjGPbzlJsHGnNKxSf1NiB0
JPa+XJPDh6nAUpm5GXKtoAeNEA1Qxx8VV1kEqla2jtlKImT1BRRM7vEFnzwsBoKI
J1uxOCobUY5jojeXaBcHlCxG0EbaG05rqAEPLkqpeVO23mNs8rHwcptL0dhC8cae
eZT2rKtpk5rUFQI1RiKQTX7+JoVPBhL/xbZjXgTl9hiuf3lT+zGBlXEF6PcW/sHs
7xnoG9CuwStR0mIOyz4hzu4sW6wueQF4MkH3
=QKzF
-----END PGP MESSAGE-----

**Comment by ejhuff** [comment]
Oh, right, passphrase is x

**Comment by ejhuff** [comment]
No trailing newline in the plaintext and encrypted using the gpg widget found at top of screen in latest tails, encrypt from clipboard.  Encrypting from command line didn't get the problem.  But command line gpg decrypts just fine.

**Comment by Valodim** [comment]
This decrypts for me in OpenKeychain the same as in gnupg. I'm guessing this was fixed along the way, I just forgot to close it here :)

Closing this issue, feel free to reopen if you can still reproduce this problem.
