### ISSUE TITLE
Cannot import .pfx file from storage as my key.

### ISSUE THREAD

**Issue by norani** [open-keychain/open-keychain#1829]
.pfx contain private and public key. I want to import my .pfx file from mass storage. So, under Manage my keys, I click IMPORT KEY FROM FILE>>Choose my .pfx file. But OpenKeyChain cannot detect it as a key.

**Comment by dschuermann** [comment]
Pfx files store X.509 keys for S/MIME. OpenKeychain only supports OpenPGP

**Comment by norani** [comment]
if I'm not mistaken, the first time I used OpenKeyChain and K9-Mail, during I setup my yahoo email in K9-Mail, K9-Mail automatically detect .pfx from my phone storage and set it as my key. but now I tried again(reinstall), it didn't detect and set it automatically anymore.. am I dreaming or what..

**Comment by dschuermann** [comment]
Must be the case. We never supported S/MIME and thus not pfx.
