### ISSUE TITLE
API: Restrict secret keys for sign operation

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1830]
OpenKeychain allows to restrict the set of secret keys allowed for decrypt operation per registered app. This means secret keys not explicitly selected by the user cannot be used to decrypt content.

The same restriction to selected secret keys must be implemented for the sign operation.

**Comment by kepuss** [comment]
@dschuermann thanks, I start working on this.

**Comment by rhari991** [comment]
Has this already been implemented in [this file](https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/ui/SelectSignKeyIdListFragment.java) ?

**Comment by dschuermann** [comment]
@rhari991 No, in this issue we mean the restriction to specific keys in the backend. The decryption operation checks for allowed keys here: https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpDecryptVerifyOperation.java#L602

Similar functionality must be implemented for https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSignEncryptOperation.java and signing keys.

**Comment by rhari991** [comment]
@dschuermann So before signing, the key used should be verified against the keys approved by the user (which can be used for both decryption and signing) ? Or do you mean that separate key lists should be maintained for signing and decryption ?

**Comment by dschuermann** [comment]
Yup,same key list should be used.
