### ISSUE TITLE
Integration with K-9 Mail is broken

### ISSUE THREAD

**Issue by neildarlow** [open-keychain/open-keychain#1836]
I unlock my key in OpenKeychain outside K-9 Mail and attempt to sign an e-mail with the following pop-up error dialog (captured by visual inspection as it is a transient dialog):

OpenPGP Error: Attempt to invoke virtual method
'org.bouncycastle.openpgp.PGPPublicKey
org.bouncycastle.openpgp.PGPSecretKey.getPublicKey()' on a null
object reference

I believe my public and private keys are correctly configured. They are visible in the OpenKeychain App keys page.

**Comment by dschuermann** [comment]
Please go to OpenKeychain -> Apps -> K-9 mail and revoke access inside the dropdown on the top right corner. Then reconfigure K-9 Mail.
Does this fix the problem?

**Comment by neildarlow** [comment]
Hi Dominik,

I have done that but there is still a problem.

Openkeychain prompts me to allow access for K-9 Mail which I have done.

When I attempt to send a signed and encrypted mail Openkeychain prompts me to assign a key for my mail account.

I can see my PGP key listed in the key selection drop-down but it is greyed and it cannot be selected so I cannot complete the key assignment process.

My PGP key was created by Openkeychain and I have trusted the key and set it as primary identity.

Regards,
Neil Darlow


-------- Original Message --------

**Comment by dschuermann** [comment]
@neildarlow That sounds really weird.

* Is your key under the section "My Keys" in the list?
* When you open your key, and then in the dropdown .-> Advanced -> Subkeys. Are there 3 keys that can certify, sign, and encrypt?

**Comment by neildarlow** [comment]
Hi,

No, there are just two subkeys. One has a red hexagon icon and the other a yellow closed padlock.

There is a single certificate marked positive.

So, it appears that Openkeychain has generated an incomplete key?

Regards,
Neil Darlow


-------- Original Message --------

**Comment by dschuermann** [comment]
There should be one subkey capable of signing with a pen icon.
I am not sure how this could have happened. Have you edited the key on your desktop with gpg?
However, you can add a new subkey for signing from that screen.

**Comment by neildarlow** [comment]
Hi,

No, the key was generated and managed entirely by Openkeychain.

I have revoked the existing subnets and identity and generated a new key. This one has 3 subkeys as expected.

My original subkeys were RSA-4096 but my new ones are RSA-3072. I'm guessing these will be OK.

Regards,
Neil Darlow


-------- Original Message --------

**Comment by neildarlow** [comment]
@dschuermann  Thank you for the assistance. All good now!

I created a new key and imported it to another Android device and PC running Linux. Same key works across all three devices without problems. Not sure what happened with my previous attempt.

**Comment by th0th1** [comment]
OK, it's been nearly a year since this exchange concluded, but I have exactly the same error, down to the missing pen icon etc., and I think I know what happened. 

It seems that, if you have multiple addresses associated with a key and use open keychain to make the second address primary, you will lose the ability to sign messages (the pen icon will disappear).

Can anyone verify this behaviour, and whether it is intended or a bug?

Thanks,

th0th

**Comment by dschuermann** [comment]
This issue report is closed. Please open a new one, also please consider opening one at K-9 Mail when you have a problem with K-9.
