### ISSUE TITLE
Import existing Key and store it on NFC device

### ISSUE THREAD

**Issue by tristan-k** [open-keychain/open-keychain#1838]
I recently purchased a Fidesmo Privacy Card as suggested on the [OpenKeychain FAQ Page](https://www.openkeychain.org/faq/#what-security-tokens-are-recommended-for-openkeychain). The FAQ only helps with importing keys to a YubiKey, since Fidesmo Privacy Card is nfc only, [this way](https://developers.yubico.com/PGP/Importing_keys.html) is not possible. I followed the [tutorial](http://about.fidesmo.com/about/devices/) linked by Fidesmo but was disapointed that there seems to be no way to import an existing key on the card. Did I miss something? Is this related to https://github.com/open-keychain/open-keychain/issues/1717 ?

**Comment by nmikhailov** [comment]
It will be available in future versions. There is a stub here:
Open Key view -> Menu -> Advanced -> Subkeys tab -> Edit -> Press on subkey -> Move Subkey to Security Token.
Not sure why it is not implemented yet, it is almost same procedure as creating key except we need to ask for a pin3. cc @dschuermann 

Also note that it will support only 2048 bit RSA key.

>  this way is not possible.

Well you can do the same thing if you have pc/sc compatible NFC card reader.

**Comment by dschuermann** [comment]
We disabled it because it was difficult to use.
In a recent version we moved the edit functionality into the "advanced" screen, so I am in favor of enabling the feature again.
@nmikhailov can you make a pull request for this? I am currently busy with other jobs, but I can make a release later.

**Comment by nmikhailov** [comment]
@dschuermann Ok, I will add it to my todo list

**Comment by dschuermann** [comment]
I re-enabled the option to move keys in 7b24679

Still, it is pretty limited, more discussion here: #1845
