### ISSUE TITLE
Make OpenKeyChain a Decryption Server

### ISSUE THREAD

**Issue by qjebbs** [open-keychain/open-keychain#1839]
Hey, OpenKeyChain is such a perfect app, thank you for all your amazing work!

Please consider making it a **Decryption Server**. By doing this, I will never have to setup PGP software or place keys everywhere. It's easy to deal with pgp message, and maybe "upload-decrypt-download" things for dealing with pgp files. The only problem is the security between the client-server connection.

**Comment by dschuermann** [comment]
OpenKeychain is a project to bring OpenPGP to Android. There are other projects trying to create a decryption server.
