### ISSUE TITLE
Synchronization checkbox checked even if no upload chosen

### ISSUE THREAD

**Issue by Thom2016** [open-keychain/open-keychain#1843]
I created a new key with OpenKeychain and have chosen not to upload / share my key. When I now click on "edit" the check box "synchronize with internet" is checked anyway and even when unchecking it won't save that state.

As I primarily use OpenKeychain to encrypt files, I am somewhat concerned that my mail address has now been uploaded or will be uploaded to the internet where spam bots get access to it.

I would appreciate
- to fix that check box function
- make the status visible whether a key is online available on a server
- adding a function to add/edit/remove key servers

Kind regards
Thomas

**Comment by dschuermann** [comment]
Thanks for raising this issue. I bundled the discussion about this here: https://github.com/open-keychain/open-keychain/issues/1847
