### ISSUE TITLE
Security Token: Admin PIN handling

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1844]
We assume that the Admin PIN is 12345678 by default when creating new keys or moving existing keys to security tokens.
A problem can occur when the token has no keys on it, but the user already changed the Admin PIN or the token has been shipped with a different Admin PIN.

Thus, we should let the user input the Admin PIN if 12345678 did not work. I would strongly favor for a solution that still uses 12345678 by default to keep user interaction to a minimum.

**Comment by top-gun007** [comment]
@dschuermann where can I learn openpgp as I really wish to contribute in this project

**Comment by dschuermann** [comment]
Not important for now, closing.
