### ISSUE TITLE
Security Token: Limitations of moving existing key to token

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1845]
Currently `EditKeyFragment` and `ViewKeyAdvSubkeysFragment` allow only 2048 bit RSA keys to be moved to security tokens.

This is a hardcoded limitation which must be changed to work with bigger RSA keys or ECC keys for newer tokens, such as the YubiKey 4 over USB.

**Comment by linux-modder** [comment]
Anyone still actively working on this ( I have a  security key and yubikey 4) and a desire to help get this working.
