### ISSUE TITLE
Use KeyRings.NAME etc instead of KeyRing.splitUserId

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1846]
Since we introduced KeyRings.NAME, KeyRings.EMAIL in https://github.com/open-keychain/open-keychain/pull/1763 we should now use this in more places to replace calls to `KeyRing.splitUserId`.

**Comment by kritkaran94** [comment]
@dschuermann I am ready to work on this. Can you please elaborate as I am new to open-keychain.

**Comment by dschuermann** [comment]
@kritkaran94 Please look into the source code of https://github.com/open-keychain/open-keychain/pull/1763/files . Now, name and email are extracted when writing a key to the database, thus we don't need to use ``KeyRing.splitUserId`` inside other UI classes etc.

**Comment by kritkaran94** [comment]
@dschuermann I will get back to you soon on this.

**Comment by kritkaran94** [comment]
@dschuermann I am referring a branch and starting to make changes. Please review it as I progress.

**Comment by top-gun007** [comment]
is this issue fixed @dschuermann

**Comment by daquexian** [comment]
I could work on this.

**Comment by dschuermann** [comment]
Search for occurrences of ``KeyRing.splitUserId`` and carefully replace them by using the new database columns.

**Comment by daquexian** [comment]
As for UncachedKeyRing, which is irrelevant to database, is it necessary to remove KeyRing.splitUserId? ( for example KeyRing.splitUserId in KeyItem(CanonicalizedPublicKeyRing ring) )
