### ISSUE TITLE
Incorrect pin error message is misleading.

### ISSUE THREAD

**Issue by skorokithakis** [open-keychain/open-keychain#1848]
I'm using OpenKeychain with the Yubikey Neo. I entered my PIN wrong once, but, rather than get "invalid PIN", I got a message saying "security status not satisfied". Having no idea what this means, I tried two more times, thinking the token wasn't close enough to the sensor, which locked my card.

Please change the message to something more informative so people won't retry the same PIN.

**Comment by dschuermann** [comment]
I tried reproducing this with a YubiKey NEO with ykneo-openpgp version 1.0.10, but I get "Incorrect PIN! 2 tries remaining".
Which version of the applet are you using?
Looks like they changed the error codes in 1.0.11, see https://github.com/Yubico/ykneo-openpgp/commit/90c2b91e86fb0e43ee234dd258834e75e3416410
Will investigate this now.

**Comment by dschuermann** [comment]
Tested and fixed in https://github.com/open-keychain/open-keychain/commit/b97971a29c6a2a80d86ff068ca8f4109d8027646
