### ISSUE TITLE
API to programmatically forget rembered passwords

### ISSUE THREAD

**Issue by mgeier63** [open-keychain/open-keychain#1851]
Having an API method or intent that would tell open-keychain to immediately forget all remembered key passwords (in the same way as when the user clicks on the "n remembered passwords" notification)
 would allow implementation of client apps that provide advanced "password forget triggers" like e.g.
- ADB (USB) connected
- Wrong lockscreen PIN input [together with "remember password forever"]
- Based on (loss of) proximity to bluetooth device (smart watch)

Probably an intent would be better than having this in the service API - with an intent users could easily implement such functionality without coding just by using the "tasker" app

**Comment by dschuermann** [comment]
Funnily, we have something like this, but it's not documented. See https://github.com/open-keychain/open-keychain/pull/1683

I am not sure if we need to introduce an OpenKeychain specific Intent for this, but we definitely should document this somewhere :)

**Comment by mgeier63** [comment]
Oh great, that's exactly what I had in mind, just couldn't find it ;-)

I don't think you need to add any other OpenKeychain specific intent, #1683 imho covers it all - it just needs documentation ;-)

**Comment by Valodim** [comment]
all of the mentioned features might as well be part of the app, I think.  They aren't overly complex (except maybe the Bluetooth device one, not sure), and people usually aren't too fond of installing extension apps for small bits of functionality

**Comment by mgeier63** [comment]
>all of the mentioned features might as well be part of the app, 

imho such features should be part of a open-keychain _client_ apps (if not part of a separate, system-wide panic-button app)

Consider this simple example: An email app is currently showing the plain text of an encrypted message (which has just been decrypted by open-keychain) 

When a security relevant event happens, open-keychain should forget the cached passwords, but also should the email app remove the plain text view (and other possibly cached decrypted messages).

Of course this could also be implemented by some kind of callback in the open-keychain API, but I think it'd cleaner to do it in the client. 

Additionally, implementing some of those features would require additional permissions (device-admin, access to radios, ....) for open-keychain which might scare users away...

**Comment by Flowdalic** [comment]
> if not part of a separate, system-wide panic-button app

Like https://guardianproject.info/2016/01/12/panickit-making-your-whole-phone-respond-to-a-panic-button/

**Comment by dschuermann** [comment]
documented here now: https://github.com/open-keychain/open-keychain/wiki/Intents
