### ISSUE TITLE
Error with Yubikey 4 Nano during decryption and signing.

### ISSUE THREAD

**Issue by LucaZulberti** [open-keychain/open-keychain#1852]
Hi all!
When i try to decrypt or sign some text/file, the app alerts me saying that it expects a sign long 128 or 256 bytes, but it was 512.

I encounter this error only when i try to use the smartcard functionality of the Yubikey 4 Nano, if i import the secret subkeys directly to openkeychain, i can decrypt and sign without problems.

The keys are RSA4096.

**Comment by nmikhailov** [comment]
I am going to receive my yubikey 4 nano today, so I will be able to fix& test.

**Comment by LucaZulberti** [comment]
Nice! :-)
