### ISSUE TITLE
Importing keys: listview may show keys although no valid keys are found 

### ISSUE THREAD

**Issue by AlexFJW** [open-keychain/open-keychain#1854]
A little bug I found when helping a user in the mailing list with key importing.
As above, when importing keys, listview may show keys although no valid keys are found.

Also, choosing to import the displayed key crashes the app.
Attached is the a key which results in this situation. 
(newline between armor checksum & ascii armored data missing) ([invalidkey.txt](https://github.com/open-keychain/open-keychain/files/253209/invalidkey.txt))

![resz-0](https://cloud.githubusercontent.com/assets/11351531/15089104/dadd9708-142e-11e6-8895-06f6caccc5a5.png) ![resz-1](https://cloud.githubusercontent.com/assets/11351531/15089105/dae4113c-142e-11e6-9760-3457aabfb74f.png)

The key is detected fine, but the code isn't sure if there's more than 1 key to import. This key is saved. Further parsing of the key file soon gives an error.

The detected key is displayed, but the activity thinks no valid keys are found and did not assign key data to its variables. Accessing this key data when importing results in the crash.

**Comment by dschuermann** [comment]
Great find and thanks for the pr!
