### ISSUE TITLE
Additional unwanted recipient is added on Encrypt&Sign activity

### ISSUE THREAD

**Issue by nmikhailov** [open-keychain/open-keychain#1857]
Additional unwanted recipient is added to 'Encrypt to' field after selecting key for 'Encrypt to' field(from the popup list) and clicking on message text field

**Comment by dschuermann** [comment]
Arg, could have been introduced with https://github.com/open-keychain/open-keychain/pull/1822
Didn't noticed this problem while testing.

@007durgesh219 Can you look into this?

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/commit/f44bd236224e782d85c9764a4b655ae922356b14
