### ISSUE TITLE
Travis crashes for pull requests

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1861]
Known issue at Travis: https://github.com/travis-ci/travis-ci/issues/5669
Waiting for a fix from their side.

**Comment by nmikhailov** [comment]
Is it possible to make a workaround?

**Comment by dschuermann** [comment]
Trying https://github.com/open-keychain/open-keychain/commit/c8a0eb3a083c92b654610f34655fed80312a8ef1 ...

**Comment by dschuermann** [comment]
Let's see if this works in the next pull request...

**Comment by nmikhailov** [comment]
@dschuermann it should be possible to restart PR build: http://stackoverflow.com/questions/17606874/trigger-a-travis-ci-rebuild-without-pushing-a-commit

**Comment by dschuermann** [comment]
Yes, but they need to be rebased on top of current git master to get the travis fix commit :)

**Comment by nmikhailov** [comment]
Right, I missed that. I would suggest to make a fake PR to be done with this issue.

**Comment by nmikhailov** [comment]
Also why #1834 passed?

**Comment by dschuermann** [comment]
Because it's a branch in open-keychain not a fork.

**Comment by dschuermann** [comment]
looks like it works: https://github.com/open-keychain/open-keychain/pull/1862
