### ISSUE TITLE
YubiKey 4 Nano Error.. Another one.

### ISSUE THREAD

**Issue by LucaZulberti** [open-keychain/open-keychain#1863]
Hi again!

I've built the source code to try the fixes made for #1852 issue.
Now when i insert the YubiKey into the OTG cable, the app alerts me with:

"Errore: USB error - failed to connect to device
Take away the Security Token now and touch TRY AGAIN."

I've inserted the correct PIN, i'm sure.

Thanks for your work!

**Comment by nmikhailov** [comment]
Have you tried replugging cable? This is a pretty early error, so it couldn't be introduced in latest patch.

**Comment by LucaZulberti** [comment]
Yes, i tried replugging cable and the token, but the error is still present. I will wait for the next patch. ;-)

**Comment by nmikhailov** [comment]
I don't think we can do anything about this, its the problem with basic android system API call.
You can try restarting the app completely and/or restarting your phone

**Comment by LucaZulberti** [comment]
Ok, but the app available on Google Play can get information from the token when i insert it.

**Comment by nmikhailov** [comment]
There seems to be a conflict between two app version when they are installed alongside and 'ALWAYS use this app for the USB device' was selected.
You can go Settings -> Apps -> Openkeychain (version which works) -> Open by default -> Clear defaults

**Comment by LucaZulberti** [comment]
Oh you're right! It works now! :-D

Thank you!
