### ISSUE TITLE
Problems when trying to restore PGP file in the Tails system.

### ISSUE THREAD

**Issue by cotrimzao** [open-keychain/open-keychain#1864]
I do all the private key backup process the in the application but at the time of import into GnuPG Tails, I insert the backup code and it gives the "bad key". I've tried the password to decrypt also and nothing.

**Comment by dschuermann** [comment]
Have you tried following https://www.openkeychain.org/faq/#how-to-import-an-openkeychain-backup-with-gpg ?

**Comment by cotrimzao** [comment]
Yes. Did not work
