### ISSUE TITLE
openkeychain unable to retrieve key from private keyserver

### ISSUE THREAD

**Issue by sharvadharma** [open-keychain/open-keychain#1872]
hi , 
i m beginner for this encryption decryption 
i used openkeychain and k9 mail 
i create a private sks server by the following link
https://njh.eu/keyserver
and then i add my key server in openkeychain as following
hkp://myserverip:11371
and i uploaded my key to the server through openkeychain 
and i checked the key in server through web interface browser
http://myserverip:11371
server returns the keydetail 
i tried to search the key from the openkeychain
i recieved mesage no keys found

what i need to do for search import keys in open keychain
from my private server

thanks in advance

**Comment by nmikhailov** [comment]
Settings - Key Search - Select OpenPGP keyservers

**Comment by dschuermann** [comment]
@sharvadharma Please stop spamming old issues!
