### ISSUE TITLE
Upload personal key to keyserver issue

### ISSUE THREAD

**Issue by countesscvs** [open-keychain/open-keychain#1873]
I have just installed the 5/16/16 update.

App was located on SD card. After update it was again in internal storage.

Able to upload all installed and confirrmed keys to keyserver.

Unable to upload my own key.  When y key is selected>advanced>share>upload to keyserver, that particular action does not work. The screen flips to a white screen with a grey header and then bounces back to the original screen where all my emails are listed under one key.  This happened both when I noticed it was in the interal storage as well as after moved to the external SD card.

Key has worked fine but I wanted to refresh my key on the server.

I do not understand this issue so I cannot relate further what is happening here.

Can you please look into it?

The issue appears to be only on my phone but all is normal on my tablet.

**Comment by dschuermann** [comment]
Sometimes keyserver are unresponsive, please try again later.

**Comment by countesscvs** [comment]
Resolved issue by backup. Uninstall and reinstall on one device. Update resolved issue on other device. 
Thanks.
