### ISSUE TITLE
Able to backup keys without passphrase check if all masterkeys are stripped

### ISSUE THREAD

**Issue by AlexFJW** [open-keychain/open-keychain#1874]
As above, it is possible to backup keys without a passphrase check if all private keys in the DB have their masterkeys stripped. 

This allows attackers to strip and steal keys of unsuspecting users, including those who use a stripped masterkey configuration. The risk is probably quite small though, given that it takes quite a long time to copy and enter the random backup key.

Users are unlikely to detect the stripped masterkey as day to day app functionality (signing, encryption, decryption) is not affected with the masterkey missing.

**Comment by nmikhailov** [comment]
Good catch :+1:

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/pull/1875
