### ISSUE TITLE
4.0 build fails on fdroid

### ISSUE THREAD

**Issue by vanitasvitae** [open-keychain/open-keychain#1876]
Hi!
I just wanted to update openkeychain from fdroid and noticed, that the current version can not be built.
Take a look at the [log](https://f-droid.org/wiki/page/org.sufficientlysecure.keychain/lastbuild_40000)

**Comment by Valodim** [comment]
This seems to be a memory problem, it can't allocate 4G heap size. I wonder if the build servers are running on 32 bit machines?

**Comment by nmikhailov** [comment]
Why it was working before?

**Comment by dschuermann** [comment]
Will make a fix shortly. It was at 2g and I increased it to try the dexInProcess feature. It didn't help and I forgot to set it back (mainly because on my system there is enough RAM).

**Comment by dschuermann** [comment]
done
