### ISSUE TITLE
Download and read encrypted messages from provider

### ISSUE THREAD

**Issue by rampisi** [open-keychain/open-keychain#1878]
I have a problem with reading emails which are encrypted on the providers server and downloaded into my email client K-9 in my android smartphone. I can´t read them directly and have to decrypt them everytime with open-keychain although the keys are known to open-keychain.

Downloading encrypted emails works fine with Thunderbird and Enigmail. Once my pgp keys are into Enigmail/ Kleopatra I only have to enter my keyphrase once a day. Each email is decrypted automatically then.

How open-keychain handles downloading encrypted messages and reading them although they keys are known is annoying.

**Comment by dschuermann** [comment]
The next time you need to enter your keyphrase into OpenKeychain, select Remember "for one day".

**Comment by rampisi** [comment]
I know this remember "for one day" function. But the message is still not readable automatically even after selecting remember "for one day". The email delivers two attachments. One message is the real email I have to open extra to be encrypted with open-keychain. One attachement is "msg.asc" and the other is "noname.". I have to open the message "noname." for decryption with open-keychain to be able to read it. Not very handy.

**Comment by Valodim** [comment]
this is not a bug in openkeychain, it's missing pgp/mime support in k9. we are [working on it](https://www.openkeychain.org/k-9).
