### ISSUE TITLE
Randomness in tests

### ISSUE THREAD

**Issue by nmikhailov** [open-keychain/open-keychain#1881]
Travis build failed.
Probably due non determenism of https://github.com/open-keychain/open-keychain/blob/ce5e5f36c56fe14cb4a90a912eece07e4cb92285/OpenKeychain/src/test/java/org/sufficientlysecure/keychain/util/TestingUtils.java#L30

Using random(especially without fixed seed) in unit tests is generally a bad practice.

**Comment by Valodim** [comment]
A failure due to `genPassphrase` would mean that there are passphrases which break our routines. I agree though that even if tests fail when they "detect" corner cases like this due to randomness, it's very difficult to find the actual cause. We might want to get rid of the randomness in tests..

**Comment by runnerway** [comment]
Today i got this on a Travis build. I don't know if it's related.

```
org.sufficientlysecure.keychain.pgp.UncachedKeyringTest > testArmorIdentity FAILED
    java.lang.RuntimeException
        Caused by: java.lang.NegativeArraySizeException at UncachedKeyringTest.java:86


org.sufficientlysecure.keychain.pgp.UncachedKeyringTest > testDecodeEncodeMulti FAILED
    java.lang.Exception
        Caused by: java.lang.NullPointerException at UncachedKeyringTest.java:130
```
