### ISSUE TITLE
Saving attachments results in empty files

### ISSUE THREAD

**Issue by vanitasvitae** [open-keychain/open-keychain#1882]
Hi!
I sent myself a ssh_key from my laptop via enigmail.
When I decrypt the mail on my phone, I can view the attachments and even copy its content to the clipboard. But when I long click the file and save it to storage, the file is empty.

Here is a log:

> 05-27 10:33:16.881  3601  3619 D Documents: Update found 7 roots in 1616ms
> 05-27 10:33:16.882  1852  2647 I ActivityManager: Killing 30896:com.android.music/u0a39 (adj 15): empty #17
> 05-27 10:33:16.914  3601  3645 D Documents: Update found 7 roots in 731ms
> 05-27 10:33:16.982  3601  3666 D Documents: userMode=0, userSortOrder=0 --> mode=1, sortOrder=1
> 05-27 10:33:16.991  3601  3666 W Documents: Failed to query
> 05-27 10:33:16.991  3601  3666 W Documents: android.os.OperationCanceledException: The operation has been canceled.
> 05-27 10:33:16.991  3601  3666 W Documents:     at android.os.CancellationSignal.throwIfCanceled(CancellationSignal.java:54)
> 05-27 10:33:16.991  3601  3666 W Documents:     at android.content.ContentProviderClient.query(ContentProviderClient.java:132)
> 05-27 10:33:16.991  3601  3666 W Documents:     at com.android.documentsui.DirectoryLoader.loadInBackground(DirectoryLoader.java:167)
> 05-27 10:33:16.991  3601  3666 W Documents:     at com.android.documentsui.DirectoryLoader.loadInBackground(DirectoryLoader.java:94)
> 05-27 10:33:16.991  3601  3666 W Documents:     at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
> 05-27 10:33:16.991  3601  3666 W Documents:     at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
> 05-27 10:33:16.991  3601  3666 W Documents:     at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:66)
> 05-27 10:33:16.991  3601  3666 W Documents:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
> 05-27 10:33:16.991  3601  3666 W Documents:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
> 05-27 10:33:16.991  3601  3666 W Documents:     at com.android.documentsui.ProviderExecutor.run(ProviderExecutor.java:107)
> 05-27 10:33:16.992  3601  3666 D Documents: userMode=0, userSortOrder=0 --> mode=1, sortOrder=1
> 05-27 10:33:18.420  3601  3666 D Documents: userMode=0, userSortOrder=0 --> mode=1, sortOrder=1
> 05-27 10:33:18.427  3601  3601 D Documents: onFinished() [content://com.android.externalstorage.documents/document/primary%3Akey.txt]
> 05-27 10:33:18.586  1852  1891 I ActivityManager: Displayed org.sufficientlysecure.keychain/.ui.DecryptActivity: +143ms

Also the key gets the suffix .txt, which could be missleading, since the file originally had no suffix.

**Comment by dschuermann** [comment]
what Android version and rom are you using?

**Comment by vanitasvitae** [comment]
Latest CopperheadOS (AOSP 6.0.1)

**Comment by dschuermann** [comment]
Please try out the newest K-9 Mail alpha.
