### ISSUE TITLE
Question: Open Keychain adaptation for laptop/desktop?

### ISSUE THREAD

**Issue by countesscvs** [open-keychain/open-keychain#1888]
Although not actively able to contribute to development of O.K. app, I am curious as to whether your code can be adapted for laptop/ desktop systems running Windows 10.

Most PgP programs available are gargantuanly miserable to implement for most people.

I would use it if there were a program which looked exactly like the Android app you are working on but for mail programs on Windows 10. Something which looks and works exactly the same?
Or just as great, an extension for the browser, (I use Yandex, a Chromium build) which works just like the Android App? 

These are things I look forward to in order to simplify Pgp for average users.

Thanks for listening.

**Comment by dschuermann** [comment]
OpenKeychain *could* land in Chrome (see https://github.com/open-keychain/open-keychain/issues/1704), but we will not create a full Win 10 application.

**Comment by countesscvs** [comment]
I specifically use Yandex Browser Beta. I greatly appreciate their in Browser security system which is primary and included in Beta. I would like to see it implemented there for their Yandex Mail platform.
