### ISSUE TITLE
Issue sending e-mail with more than one key per e-mail address

### ISSUE THREAD

**Issue by Schwefelholz** [open-keychain/open-keychain#1889]
Hello,

@dschuermann asked me to raise following issue:

I'm facing an issue with OpenKeychain and K9 Mail. I've created a new secret key for my e-mail address to mitigate a key length issue with my original key.
Of course, the new and old key need to be present in my keyring (see screenshot 1) to support
1. encryption and signing of new mails and
2. decrypting old mails.

Now, with the two keys present, it seems I cannot send an e-mail to myself (screenshot 2 and 3). OpenKeychain comes up with a selection screen, telling "there are more than one key existing for this e-mail address". Unselecting either one of the keys and pressing "OKAY" raises the same dialogue again.

I hope I#ve been clear enough. If you need any further information, I'll be glad to help.

Thanks for your support,
Thomas

![20160613-1](https://cloud.githubusercontent.com/assets/6893444/16010634/62b0b654-3182-11e6-8625-13504da4aeb1.png)
![20160613-2](https://cloud.githubusercontent.com/assets/6893444/16010635/62b1fca8-3182-11e6-8aa5-b003e3e6df49.png)
![20160613-3](https://cloud.githubusercontent.com/assets/6893444/16010633/62b05542-3182-11e6-9737-918a743c660e.png)

**Comment by alanthehat** [comment]
#1866 sounds like the same problem

**Comment by Valodim** [comment]
It is. Closing that one because we have nifty screenshots here.

This is a known problem, it's just not trivial to fix. Working on it :+1:

**Comment by dschuermann** [comment]
Fixed in 4.2
