### ISSUE TITLE
Problem while building on Mac OS (Related to #558)

### ISSUE THREAD

**Issue by kritkaran94** [open-keychain/open-keychain#1892]
@dschuermann The build failed for me too on Mac OS X. Any other alternatives ?

**Comment by kritkaran94** [comment]
Copy of #558

**Comment by dschuermann** [comment]
What steps have you taken to fix the build under Mac OS X?

**Comment by kritkaran94** [comment]
Din't fix that yet. There was already a similar issue and you had replied
to that earlier. Thus, I closed it and starting working on the other issue.






Krit Karan Singh
Indian Institute Of Information Technology, Chittoor
m: +91-7032306986
e: kritkaran.b13@iiits.in

**Comment by kritkaran94** [comment]
@dschuermann One thing is for sure exporting JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8" doesn't help much 
![screen shot 2016-06-22 at 1 29 04 pm](https://cloud.githubusercontent.com/assets/10063868/16258876/737c1cb0-387d-11e6-8786-38524b3b0113.png)

**Comment by dschuermann** [comment]
You need to install Build Tools 21.1.2

**Comment by kritkaran94** [comment]
@dschuermann Thanks for that. However, it din't completely solve the problem. Please, also review my PR so that I can proceed further. (#1893)
![1](https://cloud.githubusercontent.com/assets/10063868/16262049/b1c0ead8-388b-11e6-930c-3a91d91ff08e.png)
![2](https://cloud.githubusercontent.com/assets/10063868/16262048/b1bfe390-388b-11e6-97ec-bbc4a05faab7.png)

**Comment by dschuermann** [comment]
run "gradlew assembleFdroidDebug"

**Comment by Valodim** [comment]
Both of these are very clear error messages. If you ask on our issue tracker every time something doesn't work as expected you are wasting our time and your own while you wait for a response, please try solving problems like this on your own first.

**Comment by kritkaran94** [comment]
@Valodim, I apologize if you felt that way. I am a beginner in android and I am quite eager to get the build running quickly and @dschuermann has also been very supportive so far. I am not pinging anyone instantly. I just felt that may be someone in this community if had the similar issue could guide me. @dschuermann I proceeded in the similar way and got the following error.
![screen shot 2016-06-22 at 6 29 23 pm](https://cloud.githubusercontent.com/assets/10063868/16267442/5e9cc6da-38a7-11e6-8a7c-b20505c91350.png)

**Comment by Valodim** [comment]
Have you tried the suggestions provided by the error message itself, to get more info on the error?

Sorry for being a little rude here but this is an issue tracker, not a help desk.

**Comment by kritkaran94** [comment]
@Valodim I tried both info and debug for that matter. Still the same. Any suggestions from your side?
