### ISSUE TITLE
Security Token: Support non-numeric PIN

### ISSUE THREAD

**Issue by paalsteek** [open-keychain/open-keychain#1896]
I have a OpenPGP-Smartcard in a USB-Adapter and tried to use it with the new USB-Support of OpenKeyChain. Unfortunately I'm not able to input my PIN as it contains non-numeric ASCII-Characters and the input field only allows me to enter numbers.

**Comment by nmikhailov** [comment]
It could be configured at Menu-Settings-Passwords and PINs-use number keypad for PINs.

This is not the first time when somebody is confused about this.
I think we should do something about it. What do you think @dschuermann ?

**Comment by paalsteek** [comment]
In that case: sorry for the noise.

**Comment by dschuermann** [comment]
@nmikhailov Hmm, not sure how to solve this UI problem. I have still the opinion that it is unusual to use something different than 6 digit numbers. There is no need to use full passphrases for smartcards due to a different threat model.

*Maybe* we could put a very small button inside the PIN dialog with an "Aa" icon on it that switches the keyboard ad hoc to a alphabetic one. What do you think @nmikhailov @Valodim ?

**Comment by nmikhailov** [comment]
Hard to say. It seems we can't even reliably launch alphabetic keyboard in numeric mode by default.
I guess your proposal is good enough, can't think of anything else(considering we want to encourage numeric pins)

**Comment by dschuermann** [comment]
It's very difficult to know how many people actually have this problem vs. how many people use digits and thus don't write issue reports ;)

One of the design criteria in OpenKeychain is to have secure but usable defaults that we want to encourage. As security tokens with alphanumeric passphrases are never generated by OpenKeychain itself, it's a special use case. Again there is a different threat model here in comparison to passphrases, maybe I should write it down.

**Comment by nmikhailov** [comment]
And its difficult to know how many people have this problem, get frustrated and abandon OKC(probably none, but still).

I perfectly understand your point of good defaults. 
But I think that user desires are more important. I don't like that some people are uncomfortable with our defaults and can't find a way to work around them.

I do think that good defaults must be encouraged, but it should always be obvious how to change them.
Things to note:
- It is not obvious how to change keylength on key creation. From google play store comments:

> Key size version 3.9.5; installed on tablet (android 5)- when creating a key; doesn't give option to chose the key size 1028 to 4096 bits!!!!! Why? I hope it's not because the default key size that is forced by the gov. is only 1028 bits (crackable).

- we don't allow simple pins like 123456 for security tokens. I think we should allow everything and only display warning if we don't like them.

- we should leave an option to manually set admin pin

I think we should learn from common user mistakes and adapt our UI.

**Comment by dschuermann** [comment]
I agree with some of your points but not all of them.
Can you open new issues for each issue? I am willing to discuss these and improve.

I added a button to change between keyboard layouts in https://github.com/open-keychain/open-keychain/commit/0ad0023fac0a2948b2245bdd6c0f9025fb0d0c0c and removed the preference.
