### ISSUE TITLE
Support EdDSA keys and signatures

### ISSUE THREAD

**Issue by gwollman** [open-keychain/open-keychain#1897]
GnuPG 2.1.8 et seq. now support EdDSA (ed25519) keys and signatures.  There's an Internet-Draft for this, but alas no full RFC yet (https://datatracker.ietf.org/doc/draft-koch-eddsa-for-openpgp/).  It would be really nice if OpenKeychain supported this (particularly since some people have already started using these keys).  (It appears that the I-D for OpenPGP use is being held pending approval of the underlying specification of EdDSA, which is under review.)

**Comment by Valodim** [comment]
Duplicate of #1533. This is not a problem of awareness but of implementation effort.
