### ISSUE TITLE
K9 mail: Cannot select correct key

### ISSUE THREAD

**Issue by rugk** [open-keychain/open-keychain#1898]
When I e.g. have two keys for a mail address and I try to send a mail with K9 mail OpenKeyChain asks me to select one address of the two. So if I select one or two addresses and press OK(= tap on the send button) the screen goes away and appears again (as if the result was not recognized/accepted). I cannot end this loop without deleting one key out of OpenKeyChain, so that this message does not appear anymore.

**Comment by adamlsd** [comment]
I also am seeing this.  After some poking around, I think the issue may lie in src/main/java/org/sufficientlysecure/keychain/ui/SelectPublicKeyFragment.java

It seems like there may be a situation where it keeps rechecking the user-supplied results as if they were not user supplied.

I will do some more digging a bit later this week.  Hopefully this gives one of the project developers a lead to follow.

**Comment by adamlsd** [comment]
A bit more searching leads me here: src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java

`returnKeyIdsFromEmails` creates the key-selection dialogue when it sees duplicates.

There is a Service API call which also invokes `returnKeyIdsFromEmails`.  Something may be invoking that call, after the user key selection happens?

**Comment by rugk** [comment]
Any news regarding this bug?

**Comment by rugk** [comment]
Note that the affected key is this one: https://github.com/open-keychain/open-keychain/issues/1699

**Comment by tomsedi** [comment]
Same here

**Comment by dschuermann** [comment]
Fixed in 4.2
