### ISSUE TITLE
K9 mail complains that the signing subkey can not be found when sending mail

### ISSUE THREAD

**Issue by hirschnase** [open-keychain/open-keychain#1899]
I have a PGP key with several identities (uid). When I try to send email with k9 with a sender-address of one of these identities, K9 mail displays a message that the signing subkey can not be found. When I send mail with the sender-address of the primary identity it works. Not sure what the problem is here. I use the same key w/ OS X Mail.app and it works fine with all my mail account there.

**Comment by dschuermann** [comment]
Please use newest K-9 Mail and try to re-produce. If it still fails, please open a bug report at the K-9 Mail project.
