### ISSUE TITLE
Turn off header detection in decrypted text

### ISSUE THREAD

**Issue by piater** [open-keychain/open-keychain#1900]
Several issues have been filed about dropped lines from decrypted text, e.g. #1592. In general, OpenKeychain cannot know how to post-process decrypted text. Therefore, it would be nice to have the option of turning this feature off entirely, such that a decrypted text is displayed without post-processing.

**Comment by dschuermann** [comment]
Can you provide an actual example where the detection of mine/plaintext failed? In general we try to avoid the introduction of too many additional preferences.

**Comment by piater** [comment]
Most of my files are of the following structure:

    User: someusername
    Pass: somepassword

    more text

In all these cases, all leading lines up to and including the first blank line are dropped. The same holds for variants such as

    Bla Bla Bank
    Geschäftsstelle: GS Here / There.
    Kunden-Nummer: 1234567

    Kto.-Nr.: 987654321`

Again, the first 4 lines (up to and including the first blank line) are dropped.
However, if the file starts differently (without colon-terminated "fields"?), such as

    2016-07-24

    Hello World

then the entire text is displayed correctly, including the first line.
My point is, OpenKeychain cannot know what text to strip. One day I may want to store a message in mbox format on my SD card, encrypted, the interesting content being its raw text with headers, MIME wrappers and all. What a user is interested in cannot be inferred from the contents of a file; this is what metadata are for. A file is a file is a file. This is why Android (Amaze) offers me the choice of how to handle a file I select.
Actually, perhaps this is the right level of metadata: Instead of the configuration option I suggested earlier, it is perhaps better for OpenKeychain to register two _Open As_ options, one that applies content-based heuristics and the other without.

**Comment by Valodim** [comment]
Not a fan. Users don't know what MIME is, and neither should they. We just need to make our heuristics better.

At the moment, any header type like will cause the data to be interpreted as MIME. However, there are cases where this is wrong such as yours. But: it's quite reliable that actual MIME content has a content-type header. That should reduce our false positive ratio while keeping false negatives low.

Ideally, there would be a 'm' content flag in the literal data packet to indicate MIME content. Alas, this is only now discussed in the openpgp wg, so it will be a while.

**Comment by Valodim** [comment]
I expect this change to be fairly non-controversial (except in regards to whether it really fully solves this problem), so I implemented it and added a test case in dab4edb24e0e2219e5a363bb26642db5e230c0d0

**Comment by piater** [comment]
> The "only when run from a file manager" is a heuristic as well, because we can only guess when that happens.

I see.

> so I implemented it

Wow, you're quick :-) Will there be an .apk for me to download, or when can I expect an update on F-Droid (preferred)?

**Comment by Valodim** [comment]
We don't have much else on our dev branch right now, so might as well release it. @dschuermann ?

**Comment by dschuermann** [comment]
released in 4.1

**Comment by piater** [comment]
Thanks a bunch! Solves my use case.
