### ISSUE TITLE
`Bad data` importing gpg private keys

### ISSUE THREAD

**Issue by kehugter** [open-keychain/open-keychain#1901]
I'm trying to import private keys freshly created and exported with gpg 2.1.14. No expiry date has been changed (#996, #1003, #1026). I'm running OpenKeychain 4.0.3 from F-Droid in CyanogenMod 13.0 (unofficial).

The key only contains the signing subkey meant for the phone. The master key and all other subkeys are "present" as dummys.

The subkey was exported with the `--export-secret-subkey <subkey_id>!` command and later by removing the unwanted keygrips before the export (starting from the full key in both cases). The result was the same in both cases: the import fails with a `Bad data` warning.

Probably related: #1793. No crash in my case though. `gpg-agent` was restarted prior to the export (#1529), `gpg-agent --version` confirms that version 2.1.14 is running.

Can send the output of `gpg2 --list-packets` if needed.

**Comment by Valodim** [comment]
thanks for your report!

output of `gpg2 --list-packets` would be great. can you try to create a new key, see if you can reproduce the problem and send us the problematic key? that would make things a lot easier to debug.

**Comment by kehugter** [comment]
Sorry, I made a new key to reproduce but couldn't. I must have been working with a faulty re-imported key last time (I use a fresh Tails instance). Now I tried with the previous one again and it worked too.
