### ISSUE TITLE
Keyboard lag in password input widget

### ISSUE THREAD

**Issue by wilderjds** [open-keychain/open-keychain#1904]
With the latest upgrade it is almost impossible to type in the password in the input widget as there is a long (as in 5 seconds) lag before each character is accepted. This happens with either Swiftkey Keyboard or AOSP keyboard. 
This is so bad and so obvious that I am sure it cannot be reproduced by many others. I'll be happy to provide more info if needed
Edit: I downgraded to 4.0.1 (which I thought to recall it worked fine) and in the process cleared the app db; it still lags heavily. Even the cancel or unlock buttons are unresponsive for several seconds.
I will try to downgrade to <4.0
Edit²: I downgraded to 3.9.5: still the issue is present. If I blind-type on the unresponsive keyboard, the entered characters eventually show up (all at the same time after the long lag). The whole UI is unresponsive (home and back keys don't work either).  Running top shows just openkeychain absorbing ~50% CPU and apparently nothing else out of the ordinary.  
[trace.zip](https://github.com/open-keychain/open-keychain/files/402457/trace.zip)

**Comment by Valodim** [comment]
This was solved by a discussion on irc: The issue was caused by the [Flat Style Colored Bars XPosed module]( http://repo.xposed.info/module/com.bocharov.xposed.fscb).
