### ISSUE TITLE
Use secure_delete for SQLite

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1905]
A deleted secret key is currently not overwritten by zeros, but this behavior could maybe reached by configuring sqlite correctly.

see recently merged patches in AOSP:
https://android-review.googlesource.com/#/c/210080/
https://android-review.googlesource.com/#/c/209123/

Looks like these options can also be set with a pragma statement (https://www.sqlite.org/pragma.html#pragma_secure_delete) so maybe we could adopt these.

**Comment by harningt** [comment]
Since pragma's are conveniently not sanity-checked, if the user's Android version doesn't support secure_delete, it will just ignore it. :)

**Comment by dschuermann** [comment]
This makes problems: https://github.com/open-keychain/open-keychain/pull/1947 and is not really worth the effort -> closing
