### ISSUE TITLE
import fails with eddsa authentication packet

### ISSUE THREAD

**Issue by J-J-Chiarella** [open-keychain/open-keychain#1911]
Just like #1279

STEPS TO REPRODUCE

Attempt to add secret key (encrypted and in asci--armored format) with RSA (Sign and Certify, 2048 bits) and RSA (Encryption, 2048 bits) and Curve25519 (Authentication, 256 bits)

Tried with both file and with copy-pasting raw text.

EXPECTED RESULTS

Import succeeds.

ACTUAL RESULTS

Invalid key data

While the merge by @adithyaphilip on spongycastle (Pull#5 github.com/open-keychain/spongycastle/pull/5, incorporated into Openkeychain @Valodim) lets Openkeychain merely ignore the as yet unrecognized EdDSA keys for signing, the patch may not apply to importing private keys and/or may not apply to keys flagged for authentication and/or may get tripped up by encrypted keys.

Key was created in GnuPG 2.1.11

Few distributions have GnuPG 2.1.14+ so I can't easily test exporting an unencrypted key, then saving it onto my phone via USB and then importing into OpenKeychain.

Attempted import on arm64 running Android 5.1 and OpenKeychain 4.1.

**Comment by dschuermann** [comment]
Should be supported in 4.5
