### ISSUE TITLE
Support for OpenPGP Smartcard in USB reader

### ISSUE THREAD

**Issue by J0s3f** [open-keychain/open-keychain#1912]
I don't know how much work it would be to add this, but I assume now that OpenKeychain supports tokens over USB it shouldn't be too much work.
I have a [OpenPGP smartcard](https://g10code.com/p-card.html) in an [Gemalto K30](http://www.cryptoshop.com/gemalto-idbridge-k30-usb-shell-token-v2.html) reader. It seems to not work with OpenKeychain currently. It would be great, if it could work with OpenKeychain. I assume a lot of people have such cards, the [FSFE also gives them out to supporters](https://fsfe.org/fellowship/card.en.html).

From what I understand, the protocol is exactly the same as with the yubikey, so probably only the detection/support for additional smartcard readers is missing?

**Comment by nmikhailov** [comment]
Yes, probably it would if reader is PC/SC CCID compliant. Smartcard part will definetly work. 
It wont work for you now since we whitlist supported devices.
To test it you would need to add your reader to filter https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/res/xml/usb_device_filter.xml and compile.
For now you can try this: https://drive.google.com/file/d/0B-JY8b-Yg4sSNkdFLVlGeVRvZzA/view?usp=sharing
Insert smartcard into reader before connecting it to phone and never eject it from the reader.

Actually I have external reader(even 2), but unfortunatly it doesn't work with my phone(android crashes and reboots).

**Comment by J0s3f** [comment]
Thanks for the fast reply. 
If I connect my reader after installing that version, Android asks me if I want to open it with OpenKeychain. I accept but nothing happens. 
If I connect it while on the security token screen, after some time the error "Couldn't power up security token" appears. 
I tried it with a OTG cable with external power too, so I doubt it's a power issue. 

![screenshot_2016-08-15-21-07-07](https://cloud.githubusercontent.com/assets/604089/17676177/92f1402c-632d-11e6-9689-2051eecd2dae.png)

**Comment by nmikhailov** [comment]
Is Smartcard inserted?

**Comment by J0s3f** [comment]
Yes, this is a usb key sized reader for sim card sized cards. I never remove the card.

**Comment by nmikhailov** [comment]
Well it seems it didn't worked straight away.
Try [this.](https://drive.google.com/file/d/0B-JY8b-Yg4sSenJaMllBcC1sRzA/view?usp=sharing)
And paste `adb logcat` logs somewhere.

And also try to get logs with desktop gpg:
create `~/.gnupg/scdaemon.conf` with:
```
debug 2048
debug-ccid-driver
log-file /tmp/scdaemon.log
```
then `killall gpg-agent` and `gpg --card-status`, then paste /tmp/scdaemon.log somewhere. Also delete/rollback your `~/.gnupg/scdaemon.conf`

**Comment by J0s3f** [comment]
Ok, thanks for your work :)

Here is the log filtered for CCID-RECEIVE from my tablet (Android 5.0.1 Lenovo Tab S8-50):
[2016-08-16-20-ccid.txt](https://github.com/open-keychain/open-keychain/files/421033/2016-08-16-20-ccid.txt)


If you need the full log just tell me, I will send it to you. I just don't want to post it publicly. No idea what personal data is in there.

Here is the log from gpg on my PC. It's 2.0.30 on Windows 10.
[scdaemon.txt](https://github.com/open-keychain/open-keychain/files/421035/scdaemon.txt)


If something is missing I can do the same on another Android device or on another PC (Linux, if hat helps)

**Comment by nmikhailov** [comment]
scdaemon's log is not correct, it looks like `debug-ccid-driver` was not enabled. Are you sure you have configured scdeamon.log correctly and have restarted scdaemon/gpg-agent?

**Comment by nmikhailov** [comment]
@J0s3f Also [check this,](https://drive.google.com/file/d/0B-JY8b-Yg4sSdUJNMERlakNRbVU/view?usp=sharing) it might actually work this time.
Don't forget to copy logs, note that they will be tagged 'Keychain D'.

**Comment by J0s3f** [comment]
I just created a log on a linux machine. http://termbin.com/fs3m I hope that helps.

Will try the new version later today!

Thank you!

**Comment by J0s3f** [comment]
I tried the new version. It has a different error: "status 1 error code: fe" 

[2016-08-17-21-56-57-keychain-d.txt](https://github.com/open-keychain/open-keychain/files/423524/2016-08-17-21-56-57-keychain-d.txt)

**Comment by nmikhailov** [comment]
Ok I see whats wrong. Expect next test build at the end of the next week.

**Comment by J0s3f** [comment]
Any update on that?

**Comment by nmikhailov** [comment]
@J0s3f Very sorry I was busy. I will try to work on this this week.

**Comment by ensastiga** [comment]
This last version gets the card reader in active mode but then an error happens:
 
[logcat.txt](https://github.com/open-keychain/open-keychain/files/478994/logcat.txt)
Card reader: [USB Gemplus PC Twin CT30](https://pcsclite.alioth.debian.org/ccid/supported.html#0x08E60x3437) 
Phone: Motorola XT1045 w/locked bootloader (OS - v5.1 - Factory image)

![screenshot_2016-09-18-16-52-37](https://cloud.githubusercontent.com/assets/2986080/18619190/3e4ba132-7dc4-11e6-91de-185ba4bf4d58.png)

**Comment by thomasjfox** [comment]
@nmikhailov 
> Actually I have external reader(even 2), but unfortunately it doesn't work with my phone(android crashes and reboots).

I had those reboot crashes with some versions of Cyanogenmod when just plugging in a USB-OTG adapter.
It used to work before. Recently I've retried with a current LineageOS build for my phone and now all is fine, external USB keyboard or the Yubikey are detected. USB sticks work, too.

-> It might be worth to try again with a recent Android build.

Today I've plugged in a "ReinerSCT cyperJack Go" card reader that draws 200mA from the USB port, at least according to the ratings on the back of it. It booted up just fine, I've played a little with the menus.
So it might be possible to get this working and the "cyberJack Go" is one of the smallest smartcard readers with a pinpad.

**Comment by IceHamster** [comment]
Is there an update to this issue?
I get the same error on Gemalto IDBridge K30.

**Comment by girst** [comment]
I'd like to have this feature as well. I'm using an SCR3500 from FLOSS-Shop.de (if that matters).

**Comment by Valodim** [comment]
Hm. So, we only whitelist devices usb at this point that we tested ourselves, and thus have reason to believe that they work. So far we haven't tested any usb smart card reader, as far as I'm aware.

There is no reason I can think of why any usb smart card reader shouldn't "just work". But also I'm reluctant to just accept all of them and hope for the best. Hmm.

@dschuermann thoughts?

**Comment by nmikhailov** [comment]
There is no code to handle IC inserting/ejecting, probably would work if IC is in when usb connected, but who knows.
I have tried to test this, but connecting my reader to Nexus 5X results in phone reboot.

**Comment by girst** [comment]
I'd like to help debug this problem -- is there anything you would need? (maybe a version with my device whitelisted for testing?)

**Comment by dschuermann** [comment]
No reboots for me on Nexus 6P, Android 8, OpenKeychain git master.

I have two smartcard readers: 
* SCM Microsystems Inc. SCR 3310 (Vendor ID: 1254, Product ID: 20758)
* Gemalto Prox Dual USB PC Link Reader (Vendor ID: 2278, Product ID: 21763)

If I attach them with the OpenPGP smartcard already inserted/layed on top the NFC reader and disable our whitelisting they work perfectly.

I get differnt kind of errors based on the reader, whether the smartcard is not an OpenPGP card or it is not inserted.

Quite funny having an USB-OTG cable to connect a smartphone with an external NFC reader and put a smartcard on it ;)

@Valodim @nmikhailov I am also reluctant to just accept all. The user experience is also sub-par as we do not handle insert. Also, my two readers have been carefully chosen to work with Linux. I am not sure about other off-the-shelf smartcard readers.
One idea would be to put in an experimental switch to disable whitelist checks, so people can try out this stuff. On the long term we could implement better support and maintain a whitelist.

**Comment by nmikhailov** [comment]
Great to see confirmation that it works. I support adding an option to disable whitelisting. Or if it is impossible to disable whitelisting completly and show warnings for unkown readers.

Regarding other readers which are non-PCSC/CCID compatible they just won't work since they usually have different protocols and require custom drivers. I don't think we can do much about them.

**Comment by dschuermann** [comment]
When buying I followed this list: https://pcsclite.alioth.debian.org/ccid/supported.html
As one can see there are a lot of problems, even with "supported" ones, such as no support for extended APDU.

**Comment by Valodim** [comment]
> Or if it is impossible to disable whitelisting completly and show warnings for unkown readers.

We kind of do this: In the manifest file we have all ccid readers whitelisted, and handle them in code then, to be able to give more helpful warning

**Comment by girst** [comment]
An experimental switch to disable whitelisting seems like a very acceptable idea.

@Valodim: I did not get any warning when plugging in my reader (it is on the shouldwork list of pcsclite and I'm using it on my laptop just fine)

**Comment by dschuermann** [comment]
@girst Please first open OpenKeychain and then plugin in your reader whilte the card is already inserted. You should get a small notification on the bottom of the OpenKeychain screen that the device is not supported.

**Comment by Valodim** [comment]
That might not have been released

**Comment by girst** [comment]
That's whtat I tried, but no notification either on the main screen of Openkeychain, nor on the add-a-security-token page. 

running (as superuser) `while sleep 1; do dmesg -c; done` shows that the insertion of the reader gets detected by the phone.

**Comment by dschuermann** [comment]
@Valodim is right. In the current stable version the reader is not whitelisted inside the XML.

**Comment by girst** [comment]
could anyone send me a whitelisted version for testing please? I'll report back if i was successful; we could build a list of compatible readers this way.

**Comment by dschuermann** [comment]
We just released 4.8 with a switch in experimental settings to disable the whitelist.

**Comment by Valodim** [comment]
For the record, my Nexus 5X also just reboots when I insert a reader in it. Seems to be a problem of that model. Other things like the yubikey 4C or a nitrokey do work as expected, though.

**Comment by girst** [comment]
After wondering why Fdroid hasn't supplied the update (spoiler: their build server is broken), I downloaded the google play version, but I can't find the "disable the whitelist" switch in the experimental settings.

**Comment by Valodim** [comment]
The option is called "Allow untested USB Devices". if that doesn't exist, you're probably not on 4.8? You can make sure in Help -> About

**Comment by girst** [comment]
whoops, sorry. yalpstore handed me an old version :|

with 4.8 I can see (and flip) the setting, but when I plug the reader (with the card already inserted) into my phone, I get this error message:

>USB-CCID error! CcidDataBlock{dataLength=0, slot=0, seq=1, status=64, error=-2, chainParameter=0, data=[]}

**Comment by Valodim** [comment]
This is an `ICC_MUTE` error, the possible cause is listed as "The applications of the USB-ICC did not respond or the ATR could not be sent by the USB-ICC." in the standard, i.e. the CCID timed out while talking to the ICC.

See [usb icc standard](http://www.usb.org/developers/docs/devclass_docs/DWG_Smart-Card_USB-ICC_ICCD_rev10.pdf), page 24

There is not much we can change to avoid this error. If it is really caused by some kind of timeout, it might help to simply retry... I assume you tried this a couple of times and it happened reproducibly?

**Comment by girst** [comment]
> I assume you tried this a couple of times and it happened reproducibly?

yes; the error happens <1sec after plugging the reader in. (I've also ticked the checkbox to *always open openkeychain when inserting this device*, but the error persists) :/

**Comment by Valodim** [comment]
There should be stuff in your logs, something like "CCID: attempting to power on with voltage AUTO" around this error?

**Comment by girst** [comment]
where should the logs be? I've got a `.com.sufficientlysecure.keychain/logs/` directory in the sdcard, but nothing gets written there (I deleted it, suspecting a permission error, but it hasn't reappeared)

**Comment by Valodim** [comment]
It's in the android system logs, which can be obtained using adb logcat via usb. That's not difficult to do, but also not trivial - tons of tutorials out there that say how. What might also help is a pcsc log that comes up when you plug in the reader with a card inserted. I wonder if that does some kind of retry as well before it works.

I'd normally be inclined to say "it probably won't work", but the reader is a similar model to the one @dschuermann has and that works for him (SCR3500 vs SCR3310).

**Comment by Valodim** [comment]
Actually, this particular issue is closed at this point - with the whitelisting our support for ccid-readers is now working as we imagined. That said, I'd be happy to discuss the SCR3500 in particular, let's move back to your earlier issue #2219 to talk about that specifically.

**Comment by alphazo** [comment]
What is the status lately on CCID readers on OpenKeychain? 

I have seen mixed results with my CCID readers. Only one out of three works even when enabling untested readers in the experimental menu.

The only one that works:
- OmniKey AG CardMan 3121 CCID Smart Card Reader (ID 076b:a021)

The readers that don't work (but work on PC with pcscd).
- SCM Microsystems, Inc. SCR331 SmartCard Reader (ID 04e6:e001)
- Alcey IR05-FC Multi-function reader (ID 0bda:0169 Realtek Semiconductor Corp. Mass Storage Device)

For them I'm getting the following error either when plugging them in the first time or when trying to decrypt a file after entering the PIN code. In both cases card was always inserted prior to connect the reader. 

```
Erreur: USB-CCD error!
CccidDataBlock{dataLength=0, slot=0, seq=2, status=64, error=0, chainParameter=0, data=[]}

Remove the security token now and try again.
```

**Comment by dschuermann** [comment]
Supporting USB readers is not very high on our priority list. But we would accept pull requests that improve the current situation. Keep in mind that currently no USB readers are supported officially. You always need to enable the experimental option.

**Comment by Valodim** [comment]
the status=64 bit means "command not supported", according to spec. That's very unlikely since it's the general "transfer stuff" command, and just from the error numbers I can imagine it might happen from some internal error as well. It's the kind of error where wiggling with some parameters might just fix it, but that doesn't really work remotely.

**Comment by feklee** [comment]
Tried with three card readers, all with PIN pad:

  * [REINER SCT cyberJack][3]: not recognized by OpenKeychain (no surprise as it requires dedicated Linux drivers)
  
  * [Cherry ST-2000UCZ-R][4]: not recognized, although it normally works out of the box on Linux

  * [SCM SPR332 v2][1]:

      + Recognized!

      + Despite the lower model number, this reader is the successor of the SPR532 shown in the [list of supported][2] devices for the Linux CCID driver.

      + OpenKeychain is able to communicate with the card and retrieve the key IDs, then download the public keys from the Internet.

      + Unfortunately, I cannot decrypt: OpenKeychain asks for the PIN to be entered on screen, while the whole point of the reader is to enter the PIN on its PIN pad.

*Is it feasible to add PIN pad support to OpenKeychain?*

If anyone here is in Berlin, I’d be happy to get together and play with the readers. I’d also be happy to donate a reader to a developer.

As an alternative, I’m also looking at the [Trezor][5] hardware wallets, which now can also be used to store a private PGP key (256 bit ECC). They would require writing custom Android software though as they’re not based on the OpenPGP standard.

[1]: https://www.amazon.de/gp/product/B0092NGGWW
[2]: https://ccid.apdu.fr/ccid/supported.html
[3]: https://www.amazon.de/gp/product/B004FQL8RY
[4]: https://www.amazon.de/gp/product/B000ELJ9XY
[5]: https://trezor.io/

**Comment by Valodim** [comment]
Interesting, thanks for evaluating! Can GnuPG work with the pin entry? If it can, so could OpenKeychain

**Comment by feklee** [comment]
@Valodim Yes, of course, it does so by default without any configuration:

    $ gpg -d test.gpg
    […]

    ┌─────────────────────────────────────┐
    │ Please unlock the card              │
    │                                     │
    │ Number: XXXX XXXXXXXX               │
    │ Holder: Felix Klee                  │
    │                                     │
    │ Use the reader's pinpad for input.  │
    │                                     │
    │                <OK>                 │
    └─────────────────────────────────────┘

    […]
    gpg: encrypted with 4096-bit RSA key, ID 04FDF78D1679DD94, created 2016-12-17
          "Felix E. Klee <felix.klee@inka.de>"
    Hello world!

> If it can, so could OpenKeychain

Sounds good. The question is what changes are necessary.

**Comment by feklee** [comment]
FWIW I succeeded in compiling `gnupg` with smart card reader support in Termux on a rooted phone. I documented the process in a [gist][1]. The pin pad works, and I can decrypt files.

[1]: https://gist.github.com/feklee/92f76d2c8a7cabc477360d82b5305c19

**Comment by Valodim** [comment]
Interesting :)

As I said, if gnupg can work with the pin pad, it's just an issue of teaching OpenKeychain how to do it. I'm a bit short on time personally right now, but if anyone wants to give it a go, PR definitely welcome!

From a quick glance, the operation boils down to calling PC_to_RDR_Secure on the reader, see [usb ccid](http://www.usb.org/developers/docs/devclass_docs/DWG_Smart-Card_CCID_Rev110.pdf) specification, section 6.1.11. Everything else should work entirely between the reader and the card. Related code in Rousseau's CCID driver is [here](https://github.com/LudovicRousseau/CCID/blob/b15c8f96ca80005c3da024c031e9607051a9fe1a/src/commands.c#L311).

**Comment by thomasjfox** [comment]
given a little bit of experience from the gnupg2 side of things,
many readers require quirks to the protocol for working pin pad support.

NIIBE Yutaka wrote a little pinpad debug tool for gnupg2:
https://salsa.debian.org/gnuk-team/gnuk/gnuk/blob/master/tool/pinpadtest.py

Never invoked it myself though :)

**Comment by feklee** [comment]
*Anything on the roadmap concerning support of pin pads?* I certainly don't want to enter the pin on my phone.
