### ISSUE TITLE
Linked Identities: sign with subkey

### ISSUE THREAD

**Issue by sporkwitch** [open-keychain/open-keychain#1913]
Currently the identity-linking functionality doesn't permit signing if the master key is stripped.  This effectively prevents the use of sane and standard key policies (namely keeping the master offline, or at least on a more easily and thoroughly controllable platform that's less likely to be lost or stolen).

Does it make sense to support signing such proofs with a subkey?  If not, and perhaps easier either way, the ability to save the intended content of the message for export to a device with the master, for signing and posting, would work as well.  It should logically be possible to sign a given statement on another machine and post manually, later clicking something like "I've already uploaded it, please check it" in the android client.

Without such function, I'm skeptical of the utility of the feature, as keeping the master off the phone would seem to me to be a very common and standard process (especially given the number of potential Android vulnerabilities announced lately).

**Comment by dschuermann** [comment]
According to the OpenPGP specification RFC 4880, only the master key is capable of certifying other keys, thus "signing keys" (= certifying) with a subkey is not possible. This is also exactly the reason why some people have the master key on a different device.
The other option sounds really difficult to use for the average Joe, not sure if we will support that.

I understand your concern regarding Android security, have you thought about using a security token?

**Comment by sporkwitch** [comment]
I have, and I'm looking into the Yubikey neo for exactly that purpose since my old feitian card doesn't support pgp, but i'm broke for now heh. (now if only they had one in an actual credit card form factor that had NFC and contact-based, I'd be in heaven). 

I didn't realize that you were actually modifying data on the key with this implementation (advanced mode doesn't seem to expose it on the master key I do have on the device), hence my confusion on the need for the master. 

On August 16, 2016 3:43:29 AM EDT, "Dominik Schürmann" <notifications@github.com> wrote:
>According to the OpenPGP specification RFC 4880, only the master key is
>capable of certifying other keys, thus "signing keys" (= certifying)
>with a subkey is not possible. This is also exactly the reason why some
>people have the master key on a different device.
>The other option sounds really difficult to use for the average Joe,
>not sure if we will support that.
>
>I understand your concern regarding Android security, have you thought
>about using a security token?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/1913#issuecomment-240027334

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dschuermann** [comment]
You could get a Fidesmo card with NFC using our promotion code for 14 €, see https://www.openkeychain.org/faq/#what-security-tokens-are-recommended-for-openkeychain.
But it is only-NFC. The page also lists other options, for example SIGILANCE for 25 $ with contact support and NFC.

**Comment by sporkwitch** [comment]
Will have to check that out, as it sounds close to what I'm looking for. Thank you! 

On August 16, 2016 7:27:57 AM EDT, "Dominik Schürmann" <notifications@github.com> wrote:
>You could get a Fidesmo card with NFC using our promotion code for 14
>€, see
>https://www.openkeychain.org/faq/#what-security-tokens-are-recommended-for-openkeychain.
>But it is only-NFC. The page also lists other options, for example
>SIGILANCE for 25 $ with contact support and NFC.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/1913#issuecomment-240075752

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dschuermann** [comment]
You could also get http://shop.fidesmo.com/product/fidesmo-card-dual-interface for 12 € and afterwards install the PGP applet for 3 € using the Fidesmo app. I think that's actually the cheapest while still easy solution for contact + NFC. Maybe shipping will cost extra.

**Comment by sporkwitch** [comment]
Still more palatable than the $50 for the Yubikey neo in a form factor I'm not fond of. May just be a quirk, but I just strongly prefer a card reader and card to an all-in-one dongle (saves on upgrade and replacement costs, too, provided the new card is compatible with the old card reader). 

On August 16, 2016 7:32:31 AM EDT, "Dominik Schürmann" <notifications@github.com> wrote:
>You could also get
>http://shop.fidesmo.com/product/fidesmo-card-dual-interface for 12 €
>and afterwards install the PGP applet for 3 € using the Fidesmo app. I
>think that's actually the cheapest while still easy solution for
>contact + NFC. Maybe shipping will cost extra.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/1913#issuecomment-240076525

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
