### ISSUE TITLE
Add support for fingerprint readers

### ISSUE THREAD

**Issue by Flippylosaurus** [open-keychain/open-keychain#1924]
It would be useful if support for fingerprint readers could be added for unlocking keys. I know this on itself isn't fully secure, so it would be useful if a warning is given when only using a fingerprint without a second factor (I.e. a PIN code). 

You could create a new key with a "hash" of a fingerprint for example.

I am not a PGP expert, so don't take this seriously if it isn't possible.

**Comment by dschuermann** [comment]
That's a good idea we discussed previously, but the issue wasn't properly named to find it: https://github.com/open-keychain/open-keychain/issues/1642

This makes only really sense technically when we implement private key storage via Android's Keystore API.
