### ISSUE TITLE
Wrong passphrase error

### ISSUE THREAD

**Issue by gcala** [open-keychain/open-keychain#1925]
Hi,
I installed OpenKeyChain and K-9 Mail on my android device and imported in OKC the pair of keys I'm using on my pc. Although both apps seems correctly configured I'm unable so sign or decrypt mails using the passphrase. Since I exclude an input error, could it be that OKC has problem managing uncommon characters? For instance, my passphrase contains  ( $ @ / \ maybe one of them pops the error?

The same emails can be opened with the same key from kmail on linux.

The only gpg feauture working on android is encrypting a mail with recipient pub key.

Thanks

**Comment by gcala** [comment]
The problem seems was an error importing key. now fixed

**Comment by Valodim** [comment]
Good to hear. :+1: We do have unit tests for the backend which make sure handling of special characters is working, and I would have been very surprised if the frontend messed this up and we never noticed.
