### ISSUE TITLE
Physical keyboard causes crash

### ISSUE THREAD

**Issue by Matvei27** [open-keychain/open-keychain#1928]
If you try to navigate this app with the arrow keys on a keyboard or on an Android device with physical keys, it will crash. Usually happens on the button for the sidebar drawer.
Please fix this so I can use this app instead of the outdated APG app.

**Comment by Valodim** [comment]
Did you send a play store crash report when you get the "unfortunately..." message? That would be very helpful for debugging

**Comment by Matvei27** [comment]
It doesn't give me that option : (
I can only click OK.


On Sep 13, 2016, at 11:18 PM, Vincent Breitmoser <notifications@github.com> wrote:

Did you send a play store crash report when you get the "unfortunately..." message? That would be very helpful for debugging

**Comment by Valodim** [comment]
Ah. Can you try to obtain the stack trace from logcat, using adb? That would help tremendously :)

**Comment by Matvei27** [comment]
Sure, if you give me the commands I would need to input I can run ADB with the device in USB debug mode. 

On Sep 14, 2016, at 01:42 AM, Vincent Breitmoser <notifications@github.com> wrote:

Ah. Can you try to obtain the stack trace from logcat, using adb? That would help tremendously :)

**Comment by Valodim** [comment]
`adb logcat` should do it

**Comment by Paramjeet2810** [comment]
@Matvei27 : I tried using physical keyboard on various emulators and it works perfectly fine. So, could you please share with me about the device specifications on which the app crashes.

**Comment by Matvei27** [comment]
KDDI SHF31 

On Sep 17, 2016, at 10:29 PM, Paramjeet S Desai <notifications@github.com> wrote:

@Matvei27 : I tried using physical keyboard on various emulators and it works perfectly fine. So, could you please share with me about the device specifications on which the app crashes.

**Comment by Matvei27** [comment]
The app itself works, but navigation with the physical keys causes crashes. 

On Sep 17, 2016, at 10:29 PM, Paramjeet S Desai <notifications@github.com> wrote:

@Matvei27 : I tried using physical keyboard on various emulators and it works perfectly fine. So, could you please share with me about the device specifications on which the app crashes.

**Comment by Paramjeet2810** [comment]
@Matvei27 I have understood your problem and will get back to you as soon as I solve the problem.

**Comment by Matvei27** [comment]
Is the d-pad somehow different from the arrow keys on the keyboard? 
Based on the way they work with apps they APPEAR to behave the same, but maybe not? 

On Sep 17, 2016, at 11:08 PM, Paramjeet S Desai <notifications@github.com> wrote:

@Matvei27 I have understood your problem and will get back to you as soon as I solve the problem.

**Comment by Paramjeet2810** [comment]
I guess the behavior is the same.

**Comment by Matvei27** [comment]
The only apps I've seen crash due to keypad input are this and duckduckgo

On Sep 17, 2016, at 11:34 PM, Paramjeet S Desai <notifications@github.com> wrote:

I guess the behavior is the same.

**Comment by Paramjeet2810** [comment]
@Matvei27 
https://drive.google.com/open?id=0B7ovNgtxR6GIZXhMcVJGREd3T3c
I have the apk through drive can you please check if the bug is solved or not, because the app now works perfectly fine on emulator as well as on mobile phones when a keyboard is connected using an otg cable

**Comment by Paramjeet2810** [comment]
I have shared*

**Comment by Valodim** [comment]
Nice! Can you make a PR with your changes? :)

By the way I wasn't on the computer when you tried to reach me via IRC, timezones and such :( You can email me at `look@my.amazin.horse`

**Comment by Matvei27** [comment]
I tried it, but actually the debug version just crashes. I installed it but if you try and open it it says "Unfortunately, OpenKeychain has stopped"

**Comment by Paramjeet2810** [comment]
When does the app crashes ?? After you try to open the app or after you try to open the navigation drawer.Because in the emulator the app works fine when I use the d-pad and the app also works perfectly fine when I connect an OTG keyboard to my galaxy S6.

**Comment by Valodim** [comment]
Please create a pull request with your changes, an apk is not a good way to share your work for review :)

**Comment by Matvei27** [comment]
It's crashing when I try to open the debug APK you sent. I can install it but it does not start.

**Comment by Paramjeet2810** [comment]
Sir, I have created a pull request and I have also sent  you an email. I hope you found my email as well the pull request I created is accessible to you.

**Comment by Matvei27** [comment]
I have not received your email. Can you please try to send it again?
The version you sent me via APK doesn't work, so I'll need another way to test it.

**Comment by Paramjeet2810** [comment]
@Matvei27  I am really sorry for delaying things.
Try this apk  https://drive.google.com/file/d/0B7ovNgtxR6GIbWNtUklYcmpYWjg/view?usp=sharing

**Comment by Matvei27** [comment]
I tried to install the version you put up here, but it doesn't even open.
I took an ADB log using the official version on Fdroid.
Please check the log attached here.
[logcat2.txt](https://github.com/open-keychain/open-keychain/files/677400/logcat2.txt)

**Comment by Matvei27** [comment]
The version you gave me here, when side loaded, installs but will not open.

**Comment by dschuermann** [comment]
Is this still present in 4.2.4, if yes we can re-open. For now I will close this one.
