### ISSUE TITLE
[QUESTION] Chatsecure integration?

### ISSUE THREAD

**Issue by AlphaOmega3** [open-keychain/open-keychain#1932]
Hi! Chatsecure (in combination with Orbot) is probably the best solution for "secure" communications.. so, is possible for OpenKeychain work with Chatsecure?? (I see the integration with Orbot, but I don't understand if is possible with Chatsecure, because this don't reveals nothing like Conversations..)

**Comment by nmikhailov** [comment]
ChatSecure only supports OTR encryption. Also it is kinda discontinued. FYI: Conversations supports OpenPGP via OKC and Orbot(although I haven't tested myself).

**Comment by AlphaOmega3** [comment]
hmmm I understand. Although Conversations does not convince me.. so you prefer Chatsecure, right??

**Comment by nmikhailov** [comment]
I myself use Conversations. (just in case: when I said I haven't tested I mean that I haven't test Orbot integration).
Its FOSS and actively developed. In fact I just opened Chatsecure and it proposed to switch to Conversations. Anyway its up to you, don't switch if you are satisfied with Chatsecure, although it might be worth to check conversations out.

**Comment by Valodim** [comment]
We provide an API for other apps to integrate with, so this is not something which would require changes on our side. If you'd like to see another app using our API, please file the feature request on their side :)
