### ISSUE TITLE
Nitrokey Pro / Storage: Key generation (Put key command) fails ("invalid data")

### ISSUE THREAD

**Issue by szszszsz** [open-keychain/open-keychain#1937]
Application shows USB transmission error when trying to use Nitrokey Storage as a security token.
Please let me know how can I create / extract the logs.

App version: 4.2 beta 1 (42000)
Android 6.0.1, Galaxy S6
Nitrokey Storage v0.43 (OTG USB)
Frequency: Always (5/5)

Scenario:
1. Insert Storage stick
2. Open application
3. Tap `Manage my keys`
4. Tap `USE SECURITY TOKEN`
5. Tap `USE THIS SECURITY TOKEN`
6. Enter arbitrary name, email and PIN and tap `Next`
7. Uncheck `Synchronize with the internet` and tap `CREATE KEY`
-  A Bar with key creation progress is shown
- Image is shown with instructions to holding a security token against the NFC marker
- Red LED on the device blinks a couple of times
- After next 10 seconds the error is shown:

```
Error: USB error - failed to transmit data -1
Take away the Security Token now and touch TRY AGAIN
```
1. After tapping `TRY AGAIN` error is shown again after another 10 seconds delay
2. After reinsertion application crashes but returns to the screen where key is created
3.  Tapping `CREATE KEY` another time red LED on device is flashing for about 10 seconds
4. After the delay same error with `-1` code is shown.

Calling possibly interested: @jans23 @nmikhailov

**Comment by szszszsz** [comment]
Hi! I have just retested the issue on latest version (even if not marked as solved; by the way of other check).
On 4.4.1 (44100) I have another error window now, that the PIN is too short and it should be at least 6 characters (despite entering 9 or later exactly 6 digits). I have reset the token earlier with the menu (there were some keys on it before).
Storage Firmware: v0.47.1

**Comment by techge** [comment]
Same behaviour on Nitrokey Pro.

**Comment by szszszsz** [comment]
Retested by the occasion of #1936 with:
```
4.8-beta.1 (48000)
Nitrokey Pro v0.7
```

**Comment by Valodim** [comment]
wait, nitrokey pro?

**Comment by szszszsz** [comment]
Yes, I assumed the issue cause for both is the same. Would you like me to retest it on Storage anyway?

**Comment by Valodim** [comment]
No, I was just confused because of the title. You're right, this issue happened on all nitrokeys all along.

**Comment by Valodim** [comment]
```
10-23 18:39:12.663  21741    21741             Keychain D  D  org.sufficientlysecure.keychain.securitytoken.CardException: Failed to put data.
10-23 18:39:12.663  21741    21741             Keychain D  D  at org.sufficientlysecure.keychain.securitytoken.SecurityTokenConnection.putData(SecurityTokenConnection.java:456)
10-23 18:39:12.663  21741    21741             Keychain D  D  at org.sufficientlysecure.keychain.securitytoken.SecurityTokenConnection.setKeyAttributes(SecurityTokenConnection.java:478)
10-23 18:39:12.663  21741    21741             Keychain D  D  at org.sufficientlysecure.keychain.securitytoken.SecurityTokenConnection.putKey(SecurityTokenConnection.java:513)
10-23 18:39:12.663  21741    21741             Keychain D  D  at org.sufficientlysecure.keychain.securitytoken.SecurityTokenConnection.changeKey(SecurityTokenConnection.java:145)
10-23 18:39:12.663  21741    21741             Keychain D  D  at org.sufficientlysecure.keychain.ui.SecurityTokenOperationActivity.doSecurityTokenInBackground(SecurityTokenOperationActivity.java:269)
10-23 18:39:12.663  21741    21741             Keychain D  D  at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity.handleSecurityToken(BaseSecurityTokenActivity.java:440)
10-23 18:39:12.663  21741    21741             Keychain D  D  at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:157)
10-23 18:39:12.663  21741    21741             Keychain D  D  at org.sufficientlysecure.keychain.ui.base.BaseSecurityTokenActivity$1.doInBackground(BaseSecurityTokenActivity.java:145)
10-23 18:39:12.663  21741    21741             Keychain D  D  at android.os.AsyncTask$2.call(AsyncTask.java:305)
```

**Comment by dschuermann** [comment]
@szszszsz Just to validate because I only have a Nitrokey Pro and not Storage: Does the Nitrokey Storage work with signing/decrypting?
Is it also true that the Nitrokey Start is based on the GNUK?

**Comment by szszszsz** [comment]
That's right, Nitrokey Start is based on GNUK ([last release](https://github.com/Nitrokey/nitrokey-start-firmware/releases) is on 1.2.4).
As for Storage I believe @techge has tested this (could you comment please?)

**Comment by techge** [comment]
I can confirm that the NK Storage is working with OpenKeychain for signing and decrypting, once configured on PC.

**Comment by dschuermann** [comment]
@techge thanks for confirming

**Comment by dschuermann** [comment]
fixed in https://github.com/open-keychain/open-keychain/pull/2201

Will be released in the next beta.
