### ISSUE TITLE
Passphrase input on secret key export?

### ISSUE THREAD

**Issue by sbriskin** [open-keychain/open-keychain#194]
Need password protection on private key export (like APG does).

**Comment by Valodim** [comment]
discussion came to a conclusion here, I created a new issue for the implementation #1045

**Comment by alanthehat** [comment]
Sorry, I've just seen this
Much more of an issue is permissions on the directories. 
The underlying Linux is secure if it's set up right. 
At the moment it appears to be using the defaults from the installer.
Directories should have the 'sticky' bit set to prevent anyone other than the app's user deleting anything. 
I suggest permissions of 
01700 on /data/data/org.sufficientlysecure.openkeychain 
during setup, although I don't know what to suggest for lib, app & Dalvik cache directories.
This would probably then require a [prepare for uninstall] button to revert it.('rm' the keys & 'chmod -R 0777 * for everything else)
https://en.wikipedia.org/wiki/Sticky_bit
