### ISSUE TITLE
Ignore quotes (when sorting public keys)

### ISSUE THREAD

**Issue by rugk** [open-keychain/open-keychain#1943]
Keys created with Mailvelope have this UID format for their mail address: `"mail@example.com" <mail@example.com>`.
As it begins with `"` these keys are unfortunately sorted first under `"`. In other applications (e.g. Mailvelope itself or e.g. Seahorse this quotes are hidden anyway, so either you also do this or you at least ignore the quote when sorting the keys as it is useless if all keys with `"` appear at the top.

OpenKeyChain 4.1 (41010)

**Comment by rugk** [comment]
I'd like to make the OpenKeyChain devs aware of the succession happening in the Mailvelope issue. There is currently a statement by @DigitalBrains1:
> I'd suggest that OpenPgpKey needs to be adapted to handle a name-addr better. In parallel, I think there's the possibility of opening a feature request/bug report for GnuPG that it should also produce a properly quoted name-addr when --allow-freeform-uid is not given.

**Comment by dschuermann** [comment]
Closed in https://github.com/open-keychain/open-keychain/issues/2013
