### ISSUE TITLE
OpenPGP error CursorWindow

### ISSUE THREAD

**Issue by wiedo** [open-keychain/open-keychain#1945]
When i try to send an encrypted email from K-9, i get the error in a toast:
`OpenPGP Fout: Couldn't read row 0, col 0 from CursorWindow. Make sure the Cursor is initialized correctly before accessing data from it.`

I tried reinstalling K-9 but it didn't work.

Also when i tap the recipient of that mail in OpenKeychain (edward-en@fsf.org, key found via the server) OpenKeychain crashes.

K-9 version: 5.010
OpenKeychain version: 4.1
Both downloaded from F-Droid

**Comment by Valodim** [comment]
For pgp related issues, a lot of things changed since the stable release. please install the latest alpha (link is in wiki) and see if your issue is solved there, then tell us if it isn't :)
