### ISSUE TITLE
Date and time API

### ISSUE THREAD

**Issue by SecTec** [open-keychain/open-keychain#1949]
Hi,
is it possible to create an API that K-9 could retrieve the date and time for a verified signature and when decrypting an encrypted message?

EDIT: The corresponding issue in the K-9 repo is no. 1761.

**Comment by Valodim** [comment]
Sure, this is definitely missing data in the result parcel. PR in a minute :) 

(doesn't solve the problem on the other side though)

**Comment by dschuermann** [comment]
done on OpenKeychain's side
