### ISSUE TITLE
Crash when opening keybase profile

### ISSUE THREAD

**Issue by rmartinho** [open-keychain/open-keychain#1955]
When I open my key with keybase.io enabled, the app crashes. It only happens with keybase.io proofs enabled, and I could only reproduce it with my keybase profile so far. Other keybase profiles work as intended.
I am rmf on keybase.

**Comment by dschuermann** [comment]
Thanks, fixed in https://github.com/open-keychain/open-keychain/commit/7ec84230b0bc0bbe8f48d87e55c1162ac5ff2d4c
