### ISSUE TITLE
Fix smart card support

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#1959]
From https://github.com/open-keychain/open-keychain/pull/1885

This broke smart card support :cry: since it requires the activity to implement `ImportKeysListener` which is implemented by `ImportKeysActivity`. Smart card support uses the activity `CreateKeyActivity`.

```
java.lang.ClassCastException: org.sufficientlysecure.keychain.ui.CreateKeyActivity@xxxxxxx must implement ImportKeysListener
```

**Comment by saleemrashid** [comment]
Thanks for creating the issue @dschuermann! Since the PR was merged a matter of days ago I wasn't sure if I should create an issue :smile:

**Comment by saleemrashid** [comment]
Workaround: Import the key beforehand then OpenKeyChain will offer to bind the key, bypassing this error.
