### ISSUE TITLE
Import of ECC primary keys OR RSA4096  subkeys not working from local keyring or  smartcard.

### ISSUE THREAD

**Issue by linux-modder** [open-keychain/open-keychain#1965]
Using LG LS665, running  Android 5.1.1 and openkeyring version 4.1 (41010) --from play store.

Using  Key Search (with hkps://pgp.mit.edu | hkps://pool.sks-keyservers.net| hkps://keys.fedoraproject.org ) 
my key shows using the standard hex notation but shows as unknown,256 bit

The key has  ed25519 primary , 2 nist521 subs, 1 cv25519 [E] subkey, and one each [SEA] rsa4096  subkeys ( 6  subs in total) and openkeychain seems to be unable to toggle to teh rsa keys to import.

Same thing is observed with import from file with $keyid.asc 
this all done without an OTG or NFC.

**Comment by dschuermann** [comment]
OpenKeychain currently doesn't support Ed25519 keys.
This issue is similar to https://github.com/open-keychain/open-keychain/issues/1911

**Comment by linux-modder** [comment]
@dschuermann any  timeline or such on when this might change?  sadly I tried with my old rsa4096 primary which should as such in the ui and still same error .

**Comment by dschuermann** [comment]
@linux-modder please post the detailed error here. Click on "Details" inside the notification on the bottom and then share the log.

**Comment by Valodim** [comment]
Are you talking about the rsa4096 key which is subkey of the ed25519 primary key? If that's the case, the subkey can't be imported on its own, since we can't validate signatures from the primary key if that one is ed25519.

**Comment by linux-modder** [comment]
It was due to ed25519 as primary with rsa4096  but fixed by using nist521 and rsa4096
