### ISSUE TITLE
Sender's Pub key used

### ISSUE THREAD

**Issue by kej6** [open-keychain/open-keychain#1967]
Hi,
I have two same email adresses from different providers:
Some.email@provider1.com
Some.email@anotherprovider2.com
For each of those adresses I have separate keys. When I am sending an encrypted email from first one to second one, pubkey from first one is used.
Then, I must decrypt an email in Some.email@anotherprovider2.com with privkey for Some.email@provider1.com.

I tested on Android and on Linux with Thunderbird. Only Android with openkeychain do the mistake.

Thank you, Michael Kej

**Comment by dschuermann** [comment]
@kej6 Are you using K-9 Mail? Is this bug still present in the latest OpenKeychain version 4.2.4 and K-9 Mail? If so, I will re-open.

**Comment by kej6** [comment]
Yes, I am using k-9 mail and the bug is still present. Sender's pub key is used for encription and at the same time is signed.

8. února 2017 21:00:22 SEČ, "Dominik Schürmann" <notifications@github.com> napsal:
:@kej6 Are you using K-9 Mail? Is this bug still present in the latest
:OpenKeychain version 4.2.4 and K-9 Mail? If so, I will re-open.
:
:-- 
:You are receiving this because you were mentioned.
:Reply to this email directly or view it on GitHub:
:https://github.com/open-keychain/open-keychain/issues/1967#issuecomment-278444148

**Comment by dschuermann** [comment]
It is correct that the email is also encrypted to the sender. This allows the sender to decrypt sent mails. 

But it should also be encrypted to the recipients address. Do you have the recipients email in your contacts?
This sounds like a bug in K-9.

**Comment by dschuermann** [comment]
I think this is a bug in K-9, please open a bug report at their tracker: https://github.com/k9mail/k-9/issues
