### ISSUE TITLE
Importing keys already on token

### ISSUE THREAD

**Issue by russkrayer** [open-keychain/open-keychain#1968]
I have a Yubikey Neo already with keys stored from an air gapped machine.  I don't see how to convince OpenKeychain to use these.  If it's possible then can we get some specific documentation on the method, or if currently not possible, add a method for enabling use of keys already on token.  I could help test or with docs.

**Comment by dschuermann** [comment]
We plan to do a redesign of these at some point but are currently running on limited time resources: https://github.com/open-keychain/open-keychain/issues/1587

Please open a new issue if you have specific problems after holding the token against your device.

**Comment by russkrayer** [comment]
I guess there is no issue except vague message about import failed.  But then after using desktop gpg to 'send-keys' to the default keyserver used by openkeychain, I was able to properly import the key on the phone and successfully used my keys stored on the yubikey.  Thanks for your attention.
