### ISSUE TITLE
Uses wrong key for signing

### ISSUE THREAD

**Issue by rugk** [open-keychain/open-keychain#1969]
I am using K9 mail and in OpenKeychain I have two private keys for the same mail address, one older one without a name field (listed first in OpenKeychain) and one recent version with a name field.

For some strange reason for signing always the old one is used, probably because it is listed first. However as keys sometimes replaced by new ones and in this case it would be more useful if the most recent key is used for signing.

**Comment by Valodim** [comment]
Openkeychain uses the key that is set in the settings for signing, it doesn't care for user ideas

**Comment by rugk** [comment]
Actually I cannot set this in K9 mail anywhere.

I'm using the stable version.
