### ISSUE TITLE
Using keys for other applications (password store or k9mail) gives a "toast" error

### ISSUE THREAD

**Issue by alex9099** [open-keychain/open-keychain#1970]
Hi, I have lolipop on my phone and openkeychain seems to not be working as expected (it works fine on a kitkat phone i have), when i select the key to encrypt the files i get a "floating message" (i think it is called toast) saying something like this:

`Error from OpenKeyChain: attemp to invoke method 'android.content.intent org.openintents.openpgp.IOpenPgpService2.execute(android.content.intent, android.or.parcelfiledescriptor, int)' on a null object reference`

The error may not be exactly the same as the one that showed on screen because i dont know how to copy toast messages

**Comment by alex9099** [comment]
@Valodim 
@dschuermann 

(it seems like you are the guys that contribute more for the project :) can you help me? )

**Comment by Valodim** [comment]
Uh... can you say what you are trying to do? :)

**Comment by alex9099** [comment]
Loading key pairs to encrypt the passwords (for password manager) or selecting public keys for email encryption (on k9 mail)

**Comment by alex9099** [comment]
@Valodim  And?

**Comment by dschuermann** [comment]
@alex9099 Are you using some custom Rom or similar? This is a very strange error. I remember something similar happened in the past when the Android IPC was broken in a particular version of Cyanogenmod.

**Comment by alex9099** [comment]
Kind of, it is not the one from the manufacturer but it is based on lolipop AOSP (i installed because back in the time there was no lolipop for my phone :D, now the manufacturer released a beta version) :/ 

I'll try to install the beta official ROM, but i think i cant do that in next days :/

**Comment by dschuermann** [comment]
Closing for now. If this can be re-produced with an official manufacturer rom, please report.

**Comment by alex9099** [comment]
It works fine with manufacturer rom, thats strange because the guy that modified the original one sayed that the only difference was xposed, root, init.d support a a few more things :/

**Comment by Valodim** [comment]
Xposed is hugely intrusive, as soon as that is in pretty much all bets are off.

(Kinda like samsung :p)

**Comment by alex9099** [comment]
so it might have been because xposed?

**Comment by dschuermann** [comment]
We cannot know but that is a possibility

**Comment by alex9099** [comment]
:/ well, the thing is that it works fine now after installing the stock rom and xposed, maybe it was because of some module or some other modification i might have made :D 

Whatever... it works fine now :)
