### ISSUE TITLE
Replace "remembered passwords" wording in notification

### ISSUE THREAD

**Issue by tessus** [open-keychain/open-keychain#1976]
I've noticed wrong wording for cached passwords:

![screenshot_2016-12-31-05-29-44](https://cloud.githubusercontent.com/assets/223439/21584160/ca0a3c1c-d06a-11e6-892e-ea80cee5bfeb.png)
![screenshot_2016-12-31-05-29-08](https://cloud.githubusercontent.com/assets/223439/21584162/cc32b758-d06a-11e6-9c9f-4b77db2723af.png)

While one can ask an app to remember credentials, the app itself does not remember them, but uses a cache to store them.

The correct term is `cached` instead of `remembered`.

I've opened a pull request #1975

**Comment by Valodim** [comment]
"Cache" is a needlessly technical term. There's a reason virtually all websites call this feature "Remember me" instead of "Cache my password".

**Comment by tessus** [comment]
@Valodim I think you totally misunderstood me. Let me try this again.

I explicitely stated that asking an application to "remember a password" is ok. The term "Remember my password" is even preferred. I was talking about the part where the application actually stores "remembers" the password.

An application cannot remember a password. This is the wrong term. It seems to be translated from a different language. The action 'to remember' requires a chemical process in the brain. Since the computer does not have a brain, the application cannot rember something. So to ask the program to remember a password is ok, because you interact with the program.
(This is why I did not change the occurences of 'Remember my password' in the pull request.)

In grammar it is quite common to use different words for active and passive constructions.

Thus when it comes to state the fact that something has been remembered, you use a different word. Like `saved` or `cached`.
'1 password remembered' sounds translated from a foreign language and is not used in English. The same thing is true for 'Remembered password'.
In these 2 cases another term is used.

You can either use `1 passwod cached` and'`Cached passwords`, or `1 password saved` and `Saved passwords`.

**Comment by Valodim** [comment]
Hmmm, I see where you're coming from.

I'd like to avoid use of the word "cache", as I said it's needlessly technical. "Saved" might be better, but that usually implies storage on a more permanent medium ("Saving" a document commonly means writing from ram to disk).

Wouldn't your argument that it's a brain thing to "remember" stuff apply just as well to the active use of "remember", before it became a common word for this purpose on websites? Same for "memory"?

Considering that the passwords are stored in "memory" only, I feel like "remembered" is a very clear and self-descriptive term for "currently in memory", even though its use in this context is not super widespread.

**Comment by tessus** [comment]
The term 'cached' is technical, but let's be honest. Everybody who uses gpg is capable of understanding technical language. But apart from that, even a newbie knows what it means nowadays.

> Wouldn't your argument that it's a brain thing to "remember" stuff apply just as well to the active use of "remember", before it became a common word for this purpose on websites? Same for "memory"?

This is a bit more complicated to break down and I don't really know how to answer it. Theoretically yes. But this is not how a language develops. People have always tried to humanize computers and interact with them on a personal level. But this is projecting your action towards another.
If you really want to drill down it will become a metaphyscial and philosophical topic.

'to save' is also perfectly valid, since there is no requirement that 'saving' has to be to a permanent storage.

I used 'to cache' in the pull request, because it is the most commonly used term in the English language in this context.

Btw, the term "cached" is often used as a synonym for "data being currently in memory". Isn't that ironic. :-)

**Comment by Valodim** [comment]
"People who use gpg will understand" is pretty much the declared opposite of where we want to go - design for the users you want, not the users you have. Yes, "to cache" is exactly the right word for "keeping in memory for a limited time", but it's not understood outside of the technical community.

**Comment by dschuermann** [comment]
Agreeing with everything @Valodim wrote. "saved" does implies storage on disk, "cached" is too technical. I am open for other suggestions, but until then I propose we stick to "remembered".

**Comment by tessus** [comment]
How can I put this without being rude (please forgive me, if you feel I am though).

You are using a literal translation, which is not only wrong, but also embarrassing. I've just talked to several people at my office and their first comments were that the developers were probably not native speakers.
Then I talked to a friend who is German and he told me I should tell you that this is called a wrongly used "Germanismus".

You are also wrong that the word "saved" implies storage on disk. Saving and committing to memory are perfectly valid expressions which are commonly used in the English language.

You can either believe me, ask another native speaker, or continue to use an expression that makes every native speaker smile.

**Comment by dschuermann** [comment]
@tessus 
Let's dive deeper into the issue so that I can get a better understanding:
So you say "An application cannot remember a password.".
I tried to look into other applications and their wording and found that Internet explorer actually uses a sentence similar to yours: "Do you want Internet Explorer to remember the password for example.com?" (https://blogs.msdn.microsoft.com/ieinternals/2009/09/10/why-wont-ie-remember-my-login-info/).
Isn't this in contrast to what you said?

Please bear with us, we are not native speakers, but as we said "cached" is too technical and if I ask 10 random average people (not technical persons), "save" means storing to disk.

**Comment by tessus** [comment]
> Isn't this in contrast to what you said?

No, it is not. I explained this in my second comment https://github.com/open-keychain/open-keychain/issues/1976#issuecomment-26997912.

You definitely want to use phrases like "Remember for one hour" and "Remember until screen off".

I'm only talking about the passive use of the word (as you can see in the screenshots).

> Please bear with us, we are not native speakers, but as we said "cached" is too technical and if I ask 10 random average people (not technical persons), "save" means storing to disk.

Are these 10 random average people native speakers? If not, your conclusion is not valid. You are supposed to write the English text for people that speak English, not for people who learned English, but speak and use a different language.

Also, please note that there is a difference between:

1) I save a password
2) I use as saved password

While 1) might imply (although it's more likely that this implication is a German thing) that one saves something to disk, 2) does not. At least not in English.

In English "cached" is the most precise description of a temporarily stored/saved password. It does not even matter, if it is on disk or in memory. The key is that it is not permanent.

**Comment by dschuermann** [comment]
Thanks for your explanation, we decided for "saved".

**Comment by Valodim** [comment]
I think I'd like "5 passwords in cache" as well, but I'm good with either option.

btw, in German, no translation of "remembered" (e.g. "gemerkt") would work for this use case :)
