### ISSUE TITLE
Form for selecting multiple keys does not close

### ISSUE THREAD

**Issue by codewiz** [open-keychain/open-keychain#1978]
How to reproduce:

1. Import two different keys for the same email address
2. Create an email in K-9 Mail addressed to the above recipient
3. Enable encryption, then send the email
4. The attached form will open

The checkboxes won't toggle if I click on them.
If I hit the OKAY button, the window disappears and appears again.

There is no way to continue from here, other than canceling and returning to the mail editor.

**Comment by codewiz** [comment]
![openkeychainbug](https://cloud.githubusercontent.com/assets/1184492/21598198/c05ac21e-d11d-11e6-8dd5-ceb279e273c7.png)

**Comment by ewert59** [comment]
same to me.

**Comment by Valodim** [comment]
Fixed in #1980
