### ISSUE TITLE
K9 does not appear to recognize a PGP key if there is a capital letter in the email address

### ISSUE THREAD

**Issue by sharpe5** [open-keychain/open-keychain#1987]
If I use K9 to send an email to "Look@my.amazin.horse", it will not recognize the pgp key.

However, if I use K9 to send an email to "look@my.amazin.horse", it will recognize the pgp key.

The only difference is the auto-capitalization on the "L" at the start of the email address.

As email addresses are not case sensitive, this is a corner case that renders Open-KeyChain unusable for the vast majority of people, especially as Android automatically capitalizes the email address.

**Comment by dschuermann** [comment]
duplicate of https://github.com/open-keychain/open-keychain/issues/1935
