### ISSUE TITLE
Can't confirm keys with Yubikey

### ISSUE THREAD

**Issue by jfjallid** [open-keychain/open-keychain#1989]
I have a Yubikey with only subkeys which I use for encrypt/decrypt and signing operations. I've successfully imported my public key which is only present on keybase.io and then bound my yubikey to it in the open-keychain app. However, when I try to confirm another key with a fingerprint I can't select my key from the list. It is present but I can't select it.

Another problem I noticed is related to the Android Password Store where I can't select my gpg key to use for encryption. I can select open-keychain as an OpenPGP provider and then list the keys available. When I try to select receivers I can see my key but when I try to select it the screen is just reloaded.

**Comment by dschuermann** [comment]
So your master key is not in OpenKeychain nor on the YubiKey? If yes, you cannot certify other keys as this requires the master key.

**Comment by jfjallid** [comment]
Right, I have no clue how I could forget about that detail. Thanks for clearing that up. I'll open a ticket with Android Password Store for the other problem. Any chance this second issue could be due to open-keychain since the error is encountered in the interface which I assume belongs to open-keychain?

**Comment by dschuermann** [comment]
Can you create a new issue for the second problem and attach a screenshot what screen you mean?
