### ISSUE TITLE
Can't select keys from open-keychain to use with Android Password Store

### ISSUE THREAD

**Issue by jfjallid** [open-keychain/open-keychain#1990]
In Android Password Store I can select OpenKeychain as my OpenPGP provider to select which keys to use for encryption. Both my keys are listed but when I try to select receivers and save the screen is just reloaded showing the same keys with none selected.

![screenshot_2017-01-11-12-50-11](https://cloud.githubusercontent.com/assets/10165473/21847619/16230536-d7fd-11e6-973b-cdbeca214762.png)

**Comment by dschuermann** [comment]
Ah ok :) I think your issue has been fixed in OpenKeychain 4.2. Can you please try this new version and report back?

**Comment by jfjallid** [comment]
This is from OpenKeychain version 4.2.

**Comment by dschuermann** [comment]
Arg. This looks to me like a regression. Will try to look into this today.

@Valodim If you have time, could you also look into this?
