### ISSUE TITLE
'Unusal' key length prevents signing e-mails

### ISSUE THREAD

**Issue by bslbckr** [open-keychain/open-keychain#1994]
I'm using a signing key, that uses none of the standard lengths 1024,2048,3072, 4096 ... but a length of 3104 bits. If I try to sign an e-mail with my yubikey, open-keychain complains about about an unexpected number of bytes (388 bytes in this particular case) being were returned (I assume by the yubikey?). 

From my understanding the number of bytes returned, depends on the used key length. The key length could be - more or less - arbitrarily chosen. Hence, any sanity check must not test for only four valid but must assure that the number of returned bytes is in conformance with the used key length.

**Comment by Valodim** [comment]
Yubikey Neos only support keys up to 2048 bits. Or are you using USB-OTG for this?

**Comment by bslbckr** [comment]
That's the reason I'm not using a Yubikey neo. I'm using a Yubikey 4 and USB-OTG

**Comment by Valodim** [comment]
Ah, I see. This is indeed a bug in the implementation. I attempted a fix :)

**Comment by bslbckr** [comment]
Great! Please let me know, if I could support you with testing or sth else.

**Comment by af-anssi** [comment]
I have checked the patch and should be accepted as it improves the existing check on the signature length.
