### ISSUE TITLE
onion address on 4.2.1

### ISSUE THREAD

**Issue by canary5** [open-keychain/open-keychain#2002]
After upgrading from 4.1 to 4.2.1 onion keyserver doesnt work, it crashes. If you add new keyservers onion address, always invalid url error. Worked perfect on 4.1

**Comment by dschuermann** [comment]
Please be more precise. What steps did you do exactly?

**Comment by canary5** [comment]
I had onion address as keyserver. Now of i try to search a key with it, the app crashing. If i try to add another onion address as keyserver, it doesnt connect, bad url. I will make logcat tomorrow

**Comment by Valodim** [comment]
Did you report the crash on the play store, using the Report button in the "Unfortunately, OpenKeychain has stopped" dialog?

**Comment by canary5** [comment]
No i dont have google services. I have managed to fix it. Earlier you had one url line for keyserver, now two. If you upgrade from 4.1, your onion address moves to the top where regular url should be. And if you do search keys, it crashes. I have filled both  keyserver lines with onion address, so now it works

**Comment by canary5** [comment]
Logs of the crash
pastebin.com/ArRNTLk6

**Comment by dschuermann** [comment]
@canary5 thanks for your explanations. We will look into this.

relevant stacktrace:
```
01-18 09:08:09.403 10901 10971 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
01-18 09:08:09.403 10901 10971 E AndroidRuntime:    at java.net.URI$Parser.parse(URI.java:3049)
01-18 09:08:09.403 10901 10971 E AndroidRuntime:    at java.net.URI.<init>(URI.java:589)
01-18 09:08:09.403 10901 10971 E AndroidRuntime:    at org.sufficientlysecure.keychain.keyimport.ParcelableHkpKeyserver.getURI(ParcelableHkpKeyserver.java:166)
01-18 09:08:09.403 10901 10971 E AndroidRuntime:    at org.sufficientlysecure.keychain.keyimport.ParcelableHkpKeyserver.getOnionURI(ParcelableHkpKeyserver.java:157)
01-18 09:08:09.403 10901 10971 E AndroidRuntime:    at org.sufficientlysecure.keychain.keyimport.ParcelableHkpKeyserver.getHttpUrl(ParcelableHkpKeyserver.java:192)
01-18 09:08:09.403 10901 10971 E AndroidRuntime:    at org.sufficientlysecure.keychain.keyimport.ParcelableHkpKeyserver.search(ParcelableHkpKeyserver.java:254)
01-18 09:08:09.403 10901 10971 E AndroidRuntime:    at org.sufficientlysecure.keychain.keyimport.ParcelableHkpKeyserver.search(ParcelableHkpKeyserver.java:61)
01-18 09:08:09.403 10901 10971 E AndroidRuntime:    at org.sufficientlysecure.keychain.keyimport.CloudSearch$1.run(CloudSearch.java:66)
01-18 09:08:09.403 10901 10971 E AndroidRuntime:    at java.lang.Thread.run(Thread.java:761)
01-18 09:08:09.409  5905  6611 W ActivityManager:   Force finishing activity org.sufficientlysecure.keychain/.ui.ImportKeysActivity
01-18 09:08:09.415  5905  6611 W ActivityManager:   Force finishing activity org.sufficientlysecure.keychain/.ui.MainActivity
```

**Comment by canary5** [comment]
Also its crashing when you click upload to keyserver

**Comment by dschuermann** [comment]
Fixed in https://github.com/open-keychain/open-keychain/commit/72d62a847f713bd0a76d7282d057c2f577223109
