### ISSUE TITLE
Can't import private key

### ISSUE THREAD

**Issue by NHcoder** [open-keychain/open-keychain#2003]
I exported my private key using Enigmail (v1.9.6.1) on Win7. When I try to import it using OpenKeychain (v4.2.1) [Android 6.0.1 (Android security patch level Dec 1, 2016) on my Galaxy Tab S2], the program crashes. If I copy the private key to the clipboard and try to import it that way, I get an error "bad data". I have not modified the expiry date of the key (it has no expiration date).

I can import the key on CentOS using gpg (v2.0.14). If I export the private key from there, I get the same crash on Andriod if I try to import the key.

The key uses RSA 2048 bits. They key has three email identities,

**Comment by d-tamm** [comment]
I also get the error "bad data" on all my attempts to import keys from file, both private and public ones. 
[Daniel Tamm daniel@tamm-tamm.de (0x89935B87) pub.asc.zip](https://github.com/open-keychain/open-keychain/files/794927/Daniel.Tamm.daniel.tamm-tamm.de.0x89935B87.pub.asc.zip)
Attached a public key which caused this error.
I have not found any way to get my keys into the app yet.
Using a Samsung GT-i9305 with android 7.1.1

**Comment by Valodim** [comment]
I unzipped your file, pushed it to my android and importing that file works as expected. I also opened the file an editor, selected the whole text and then did "read from clipboard" in OpenKeychain, and that also works.

How do you move this file to your android, and what mechanism do you use to open it?

**Comment by d-tamm** [comment]
Well, that's strange. Now, I have no problems either, both importing from clipboard (had not found that button before) and from file works now... Did exactly the same things as before. However, I have configured a lot and installed some other apps the last days after having installed a new ROM.

**Comment by kodoub** [comment]
It also happened to me if I passed keys through bluetooth. After transferring the .asc file via email, everything was OK.
