### ISSUE TITLE
Crashes whenever I try to use a key

### ISSUE THREAD

**Issue by gloomytrousers** [open-keychain/open-keychain#2004]
I've imported the key for edward-en@fsf.org via search. Whenever I tap the key, Open Keychain crashes. I have tried deleting and re-importing, but no use. The same thing happens 100% consistently.

I also cannot encrypt mail to the recipient in K-9 mail. An error about selecting row 0, col 0 from cursorwindow.

This is on CyanogenMod on a Galaxy S5, and Open Keychain 4.2.1 from f-droid. Let me know if you need me to test or collect further diagnostics.

**Comment by Valodim** [comment]
Thanks for your report! I was able to reproduce this issue, will look into it

**Comment by dschuermann** [comment]
Duplicate of https://github.com/open-keychain/open-keychain/issues/1714
