### ISSUE TITLE
Use of Open KeyChain for Twitter, Github, etc.

### ISSUE THREAD

**Issue by countesscvs** [open-keychain/open-keychain#2009]
Hello.

I am interested in instructions on how to use the Linked Identities feature under the Settings/Experimental Features tab.

This seems interesting. How does it work?

**Comment by dschuermann** [comment]
Please use mailinglist for questions

**Comment by 9662** [comment]
A link to the mailing list would be helpful.

**Comment by dschuermann** [comment]
@9662 https://www.openkeychain.org/help/
