### ISSUE TITLE
Cannot import public key from file

### ISSUE THREAD

**Issue by bartgenuit** [open-keychain/open-keychain#2012]
## Expected Behavior
When trying to import [this public key](https://gist.githubusercontent.com/bartgenuit/a7cdb77ab3a5b80fde84c1c669c357d6/raw/6d1a560bbd3db24f5461864b12b297e60ae91ac2/werner.asc) (of Werner Koch, ~1MB), I expect OpenKeychain to import the keys contained in the file.

## Current Behavior
OpenKeychain throws error
```No valid keys found in file/clipboard!```

## Possible Solution
I suspect this having something to do with Werner's key not being standard, or possibly malformed by GnuPG. Loading from keyserver doesn't work either, nor does loading from the key at eifelkommune.de.

## Steps to Reproduce (for bugs)
1. Import [this key](https://gist.githubusercontent.com/bartgenuit/a7cdb77ab3a5b80fde84c1c669c357d6/raw/6d1a560bbd3db24f5461864b12b297e60ae91ac2/werner.asc) or [this key](http://werner.eifelkommune.de/mykey.asc) from file, OR
2. Import the key by searching for handle ```0xF2AD85AC1E42B367```, OR
3. Import the key by searching for email ```wk@gnupg.org```.

## Context
I'm trying to add the public key or Werner Koch, as I'm subscribed to the gnupg mailing list, which is signed with his key, and K9 doesn't even *display* a signed message if you have encryption enabled but don't have the signing key (not your fault, but that's what started this in the first place :sweat_smile:)

## Your Environment
* Android Version: 5.1
* OpenKeychain Version: 4.2.1
* From Google Play or F-Droid?: Google Play

**Comment by dschuermann** [comment]
Can you try importing the key from a file instead of clipboard? I think there is a limitation of Android's clipboard.

**Comment by bartgenuit** [comment]
I tried both. Does the supplied file (link to gist) work on your OpenKeychain?

**Comment by bartgenuit** [comment]
And this is the error log when using a keyserver:
```
[START] Importing key
 [DEBUG] Using keyserver hkps.pool.sks-keyservers.net
  [INFO] Retrieving from keyserver: 0xf2ad85ac1e42b367
 [ERROR] Import operation failed!
```

**Comment by dschuermann** [comment]
You are correct this is independent of clipboard issues. We will look into it.

**Comment by bartgenuit** [comment]
Thank, if I can be of any use running more tests, I'd be happy to, just let me know.

**Comment by bartgenuit** [comment]
With the new version 4.2.2, importing from keyserver works okay, from file
does not.

**Comment by dschuermann** [comment]
Can you try again with 4.3? We fixed some things related to import. If this does not help, I can re-open this report.

**Comment by bartgenuit** [comment]
It works now, thanks! 👍 
(Android 6.0.1, OpenKeychain 4.3)

**Comment by JoeBattams** [comment]
Hi, I'm on Android 7.0 and am having the exact behavior identified by bartgenuit- cannot import a public key from file (no keys found)- have tried multiple file types and editors, both on android and linux. OpenKeychain will not recognise any file as containing keys (gpg4usb works fine with same files). Thanks

**Comment by dschuermann** [comment]
@JoeBattams please open a new issue.

**Comment by ld1756** [comment]
I'm running Android 11, OpenkeyChain 5.2.1 fm PlayStore and! Effective 09/25/2021, can *not* Import Key w/ clipboard (already ruled out, I know Schuermann), nor DL docs & images.
  I'm really stuck  *right here".
Not a coder, just high-level user skills (yeah, all app. permissions granted and it's Tor 5.5.5, 04/21).
  Pretty please help, anyone??  Import Key worked just fine in March, April 2021, haven't used again til 9/25/2021- did the Tor 4/21 update introduce something buggy that made Openkeychain unhappy? 
  Hope this helps narrow the focus.  Thanks all.
