### ISSUE TITLE
Some operation tests are failing

### ISSUE THREAD

**Issue by rhari991** [open-keychain/open-keychain#2016]
Running the tests in the operations test directory except the BenchmarkOperationTest causes an AssertionError with the message "initial test key creation must succeed".

**Comment by dschuermann** [comment]
Hmmm, cannot reproduce this on my local installation (Debian stable, OpenJDK). Also, tests on Travis CI are passing.
What OS and Java version are you using (OpenJDK or Oracle?)?

**Comment by rhari991** [comment]
Windows 8.1 and Oracle JDK 1.8

**Comment by dschuermann** [comment]
Please switch to OpenJDK, We cannot compile with Oracle JDK due to cryptographic restrictions on the JCE.
