### ISSUE TITLE
Does not find keys with an empty email address

### ISSUE THREAD

**Issue by c64bob** [open-keychain/open-keychain#2021]
I have imported a public key that contains only a name, and no email address. I have linked this key to the corresponding contact in OK. However, I can't encrypt emails to this contact in k-9 mail. It only shows a red padlock, and when trying to force encryption it says "private mode activated, but some recipients don't have keys".

## Your Environment
* Android Version: 6.0.1
* OpenKeychain Version: 4.2.1
* From Google Play or F-Droid?: Google Play
* k-9 Version: 5.203

**Comment by dschuermann** [comment]
This is a very special use case currently not supported. Also this is a limitation of K-9 Mail, not OpenKeychain. So, sorry but we are closing this one.

**Comment by c64bob** [comment]
I understand, thanks for your answer.

**Comment by Valodim** [comment]
This is a work in progress in k-9,though I cannot say how long it will be

**Comment by c64bob** [comment]
@Valodim that is awesome. Is there an open issue where I can follow along?
