### ISSUE TITLE
Display insecure key warnings

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#2022]
On import:
* If a subkey is insecure (as in ``PgpSecurityConstants.isSecureKey()``) it should be marked as insecure in our database, similar to revoked. 

In OpenKeychain's key lists/views:
* If all subkeys and the master key in an OpenPGP key are insecure, display them exactly like revoked keys are displayed. Only with a different message such as "This key is no longer secure and thus must not be used anymore."

Selection for encryption:
* Do not allow selection of these keys for encryption, similar to revoked keys handling

**Comment by rhari991** [comment]
I'd like to work on this.

**Comment by dschuermann** [comment]
sure go ahead

**Comment by rhari991** [comment]
@dschuermann When should the key be marked as secure/insecure ? When it is created ?

**Comment by dschuermann** [comment]
@rhari991 When a key is saved into the database. I think an approriate place is in ProviderHelper:423.
