### ISSUE TITLE
Scanned QR codes have to be in an overly specific format

### ISSUE THREAD

**Issue by M1dgard** [open-keychain/open-keychain#2035]
## Expected Behavior
If I create a QR code with just a fingerprint, e.g. `ABAF11C65A2970B130ABE3C479BE3E4300411886`, I expect the app to recognize it. It should also work with spaces in between, e.g. `ABAF 11C6 5A29 70B1 30AB  E3C4 79BE 3E43 0041 1886`.

## Current Behavior
The app expects the QR code to be a URL using the `openpgp4fpr` scheme and rejects everything else with the non-obvious error message "QR Code malformed! Please try again!"

## Possible Solution
Modify `ImportKeysProxyActivity` below [line 136](https://github.com/open-keychain/open-keychain/blob/d826e2c32ec49a97eb89e4fa2189143c80d69613/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/ui/ImportKeysProxyActivity.java#L136).

## Context
I thought the app was broken because I created a normal QR code and it kept saying "QR Code malformed! Please try again!". I only discovered how to make QR codes that the app can read when I created a QR code of my key with the app, and then scanned it.

If you do not find it acceptable to accept arbitrary fingerprint formats, you could instead make the app inform the user about the `openpgp4fpr` scheme when he scans a QR code that doesn't use it, so that people making their own QR codes and testing them with OpenKeychain can learn more easily about it.

**Comment by dschuermann** [comment]
Fixed in https://github.com/open-keychain/open-keychain/commit/68916c5838bc03af1f3bcba3996a718285090736

I also prepared a wiki page: https://github.com/open-keychain/open-keychain/wiki/QR-Codes

**Comment by Valodim** [comment]
It makes sense to have the openpgp4fpr uri in qr codes, because that way scanning the code with a regular Barcode scanner will also open OpenKeychain. This isn't possible with free form fingerprints, so we shouldn't encourage this.
