### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by CaptainKhan** [open-keychain/open-keychain#2037]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version: 4.4
* OpenKeychain Version: Newest Feb 6th 2017 as of,
* From Google Play or F-Droid?: Aptoid
* TOR: enabled

**Comment by CaptainKhan** [comment]
basically app doesnt remember last app page visited and menu/checkbox selection once app is closed and reopened.

i only use app to encrypt and decrypt using a password, and i have no ise whatsover for all the key server, key manage, key retrieval, key generation erc functionality, i would love tp simple be able to hide 80% of all Openkeypass options.

**Comment by dschuermann** [comment]
If you click on your home button and then open the app again the last page is opened. works for me

**Comment by CaptainKhan** [comment]
It doesnt work, bear with me and follow tgese steps:
1. open Openkeychain app, in menu navigate to encrypt decrypt files,
2. close app,
3. open app again, it will go to "My Keys" instead of Encrypt/ Decrypt,

So it certainly doesnt work for me.

**Comment by dschuermann** [comment]
please explain step 2., do you mean clicking on your home button or back?

![image4](https://cloud.githubusercontent.com/assets/321888/22709369/d766b878-ed79-11e6-92e5-9f8ea3a5c1dd.png)

**Comment by dschuermann** [comment]
And please: get OpenKeychain from F-Droid or Google Play, Aptoid is not updated by us and no trustworthy channel.

**Comment by CaptainKhan** [comment]
@dschuermann - thanks ill keep that in mind when installing the next version update, i do use f-droid through TOR usuall, just got lazy this time.

With Step 2 i am talking about closing it, for example in IOS app switcher carussel, flick upward to remove from memory and running apps. So in my case its Swipe down from top edge of screen to close the app.

I am no talking about suspend, freeze, pause or minimizing of Openkeychain. I am talking about stopping all processes and removing it from working memory.

**Comment by dschuermann** [comment]
@CaptainKhan If you remove it from the task stack it will not keep its last screen. This is by design and I don't know of any other Android app that remembers the last screen. So, sry we will not implement this.

**Comment by CaptainKhan** [comment]
One app that is more encrypt/decrypt using password centric in a way jas acxomplished that:

Cryptomator

It remembers and does background upload/download encryption operations. I dont think if you enable Background refresh on certain apps, background processes allow to be run. This function would consequently allow you to remember, maintain and continue menu position. (maybe i am not a developer)

**Comment by dschuermann** [comment]
I am planning to implement a Tasker plugin that should allow background encryption/decryption stuff.

**Comment by CaptainKhan** [comment]
@dschuermann i am looking forward to that, it would be a great addition, files i am encrypting (using my mobile device) are usually of the order of 200-500MB and a reliable process that doesnt time out is key. That a slightly different topic, but thought i mention it here.
