### ISSUE TITLE
Fresh developer

### ISSUE THREAD

**Issue by mani94454182** [open-keychain/open-keychain#2038]
Hello
I'm a new developer and I want to contribute to your project as it seemed to be very interesting.
I ensure you that once it get comfortable and gain enough knowledge in your work, I will give my 100% to work for it
I'm waiting for a chance to prove myself capable
Hoping to get a chance this time
thanking you

**Comment by dschuermann** [comment]
follow https://github.com/open-keychain/open-keychain#contribute-code
