### ISSUE TITLE
Cannot import any type of key

### ISSUE THREAD

**Issue by reesejohn291** [open-keychain/open-keychain#2046]
I cannot import any Public or Private key from file manager. 
I am able to do so by downloading them from any Key server. 
I am facing this issue since I upgraded to Android 7

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version: 7.0
* OpenKeychain Version: 4.2.4
* From Google Play or F-Droid?: Google Play

**Comment by Valodim** [comment]
That isn't enough information to know what could be wrong, please be more precise. What exactly did you do, what did you expect, and what happened instead? Did you get an error?

**Comment by dschuermann** [comment]
Will re-open if enough information is provided.
