### ISSUE TITLE
Cannot import keys from local file

### ISSUE THREAD

**Issue by reesejohn291** [open-keychain/open-keychain#2047]
I use a Moto G4 Plus. Recently it got Android 7 upgrade. After that upgrade whenever I try to import any public/private key using a .asc file the app crashes.
## Expected Behavior

The app should be able to import keys.

## Current Behavior

I am able to download keys from te Keyservers and can make new keys. But I am not able to import new keys from local files.

## Steps to Reproduce (for bugs)

1. https://youtu.be/KYDYBqfF1rk

## Your Environment

* Android Version: 7.0
* OpenKeychain Version: 4.2.4 
* From Google Play or F-Droid?: Google Play

**Comment by reesejohn291** [comment]
I am really sorry for bugging like this, but was anyone able to recreate this error and look into possible solution.

I am still not able to import any key.

**Comment by dschuermann** [comment]
Please re-try with 4.3, we improved import for specific asc files.
