### ISSUE TITLE
Saving encrypt file with same file name destroys source file.

### ISSUE THREAD

**Issue by CaptainKhan** [open-keychain/open-keychain#2048]
1. select encrypt,
2. encrypt with password
3. add data file to be encrypted
4. select save
5. fpr file name choose the same as in folder of added file in step 3.
6. select save,
7. source file now effectively destroyed through encryption and cannot be accessed any longer,

## Expected Behavior

What should happen is encryption of file with same name PLUS added ".GB" type file extension of the open-keychain.

The app should not be able to or allow encryption and saving over same file which kills the source file.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version: 
* OpenKeychain Version: 
* From Google Play or F-Droid?:

**Comment by dschuermann** [comment]
OpenKeychain already appends a ".pgp" extension. Not sure what you want us to do here.

**Comment by Valodim** [comment]
Ah, no we don't append .pgp to name for selected files. Selecting the same file for input and output replaces that file in place, which arguably is expected behavior...

**Comment by CaptainKhan** [comment]
Yes thanks for the clarification gp or pgp same idea.

Let me illustrate and see steps above:
File Name: backup_2017-02-09.gs-bck

I want to encrypt it using password. So follow steps above. You could create a txt file and rename as file name shown above to test.

Now encrypt with open-keychain and password and SAVE from app menue (little disk symbol) use same file name "backup_2017-02-09.gs-bck" (~200MB file) in the SAME file folder.

Now the new file name is "backup_2017-02-06.gs-bck" with NO ".pgp" extension and a size of 192 Bytes instead of ~200MB, so thats what i mean when i say your tool destroys the file it overwrites it with something else and elliminates most of original data.

**Comment by CaptainKhan** [comment]
what it should do is append new file extension to backup_2017-02-06.gs-bck so it reads

backup_2017-02-06.gs-bck.pgp

and if former periods in file name cant be handled automatically encapsulate as text string if thats possible in linux.

**Comment by Valodim** [comment]
Thta's your expectation, but I would argue that - from a "choose file to save to" dialog, the user expects the file they choose to be the one we write to, not some other with an extension.

Anyways I think you're right that this workflow is not as nice as it could be, we'll think about how to improve it.

**Comment by CaptainKhan** [comment]
@Valodim now thats the crux of it. The workflow are actually two processes wrapped i to one. An idea could be to split them out.

1. select file to encrypt, execute encryption through button, which will encrypt file and place in local temp storage/memory?,
2. What do you want to do next dialogue, save file in location X, overwrite original file Y etc,

Just a thought.

**Comment by dschuermann** [comment]
We now propose "backup_2017-02-06.gs-bck.pgp" by default in the next OpenKeychain version. So you only need to click save in the dialog.

Closed with https://github.com/open-keychain/open-keychain/commit/5566cf717649e78bc45c4f38fb7b0995bcfcad26

**Comment by CaptainKhan** [comment]
@dschuermann much appreciated.
