### ISSUE TITLE
OpenKeychain not returning results from keys.mailvelope.com keyserver

### ISSUE THREAD

**Issue by ThatGuy435** [open-keychain/open-keychain#2051]
Adding the hkps://keys.mailvelope.com server to the key server list in OpenKeychain OpenPGP keyservers list and moving to the top priority does not return any results.

## Expected Behavior
On searching for a key by a known email address, the appropriate key should be returned.

## Current Behavior
All searches (even for addresses known to be in the keys.mailvelope.com list) return no results.

## Steps to Reproduce (for bugs)
1. Add hkps://keys.mailvelope.com to OpenPGP keyservers list (uncheck trusted only, as mailvelope's certificate is not pinned)
2. Move to top
3. Search for an address known to be in the database

## Context
I use Mailvelope because it is a straightforward and convenient way to implement OpenPGP on my existing e-mail accounts. Manually moving all the public keys of all my contacts is time consuming and frustrating, when mailvelope's keyserver already contains them - but it appears OpenKeychain isn't on speaking terms.

## Your Environment

* Android Version: CyanogenMod 13 (Android 6.0)
* OpenKeychain Version:  4.2.4
* From Google Play or F-Droid?: Google Play

**Comment by dschuermann** [comment]
I somehow opened a new issue for this: https://github.com/open-keychain/open-keychain/issues/2061

I am investigating.
