### ISSUE TITLE
Support for Gnuk security token

### ISSUE THREAD

**Issue by teythoon** [open-keychain/open-keychain#2056]
The Gnuk token is a free hardware project implementing the OpenPGP card protocol on a generic microprocessor.

I can arrange that a sample Gnuk is shipped to a developer who wants to work on Gnuk support (preferably someone who is interested in also doing so in the future, as we are thinking about either extending the OpenPGP card protocol, or adding a custom protocol to it in the future).

Project home: https://www.fsij.org/category/gnuk.html

## Expected Behavior

Using the Gnuk with Open-Keychain should just work (like e.g. with a Yubikey).

## Current Behavior

Nothing happens when I plug it in.

## Possible Solution

I see that work is underway to support a derivative of the Gnuk in #1834.

## Your Environment

* Android Version: 5.1
* OpenKeychain Version: 4.2.4
* From Google Play or F-Droid?: F-Droid

**Comment by Valodim** [comment]
Related recent work on this in #2201

**Comment by dschuermann** [comment]
fixed in https://github.com/open-keychain/open-keychain/pull/2201

Will be released in the next beta.

**Comment by Valodim** [comment]
this is only partially tested so far. it would be nice if someone could confirm this works with their gnuk, including a version number. Gnuk >= 1.2.5 supports reset and key generation, gnuk < 1.2.5 will refuse to reset or generate key, but can be used for signing and decryption at least.

**Comment by dschuermann** [comment]
Missing fixes are here: https://github.com/open-keychain/open-keychain/pull/2206
