### ISSUE TITLE
Unable to encrypt email to self (from k9 mail)

### ISSUE THREAD

**Issue by nickmdowson** [open-keychain/open-keychain#2062]
## Expected Behavior
When I type in my email address in the to line in k9mail, it should show my contact as a green (has key) and then successfully encrypt to it.

## Current Behavior
my contacts (both emails for which I have my own keys (public and private) show up as red; when I tell it to encrypt then try to send it says 'no keys found for some of the recipients (or similar)

## Steps to Reproduce (for bugs)

1. Install F-droid version 4.24, setup
2. try to send an email from yourself to yourself in k9mail.

## Context
Forgive me if I'm doing something wrong in how this is supposed to work but I can't get it to work for me...any suggestions appreciated. I appreciate I'm experiencing this within k9mail but it seems to relate to openkeychain...

## Your Environment

* Android Version: CyanogenMod 13 / Android 6.0.1
* OpenKeychain Version:  F-droid version 4.24

**Comment by dschuermann** [comment]
Please open a bug report at https://github.com/k9mail/k-9 
@Valodim will handle it there.

**Comment by nickmdowson** [comment]
ok thanks
