### ISSUE TITLE
Put SHA1 on insecure algorithm list

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#2068]
Due to http://shattered.io/, I propose we put SHA1 on the list of insecure algorithms. See https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSecurityConstants.java#L82

Any objections?

**Comment by Valodim** [comment]
We don't know any usage numbers here, so it's hard to tell how many people's workflows this breaks. What are gpg's defaults and how recent does it have to be to work? On top of that, our error reporting sucks, right now the user would not even be told that this was the actual problem. I've been working on that, but until we have something better there I wouldn't blacklist sha-1.

There is also the matter of canonicalize, where we don't respect blacklisted algorithms iinm, so the weakest link remains regardless of blacklisting :(
