### ISSUE TITLE
YubiKey 4 (USB): Key generation fails (put key) ("Invalid data")

### ISSUE THREAD

**Issue by uvok** [open-keychain/open-keychain#2069]
When creating new keys on a YubiKey 4 via the "Use security token" wizard, I end of with "Entered PIN is too short. PINs are at least 6 digits long. Error Invalid data".

## Current Behavior / Steps to Reproduce

The page "Would you like to use this blank security token..." appears, either when I insert the Yubikey via an USB OTG cable while OpenKeyChain is open, or when navigate to Manage my keys -> Use security token when it was connected before. When I insert the YubiKey when the homescreen is shown, the screen flickers shortly, but nothing else hapens.

The first page of the security token wizard says "You will be prompted when it is needed again", but when I click next on the page where I choose my PIN, and the YubiKey is not connected, OpenKeyChain crashes with

```
03-01 11:02:15.962 21967 21967 E AndroidRuntime: FATAL EXCEPTION: main
03-01 11:02:15.962 21967 21967 E AndroidRuntime: Process: org.sufficientlysecure.keychain, PID: 21967
03-01 11:02:15.962 21967 21967 E AndroidRuntime: Theme: themes:{default=overlay:org.cyanogenmod.hexolibre, iconPack:org.cyanogenmod.hexolibre, fontPkg:org.cyanogenmod.hexolibre, com.android.systemui=overlay:org.cyanogenmod.hexolibre, com.android.systemui.navbar=overlay:org.cyanogenmod.hexolibre}
03-01 11:02:15.962 21967 21967 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from null array
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at org.sufficientlysecure.keychain.securitytoken.SecurityTokenHelper.parseOpenPgpVersion(SecurityTokenHelper.java:107)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at org.sufficientlysecure.keychain.ui.CreateSecurityTokenPinFragment.nextClicked(CreateSecurityTokenPinFragment.java:204)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at org.sufficientlysecure.keychain.ui.CreateSecurityTokenPinFragment.access$100(CreateSecurityTokenPinFragment.java:41)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at org.sufficientlysecure.keychain.ui.CreateSecurityTokenPinFragment$3.onClick(CreateSecurityTokenPinFragment.java:163)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at android.view.View.performClick(View.java:5204)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:21158)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-01 11:02:15.962 21967 21967 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-01 11:02:15.969  1527  3169 W ActivityManager:   Force finishing activity org.sufficientlysecure.keychain/.ui.CreateKeyActivity
```

Otherwise:

On the PIN screen, I enter my chosen PIN.  I tried entering a 6 and a 7 digit PIN.
When I attach my YubiKey on the PIN screen, unfortunately the first page of the wizard appears again, since I set OpenKeyChain as default application for this USB device. I can navigate back, though. The Admin Key changed then. The PIN fields still show dots.

When I click Next now, I get the "You entered the following identity" screen.
When I click "Create Key", the key is created, but then I get the error "Entered PIN is too short. PINs are at least 6 digits long. Error Invalid data". (No warnings / errors to see in the logcat in this case, though).

Unfortunately, I can't re-enter any PIN while the YubiKey is connected on the PIN screen.

## Expected Behavior

 * Keys get generated on the YubiKey without the error being shown, since the PIN is 6 digits long.
 * If possible, the wizard shouldn't get opened again if it is already being shown

## Context

I'm trying to generate keys on a blank YubiKey 4 with OpenKeyChain.

## Your Environment

* Android Version: LineageOS 13.0, self-built, (20170227)
* OpenKeychain Version: 4.2.4
* From Google Play or F-Droid?: Installed via F-Droid
* Asus Zenfone 2
* YubiKey 4, Firmware Version 4.3.4

**Comment by dschuermann** [comment]
We got a batch of new Yubikey 4, 4 Nano, 4C, 4C Nano from Yubico for testing and all of them work with the current master branch. This is now also written down in our wiki at https://github.com/open-keychain/open-keychain/wiki/Security-Tokens

I cannot reproduce this problem with the current master branch. Please check out the upcoming version of OpenKeychain if it fixes your problem.

**Comment by uvok** [comment]
I can't reproduce the original situation anymore, since I already put a GPG key on the Yubikey on my PC, and I don't want to reset it. However, the import of the GPG key already on the Yubikey works fine
