### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by jvoigt** [open-keychain/open-keychain#2070]
The app is closed instantly after opening.

## Current Behavior
since shortly the App is not workung anymore.
*When i hit the icon the app opens and display a white screen, after 1 second the app closes it self.
*decrypting with k9 still works: it prompts the overlay for password entry.
*opening the app via an intent ( import to openkeychain) still works to: as soon as i return to the homescreen of the app it it closed
*Encrypting with k9 is not working too.

Normaly i would try to uninstall an re-install the app: but me newly generated key is still within the phone. and i wasn#t able to back it up somewhere: so if ich would delete the app my key would belost but still unrevoken

## Your Environment (friends phone)
Sony Xperia M4 Aqua
* Android Version: Android 5.0
* OpenKeychain Version: 4.2.4
* From Google Play

**Comment by dschuermann** [comment]
This is bad, sorry this happened to you.
I don't know what really happened in your case. Maybe a key has been updated that made it grew in its size and now Android has problems loading the database entry. We fixed this in 4.3, but only for newly imported keys. So an update would not help here.

I am sorry to say, but I will close this for now. I recommend re-installing, generating a new key and distributing this new one. Also make a backup then.
