### ISSUE TITLE
Passphrase necessary when sending mail - bug?

### ISSUE THREAD

**Issue by DaCryptor** [open-keychain/open-keychain#2073]
Hi,

after having installed the latest version from Google Play, I am always asked for my PGP-passphrase when sending an encrypted email via K-9. This is a bit annoying and destroys the usability. I think this is a bug, as I believe I should only be asked to enter my passphrase when **de**-crypting an email.

What do you think?

Best regards,
dacryptor

**Comment by ArchangeGabriel** [comment]
Not a bug, design decision in K-9. See https://github.com/k9mail/k-9/issues/2096, https://github.com/k9mail/k-9/issues/1768, https://github.com/k9mail/k-9/issues/1961, https://github.com/k9mail/k-9/issues/2112, https://github.com/k9mail/k-9/issues/1926 and https://k9mail.github.io/2017/01/30/OpenPGP-Considerations-Part-II.html for the reasoning.

**Comment by DaCryptor** [comment]
I see that this "feature" has been implemented to guarantee that the message is signed/authenticated, but it is really unconfortable if you have to always enter your passphrase when just wanting to send an encrypted message! I believe that this should be an --> optional <-- feature, not an enforced one!

Please re-consider your decision, @Valodim .
