### ISSUE TITLE
Mention Using adb push as a way to transfer key to android device

### ISSUE THREAD

**Issue by IvanMalison** [open-keychain/open-keychain#2074]
Perhaps I'm missing something obvious here, but it seems `adb push` should be among the recommended ways to transfer keys to one's android device in the frequently asked questions on the official website (https://www.openkeychain.org/faq/#what-is-the-best-way-to-transfer-my-own-key-to-openkeychain). Is there a reason that this method is not mentioned?

**Comment by dschuermann** [comment]
Yup, this is nothing you can recommend to your average Joe.
