### ISSUE TITLE
Cannot import keys from Yubikey 4 if public key is stored locally

### ISSUE THREAD

**Issue by JohanLorenzo** [open-keychain/open-keychain#2075]
First of all, thank you for maintaining this project! 😃 

Although a Yubikey and the public key are correctly detected, no match is done between the 2.

## Expected Behavior
When selecting the public key associated to the one present on the Yubikey, OpenKeyChain should put the key under "My Keys" on the main screen.

## Current Behavior
OpenKeyChain imports the key as if it were an untrusted contact's key.

## Possible Solution
I looked at the logs and the state of the SQLite database, and I think the public key is not matched to the one present on the Yubikey.

## Steps to Reproduce (for bugs)
1. From a blank yubikey, generate a new set of keys or import existing keys. Both lead to the same results. Regarding the case of generation: 
   1. `gpg --card-edit`
   1. `generate`. You can change values or not. In this example, I stuck to the default values.
1. Export the public key: `gpg --armor --export issue-2075@git.hub > public.gpg`
1. Push it to your phone: `adb push public.gpg /sdcard/public.gpg`
1. Launch OpenKeyChain and plug your yubikey on your phone via USB-OTG.
1. Yubikey is detected, select "Import key information from file", and pick `public.gpg` store at the root of your sdcard.
1. See the key details being correctly displayed, and tap "import"

For more details, I extracted [this piece of logcat](https://gist.github.com/JohanLorenzo/22161fc09e9dfe026e30aba576191322) from a debug build.

## Context
I'd like to use a Yubikey 4 on Android. I saw it's currently not officially supported, but #1833 is being worked on.

## Your Environment
* Android Version: LineageOS 14.1 (This may be a bug on the OS. But I don't see a clue [in the logs](https://gist.github.com/JohanLorenzo/22161fc09e9dfe026e30aba576191322) at the moment).
* OpenKeychain Version: Debug version built from master, which is currently at tag [v4.3-beta1](https://github.com/open-keychain/open-keychain/releases/tag/v4.3-beta1). This is also reproducible from the Google Play beta version (still 4.3-beta1) 
* From Google Play or F-Droid?: Google Play
* Yubikey Firmware: 4.3.4

Please tell me if you need more information, I'll be glad to provide some 😃 
 
Edit: Corrected logcat link.

**Comment by JohanLorenzo** [comment]
#2069 may also be related.

**Comment by dschuermann** [comment]
What is your key configuration on the YubiKey? Is the master key on it?

**Comment by JohanLorenzo** [comment]
I believe the master key is on it, because I generated them all directly on the card. I can retry by generating a new set of key and making sure the master key is on there.

**Comment by dschuermann** [comment]
Yup, please re-try. If the master key is not on the YubiKey you might hit https://github.com/open-keychain/open-keychain/issues/1681

**Comment by JohanLorenzo** [comment]
I confirm I can reproduce when the master key is present on the Yubikey. I tried in 2 cases:
1. When the keys were generated on the Yubikey
2. When I manually pushed the master key on it.

Between scenario 1 and 2, I factory reset the Yubikey.

**Comment by JohanLorenzo** [comment]
I understood what's wrong. It's actually a problem on the wizard side. There's a way to workaround it. I left all the details in #2098

Closing this misleading issue.
