### ISSUE TITLE
Which code is the private key?

### ISSUE THREAD

**Issue by stasik805** [open-keychain/open-keychain#2076]
## Steps to Reproduce (for bugs)

1. I have joined a website that requires a PGP  After entering the public key, it asked for the private key. I tried all 3 of the subkeys. What do I do?
2.
3.
4.

## Your Environment

* Android Version: 
* OpenKeychain Version: 
* From Google Play or F-Droid?:

**Comment by dschuermann** [comment]
To export the private key use the backup screen.
