### ISSUE TITLE
[FR] please provide apk file in releases page

### ISSUE THREAD

**Issue by krihsna** [open-keychain/open-keychain#2079]
i have device without google play services. i use apps which are absolutely necessary for me.

can you please provide apk file, if possible: https://github.com/open-keychain/open-keychain/releases

downloading from other apps has its own quirks & from web is fraught with risks.

**Comment by dschuermann** [comment]
F-Droid is the alternative trustworthy way besides Google Play we support. Download the apk here: https://f-droid.org/repository/browse/?fdid=org.sufficientlysecure.keychain
