### ISSUE TITLE
When trying to link github account to a key, Authorize applications is greyed out

### ISSUE THREAD

**Issue by nekosune** [open-keychain/open-keychain#2080]
## Expected Behavior
What should hapen is I can press the green authorize application button to link github and open keychain

## Current Behavior
Instead the button is greyed out,and if I try andclcik thedropdown by "Read and write gists" the page refreshes.

## Steps to Reproduce (for bugs)
Have a key through Yubio and a 2-step authentiction protected github.
Try to link the two together

## Context
This prevents me from linking my github .

## Your Environment
From Google play.
Android: 6.0.1
Open-Keychain : 4.2

**Comment by MartinX3** [comment]
Same problem.

GPG-Key.
Tried to  connect GitHub to it.
After login and using two factor, it ask me, to authorize the application.
A click on the arrow on the right site of "Gists" refreshes the page.
The button "Authorize application" is greyed out. Not clickable.

From Google play.
Android 7.1
Open-Keychain : 4.2.4

**Comment by Diagoras** [comment]
This SO answer claims the issue is that Javascript is disabled by default in Android's WebView: https://stackoverflow.com/questions/44425233/why-is-the-github-authorization-button-in-the-oauth-flow-grayed-out

**Comment by SenzoNgele** [comment]
Lool after I struggled for years.. I have found a Solution to This
The course is. First I use my google chrome which I saved my Github account with.
So my VS was taking me to Microsoft Edge and get the button disabled.

All you have to do is to change you Default browser on your machine to the one u have signed is with on github

**Comment by nekosune** [comment]
This was for an android app that used an internal browser for logging in. Nothing to do with Visual Studio or a PC or the like
