### ISSUE TITLE
Repopulate Key list 

### ISSUE THREAD

**Issue by iminderN** [open-keychain/open-keychain#2084]
We were using an older version of openkeychain (I think 3.7). After updating to the latest (i.e. 4.2.4) the name and email of keys have disappeared and are replaced by "no name". Is there a way I can bring the names back without deleting and readding the keys?
![screenshot_20170324-114055](https://cloud.githubusercontent.com/assets/22820969/24309004/5ccb28ca-1087-11e7-811f-2873e001b8d0.png)

**Comment by Valodim** [comment]
Why was this closed? Did the issue disappear?

**Comment by iminderN** [comment]
I resolved it myself, by calling "consolidate()" method in keyslistfragment
