### ISSUE TITLE
Show either key(s) or create if none exist

### ISSUE THREAD

**Issue by ghost** [open-keychain/open-keychain#2085]
More of a how to then an issue. I was playing around with K9 and Openkeychain, and noticed that when select key from cryptography settings of K9, I am given 3 options (i.e. if I only have 1 masterkey) - Choose none, choose the master key, choose to create one.

What if I want to enforce openkeychain and give the user the option to only select the master key, create one if none exist and disable the none altogether?  how would i do that

Apologies in advance for the question as I am very new to this.

**Comment by dschuermann** [comment]
> What if I want to enforce openkeychain and give the user the option to only select the master key, create one if none exist and disable the none altogether? how would i do that

I don't get this. So you want to make a fork of OpenKeychain/K-9 that enforces this behavior?
Your issue is not very clear. Please open a new one with a clear description of what you are trying to do. Also please use the GitHub template.
