### ISSUE TITLE
Symantec PGP desktop: Key encoding unspecified

### ISSUE THREAD

**Issue by tigerwoods2k17** [open-keychain/open-keychain#2089]
I was using Symantec PGP desktop to compare keys hosted in their keyserver and found that the "Encoding" field on their keys showed "PGP/MIME" while my keys showed "Unspecified"

Is there a setting that I am missing?

**Comment by Valodim** [comment]
I'm not sure what you are referring to, PGP/MIME is an email encoding and doesn't directly affect keys.

Can you link to (or send to me via mail -> look@my.amazin.horse) examples of public keys that exhibit this difference?

**Comment by wiktor-k** [comment]
Maybe they are using `preferred-email-encoding@pgp.com=pgpmime` notation just like this key: http://pool.sks-keyservers.net/pks/lookup?op=vindex&search=0xac6b0b0884ce93fe&fingerprint=on

**Comment by Valodim** [comment]
We're at a point where mail clients can safely use pgp/mime by default (K9 does), which makes this setting mostly obsolete. It's also definitely not something the user should (have to) choose themselves. If you want this annotation on your key regardless, I recommend using GnuPG to modify the key.
