### ISSUE TITLE
Additional information regarding "Insecure key must not be used anymore!"

### ISSUE THREAD

**Issue by sprig** [open-keychain/open-keychain#2090]
I imported a secret key and received the above message.

## Expected Behavior
I would like to know why OKC considers it insecure.
## Current Behavior
Am just told that it is insecure but it is unclear which are the offending parameters
## Your Environment
* Android Version: 7.1.2
* OpenKeychain Version: 4.2.4
* From Google Play or F-Droid?: G

**Comment by d-t-o** [comment]
I have the same issue when I try to import the public key from my bank:

https://www.1822direkt.de/pgp5key.asc

My assumption is that one of the subkeys is considered insecure by todays standards, but neither can I remove that subkey nor do I see a reason for marking the whole key insecure. The 4096 bit subkey is still good and the other one not actively used by the bank anymore, they probably only include it for legacy reasons.

So a more descriptive error what's the cause for the message plus a hint how to proceed in that case (allowing the deletion of the insecure subkey?) would be handy.

**Comment by Valodim** [comment]
We're definitely missing more descriptive error messages here. It's in the works :)

Regarding that key from your bank: That's a 1024 bit DSA key, generated in 1999. It shouldn't be used anymore.

**Comment by dschuermann** [comment]
For more explanation: Even when the subkey is 4096 bit, as long as the master key is 1024 bit the whole key cannot be considered secure. This is because the master key can add new subkeys to the keyring etc.

**Comment by d-t-o** [comment]
Thanks for the explanation, makes the behaviour of open keychain understandable :+1:

**Comment by dschuermann** [comment]
Will be implemented in the next version.
