### ISSUE TITLE
Stop service when passphrase is cleared

### ISSUE THREAD

**Issue by Bombenleger** [open-keychain/open-keychain#2095]
The passphrase caching system service should be exited when the passphrase is cleared to free up system resources.

## Expected Behavior
When passphrase is manually removed from cache or expires automatically, the passphrase caching android system service should be stopped.

## Current Behavior
Services continues running forever.

## Your Environment

* Android Version: 7.1.2
* OpenKeychain Version: 4.3
* From Google Play or F-Droid?: Google Play

**Comment by Valodim** [comment]
nice catch! fixed in 43757bf345e116153cb6f4040852842c145e8c9b
