### ISSUE TITLE
Yubikey: Wizard should allow to bind token after public key is imported (from file)

### ISSUE THREAD

**Issue by JohanLorenzo** [open-keychain/open-keychain#2098]
I understood why I thought the import of a Yubikey failed (in #2075): the wizard brings you back to the key list.

## Expected Behavior
After importing the public key (from a file), the wizard should show you the `ViewKeyActivity` which shows the button "Bind key"

## Current Behavior
At the moment, you're brought back to the main list. This may lead users to think the import went wrong (#2075), because only the public key is imported.

**Workaround:** Go through the "Manage my keys" wizard one more time, and `ViewKeyActivity` will be displayed in lieu of step 3.

## Possible Solution
Modify `ImportKeysActivity.handleResult()` to redirect the activity to `ViewKeyActivity` instead of going back to the main list, in this particular case.

## Steps to Reproduce (for bugs)

1. Go to "Manage my keys" (or start the first time usage wizard)
1. Tap "Use security token"
1. Select "Import key information from file" and select the file
1. After the key data is display, tap "import"

Reproduction rate: 10/10

## Context
I thought the usage of a Yubikey was impossible in my case, and it seems I'm [not the only one](https://github.com/open-keychain/open-keychain/issues/1681#issuecomment-280689658) 😃 

## Your Environment

* Android Version: LineageOS 14.1, 20170418
* OpenKeychain Version: Debug version built from master, which is currently at 6c2c8b248073864f9750e7a4dbd54c5282aa7dfd. This is also reproducible from the Google Play beta version (still 4.4-beta1)
* From Google Play or F-Droid?: Google Play
* Yubikey Firmware: 4.3.4

**Comment by Valodim** [comment]
This should be improved with #2157
