### ISSUE TITLE
Error Message when sending mail

### ISSUE THREAD

**Issue by coogor** [open-keychain/open-keychain#2102]
When sending an encrypted mail (to myself or to others) I see an error messages. Sending with encryption is not possible.

Please see https://github.com/k9mail/k-9/issues/2421 for description and error screenshot

## Steps to Reproduce (for bugs)

1. select mail recipient that has public key
2. send encrypted mail
3.
4.

## Your Environment
Galaxy S7 Edge with Android 7
Galaxy Tab A with Android (5 or 6)
K9 Mail  5.206

**Comment by Valodim** [comment]
can you post a screenshot of the "Subkeys" tab under the advanced view of your key?

The info in there is not secret and can be read from your public key, but if you don't want to post it here, feel free to mail it to me instead -> look@my.amazin.horse

**Comment by coogor** [comment]
Are you talking about the 'Details' view of the respective key? Starting with 'Key status'...?

**Comment by dschuermann** [comment]
open key -> in the menu with the three dots in the right corner select "Advanced" -> Go to subkey tab -> screenshot

**Comment by Valodim** [comment]
This key is a 1024 bit dsa key, it is no longer and support for such outdated keys was dropped.

Our error reporting in K-9 for this case is atrocious, and we need to improve that. Note that your key should already be displayed as insecure in OpenKeychain including an explanation with the most recent release.

**Comment by coogor** [comment]
GnuPG on the Laptop still works with it, and it does not make sense to prevent sending mails with it...better an old key (from 2004....) than no key

**Comment by Valodim** [comment]
1024 bit DSA keys are *not* secure. To give you an intuition here, a 768 bit dsa key was [successfully cracked](https://listserv.nodak.edu/cgi-bin/wa.exe?A2=NMBRTHRY;a0c66b63.1606), taking ~1.5 years of real time and ~6500 years of cpu time. A DSA 1024 bit key is roughly 1000 times more difficult to crack than that. That's not even close to an acceptable security margin, considering the limited resources of a bunch of independent researchers compared to state-level attackers.

It's a huge failure of the OpenPGP ecosystem that you weren't warned about this many years ago, to give you time to swich when convenient. I know it's annoying, but at this point tough love is the only option we have. Sorry about that. :(
