### ISSUE TITLE
Restore own key with yubikey neo

### ISSUE THREAD

**Issue by bikb** [open-keychain/open-keychain#2104]
Hello,
I don't have an openkeychain specific backup. I don't habe an Internet connection. But Plesse tell me how to connect my yubikey neo with openkeychain? I lost the APP data. But all keys in yubikey are OK. And I habe a file which can be imported to restore the public keys. But how to tell my private key is in yubikey and can be used. TIA

**Comment by Valodim** [comment]
Import the public key, go to key view, hold your yubikey against your phone. A new view should show up showing some yubikey details and a "Bind" button.

**Comment by bikb** [comment]
This works. Its a little bit tricky.

**Comment by Valodim** [comment]
It is! If you have a good workflow in mind, or maybe still know the places you expected this to be, or things you tested before you posted here, do tell!

That said, it should also be possible in the "Manage my Keys" dialog to hold the and be forwarded to that key's view key dialog. But this surely isn't a workflow that we have nicely figured out yet.
