### ISSUE TITLE
Cannot upload/download my key

### ISSUE THREAD

**Issue by aelmahmoudy** [open-keychain/open-keychain#2112]
OpenKeychain refuses to upload or download my key after I edited it to rekove an old identity.  My key ID is EDDDA1B7. I tested the following:

* Edited my key to remove the old identity, then when I attempt to upload the key, the upload fails with an error message to check the internet connection. Although uploading/downloading any other key using the same keyserver is successful.

* Hence I uploaded the updated key using APG, then try to update the key on OpenKeychain from the same key server, this also fails with an error message that keyserver cannot be contacted.

Android version: 4.1.2
OpenKeychain version: 4.4.1 from Fdroid

**Comment by Valodim** [comment]
I have no explanation :(

Your key looks fine to me, nothing odd about it. Did you generate it with OpenKeychain, or something else?

**Comment by aelmahmoudy** [comment]
Please try downloading the key, then upload it again (without changing it).

The key was generated using gnupg.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Valodim** [comment]
imported from keyservers, then uploaded, and it works fine.

can you send the key that fails to upload to me via the "Share with..." option under the Share tab in advanced key view? e.g. via mail -> `look@my.amazin.horse`

thanks for your report, hope we can figure this out! :)

**Comment by aelmahmoudy** [comment]
Attached is my public key that fails on upload,although it is the same  key that was just downloaded.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Valodim** [comment]
Attachments don't work on github, sorry. Please upload it somewhere or send to me directly

**Comment by Valodim** [comment]
I think I solved this: do you use the pgp.mit.edu keyserver for upload on the device where it fails?

That server recently got a new certificate, which we didn't have, and which is why the upload failed. Will be fixed in an upcoming release.

**Comment by aelmahmoudy** [comment]
Actually, I was trying to upload to the SKS server, which fails.
Uploading to MIT also fails.
Also I added keyring.debian.org (non secure) server, but uploading to it also fails

**Comment by aelmahmoudy** [comment]
The problem still persists with OpenKeyChain 4.5.

Uploading my key fails with both SKS and MIT key servers.

I even tried a fresh install of OpenKeyChain.  
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by aelmahmoudy** [comment]
Update: I tried on another phone running Android 6.0, and I didn't experience this issue.

This issue shows on Android 4.1.2 phone. 

On May 28, 2017 3:29:17 PM EET, Vincent Breitmoser <notifications@github.com> wrote:
>I think I solved this: do you use the pgp.mit.edu keyserver for upload
>on the device where it fails?
>
>That server recently got a new certificate, which we didn't have, and
>which is why the upload failed. Will be fixed in an upcoming release.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/2112#issuecomment-304514866

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dschuermann** [comment]
Please send your revoked public key to ``dominik@schuermann.eu``. We will need to investigate further.

**Comment by Valodim** [comment]
Can you down/upload *any* keys? This doesn't sound like it's an issue with the specific key, really.

**Comment by aelmahmoudy** [comment]
Yes. I have updated my new key (a7ef5761) and uploaded it using OpenKeychain without any problems.
Also I signed (ie. verified) a key and uploaded it.

-- 
‎أحمد المحمودي (Ahmed El-Mahmoudy)
 Digital design engineer
GPG KeyIDs: 4096R/A7EF5671 2048R/EDDDA1B7
GPG Fingerprints: 6e2ee4bb72e2f417d0666abf7b30b496a7ef5761
8206a19620847e6d0df8b176bc196a94eddda1b7

**Comment by Valodim** [comment]
I think dominik misread this. Anyways we don't have a lot to go by here, and it seems to special circumstances. maybe there is something broken (local certs?) in that particular key on that particular phone, or it has to do with the android version (4.1.2 is quite old at this point). either way I'm gonna say we'll leave this as is, but keep it in mind in case it pops up again for somebody else.

thanks for the thorough report and follow-up!

**Comment by agschaid** [comment]
Hi there,

I am having the exact same issue.

Here is what I did within the app (within 5 minutes):

- searched for and added my brothers key
- added  another identity to my own key
- tried to refresh my own key

Now with keyserver.ubuntu.com as default I am getting an error. According to the protocol the root error is ```Network error (CertificateException) for 'hkps://keyserver.ubuntu.com'. Check your internet connection.```
When I am trying to refresh my brothers key (I just had downloaded 5 minutes earlier) I am getting the same result.
Searching for keys fails without a generic error message ("there has been an error")
Testing the connection to the ubuntu keyserver in the settings fails (remember: it worked 5 minutes earlier)

When setting the default server to the (also preconfigured) pool.sks-keyservers.net, I can successfully test the connection. But when trying to refresh my key I am getting a "not found"  root message.

Same with pgp.mit.edu.

(remember: I can't verify that the last two worked before)

trying to (re)upload my keys to the ubuntu or sks keyserver fails with a generic error message. Uploading to the MIT keyserver fails after showing a 0% progress bar for about 30 seconds.

My phone is a Fairphone 2 with Android 7.1.2
My OpenKeychain version is 5.2 (obtained via F-Droid)

Please let me know if there is any other info you need (consider, that I am a half-educated pgp user at best).

**Comment by dschuermann** [comment]
@agschaid please open a new issue.
