### ISSUE TITLE
Locked out of my key after phone reset, even with backup key?

### ISSUE THREAD

**Issue by sidedtech** [open-keychain/open-keychain#2120]
Phone crashed, have a backup of key, passphrase, and the 'backup key' but the key just keeps asking for the backup phrase upon import. 

Without the backup phrase, is there ANY way to recover my key? Or even revoke it?

**Comment by dschuermann** [comment]
Nope, there is no way. That's why require you to re-enter the backup code after displaying it.

**Comment by Valodim** [comment]
I'm confused. Did you make a backup of your key but not wrote down the backup code? Or did you lose it?
