### ISSUE TITLE
Support 25519 keys

### ISSUE THREAD

**Issue by keks** [open-keychain/open-keychain#2123]
Support for 25519 keys has been added to GnuPG a while ago and people are busy adding it to the OpenPGP RFC. It would be really nice if we could use those keys with OpenKeychain.

## Expected Behavior
You can use ed25519/cv25519 keys just like any other key, covering generation, import/export, signing, encrypting and decrypting.

## Current Behavior
Currently it doesn't work.

**Comment by dschuermann** [comment]
@Valodim is working on this, see https://github.com/open-keychain/open-keychain/pull/2053

**Comment by keks** [comment]
Ohh, nice! I was searching for 25519 and nothing came up. Should have tried prepeding ed or curve! Thanks!
