### ISSUE TITLE
Empty directory generation

### ISSUE THREAD

**Issue by asnelt** [open-keychain/open-keychain#2125]
Every time OpenKeychain starts, it generates an empty directory called "OpenKeychain" in "/sdcard". It would be better if this directory would be generated only if OpenKeychain actually has to store something on external storage. At the very least, the location of this external directory should be configurable in "Settings".

## Environment

* Android Version: 7.1.2
* OpenKeychain Version: 4.4.1
* From Google Play or F-Droid?: F-Droid

**Comment by dschuermann** [comment]
fixed in https://github.com/open-keychain/open-keychain/commit/ecf9249247948c4fbe8f91a36320f0e0917cdab3
