### ISSUE TITLE
Search user using email instead of keyid

### ISSUE THREAD

**Issue by tigerwoods2k17** [open-keychain/open-keychain#2126]
When trying to import contact from K9, can we search the user using email instead of keyid?
I know keyid is passed here:
https://github.com/open-keychain/open-keychain/blob/6459deb6b8e772df1f9d24116f0ddc14f0df7108/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/remote/OpenPgpService.java#L503

When I try signatureResult.getPrimaryUserId(), I get a null value.

**Comment by Valodim** [comment]
Hum. For the record, we get the key id from the signature, and it's unambiguous (though not cryptographically unambiguous) on the keyservers. Not sure how searching by user id could be useful here. But I'm guessing that's why the issue was closed :)
