### ISSUE TITLE
Yubikey 4C Support

### ISSUE THREAD

**Issue by lrvick** [open-keychain/open-keychain#2129]
Yubikey 4C not recognized by OpenKeychain at all.

## Expected Behavior
Should be able to import keys and use transparently with k9mail and android-password-store like I can with my Yubikey 4 or Yubikey Neo.

## Current Behavior
Openkeychain pops up and asks for key when expected. Does not recognize that key is inserted or tapped when that key is a 4C

## Possible Solution
Perhaps the usb id of the 4C needs to be added to a whitelist somewhere?
Happy to patch/test myself if someone can point me in the right direction.

## Context
I currently must use both a Yubikey 4 and a Yubikey Neo day to day since the Neo is the only one I can use on my phone without carrying an adapter.

Support for the 4C will allow me to use a single yubikey for all devices and reduce complexity in my life :)

## Your Environment
* Android Version: 7.1.1 on Nexus 6P
* OpenKeychain Version: 4.4
* From Google Play or F-Droid?: F-Droid

**Comment by dschuermann** [comment]
Please make sure that CCID is enabled: https://www.yubico.com/support/knowledge-base/categories/articles/use-yubikey-openpgp/

**Comment by wiktor-k** [comment]
Yubikey 4 and 4C come with CCID enabled and as far as I know it's impossible to disable. If you read the link carefully it says that CCID need to be enabled only on old versions of Yubikey NEO:

> If you are using an older version of the YubiKey NEO, may also need to change the mode to enable CCID.

**Comment by dschuermann** [comment]
Thanks for the info. Do you have the same issue @wiktor-k ?

**Comment by dschuermann** [comment]
@wiktor-k I checked a Yubikey 4 Nano laying around here: It has only OTP and U2F enabled. 
I also checked the guide again, it is not that clear in https://www.yubico.com/support/knowledge-base/categories/articles/use-yubikey-openpgp/#configure item 4 in the enumeration:
> Continue with the following instructions for all other YubiKeys.Tip: You can also enable CCID mode using the Yubico Personalization Tool command, “ykpersonalize -m86”, to change modes for YubiKey 4 and YubiKey NEO devices sold after September 2014. For devices sold prior to September 2014, use “ykpersonalize -m82”. Reboot the device if you use the command line to change modes by removing the YubiKey from your computer, and then reinserting the device in the USB port.

**Comment by wiktor-k** [comment]
Nope, I don't have 4C. I was planning on buying one but if it's not working then I'd rather wait and use the adapter.

> change modes for YubiKey 4 and YubiKey NEO devices

So it is possible to disable CCID. I don't know why anyone would disable it except for testing but it's a good idea to check. For the record Yubikey 4 through USB A to C adapter works seamlessly. I'll buy 4C in a near future and report here if it works.

**Comment by dschuermann** [comment]
@wiktor-k Great to hear that Yubikey 4 works for you. Did you generate the on your yubikey 4 using OpenKeychain? Did this not happen to you: https://github.com/open-keychain/open-keychain/issues/2069 ?

**Comment by wiktor-k** [comment]
Nope the key was imported but I'll be receiving a new batch soon so I can test key generation. I'll reproduce #2069 and report on that ticket.

**Comment by dschuermann** [comment]
@wiktor-k great, thanks!

**Comment by wiktor-k** [comment]
Oh, just for posterity but RSA keys generated on these Yubikeys [can be unsafe](https://keychest.net/roca). Only [Yubikeys 4 issued after June 6th](https://www.yubico.com/2017/10/infineon-rsa-key-generation-issue/) are safe for generating RSA keys in hardware.

**Comment by dschuermann** [comment]
@wiktor-k yup, I know, thanks.

**Comment by dschuermann** [comment]
Closing this issue for now. @lrvick Please open a new one if you made sure CCID is enabled and it is still not working.

**Comment by dschuermann** [comment]
We got a batch of new Yubikey 4, 4 Nano, 4C, 4C Nano from Yubico for testing and all of them work with the current master branch. This is now also written down in our wiki at https://github.com/open-keychain/open-keychain/wiki/Security-Tokens

**Comment by wiktor-k** [comment]
Good to know. I just received 4C and it doesn't work with the Play Store version (I tested key generation). I'm looking forward to the new version. Thanks!

**Comment by dzervas** [comment]
I have a Nexus 5X (bullhead) and I'm thinking about buying a 4C. The phone though does not have OTG support (although it has USB-C port). Will it work?

**Comment by dschuermann** [comment]
@dzervas yes with the next OpenKeychain release.

**Comment by dzervas** [comment]
Just a note: YubiCo reports that there's no OpenPGP support for android devices via USB (A or C) [here](https://www.yubico.com/support/knowledge-base/categories/articles/can-yubikey-4c-plugged-directly-android-phones-tablets-usb-c-ports/)

**Comment by dschuermann** [comment]
@dzervas thanks for the link. We are in contact with them and will report this.

**Comment by dschuermann** [comment]
We just released OpenKeychain 4.8. It supports all YubiKey 4 models officially as we tested all of them and made sure they work.

**Comment by jrtapsell** [comment]
Can you confirm the process to add an already generated key on a 4C, I'm not seeing it in the list on my Pixel (android 8.1).

**Comment by dschuermann** [comment]
Which list? Can you make a Screenshot which step you mean?

**Comment by jrtapsell** [comment]
I have found the steps to reproduce:

- Set Yubikey Authenticator as the default app for the Yubikey being inserted.
- Trying to import the key fails

Steps to reset back to working:

- Open the app details page
- Clear the default associations with the button at the bottom

**Comment by dschuermann** [comment]
@jrtapsell That is Android's behavior we cannot influence. Only the selected app gets the permission to access the USB device. So never set one as default! I added an FAQ entry here: https://github.com/open-keychain/open-keychain/wiki/Security-Tokens#how-to-use-two-different-apps-with-a-usb-security-token-yubico-authenticator-and-openkeychain

**Comment by Valodim** [comment]
I wonder if we can enumerate usb devices at least, so we can detect a connected token and give the user feedback that it is in use by another app.

**Comment by jrtapsell** [comment]
From what I can see this may be possible (although maybe have a USB button, so NFC users don't have to go through a permission prompt).

> Your application can discover USB devices by either using an intent filter to be notified when the user connects a device or by enumerating USB devices that are already connected. Using an intent filter is useful if you want to be able to have your application automatically detect a desired device. Enumerating connected USB devices is useful if you want to get a list of all connected devices or if your application did not filter for an intent.

https://developer.android.com/guide/topics/connectivity/usb/host.html#working-d

**Comment by Valodim** [comment]
Yeah this can definitely work. We should add that, besides solving this problem it can make our handling more reliable in those cases where the broadcast doesn't get through.

**Comment by dschuermann** [comment]
@Valodim @jrtapsell Can you please open a new issue.

**Comment by lrvick** [comment]
@dschuermann This issue is still present for me. Tested today with a new yubikey 4c and new phone. (Was stuck in an RMA process, sorry for huge delay on following up).

Got to test everything with my yubikey 4c again today. Importing from it worked just fine, but decryption via Android Password Store intents does not work at all. CCID mode is enabled and a full gpg keychain is on the yubikey and works as expected on other devices.

I get the "tap key" prompt and an "enter pin" prompt. I enter my pin and insert the key and nothing happens.

It is worth noting I used "ykman openpgp touch enc fix" which means I always have to touch my key in addition to providing a pin. It never starts blinking to request a touch as it does on a desktop during the attempted decryption flows.

**Comment by dschuermann** [comment]
@Valodim @jrtapsell I created a new issue: https://github.com/open-keychain/open-keychain/issues/2244

@lrvick Can you try without the touch feature and open a new issue where you describe your configuration in detail, such as OpenPGP key config with master/subkeys, Android version, device etc? Also please try without the touch feature enabled and describe this. I will keep this issue closed as Yubikey 4Cs generally work in our tests.

**Comment by lrvick** [comment]
@dschuermann The touch flags can not be turned off once enabled without a factory reset of the key to prevent malware from bypassing it.

I have 3 4096 subkeys installed the (S)ign (A)uthenticate and (E)ncrypt slots respective on this key.

Master key with (C)ertify permission is offline.

I am able to reproduce this issue on:
* Nexus 6P
** Android 8.0.0 (Google stock)
** Open Keychain 4.8.1 (Google Play)
** Android Password Store 1.2.0.73 (Google Play)
* Pixel XL
** Android 8.1.0 (Copperhead OS)
** Open Keychain 4.8 (F-Droid)
** Password Store 1.2.0.73 (F-Droid)
