### ISSUE TITLE
Unable to import new PGP or Decrypt PGP messages with clipboard

### ISSUE THREAD

**Issue by 2throwAway26** [open-keychain/open-keychain#2132]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version: 
* OpenKeychain Version: 
* From Google Play or F-Droid?:

**Comment by Valodim** [comment]
sorry, this is litterally no information to go on. please write some details about your problem, what exactly you did, what you expected, what happened instead, etc.
