### ISSUE TITLE
Support for the Ledger Nano S (requires T=0 protocol)

### ISSUE THREAD

**Issue by nyanloutre** [open-keychain/open-keychain#2135]
The Ledger Nano S is a cryptocurrency wallet that also implement the OpenPGP smart card protocol.

Web page : https://www.ledgerwallet.com/products/12-ledger-nano-s

Some details about the implementation : https://github.com/LedgerHQ/blue-app-openpgp-card

## Expected Behavior

Using the Ledger with Open-Keychain should just work (like e.g. with a Yubikey).
## Current Behavior

Nothing happens when I plug it in.

## Your Environment

* Android Version: 7.1.2
* OpenKeychain Version: 4.4.1
* From Google Play or F-Droid?: F-Droid

**Comment by nyanloutre** [comment]
If I understand correctly it would work with this line in the USB filter ?

<usb-device class="11" vendor-id="11415" product-id="1"/>

**Comment by Valodim** [comment]
ping @nmikhailov

**Comment by nmikhailov** [comment]
Yes, you can try adding such entry to filter and testing it. I also have nano s, so I might also try it on weekend if I will have time.

**Comment by nyanloutre** [comment]
I tried to add the device in the filter. It is detected but throw an error "T=0 protocol is not supported"

**Comment by nyanloutre** [comment]
Any update on this issue ? @nmikhailov

**Comment by nmikhailov** [comment]
T=0 is indeed not supported. Nothing is stopping us from supporting it though.

**Comment by nyanloutre** [comment]
That would be awesome

**Comment by Valodim** [comment]
I'm confused. Are we doing T=1 at the moment?

**Comment by nmikhailov** [comment]
Yes, see https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/securitytoken/usb/T1ShortApduProtocol.java

**Comment by nyanloutre** [comment]
Is there any improvements on this issue ?

If I wanted to try to implement it, the basic principle would be to create a new class T0TpduProtocol.java that implement CcidTransportProtocol ?

**Comment by dschuermann** [comment]
I just asked Ledger for a test device. Due to high demand they currently can not provide a hardware sample for us.

**Comment by gusarov** [comment]
Sorry guys, can you point me to some documentation or to some details where I can understand how hardware wallet communicates with chrome app? I literally mean protocol details, both for hardware wallet developers and for client software, to make it interchangeable with other wallets

**Comment by chozian** [comment]
+1 for implementing support for this. This would add a lot of value to the Ledger Nano S in my opinion.

**Comment by Valodim** [comment]
We don't have a test device, and the Ledger folks didn't want to provide one. I don't particularly feel like spending 100€ on a Ledger Nano S to improve its value in my free time, so this will be on the back burner for now. Sorry :)

**Comment by Valodim** [comment]
We received Ledger Nano S for testing from a kind soul. Sadly, the ledger app isn't actually in their store for now after a recent firmware update (see https://github.com/LedgerHQ/blue-app-openpgp-card/issues/23). I'll look into this when it's available again.

**Comment by chozian** [comment]
The OpenPGP app is now available in Ledger Manager for the 1.4.2 firmware. Thanks!

**Comment by Valodim** [comment]
Welp, that was easier than expected. A trivial T=0 protocol based on short APDUs just worked :)

**Comment by pjz** [comment]
This is broken - see my report #2604
