### ISSUE TITLE
[feature] Full support for ECC

### ISSUE THREAD

**Issue by NeverMine17** [open-keychain/open-keychain#2139]
It would be great if you could add that!
More text in here soon...

**Comment by dschuermann** [comment]
Please be more clear in what you want, we already support NIST and SECG curves

**Comment by NeverMine17** [comment]
@dschuermann Yep, sorry, my bad. I'm talking about Curve25519.
Will you add support it?

**Comment by dschuermann** [comment]
duplicate of https://github.com/open-keychain/open-keychain/issues/1627
