### ISSUE TITLE
Add andOTP openkeychain supported app

### ISSUE THREAD

**Issue by chikenchik** [open-keychain/open-keychain#2140]
This is a fork of the OTP Authenticator app. It's open sourced, encryption (openkeychain) and lock screen supported awesome app.

[https://github.com/flocke/andOTP](url)

Expected Behavior

You may add this app to [https://www.openkeychain.org/apps/](url)

**Comment by dschuermann** [comment]
Wow nice app.I added it to the list. I will probably switch myself to this, my current OTP app does not allow backups.

**Comment by Avamander** [comment]
@dschuermann For some reason andOTP is not currently listed under the apps subsection. Could it be added (back)?
