### ISSUE TITLE
App crashes while moving subkeys onto a NFC Security Token

### ISSUE THREAD

**Issue by maxmagorsch** [open-keychain/open-keychain#2147]
Moving subkeys onto the Fidesmo Card as suggested in [#1838](https://github.com/open-keychain/open-keychain/issues/1838) results in a crash. Afterwards the subkeys are detected on the NFC Security Token, but entering the passphrase results in a error now: "Wrong PIN"

Creating a new key on the NFC Security Token instead works indeed without any problems. 

## Expected Behavior

The app shouldn't crash. 

## Current Behavior

While moving the subkeys the app crashes. Afterwards the keys can't be used correctly anymore

## Steps to Reproduce (for bugs)

1. Import an existing key (2048 bit RSA keys due to the limitation of the Fidesmo Card: [#1845](https://github.com/open-keychain/open-keychain/issues/1845))
2. Open Key view
3. Go to Menu
4. Go to Advanced
5. Go to the Subkeys tab
6. Press Edit
7. Press on the Subkey
8. Press Move Subkey to Security Token
9. Press Save

## Context

It's not possible to use a NFC Security Token with an existing key this way. 

## Your Environment

* Android Version: 7.1.2
* OpenKeychain Version: 4.5 from F-Droid

**Comment by navgib** [comment]
Same problem.
After moving, card work with default pin ykneo-openpgp (123456). But how to change it?
Also impossible to move a subkey if the primary key is detached.

**Comment by cegg1** [comment]
@navgib you can change the PIN of the PGP applet on the Yubikey Neo or the Fidesmo Card at any time using the Sigilance app. It can be downloaded from Play Store (com.sigilance.CardEdit).

**Comment by Valodim** [comment]
This feature was always half-baked, I disabled it for now #2160 

Since it was mentioned here, there is now a way to change PIN with #2157. It's a little hidden (overflow menu in security token activity) because it was not the main focus of the PR and I didn't spend a lot of time on it, but I thought I'd add it while I was at it.
