### ISSUE TITLE
UI language selection

### ISSUE THREAD

**Issue by sbriskin** [open-keychain/open-keychain#215]
Just a small future request:
For people who prefer en_US as a global system locale but want to use this app in native language need an option for manual in-app language selection.

**Comment by dschuermann** [comment]
https://gitlab.com/fdroid/fdroidclient/commit/de3e34060c6dca60a807d3e2d6ef954b5626444f

**Comment by eighthave** [comment]
Also, I think that a manual language picker should not include country variants.  Once you get a fair amount of translations, the language chooser list becomes epicly long and daunting to navigate.  For our language choosers, we present one choice per language.

**Comment by dschuermann** [comment]
@eighthave thanks, you are right.

**Comment by Diapolo** [comment]
I second that request, reasons:

1. Makes it easier to see context when translating via Transifex.
2. Ensures I don't have to see unprofessional parts of german translation that sneaked in, because I took a translation break ^^.

**Comment by revi** [comment]
I second this too. I do the localization stuff but I (ironically) prefers English versions.

**Comment by dschuermann** [comment]
Just a note: This lib looks interesting: https://github.com/delight-im/Android-Languages

**Comment by eighthave** [comment]
I went through that library and merged the useful bits into our Languages.java that is slowly becoming a library.  You can find the latest version here:

https://github.com/zom/Zom-Android/blob/master/awesomeAppCore/src/main/java/info/guardianproject/util/Languages.java

**Comment by dschuermann** [comment]
@eighthave awesome

**Comment by eighthave** [comment]
Now that Android as of 6.0 provides real language preferences, with a list of prioritized languages, I think this kind of language hack is no longer needed.  In F-Droid, we've disabled our language chooser on all Android versions that have the real language preferences.

**Comment by dschuermann** [comment]
@eighthave Yup, I think this issue is obsolete now.
