### ISSUE TITLE
Please support adding comment field in user ID

### ISSUE THREAD

**Issue by aelmahmoudy** [open-keychain/open-keychain#2151]
When adding user ID to own key, one is only able to add a name and an email address, although PGP also supporta a comment fielx for user IDs. Please support setting the comment field for user IDs. 

OpenKeychain version: 4.5

**Comment by NeverMine17** [comment]
Please close #2501

**Comment by Valodim** [comment]
Comments are almost universally a misfeature, see dkg's [blogpost](https://debian-administration.org/users/dkg/weblog/97) on the matter. We won't support it in OpenKeychain, sorry.
