### ISSUE TITLE
[Question] Why support for elgamal algorithm is dropped?

### ISSUE THREAD

**Issue by aurora-potter** [open-keychain/open-keychain#2152]

**Comment by Valodim** [comment]
We still support ElGamal keys if they are imported, we just don't support generating them. Do you have a special use case for them?

**Comment by aurora-potter** [comment]
No. I just feel you're limiting users to less algorithms to make the big guys feel better.

**Comment by aurora-potter** [comment]
Add, not cut.

**Comment by dschuermann** [comment]
``to make the big guys feel better``
I don't understand what you are talking about.

**Comment by aurora-potter** [comment]
@Valodim
Yes, it's correct.
