### ISSUE TITLE
Cannot enter PIN with letters for Yubikey

### ISSUE THREAD

**Issue by vizv** [open-keychain/open-keychain#2155]
Cannot enter PIN with letters for Yubikey.

## Expected Behavior
When prompt for entering a PIN to unlock smartcard, letter keyboard should appear.

## Current Behavior
Only numeric keyboard appears, cannot enter letters.

## Possible Solution
Change to letter keyboard when prompt a PIN.

## Steps to Reproduce (for bugs)
1. Set Yubikey PINs with letters (use `--edit-card` from GnuPG 2 on computers);
2. Insert Yubikey to Android Phone with OTG adapter to import the keys;
3. Draft a message, encrypt with the Yubikey;
4. When prompt for a PIN, cannot enter letters to unlock.

## Context

According to OpenPGP card spec, "Length of PIN between 6 and 254 characters; not restricted to numbers."
#1393 states "(for the record) even though they are called "pins", technically any password can be used. we will stick to numeric pins though", but it should support letters.

## Your Environment

* Android Version: 6.0.1
* OpenKeychain Version: 4.5
* From Google Play or F-Droid?: F-Droid

**Comment by dschuermann** [comment]
You can enable the numeric keyboard by pressing the small button labeled "abc" on the right of the PIN input.
