### ISSUE TITLE
No longer encrypting to the singing key

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#2158]
## Expected Behavior
If you encrypt+sign in OpenKeychain it should also encrypt to signing key.

## Current Behavior
No longer working

## Steps to Reproduce (for bugs)
1. encrypt to someone + sign to your own key directly in OpenKeychain
2. try to decrypt -> fails

## Your Environment

* Android Version: 7.1
* OpenKeychain Version: 4.6
* From Google Play or F-Droid?: Play

**Comment by Valodim** [comment]
Fixed in 4a4e325bca629162377810dd3ab0202b8d4f9b40
