### ISSUE TITLE
Copy And pasting keys issue

### ISSUE THREAD

**Issue by digitalmafiaboss** [open-keychain/open-keychain#2161]
I try and copy&paste a pgp key and it never reads the paste from Android. Is there a specific text editor I could use and what exact format does a pgp key and a pgp msg look exactly like?

**Comment by digitalmafiaboss** [comment]
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBFlySQYBEAC0/2Ftw1sYemzPOqp4gNgsvNlZhkiWjzRJyxMAwNg11itwThCL
aGfaZ3lgKQ+jo5TbughuLcbHHvk9pFa9nkt49i/pJE9CQy8StoU4CCRTDrNYi1Ml
f7biwLP5XqkWf3SYIYFA4ZNqMVvevfPjtEhoq/QTPZ88jdL0phyh9pLIxs5SEpyI
FXJGEWzEEQGtMKVdmHhh2i0QiAHwP6laaR+qLPy5E1BxAz5SSrY268f3W2KwAKvY
uT5e//q/Iiwdp59IME31bP1R50/Gp2hNAaDkPxj47JSYjEaIwptNsLWHtgDaiqSn
Fbsn4Vyyd6TCte1MFoxmhaLPuU1km2TbUlMnCaSmNZWgmWeHfZbIlHtGrdOWdeDS
A6olFQTMCD2jL6wF0/vU5NrvQe18XzTbdKtgh7Db1ZT9Y844KvWGgpYLZsuB0OdF
qX7oboEfP3ncq0TQI5+IvZuLIHJaY+XpQIXhZH9TRpBH1OEsFggQV6fLLGCx7YFn
rLJbvdGubUm52b8fxOKxFfdIswnAk3ldNdJ5M29c+VDLoeIt/PUyEOIOnQuxOFWM
pCIwd2q4BuAcw4bCwqV+up3yVwTGuUSMcZyGI82dGijGc8Tt890lUivP2HcPSgl8
8zlkx6VPP2A1uX7KAIDHDARKMl6/1IzdXEHeWmufY6NgP4OmKiPUBtZqFQARAQAB
tDhVbmRlckdyb3VuZERydWdSb2FkIDxVbmRlckdyb3VuZERydWdSb2FkQHByb3Rv
bm1haWwuY29tPokCTgQTAQoAOBYhBFFd02eLHPrNg59w93/eEJCfN0uiBQJZckkG
AhsDBQsJCAcDBRUKCQgLBRYCAwEAAh4BAheAAAoJEH/eEJCfN0uisCoP/1K9DjgX
l5/ks4hqiCIcvLHDkVW21RHagx32QXPCm8WKYZacD+wp9J3jOHDqSr77IG/N1KOh
aaEI7tZwhwMZk2QfhonIittMt0zF0YARc/fGzGOc/E/TtSG9YlLpGF4clAZLnR11
PdizwYQT2gQcr8fn45ciNCjP7XguGLE62gClfDyEvyRBlqqFY07Wmuvb2Zt3Dfl+
WKDcPm4WPpjlPNmBq4XW6COs79q73h/chSQLC3KBsjEEtQeSvZg4kyyeOmH4SgBY
oylYHZ6SxLCOzPUAg+sYqARLKiG/cy+mCi82FH5DUm+KMv9clBSNjSaSSX0XJGT7
YwzzDP45Dac3pxXIXuVepKM/l1G8aaMXlqAMi6RbSd+Y/L+oGAtvnybidTYIq8pG
4jrSQMRV7wuRA20Os2BJtOCwLqxk6Pg8FyNn2cpOqodN2CnNpA9DE6n2NhwvESsx
mXbw0EqeDux9EQBGKg5FrO6TJ8Yz5uexmuIcRkwU25pd145GNrm/gR95vQjmfgKN
K/n2tmrgxzFr6EyYtvAUkqFjZAcu/gyFz1axqQ1UxIybvyHMkJApWLiFZURmiQAs
pB5kBSxeTpbyucMBNbWpK6PnpMAqjE1sowSVPqsLeeMK8GAe9174zCGhPKyGxUWo
IgDXvL6nCrUHbxH4jVPTzYWL2iGZ88cYdGjTuQINBFlySQYBEAD6tKqCbvLYs38+
CKxoZX55YHDaAJHZpIG7h4QsTE9rf7QPoVbF3fnCmCQuE6gJYebF7jyjq5CwzyWf
LsNLVGefecnROdWJgFaCptbbWBTYHewEFD54Iov+rObY1dt9LHqseeXySgMdc9//
zDSt2dCeJ7AjxqogcfhYuydVHk1oS3Jdc0+bbDXoq0tfdIF2i2lDLQOLO8gCDeu7
7kByk6at8efJYwGfvVWjzEZb8wLabuL8h7xzzzstaNCqKAb9sUzMreOhfzQyxJEL
Ysx459k/cLHvDx2grdwCpey0FZXRUkgX40YOAILHcDOcMAeNxMUbQNHiBbqIrSn8
3mTujKOZxrpn4pdSha2wv/VEktzi0HRsK6JjxujKYWIemlVK5U8cMJ9Vc5cVgfsU
8JpIvPxY1fzuThZfhISmZ36rEwIV4+YMI2M+p5obrZvqNlGs+wiAG+XrFNXRsM7l
HXiVcwPlMtHpjmIDxyTuVTmYT1SWsHQB0DvCpKUAe+qI47v7CttPw5z3feYaUO0Z
ZPFv8fVycR30u5tPZKYZGl8sVwZbWQSvdO1pO57nEGyXFKSg0hEsKsc4ZOAXH7AG
F4BdKtjHNRTSz9I9XHN6n6t39DxfUP6RCamiBt6Wj/nRFHjO4wbKn5r5YmPlvVNy
W45ZIMyRXON5JoLCIR7iPsUHVgxT7wARAQABiQI2BBgBCgAgFiEEUV3TZ4sc+s2D
n3D3f94QkJ83S6IFAllySQYCGwwACgkQf94QkJ83S6IWDw/8DWG+uUPBz0JuAFZV
9e32bmKtVhNqHyzm3TQL4cBXpj3dt28NXIjsqzy0EoSKnOw4idCOvo2FFLMymaTq
QTwZ10km327JyUum4wb+8Z5/iI7WZiUqSCU2bb36dnmIIU5lMASLvpOOcKqIdmh6
lbvJ3KapFlrbpAZpdrj/rBtV+5clLUYLsYZOSn56nBL45REr1oaoSa0UI9T3YNJj
6dSTSoNXyCvnqooTaq2NrByvO/XQFRoq2YPlubAqncsVMYAZf6eABmGuLN0a7poC
0p8DKerdWqmE1i+BCjWtBxqu3D8mX0RLNRRvX8mgTYHJVNBx1uoWhnGcel8NxUKq
z9Ob/qLCCmIn1AUYoEJZw1PThxOi2u0WJS5a5yxSkt/gAyIpxA4rft6AJ+0XoAXY
7bMdhhXtoFLx3RVRg62MBkTb9Ef/uJqejfEqZHItxv+Bw5+Ku5w1YQKzn3w9sDLB
F7MdirpN5ILBDtbYNVxd4a5vENigZWwTe0s0UL534FvEHL9OBfZBfSu4zuQxFO93
puiU+LYs5fuNi42v3r8bxOvMgB/pSbt5eWZp8KC2fK3AJJqvD8LFPX9lSkRtbvYq
b471QB+K4UN+wwfnZewE608EB4BpfLkav0VtuqRK6SNnEKofNCjnAKZVMWLjnvK9
gbOz9m9N3dpVii0TnHljs3m88yE=
=vo0A
-----END PGP PUBLIC KEY BLOCK-----

That copies and pasted just like that into chrome but won't read on open key chain

**Comment by Valodim** [comment]
I copied this exact text to clipboard from my mobile browser, and it worked fine for me in openkeychain stable. So it must be something system-specific :\

We recently fixed an I/O issue that might be related (2d2dce754d4d6ca3be756036a9f01ed8089f416c). Please wait a short while for the next release, this problem might be fixed then. I'll ping you to try again when that happens.

**Comment by digitalmafiaboss** [comment]
-----BEGIN PGP MESSAGE----- Version: GnuPG v2 hQGMA0eNbi4HlKHCAQwAlwg1u/iL2/Fk5rKliZq8WeZJTI/wdD0luun7TWKTeUUG TBm2f9Gr99V4vSfjzmPV1yeizMsuImJxpmsZOZdVx0H1YlJgjrHVoNI6g4FmK11v tqGkIexK0xuHPA5DW2itXiAXV/B0t3PslFY719+TJHVfHOWAUp70KvqcAv3I7gsB b3fGNVGH4uQVSwgeSZZw8zjJXZJxvWJVD+TqXkFbPrJDGLvgr4FQhanyAHihmhOa i+gw9EAxguQO6IcQ3zu+FYJiBYTf+7Ao/5YgRhbDZS+Us7klw/k7rQjO721ODOI2 XMR8oPAuq2S6KKDtiiavwkKFuWv1/lqmMRBm3ehhrTzCt5l50/QjzzxNuwrwESsm Qv/HoRKHu5WlK+3VGyOupWc3woarPFocv86pQGGV88ac07oWV+OJLC7slWt6nXDM d8p37Jq+bX/2Vkh2IXLUvlzxKPxj8AZgSkUgUiCf8wR/qoC4cOXwXEd6CaZ3vVyi lLDNHotKQ7mM0j6KHYlu0lABIXNsYL1/qIyqY/flZMlXWUjp5vK1ndvGAO7sjLLx kQEIfdx+eUSui7dEDJ8Cz2aLNOIRvlrzLttm9RVsnD7OwyLcU/0nN1bUaXLsaJ12 Dg== =tliY -----END PGP MESSAGE----- 

When I copy it from Firefox it comes back like this

**Comment by Valodim** [comment]
The issue with broken whitespace in keys from the clipboard has been around for years, we've been putting that off for far too long. I made a PR that adds reformatting to clipborad handling, which should hopefully fix this issue. :)
