### ISSUE TITLE
Request: return the "time to live" setting

### ISSUE THREAD

**Issue by dutchgecko** [open-keychain/open-keychain#2173]
## Expected Behavior

I use OpenKeyChain exclusively with Password Store, a [pass](https://www.passwordstore.org/) client for android. Until v4.7 of OpenKeyChain I could configure the app to cache the password for a key until the screen was turned off, then erasing the key automatically. This fits my use case well since my passwords will only be decryptable while I am actively using my phone.

## Current Behavior

In version 4.7 the TTL option has been removed, and the used TTL seems to be very long (24 hours)? The cache can be erased manually by clicking a notification, but I'd rather this behaviour occurred automatically as it used to.

## Your Environment

* Android Version: 7.0
* OpenKeychain Version: 4.7
* From Google Play or F-Droid?: Play

If there is a reason for the feature being removed I'm sure I could accept that, it just appears that if a reason exists it hasn't been communicated.

**Comment by Valodim** [comment]
The password input dialog has a selection, where you can choose how long the password you are entering right there should be remembered. Does this cover your use case?

**Comment by dutchgecko** [comment]
I'm a fool :) Thanks!

**Comment by Adonai** [comment]
I'm a fool too! Thanks!
