### ISSUE TITLE
Connected identities is off, but shown in UI anyway

### ISSUE THREAD

**Issue by rugk** [open-keychain/open-keychain#2176]
## Expected Behavior

When the slider is off, the feature should be off.

## Current Behavior

The setting for "connected identities" in advanced/experimental settings is off, but UI item is shown and can be used.

## Steps to Reproduce (for bugs)

1. Go to the settings and disable/enable that button.

## Context

Previously I always had it disabled, discovered the functionality in the UI now and tested it (see https://github.com/open-keychain/open-keychain/issues/2175). Then I noticed that the slider in the settings for exactly that thing is actually set to "off". Enabled it and I did not see any difference. Disabled it again – no difference.

## Your Environment

* Android Version: LineageOS 14/Android 7.1.2
* OpenKeychain Version: 4.7
* From Google Play or F-Droid?: F-Droid

**Comment by Valodim** [comment]
Thanks for your report, fixed in 4536645170cfd50e2d1e40338ab4fb42cbda2fb5 :+1:

Just to be clear, the ids themselves didn't show up, only the button to add one, right?

**Comment by rugk** [comment]
That's what showed up:
![screen](https://user-images.githubusercontent.com/11966684/31053126-6f3e9ffa-a696-11e7-9d89-576911ad2a43.png)

**Comment by Valodim** [comment]
ok, that's what I thought. geez that is huge in German. :|
