### ISSUE TITLE
Can this library can restore key and certificate data after re-install application on Android?

### ISSUE THREAD

**Issue by silverstar235** [open-keychain/open-keychain#2191]
## Current Behavior
Hi, I am developing an app to encrypt/decrypt file with public/private key. The problem is in case the user remove app and re-install it, i must create new keypair and this can not restore old keypair for derypt the file before. Have this project can save key after remove application?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version: 5.1

**Comment by dschuermann** [comment]
The user can use the backup/restore option inside OpenKeychain. Or are you referring to an API for this?

**Comment by silverstar235** [comment]
Yes, i think if it be Okay, it should backup/restore automatically when i generated keypair and it can restore this keypair after user uninstall and re-install app.

**Comment by dschuermann** [comment]
We currently do not do automatic backups into Google Drive or anything similar.

**Comment by silverstar235** [comment]
And keychain in Android can not backup key and restore it after re-install it like the IOS can be?

**Comment by dschuermann** [comment]
I don't think it is a good idea to leave the secret on the device even if OpenKeychain is deinstalled. We also don't use Android's Keystore API because of https://doridori.github.io/android-security-the-forgetful-keystore/

**Comment by silverstar235** [comment]
Because i have read about Keychain on android: https://developer.android.com/reference/android/security/KeyChain.html
This said that KeyChain can store key data. My application is encrypt/decrypt file so if user remove app, and re-install, they can not decrypt the old files

**Comment by dschuermann** [comment]
Keychain API can be used for X.509, but we do OpenPGP.
