### ISSUE TITLE
I can not build project with Openpgp-api-lib

### ISSUE THREAD

**Issue by silverstar235** [open-keychain/open-keychain#2196]
## Expected Behavior
Hi, i can not run Open Keychain master because the configuration for openpgp-api-lib, i have move this project to Open-keychain-master but it still have error related with openpgp-api-lib project compile. Can you help me about that?
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version: 
* OpenKeychain Version: 
* From Google Play or F-Droid?:

**Comment by dschuermann** [comment]
Follow item 2 in https://github.com/open-keychain/open-keychain#build-with-gradle

**Comment by silverstar235** [comment]
This's mean that we must build with gradle and get all sub project, then we can develop with android studio?

**Comment by dschuermann** [comment]
yep
