### ISSUE TITLE
How to backup/restore keypair only with a password by pgp

### ISSUE THREAD

**Issue by silverstar235** [open-keychain/open-keychain#2198]
## Expected Behavior
Hello, I have build your source, That's very use full but now i only want to create a RSA keypair, and store it to pgp file with a string password as open-keychain. Which class i can view for do this? Thank you!
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version: 
* OpenKeychain Version: 
* From Google Play or F-Droid?:

**Comment by dschuermann** [comment]
Please use our mailinglist for questions
