### ISSUE TITLE
Edit/Remove/Update GitHub, Twitter, WebSite — Identities

### ISSUE THREAD

**Issue by OKCPMT** [open-keychain/open-keychain#2202]
## Expected Behavior

Edit/**Remove** custom identities. Or update/upgrade.

## Current Behavior

Nothing.

## Possible Solution

Upgrade code/feature.

## Steps to Reproduce (for bugs)

1. (Identities) Link to account
2. Proof account
3. Change username account
4. Proof account again
5. Have old/double version identity
6. Can't remove old/double version identity

## Context

I need it feature.

## Your Environment

* Android Version: 4.4.2
* OpenKeychain Version: 4.8-beta1 (48000)
* From Google Play or F-Droid?: Google Play

**Comment by wiktor-k** [comment]
I think this can be closed @Valodim as it is no longer supported.

**Comment by Valodim** [comment]
Yep
