### ISSUE TITLE
Bad performance on Android 8/Copperhead OS

### ISSUE THREAD

**Issue by craftyguy** [open-keychain/open-keychain#2204]
## Expected Behavior
Unlock key and/or decrypting text (k-9 email) should be much faster. This was the case on this same device & with the same key in the past. Unfortunately I don't know which version of openkeychain this issue started..

## Current Behavior
Unlocking a key takes several minutes (either on import, or if the key has been 'cleared' in the notification). Decrypting text emails now takes several seconds.

## Possible Solution
Is there a way to profile performance? I will try to install older versions of openkeychain to bisect the version where this started to occur.

## Steps to Reproduce (for bugs)
1. Install openkeychain
2. Import key from file
3. Enter passphrase to unlock key
4. App sits at "unlocking..." screen for several minutes before it succeeds. Note: this also occurs when unlocking the key after clearing the passphrase from the openkeychain notification.

## Your Environment
* Android Version: 8.0
* OpenKeychain Version: 4.7
* From Google Play or F-Droid?: F-Droid
* Device: Nexus 5x

**Comment by dschuermann** [comment]
Interesting, thanks for the report. I suspect this has to do with Android 8, we will look into it.

**Comment by ucwhatic** [comment]
sometimes it will just freeze until you manual force close or reboot on Android 8 as well. At least on Copperhead OS (no google services framework)

**Comment by craftyguy** [comment]
I'm also on copperheados. those folks have confirmed (in IRC) that there are no problems with openkeychain on COS.

I built openkeychain all the way back to 4.0 (trying to bisect), and experienced this issue the whole way. I definitely don't remember this being an issue as far back in time as that release. I highly suspect a recent change in copperheados after @ucwhatic's comment, but I have no idea how to prove/disprove this theory at this point, given that this device is my 'daily driver' and I cannot afford to be building custom ROMs to test.

**Comment by hagau** [comment]
I can not reproduce this with with OpenKeychain master on a Nexus 5X running CopperheadOS master.
Decrypting mail in K9 (this was tested with a key on a external token) and unlocking the key is fast (both for token keys and internal ones).

**Comment by craftyguy** [comment]
After a series of reboots, this issue seems to have magically resolved itself. I still have no idea what caused it, and no confidence that it won't come back (because I don't know what caused it), but I'll close this issue for now until I get more info to help figure out what went wrong.
