### ISSUE TITLE
Unable to decrypt messages from Perl Crypt::OpenPGP

### ISSUE THREAD

**Issue by jschwartzentruber** [open-keychain/open-keychain#2215]
## Expected Behavior
When I receive PGP encrypted emails generated by Bugzilla (Crypt::OpenPGP) in K9 mail, OpenKeychain should decrypt them normally.

## Current Behavior
The message fails to decrypt without even prompting me for my password. The message I get is:

    Error decrypting email
    No encrypted data with known secret key found in stream!

No extra info is logged to logcat with debugging enabled.

I'm able to decrypt these emails without warning in enigmail, and I'm able to decrypt other emails in K9 Mail.

## Possible Solution
My only guess is from the integrity protection warning from gpg. Decrypting the PGP block in a shell I get:

    gpg: WARNING: message was not integrity protected

## Steps to Reproduce (for bugs)
1. Put your public key in my.key
2. Save the following perl script locally and run it. (extracted from [bugzilla source](https://github.com/bugzilla/extensions-SecureMail/blob/master/Extension.pm))

       use Crypt::OpenPGP::Armour;
       use Crypt::OpenPGP::KeyRing;
       use Crypt::OpenPGP;
       use Email::MIME;
       
       sub _pgp_encrypt {
           my ($pgp, $text) = @_;
       
           my $encrypted = $pgp->encrypt(Data       => $text,
                                         Recipients => "@",
                                         Cipher     => 'CAST5',
                                         Armour     => 1);
           if (!defined $encrypted) {
               return 'Error during Encryption: ' . $pgp->errstr;
           }
           return $encrypted;
       }
       
       sub _make_secure {
           my ($email, $key) = @_;
       
           my $pubring = new Crypt::OpenPGP::KeyRing(Data => $key);
           my $pgp = new Crypt::OpenPGP(PubRing => $pubring);
       
           $email->body_set(_pgp_encrypt($pgp, $email->body));
       }
       
       my $email = Email::MIME->create(
           attributes => {
               content_type => 'text/plain',
               charset      => 'UTF-8',
               encoding     => 'quoted-printable',
           },
           body_str => "hello world"
       );
       
       open(my $fh, "<", "my.pub")
        or die "cannot open < my.pub: $!";
       my $public_key;
       { local $/ = undef; $public_key = <$fh>; }
       close($fh) or die "$!\n";
       Crypt::OpenPGP::Armour->unarmour($public_key) or die "failed to read valid key";
       
       _make_secure($email, $public_key);
       
       $email->walk_parts(sub {
           my ($part) = @_;
           print $part->body;
       });

3. Paste the output into a plaintext email and decrypt it with K9/OpenKeychain

## Your Environment

* Android Version: 7.1.2 LineageOS
* K-9 Mail Version: 5.303
* OpenKeychain Version: 4.8-beta1
* From Google Play or F-Droid?: Google Play

**Comment by jschwartzentruber** [comment]
btw I had trouble installing the the perl dependencies myself. If it helps I can send an example email too.

**Comment by Valodim** [comment]
Hum. So I don't have an overview of the perl toolchain, Crypt::OpenPGP is not debian-packaged, and I couldn't get cpan to install the package without sudo. Could you paste a test mesage like that? Encrypt to 0xdeadfa11 please

**Comment by jschwartzentruber** [comment]
The cpan install is broken. I had to follow some bug reports to get it installed. It also didn't like your key, I had to trim the expired subkey to get it to work.

```
-----BEGIN PGP MESSAGE-----
Version: Crypt::OpenPGP 1.12

hQIMA3vRgyDerfoRAQ/+IIC1N/DTqwOuYR9REZZ1d0KzH7wrwLM9H/IFB03iMy3g
aUufsmG+dGRDsBUEM/2qE6CmAu1ch7W/uBKEoLTu5enzsJeFMHQExoCOtB5FvLlr
aey/Y0HcRo5YdsWLLzJBdI7PZoFRS4vFWQGdpYZAf16U/08MB3VY1I/BNTPOGTYy
5lMOGMRUhRRw4sWXCCApk6wkrsyt1NZpou10KexpakIF0f7U0JgqkXSaD70dHmYL
fBPpR1YXo5Tu9b54OnZpNgSF4OrSl62joa7ud1/Re3zI1LAghau9uGxTyrxFG5+i
VbOClZ99kP+Bt3mWiAaQiLD36M/Ryn3mqiuxvEN5ZCkaaX7dNalyAGPPWG06fbe6
USaAeT1p+Rfe66beZ4Q+0Mbx4HCNxEox3rhXY8fNEZew4eXQhKRUmjrpS7mF6KYe
G06v5SVtI99QfJG4wHeeHTiArrxha0mKA6XcBvwmIvkPwGm1Gyo6k8+62FbFtZhw
PV/ylSRTUuRy/0S1+10ru3fmOQzodv/cQSBReXkG9v2Ix3myn/rswJlcco/WPGQN
a8DvMz3UDO8/v2N3urq2YYKWd+UNfBcz5Ar7S/ru3x9MC6XIGAIXe5yWIaDSBKMx
llJVk7zlcFpKcCU55o+f8MUXhLTHtFL6ETjGZgwyQaRyTBTfpUhMBZwpRJFDEwak
IEIsWv0ODU5uPUTagED4jAaPYEkKJmLv/c03kVn4Jo4M
=7TeB
-----END PGP MESSAGE-----
```

**Comment by Valodim** [comment]
Ah, I think I have an idea what the issue is. Thanks for reporting, I will get back to you after I ran some more checks.

**Comment by Valodim** [comment]
Whoops, only now noticed I never wrote what the problem here was. This issue is that `Crypt::OpenPGP` doesn't take key flags into consideration, and encrypts to a key that is flagged for use in signatures only. That's a pretty horrible bug in that library, but also testament to the overly complex mess that is OpenPGP.

Either way, I believe we behave cryptographically correctly here by not accepting those messages.
