### ISSUE TITLE
unable to import key from Yubikey neo

### ISSUE THREAD

**Issue by cws-khuntly** [open-keychain/open-keychain#2238]
after presenting Yubikey neo for NFC key transfer, app finds no keys. keys do exist on key card and can be seen through gpg --card-edit on the desktop
## Expected Behavior

expected behavior: key should import from NFC device

## Current Behavior

no keys are found on the key

## Steps to Reproduce (for bugs)

1. add key to Yubikey neo 
2. ask app to add key from NFC
3. swipe key
4. no keys are found
## Your Environment

* Android Version: 8.0.0
* OpenKeychain Version: 4.8.1 (48002)
* From Google Play or F-Droid?: Google play

**Comment by Valodim** [comment]
"ask app to add key from nfc"? can you be more precise? what exactly did you do?

**Comment by cws-khuntly** [comment]
manage my keys -> click key with + on it -> select "use security token" -> slide Yubikey across the back until the NFC tone is heard. the following output is provided:

searching in key list...
searching at token url...
searching on keyservers...

keys not found!

**Comment by Valodim** [comment]
openkeychain can't get the key itself from the token, it can only bind to a key that is acquired from somewhere else. for this purpose, we check the token's url and public keyservers. import your public key, then try again.

**Comment by cws-khuntly** [comment]
I am able to generate a key via the application and save it to the Yubikey - that works just fine it appears

**Comment by Valodim** [comment]
the key only holds the private key material that is used for decryption and signing operations. it does not hold the metadata of the actual key (the part you share with others)

**Comment by cws-khuntly** [comment]
ok, I'll try that. should I just add the url to the pubkey on the mit keyservers to the card in the "url" field?

**Comment by Valodim** [comment]
if it's on the keyservers, the key should be found automatically

**Comment by vctls** [comment]
Sorry to unearth this issue, but I can't find much info on this kind of problems anywhere else.
I've put my keys on my YubiKey 5 NFC. I can see them with `gpg --card-edit`, in Kleopatra, and I can send and receive encrypted messages with Thunderbird no problem.
I've also set the public key URL.
When I add the YubiKey to OpenKeychain, it can see it and downloads the public key, and I can send encrypted and signed messages with K-9.
But it doesn't see the decryption key.

**Comment by pLum0** [comment]
@vctls I have the same strange issue, did you find a solution?

I successfully import the Key from the Yubikey to Openkeychain. The Key+ Subkeys are there, IDs are correct, no prolem reported.
Then using K-9, I can encrypt and sign, which Thunderbird + Enigmail can open. But mails from Thunderbird to K-9 won't work (No matching key for decryption found (or similar)). Same with manually encrypted text copied to Openkeychain. The Yubikey is not asked at all.
