### ISSUE TITLE
(Website) Oversec seems to be open source.

### ISSUE THREAD

**Issue by Luraktinus** [open-keychain/open-keychain#2248]
I visited the APPS section on the OpenKeychain website, and saw that Oversec is noted as NOT open source.

however, on the Oversec Website is a link to the source (https://github.com/oversecio/oversec_crypto)
which is under Gnu GPL3

please review and correct the information that you host.

Thanks for your work,
---Lue

**Comment by dschuermann** [comment]
The website says " Protocol and encryption related code is Open-Source, can be verified by 3rd parties. " Thus,  the full app is NOT open source.
