### ISSUE TITLE
Stop requiring dangerous permissions!

### ISSUE THREAD

**Issue by KOLANICH** [open-keychain/open-keychain#2259]
There is no legit need in requesting the following permissions:

https://github.com/open-keychain/open-keychain/blob/2619cb1db38f2b9c21a49e2c928cb48d4bc16c8a/OpenKeychain/src/main/AndroidManifest.xml#L29L37

The following must be moved into plugins, manually installed by a user if he needs this feature:

https://github.com/open-keychain/open-keychain/blob/2619cb1db38f2b9c21a49e2c928cb48d4bc16c8a/OpenKeychain/src/main/AndroidManifest.xml#L47L49

https://github.com/open-keychain/open-keychain/blob/2619cb1db38f2b9c21a49e2c928cb48d4bc16c8a/OpenKeychain/src/main/AndroidManifest.xml#L64L71

https://github.com/open-keychain/open-keychain/blob/2619cb1db38f2b9c21a49e2c928cb48d4bc16c8a/OpenKeychain/src/main/AndroidManifest.xml#L83L85
https://github.com/open-keychain/open-keychain/blob/2619cb1db38f2b9c21a49e2c928cb48d4bc16c8a/OpenKeychain/src/main/AndroidManifest.xml#L87L88

https://github.com/open-keychain/open-keychain/blob/2619cb1db38f2b9c21a49e2c928cb48d4bc16c8a/OpenKeychain/src/main/AndroidManifest.xml#L86

**Comment by dschuermann** [comment]
Since Android 6.0, permissions are requested during app runtime by showing a dialog. Thus, moving features into plugins to request more permissions makes no longer sense.

If you are on Android < 6, you should get a secure modern Android version.

**Comment by dschuermann** [comment]
An addendum: 
```

    <uses-feature
        android:name="android.hardware.microphone"
android:required="false" />
```
is not a permission. This means that we do NOT require a microphone.

**Comment by KOLANICH** [comment]
OK, but if it is not needed, why not to delete that line too?

**Comment by KOLANICH** [comment]
>Since Android 6.0, permissions are requested during app runtime by showing a dialog. Thus, moving features into plugins to request more permissions makes no longer sense.

Android 6.0 permission system is broken by design. For example a permission to access to wifi is not showed at all when an app is installed.

>If you are on Android < 6, you should get a secure modern Android version.

Who will pay for a new phone, where a one is going to get a non-backdoored phone without any biometric sensors after Google required all the manufacturers to have it and why the hell I have to change the phone in order to get a new Android (big thanks to chip manufacturers and samsung for unportable blobs!)?

**Comment by Valodim** [comment]
> OK, but if it is not needed, why not to delete that line too?

https://developer.android.com/guide/topics/manifest/uses-feature-element.html

**Comment by KOLANICH** [comment]
I have read that and I understand that it is only metadata. But why to restrict this app to the devices with a microphone?

**Comment by dschuermann** [comment]
You got that wrong again. It is the other way around, we ALLOW it on devices WITHOUT microphone.

**Comment by Valodim** [comment]
specific relevant part of the linked page is

> Note: By declaring a feature explicitly and including an android:required="false" attribute, you can effectively disable all filtering on Google Play for the specified feature.

I guess we could add a comment that these things are about gplay metadata only...

**Comment by KOLANICH** [comment]
Thank you for clarification about the features.

**Comment by dschuermann** [comment]
Added a comment here: https://github.com/open-keychain/open-keychain/commit/85a7c63d9bcfdf0652e0cab84aa0535a185e5802

**Comment by Valodim** [comment]
Ah right, dealing separately with the rest of the issue then:

> The following must be moved into plugins, manually installed by a user if he needs this feature

No :)

**Comment by KOLANICH** [comment]
I knowed that the devs would say that.
