### ISSUE TITLE
Forget (remove from memory) privkey password after a while

### ISSUE THREAD

**Issue by sjau** [open-keychain/open-keychain#2263]
Hi there

I'm using open-keychain together with the android password store app. It works all well. However one thing I haven't figured out yet is how to make it forget the gpg privkey password after a while.

Currently I boot my cellphone, open password store - I get prompted to enter the gpg password to unlock the encrypted pass files.

Then, the privkey stays unlock until I reboot my phone.

I would wish to have expire the privkey password after a while from memory and be prompted again to submit it.

## Expected Behavior
After a (definable) amount of time, the privkey password should be removed from memory so that the user is forced to re-enter it again.

## Current Behavior
Once the privkey is entered it can access encrypted files until next reboot.

## Your Environment
* Android Version: 7.1.2 (LineageOS)
* Device Model:  Google/Motorola Nexus 6
* OpenKeychain Version: 4.8.1 (48002)
* From Google Play or F-Droid?: Google Play

**Comment by Valodim** [comment]
You can 1) click the notification to clear the password, or 2) change the timeout in the very same dialog where you type in the password. Does that address your use case?

**Comment by sjau** [comment]
Ha, never noticed that option. Thx.
