### ISSUE TITLE
ECDH (encrpytion) subkey w/25519

### ISSUE THREAD

**Issue by J-J-Chiarella** [open-keychain/open-keychain#2266]
Are ECDH encryption subkeys with Curve 25519 usable? I know EdDSA support was added and that uses Curve25519 as well.

* Android Version: Marshmallow
* Device Model: BLU Life One X (2016)
* OpenKeychain Version: 4.8
* From Google Play or F-Droid?: Google Play
 
Key created via GnuPG 2.1.15 and exported unencrypted to test.

Error message is only "No valid keys."

Thank you for all the great work, of course.

**Comment by Valodim** [comment]
I looked at this a couple of times, and just two days ago finally figured out how to actually get it to work :) I just need to get it into a mergable state, but it shouldn't be too long until we support this.

**Comment by Valodim** [comment]
I have a working variant of this in a branch, but there is some amount of confusion about the spec. I asked for clarification on [gnupg-devel](https://lists.gnupg.org/pipermail/gnupg-devel/2018-February/033437.html), we'll include this feature as soon as that's cleared up.
