### ISSUE TITLE
Feature: Support for WKS/WKD key discovery

### ISSUE THREAD

**Issue by wiktor-k** [open-keychain/open-keychain#2270]
[Web Key Directory is a draft](https://datatracker.ietf.org/doc/draft-koch-openpgp-webkey-service/) for a new key discovery scheme (implemented e.g. in new gnupg). It is similar to HKP but instead of querying the keyserver it queries the domain from the UID's e-mail address. The difference is that WKS returns binary data and HKP ASCII-armored.

For example, when looking for key for `Joe.Doe@Example.ORG` the key would be fetched from `https://example.org/.well-known/openpgpkey/hu/iy9q119eutrkn8s1mk4r39qejnbu3n5q`.

Open Keychain could support this in several ways:
  * register as a handler for URLs containing `.well-known/openpgpkey/hu`,
  * when searching e-mails additionally query WKS,

Several services (like kernel.org) already have WKS support, for example Linus' key is at: https://kernel.org/.well-known/openpgpkey/hu/pf113mfnx1f3eb1yiwhsipa91xfc7o4x. Some third party services like posteo.de [support WKS too](https://posteo.de/.well-known/openpgpkey/). WKS is also [supported by Enigmail](https://www.gnupg.org/blog/20170803-web-key-in-enigmail.html).

More details here (in German): https://www.golem.de/news/web-key-service-openpgp-schluessel-ueber-https-verteilen-1609-123194.html

If this is in scope of Open Keychain I could work on a PR.

**Comment by Valodim** [comment]
WKD is definitely in scope for OpenKeychain, and looking up wkd entries when the user searches for an e-mail address makes sense. It's not particularly high on my own list of priorities, but if you make a nice PR we would probably merge it :+1:

That said, I'm not fully convinced WKD is the way to go for most encrypted mail use cases, and I have yet to see any actual user workflow considerations based on it.

**Comment by wiktor-k** [comment]
Thanks @Valodim for 👍.

I know there is certain [conflict of interests](https://autocrypt.org/) 😉 but I'm mostly interested in WKD as a quite simple *key* discovery mechanism, I didn't think of encrypted mail in particular.

I'll see what can I reuse from existing KeyserverClients...

**Comment by Valodim** [comment]
Don't worry about that. We know there are use cases that Autocrypt doesn't cover, and even then testing multiple approaches to see what sticks is a good thing! ;)

**Comment by bam80** [comment]
>If this is in scope of Open Keychain I could work on a PR.

@wiktor-k is the work on a PR going? Thanks

**Comment by wiktor-k** [comment]
Not at the moment sorry. I did a quick glance at the source and it's not as straightforward as I initially thought. I still want to work on it but no ETA.
