### ISSUE TITLE
Default delete action should be to delete

### ISSUE THREAD

**Issue by JohnMH** [open-keychain/open-keychain#2272]
Because the default action isn't to delete, I just accidentally revoked my key. With no confirmation after choosing the action. Awesome.

**Comment by dschuermann** [comment]
It pretty explicitly says that it revokes a key. More often we have the other way round: People delete their keys and then ask how to revoke them.

**Comment by JohnMH** [comment]
@dschuermann I didn't even see this prompt that supposedly "explicitly says that it revokes a key", I selected the delete option and bumped the confirmation button, immediately revoking my key.
