### ISSUE TITLE
FR: Adaptive icon

### ISSUE THREAD

**Issue by mueller-ma** [open-keychain/open-keychain#2273]
Api 26 introduced adaptive icons where background and foreground are two different images.
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html

**Comment by Valodim** [comment]
I guess it would be possible to change the existing icon into an adaptive one. Neither @dschuermann nor me are graphic designers though - if anyone wants to take a stab at it, that'd be great!

**Comment by c-e-p-x-u-o** [comment]
Really it's not a graphic designer. It's just a shape of the icon's background.

**Comment by Valodim** [comment]
Sounds good! Contributions welcome :)

**Comment by lokesh-krishna** [comment]
Could you please share the SVG sources? I'd like to take a shot at this.

**Comment by dschuermann** [comment]
https://github.com/open-keychain/open-keychain/blob/master/graphics/drawables/material-launcher/vector-src.svg

**Comment by lokesh-krishna** [comment]
@dschuermann could you take a look at #2324?
