### ISSUE TITLE
Android App reports CertificateException

### ISSUE THREAD

**Issue by geomandolyn** [open-keychain/open-keychain#2277]
Android App reports CertificateException.
## Expected Behavior

Trying to sync my keys.
## Current Behavior

One Android device works fine, another fails with CertificateException.
## Steps to Reproduce (for bugs)

1.  „Alle Schlüssel aktualisieren“
2. Import fehlgeschlagen 
3. Network error (CertificateException)
4. Schlüssel konnte nicht abgerufen werden

## Your Environment

* Android Version: 6.0.1
* Device Model: Samsung S5
* OpenKeychain Version: 4.9
* From Google Play or F-Droid?: Google Play

**Comment by geomandolyn** [comment]
Keyserver is hkps://keyserver.ubuntu.com

**Comment by Valodim** [comment]
Thanks for your report! We're on it, see #2276 :)
