### ISSUE TITLE
Signing encrypted message add signing key to receivers.

### ISSUE THREAD

**Issue by 5h4d0ww0lf** [open-keychain/open-keychain#2279]
When encrypting and signing at the same time signers key is added as a receiver.

## Expected Behavior
If I create a signed message encrypted for somebody my key shall not be one of the receivers.

## Current Behavior
Signing message automatically adds signing key as a receiver.

## Steps to Reproduce (for bugs)
1. Encrypt message for the key you own but secret key isn't presented on the Android device and signs it with some key then save as text.
2. In gpg use `gpg --list-packets --list-only "msg.txt"` you will see two receivers (sender and receiver) but there should be only one (receiver).
## Example
```
gpg --list-packets --list-only 2.pgp
# off=0 ctb=85 tag=1 hlen=3 plen=2060
:pubkey enc packet: version 3, algo 1, keyid 92594C1DD2C6FF46 #legitimate receiver
        data: [16382 bits]
# off=2063 ctb=85 tag=1 hlen=3 plen=396
:pubkey enc packet: version 3, algo 1, keyid A2D79E1C5FAB35C5 #sender
        data: [3071 bits]
# off=2462 ctb=d2 tag=18 hlen=6 plen=21366 new-ctb #message
:encrypted data packet:
        length: 21366
        mdc_method: 2
```

## Context
When I want to send files from my tablet I want them signed but I don't want them to be decrypted if the tablet will be compromised

## Your Environment

* Android Version: 7.0
* Device Model: LG-G5
* OpenKeychain Version: 4.9 (49001)
* From Google Play or F-Droid?: F-Droid

**Comment by dschuermann** [comment]
Puh, this is an untypical scenario we currently do not support. By default users want to read their own messages. Not sure this will change due to UX issues.

However, your scenario could be implemented using our API.

**Comment by Valodim** [comment]
I think I would be fine to have an option for this, in the overflow menu next to "Enable compression", and also allow switching the default in the Snackbar. That way it shouldn't get into anyone's way but people can still do it if they choose.

**Comment by Valodim** [comment]
Simple enough, I just added an option for this :)

**Comment by Valodim** [comment]
Will be in the next release :+1:
