### ISSUE TITLE
can't decrypt from clipboard

### ISSUE THREAD

**Issue by EternalHidden** [open-keychain/open-keychain#2284]
Popup - like "can't decrypt, can't find known private key"

though not long ago all worked well, with same settings and keys

## Your Environment

* Android Version: 4.2
* Device Model: 
* OpenKeychain Version: 4.9.1
* From Google Play or F-Droid?: GP

**Comment by 5h4d0ww0lf** [comment]
@EternalHidden Can you post your message and key id?

**Comment by 5h4d0ww0lf** [comment]
Can you provide me a message and your pubkey, I just want to know if your message is encrypted for you. And way to reproduce your problem I have imported multiple test keys with subkeys and I still don't encounter your problem.

**Comment by EternalHidden** [comment]
-----BEGIN PGP MESSAGE----- hQIMA9cOi+QFZhSQARAAmXoaGu3wFmc6vV/6CD+JNQE59Cy1NekizS8nlF0XzBj4 ozNOC2aO0z8ODUv/cd5tCHJa7MB3SGUZ9J6pj680LjPPz3B0sVyubBTWTBkOCCck X6n6ORoYOpAkMxEE31HemMaJ+B7xMzJhg9HOuL/2j0TdplzdMNfiUJJhSoEoZuX6 i3pVYl1fEQY0SqwXzJUmmOTQPNrVONK/ZpmMPSWGqsRwMuCdAKjIrpJZsQsu1J8Q uK6k1S+rxkRdDqr1PhrnFozLlvbWo/M4tCjkb3NCjmdMpb80yfi3W76cHBfVLtQU UHIBkYnA+qY8d/9Ml0GuIUC8HuqVEjdKfDGGt9IvEwXn1YZaiZmrHtK/xh8TBQEc sMPX41BvkY8xVz+BBmyXs5vQtB+ENL0NgSQqtKNwwI0KKBy5HAKvCGgZvCctMJHc XX5wc65lzRDInQ5ldbXvx730BLjNo1d+SlCiFXjOBO1Ws/16cSPA6ZE/onmlty3p /tQ7VmAcC77Dy9mJuGyBQ9JP/+EE+rD2cgErwiMKpFBVMblvtfKl4Eet0nfA+GW6 rLsqA0QXyaRdHIijFU+jYhSJXRcsqmMyo3uQm71H/1VUb1pSqlAAzqMQs0ocyutl Re9z1LQImLpiVXKrIY2guh1oehFJQlLo1Fm7jkgxx+aPPudf5ADeOiNCs1hpCv3S VgEgUOZFiPQfmM/wN+9r0ApftmcJr5nSjkg2MNZV490X/3FbxHcrthSd7YetBlut Kuuq4EmAnUIt2BkhHxMVAuyLozXic27pXVG7Is6kcmovXR95BVIV =P7Gq 
-----END PGP MESSAGE----- 

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBFqR2TQBEADF5WMjuP2BF4u+C5J/rqNLRnOhR6A49A05gI1ptdR32CGBQyXQ
UjAuzyUhVU+p/CkykbST5V5xe5e7EcO2M2zHSvPJe8uQuIFePQgk6sYWyXHZarV/
paooNY6qnZRRKE8+KWblan+vdYTW28vpSoyOKyfr/GVLL4AcRlXJjXEuQbh7r6PD
WtQfJ039EecTy6SvTrGsc4awis1MxfkSOh/BNQKwCIzjX6D01EZ07U15looth2SE
TG8Nvr0bPVH/ILo21i0SmdJpSEPQg2ZpKfg6WDalbzOBQ5A1PCgeztqXj4PpKUKI
JbKRugmnLjbWGTO/Vaw11b+S2GAeQ6QhhiMPsixy//8Ywdytz3OmPU3o1j2NCGxr
R3oFX1ckK9K0bnGBfIfUd3uuUStmEw2UrHTB7TbJvA36tyT+ToXqKEhnW53/18wy
tDXJRlN8KMB28G3HhHp9OPgSKhaC3/mzJhbFPt7lkujD3uZMiN1L2zyQSmihPfZu
bgUTucK7/js6XXoCew6IEjAbXA4+osxWu4cv+6zYBpp++SaLwPLaBFyJ6Vmn74jw
3GSg/hFtJHLKhixDWtXYVH1nJR3bVPTzQ+eZOJVXkmgSlyvj/llmzb/qGNVy/MK2
qgBVqJXO3xvNSmBwpnzJu8qJTYYP76DuZavmGs1rcGoW5nRvync/FkWGQQARAQAB
tB1Hb2RIZWFscyA8cHJhY2hvZGFAeWFuZGV4LnJ1PokCHAQQAQgABgUCWpIVJgAK
CRCMurAdxrz5CpZMEACjmObNEMG7oNrcEJHF8V4MI4rIHHPiR6Crz8wXm1iBXOHr
B8zcJtxHrY/OBqhrKKM3s+0njF5A5UDXfnhZvZvQOzQlQibtcC+6OGeXdgxaxyl6
3s1k7A27BB8dzvzRZ4dWNDySteQwHk06kfy/Fq6RDt5qeHhH3/YCMw9c1O2jfg47
1vD01v8aG3+2Xjri+KaicHnwXGTvUgotUkNvJLj846GlvkZavPY3OafSQ5IZkNQD
KGtivd6qu2ECFD7gx016ySqfiLrxaX0a9FzV+hPNqszbMRlhRxqrsOAKRePMOA1L
EKIPklCPZIrcJVfIWtSziz5cZnBSAYdovRjTEmtnzaxBaanBp7dSaMkUCjXIBFX9
KxIO7aAwsRn8wp4xveuSdko5dj4Z8hdAjahhhDl4jZyxBCVqhOzxGD/59E173Yf5
ILeLSASPgMyy+/oE9YrPdGZeccFRCBUdeI3KArVZsUmX+RBxuK/NVB4gNunZ3Ll+
6IeEd+HkFwT5W8UnGUGPyDV2OOGOw0zf/skT0yT0ZuseQZ/RF5asv1NZOHYCAV9l
+ECrWU3Gsn+tCVf2cKPkSvOo+7fCofqYKb9qig9VMza/kIokOAkxLrKKTHEEvLwP
jEiVMlqE/EzI3LrlK2KplrgXWYu47Wqqqxz6UzqelbhODxsj7hBOq0SJPD6s34kC
HwQwAQoACQIdAAWCWpKLegAKCRCMurAdxrz5CqmuD/0SQwHlW7Zeds0/fEwD65FN
J+KV97HI+wXlFJIkjDztcGQmtufgseMoMBstluqcGHTd8I+AdfqjzZCGuiLLn31H
iSZ145ykaQmKKpMojScweVrF/K98cR+4DH9XJbiGnKMvuWgoNuG1G/ruI/bM4f/R
2vEMntHZB45S4X2pr7A4LgKVkJTadWzxYWgsee8ZrBPLhnrgPP5sLUMn82qFtbrM
dzRZncEJm+mgE5rAik9ZzjkdfYiOKAz44/uwEU9rNrCEn9m4AXKW94RkUBM9XyUz
bbzDymNpFy98pOtCStWVDTysH1Z55Gtba/x6lKuNdp86k4KEMSHZHsHV/adxcYUM
hblWaO1uswglBOUQIGJ2siKsJKkJBN9qrbW4Xe+ZA0PH5kcyed24wI+seVFW2uNw
0JRQYpvEo1mKpxptLmmKYOS96PxbIdKGYmsmAHMT4Iwgc7rKHtpyxh4tkY8yvhgl
YwOzsgC6rXDWhiC5cNvHq/6ojC+SYS5KklLc/7pUajMEhdXEluw1m23nu1VtGMDX
3Cv90Z16Sdmmfy1ChhiZ7sizPhwDrj8vYGF7F2GF+HqciVj35yax0k9pI6lEWQl+
MEgcg4eaztbTkZPVFgAKgh+bZgC6ZWTv9jp31Y/k/RfwQvpyrhSkn1/cK2vcmhM+
sLVxq7Sinm2wfIaEtJx6/LQfR29kSGVhbHMgPGphZ2FiYWRhQGhtYW1haWwuY29t
PokCNgQTAQoAIAQLCQgHAhUKAhYBAhkABYJakoukAp4BApsDBYkHiMKAAAoJEIy6
sB3GvPkKmY0P/3c5pl72oRIAcC9PcMRb78YrFEYle6qPOtPeypR+yoBo6olzECCi
XGrZCal9K3PMwX55XLn1r3kxn1Jpp9wPx/Kw2WjsBxN16C7yhyqps6UWbpeG7eKV
bGSs0f5e/9FjmPXXTwssMX13EMKhmFrs/647j/oXg9RbVFETQCY5UtpCGuvN9W14
AbW0mg51IXqguslaf0owfwqYqAWHbn5gFEIdCf3cmL2JnooUSyjF9jluyPLQKY4r
YE6aMMSgqr19+Pd2zrLOKAsc6Zl+Jjmi4NVM3zqwg034M89Vm+t2bP/3+bmpchl0
hL7ZfGadiysM/0vaT+vvM3Le3MctkGQD5M/2ucmLpXZVbRcDIcgVU2c2gLlFPE3n
T0qYgYyr5PWiOG3edkOnsCG/b96GTFNtNpP2VR12BrpYsQHncHS77k+cl0Bj+GDM
KwxjDBqOTQR5PQu7FNXL94Q0JTjhfmrOBclFg/ht4e0V4feonHaUzrudQxC52zCz
WL89MqwfDxkfm08hfNzUstT1EL3f3o6QFqaRG5g7GL3h3Zj7pBXz1F+9S7A0NYY7
72C7LP+dUsunHRylhGUE1dWZGjaGCmzZ70jYcVAbRWkJL58R7Vi4lBwOjJCurBRY
tyQoDdqDJurE6qd1LHUoHLlyR+TSTTzuoR3b8Ov6SjiVfn/+2QXhaMODiQGcBBAB
CgAGBQJanZaVAAoJEKIvUwLXsA5Uj8QMAKL6bz4k1Zv/Cj3WrAAebsbJTwoIX/eE
Qbs6Vg9DJGvYQkuTAIq3fx3sstjtRyHKw3DiqMBD1nm8K0njBylbI8ZbAWGr7Cpo
GeG5AzoPUILAtr72j3s4B8k46m9EajkWD/0ugAMdNXGKZp6LSO/QUK/kdyCaaAEI
LoQL2uDvkvZvvQ6PTppDuwdo7odDtMUHkeUEwqocGX+F9ef/9Z0lSKFfyYxbN/kD
7OvoCaDFdnLV2SmAxraAxeJwQGYiLCeFrh2BJiAugdedgXL7kHY97FBUJA/rliqV
5h+JKNmWbGaWHv6r15ASnUBH2u4UYwMvoIqS/F9b7GEC7DaZzyicWtLsBrJda0tE
zGIyTk4Sp8ts2hTSTxaWxIiVsDZeeCsPp2GEbF12TySAqw1A/YQSi6SykFl0MFx2
NoNZWwRj6MoFJl+EDdamor94Xrl8THKJ12bxbJsNaTjBBr3UYdczNIkkQoTWWuDR
9yT1K2OcQvE3XvEXnBtmHQdpHnLenk942LkCDQRakdk+ARAAwWmHlhaurUDjJA5b
6WqCBp7dWp2djGwnab0fLXiRrK8QbVSno8+C3SRg9QgigV4BxiJPcHDlNltGTBFZ
Zdw+T5nFscQEGaV7vRQc3BOiK9xpLJpzkHHCQ2kbdlwRuhwthCPrr087lJQCz73A
wMP5yxqYPa+2pemefPu375bmlGafXTayrokWqsOHEBAJLDcdrWZd77Q5APS7mWWQ
v3SE1p/isLzgeNQg7+bLcUKsCUQUPGSLDHWq/714BjbXp7MQcSIRJjFAEJUnzlnO
SnXJkeg0T30niHAniZP007JWp+QmNdyaS5Zk3d4U3ErdIAe5joAWfkiUcINI0yZw
leoO9NNjwj7GfU2Q1yhuXafb4FG8WV2gYmaAydL7St/3dwZJfDvTVzGmaD6Xn6oN
xv7XgICvR2cl1dZ93Z6d88JiMIVf+PB2y1NPC6oJxRsdSFvSzvgZuj897PEblG9g
ntON9JCdei1AIh03vx8Z/35gUG0uI3/cs1fnPtWTRi422OWBbrBwNM4kFs9iomEA
82sERwz19axxIKiwN2JsP+kOo/quuPJR5iyZ4/ki93w80ZA/mFvB54imDHB9JR5O
IgEqxKAD4+DeZ5pSgLC25kTqqys60BTBNjRr+zVH7wAQGvUmWREsrHFlWz1Hyjfz
94UWmHyJtfU2Iz18njganjhOnIMAEQEAAYkCJQQYAQIADwUCWpHzWgIbDAUJB4jC
gAAKCRCMurAdxrz5CtgbD/4vPRjkR0zkzkP/uOEhrIBoiPxX8bwpj/vAP0Zj9vPQ
LBEO4m40T02XeBvIAY9qMqVYHMkiNh/ExcbfOuACOImSEK59cCELl1r1kh7tHvqX
49by3B4yd/n4yJWG/hKONKYY4lLih/PhUEEU0H+Z1hciywr4ElVgWhA8H/eutkQN
zFwUmcRDvsqZWDrcMeXNhrocto3d7dNIxHR3/LFqVPNru7wCoI1YDIeTU86IQ41v
px2LbX9jlOZRc+/t1kR0UwJRfJKdoP7f3zni0cJNmQXGp0FIbrV3YVkiuhpqLALk
zmMh85pJhgQpjPTdSAzXAkFzauAAmJr9UxULG/ne47AdcEtRTvhFBywuBt3zvX5S
bXv/TEHfkWcRanI6U9jRSFj5uGSmMN16FkD/2pl10OgzJD+dOChUia6XMr9u+B/i
kf/VnMpFR8xOSnNQqs0XTLbHAl0Lh1EVV1BUQLIb72hDguCm14gxPDsMVeL/3vPu
t81xN5CTMZSnCHvx5Uv04XnE4ZmEZTAZlPJ3gTfk3m455LaoPkrbZoWOziQIuxrT
N/k+oOyRFpR4GuP77gfIh39ZPhZSTavvywEhU/iZgbY2cpGu2mt0LmA/3fmYHhpL
TLwi+fG2fEOFXPnriuZjEgWlxpUs4UoeMuGXpe2P6MecbqBTqpEW6I4E7Z0a2ITH
sQ==
=DeQA
-----END PGP PUBLIC KEY BLOCK-----

**Comment by 5h4d0ww0lf** [comment]
@EternalHidden try this one
```
-----BEGIN PGP MESSAGE-----

hQIMA9cOi+QFZhSQAQ//bcsl21VFvr+drvk/F4t1J7Bow8D4zmorlLA2H4bYnDPI
xT0F2Jl2m1Bld9DYQUGrhdzrjPoUWfGIUbijriIf8+7yTNwDu1Fvyxy8+p8wWrwL
sAI3It9+uRcB2NTgeyyJmvIJNX3kcDMs9Nvm+pHs9p9AP9s3Fr0QR2KoSAq+SSiy
u+tm/wsERJM060+/cD4mKKrJaP+5XS4ax53g6Jh+a418SBwLAinP1iBatqfILZZB
Klu4ZIm7tHVWo828VneMAGm3pr09zgRb+Cbk/28nqRHdqC3k3zLeNZqAEgMQFZov
Gam/En3xKGNtMuJCCYql/Qlwpd9R0g+GnVNMpp2ldeRBJ2B3H5bQZV86OtskS9/U
AJAd3dhFutiA5KYvQW4Pm/ND0nDgfpwyP9LUSxg+9hVM5VC/gYvfXCjW0spW7AwF
EgMymsccNLm+eXmF5RiCwEjfXRRU6TsALSTsowSE1+GweUYST+ZzMKaRrjL+cknQ
JtaO62UD9Lb0/2MmMZv2P3Rh2npoJ1MRQlt2Fyj4mM7BI6NSK7wOpmGnPvR9f8QC
CsOtB6dnJpZZ5S09LGjzVeJgKmuOPQuM/mR/EMsRT9ntpZh/d3/E9J/png4ryiQn
UCtT5EakdyqYKYyI6z2T+jA/Aoieiq2gqNq+o7z+psT2MmuXHNAhxbuOME5+EinS
OQEmOYPaVLF+haUEGoWTMOmaWd3dgNsK4h60t3OYZjdgY3/mnpOBQxm2fajWol61
e4NYhUsvoSUH3g==
=ZW2q
-----END PGP MESSAGE-----
```

**Comment by 5h4d0ww0lf** [comment]
@EternalHidden worked?

**Comment by Valodim** [comment]
Unfortunately the pgp message format is a little brittle :( I tried making our parser a bit more robust, but we never merged this because it's really just a ton of guesswork #2225

**Comment by skizzy57** [comment]
I'm having the same issue and not sure about how to resolve it.

**Comment by XBEAST1** [comment]
I Made This PGP Progressive Web App Which Is Fully Open Source And Stores PGP Keys In Local Storage It Works Flawlessly On Any Device Make Sure To Check It Out 🖤✨
Link: https://nextpgp.vercel.app
