### ISSUE TITLE
disable Security Warning if message was encryted, but not signed

### ISSUE THREAD

**Issue by iggs0** [open-keychain/open-keychain#2285]
Im using K9 mail together with Openkeychain 4.9.1 on LinageOS Android Version 7.1.2.
When reading mails which are send to me and are GPG encrypted but not singed the system display a warning which I have to approve every time.

Security Warning
This message was encrypted, but not signed. It is not end-to-end secure!

Since I encrypt all eMails on my server with my own PGP Key if they are lying around longer than one day - this message really gets to me.

## Expected Behavior

If I receive unsigned messages - I can go to the options and disable the above message.
Default would be that the warning is show.

## Current Behavior

An experience user can switch of repeating warnings.

## Possible Solution

If I receive unsigned messages - I can go to the options and disable the above message.
Default would be that the warning is show.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version:  7.1.2
* Device Model: Xiami Mi5
* OpenKeychain Version:  4.9.1
* From Google Play or F-Droid?:  F-Droid

**Comment by Valodim** [comment]
The warning will no longer be a full screen overlay in the next release of K-9 Mail.
