### ISSUE TITLE
Impossible to uncheck "Synchronize with the Internet"

### ISSUE THREAD

**Issue by steelman** [open-keychain/open-keychain#2286]
I am effectively unable to uncheck the "Synchronize with the Internet" checkbox under "Edit identities". 

## Expected Behavior
The "Synchronize with the Internet" checkbox should remain unchecked after saving and exiting the "Edit identities" screen.

## Current Behavior
The checkbox remains checked after pressing "Save" and enterig the "Edit identities" screen again.

## Steps to Reproduce (for bugs)
1. Enter "Edit identiies" screen.
2. Uncheck the "Synchronize with the Internet" checkbox.
3. Press "Save" (OpenKeychain says there is nothing to do) and exit the screen.
4. Enter "Edit identities" again.

## Context
The key I am trying to configure is a local one I don't want to be either pushed or puled from keyservers.

## Your Environment
* Android Version: LineageOS 14.1 (Android 7.1.2)
* Device Model: Moto G LTE (XT1039)
* OpenKeychain Version: 4.9.1
* From Google Play or F-Droid?: F-Droid

**Comment by Valodim** [comment]
This issue is based on a misunderstanding of the purpose of this checkbox. The whole dialog is gone now in favor of identity editing under advanced :)
