### ISSUE TITLE
Keyserver drop down unreadable on dark theme

### ISSUE THREAD

**Issue by volker-raschek** [open-keychain/open-keychain#2287]
## Expected Behavior
When I want to search after some keys about a keyserver, I type into the search field the name of the person for which I search after some public keys. OpenKeyChain sugest me some contact names from my phone address book. 

## Current Behavior
The suggested list is empty, I see only empty field in the drop down list.

## Steps to Reproduce (for bugs)
1. Set theme to dark
2. Search after some keys, for example from Linus Torvalds
3. Check if your suggestion list is empty, too.

## Your Environment
* Android Version: 8.1 (LineageOS 15.1)
* Device Model: Google Nexus 5x
* OpenKeychain Version: 4.9 (49001)
* From Google Play or F-Droid?: FDroid

**Comment by dschuermann** [comment]
This only works when you give OpenKeychain access to contacts (by enabling "link keys to contacts") have you done this?

**Comment by 5h4d0ww0lf** [comment]
@dschuermann I have to confirm when is switched to dark theme suggestion still work but the text (name) isn't visible.

**Comment by volker-raschek** [comment]
@5h4d0ww0lf 
Thanks for the screenshots. This is the behavior what I mean.

@dschuermann 
I have set access permissions for OpenKeychain

**Comment by Valodim** [comment]
Finally got around to fixing this. The background of the search activity should be dark to match the bright text, of course. Thanks for your report!
