### ISSUE TITLE
Nitrokey Pro: Decryption fails starting with v4.9

### ISSUE THREAD

**Issue by tulir** [open-keychain/open-keychain#2291]
When trying to decrypt any data, the decryption fails with "Data is corrupt!". I've tried password store files (which work fine on my PC) and encrypting test data in open keychain and decrypting it right away: both fail.

```
[START] Processing input data
 [DEBUG] Attempting to process OpenPGP data
 [DEBUG] Starting decrypt operation…
  [DEBUG] Found block of asymmetrically encrypted data for key 0x1a048f1d7d6f69c8
   [ERROR] Data is corrupt!
```

Decrypting worked fine a few weeks ago (before v4.9). Using the wrong PIN correctly shows "Error: Bad PIN!", so that is not the problem.

## Environment
* Android Version: 8.0.0 and 7.1.1
* Device Model: Huawei Mate 10 Pro (BLA-L29) and Nexus 9
* OpenKeychain Version: 4.9.1
* From Google Play or F-Droid?: Google Play
* Nitrokey Pro: probably v0.7

**Comment by dschuermann** [comment]
Can you try a version before 4.9 from https://f-droid.org/packages/org.sufficientlysecure.keychain/ and report back please.

**Comment by tulir** [comment]
Reinstalled version 4.9 from F-Droid, now it fails with
> Error: Deciphering with Security token failed on receive.
Take away the Security Token now and touch TRY AGAIN.

Just clicking try again produces the same error immediately. Removing the Nitrokey makes it go to the "Hold Security Token against the NFC market at the back of your device" stage and reinserting it animates the image a bit, but doesn't do anything else (visually).

**Comment by dschuermann** [comment]
Please try with 4.8.1 and report again. You said it worked with a version **prior** to 4.9.

**Comment by tulir** [comment]
I edited my previous comment ~5 mins after posting it:

> For now, I've rolled back to v4.8.1 from F-Droid where everything works fine.

**Comment by Valodim** [comment]
Yeah we changed a bunch of things in 4.9 that could affect this, like #2257. Not much we can do without some more debugging info. Do you have a nitrokey pro somewhere @dschuermann ?

**Comment by dschuermann** [comment]
@Valodim yes.

**Comment by Valodim** [comment]
Cool. I'll take care of this then.

**Comment by Valodim** [comment]
Likely the same issue as #2049
