### ISSUE TITLE
Cant save encryptes files 

### ISSUE THREAD

**Issue by canary5** [open-keychain/open-keychain#2294]
after upgrading from 4.8 to 4.91, cant save decrypted file to storage

## Expected Behavior

before you decrypt pgp file, there you see decrypted file. You long click on it and was given menu to save, share etc. Now just crashing

## Steps to Reproduce (for bugs)

1. Encrypt photo.
2. Decrypt it
3. Try to long click on it
4.

## Your Environment

* Android Version: 8.1
* Device Model: pixel xl
* OpenKeychain Version: 4.91
* From Google Play or F-Droid?: fdroid

**Comment by Valodim** [comment]
Thanks for your report! This is already known and fixed, see #2278. We will make a release with the fix soon :+1:

**Comment by canary5** [comment]
Ah sorry didnt see, thanks

**Comment by dschuermann** [comment]
We just released 4.9.2, should be fixed in this version.
