### ISSUE TITLE
[Feature request] Add support for encrypted email subject compatible with Enigmail 2

### ISSUE THREAD

**Issue by samtuke** [open-keychain/open-keychain#2299]
In the recent release of Enigmail 2.0, encryption of the email subject is supported. This is a useful privacy feature, and it would even more useful if it was supported by OpenKeychain and K9. Currently, when a message has been encrypted by Enigmail, including the subject, and then opened in K9, then dummy text becomes the new email subject for the remainder of the discussion, regardless of mail client used.

## Expected Behavior
Email subject's encrypted by Enigmail 2.x are readable by K9 with OpenKeychain.

## Current Behavior
Dummy text appears in K9 instead of the unencrypted email subject.

**Comment by 5h4d0ww0lf** [comment]
@samtuke Isn't this issue with K9mail?

**Comment by Valodim** [comment]
It is. I have this on my radar, but taking care of [other things](https://github.com/k9mail/k-9/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3AValodim+) first.

I'm also not perfectly happy with the protected headers ("memoryhole") specification, but I guess it'll do for encrypted subjects.

**Comment by samtuke** [comment]
@Valodim Thanks for confirming.

As this apparently relates to K9 rather than OpenKeychain, I'll close this issue.
