### ISSUE TITLE
[feature request]: import keys from host over ssh

### ISSUE THREAD

**Issue by bam80** [open-keychain/open-keychain#2307]
Would be fine if "Manage my keys" screen does supply this as an option.
It seems to be much simpler than existing importing from file/clipboard when the keys are stored on host initially.

**Comment by Valodim** [comment]
import keys over ssh? Sounds odd to me. Can you describe your envisioned workflow a little more? Typing ip/host and password to get a key off a server sounds very niche to me, how many people have their secret key on an ssh host they can reach from their phone?

**Comment by bam80** [comment]
The ssh host supposed to be just your home/work PC, to which you should connect over wifi by ssh without problems and import your keys in a secure way. I thought it rather common scenario. Also, it would allow to not having to connect your phone to PC by cable to transfer the key file, or relaying on third-party tools as KDE Connect to share clipboard with the PC. So the all process would be much more streamlined in my opinion.

**Comment by Valodim** [comment]
Our attempt at such a mechanism is the 'secret key transfer' method, which uses tls-psk and a qr code to share a preshared key. It works very well, except there is no great desktop client for it. We even talked to the gnupg folks about this and had some hopes gnupg would grow support for it - alas, it never happened :)

A friendly soul (from the KDE Connect folks actually, iirc) actually took a stab at this: https://github.com/MauroMombelli/opengpg-skt it works, lacking only a little polish to be actually useful in practice.

The canonical and encouraged way to do this in the future, at least in an email context, will be the Autocrypt Setup Message -> see https://github.com/k9mail/k-9/pull/3342

**Comment by bam80** [comment]
Well, I just thought ssh method could complement the other ones, as it very straightforward, doesn't require any 3-rd tools and provides comparable ease of use, IMO.

**Comment by MauroMombelli** [comment]
oh hello, the implementation works and has been clean up quite a lot from original state. It can still be improved, but if it should be able to make most paranoic compilation flag happy.

Please note this methos is using TSL (util_tsl_server), that part can be easily changed to be SSH; but you can still use the code about share the IP (util_network_info) and key over QR code (util QR) and the actual managment of the pgp keys (util pgp), the code sould be quite decoupled and reusable without gbig issue.

As you can see from https://github.com/MauroMombelli/opengpg-skt/blob/master/util_tsl_server/tsl_server.h, teh method to implement are pretty easy and stright forward.

Imho is not that tech that create easyness of usage, but a little GUI over it (yes, the QR is on the terminal)

ps. im not part of KDE Connect or anything.

**Comment by Valodim** [comment]
Not sure I agree with that assessment :)

The user needs a machine with ssh running, which allows log in to their account. They then need to type an ip or hostname plus password (pubkey doesn't make sense, obv). After that we need a path (or file selection, but that's tough UI).

Even among linux users, I think this is a rare setup to have, and otherwise requires a lot of knowledge -
 "just start ssh on your system and configure it to allow password login" is far from trivial. There is significant potential to screw up security-wise - a password you use to conveniently log into your laptop given physical access is not a password you wanna use on an ssh server that is commonly exposed on wifi. There are also lots of error cases along this way, which require effort to implement in a way that gives enough guidance to the user isn't stopped in their tracks on the slightest mishap.

All in all I think there are better ways to transfer a key that we can focus on. Thanks for your input, still! :)

**Comment by Valodim** [comment]
@MauroMombelli Ohai, nice to hear from you. Your implementation does work, I actually used it a couple of times myself :) still thinking we should totally get that packaged for debian and make it available for users.

I still think tls-psk is a good choice for the key transfer protocol, as it's fairly easily available and actually designed for the purpose. ssh has a lot of complexity that is unneeded purely for transport encryption.

**Comment by bam80** [comment]
Ok, let me leave some notes though:
1. I thought for any distro all what is needed to get to ssh is just run corresponding service, since login by password would be enabled by default. Am I wrong?
2. > After that we need a path (or file selection, but that's tough UI).

We don't. Obviously, user has gpg utils installed. All ssh operations should be done with that utils, and they know where the key storage is :) So after connect, user should get list of keys for import in UI immediately.

Overall, I'm certainly not insist. You guys do a great work, just wanted to leave my experience with the setup. Not sure I will have enough energy for this later.

**Comment by MauroMombelli** [comment]
Ssh come with most distro by default but is not enabled as service.

IF (and that is a big if) openssh provide api to start a local instance and
set a custom shell/login (our script) and somehow there is a way to compact
the server key in the qr code, this could be achieved.

But considering opentsl/opentsl(6.4MB) as the only dependency, and user has
to do nothing, I don't see the practical advantage.

**Comment by bam80** [comment]
>IF (and that is a big if) openssh provide api to start a local instance and set a custom shell/login 

Too complex. Supposedly, all that user has to do on his PC is manually start ssh service, if it was not started already, and stop it after the key exchange. Simple as that. That way we would comply to KISS principle :) If it inappropriate for the user for whatever reasons, he could just consider another methods.
But, if no one interested, I don't see the point to discuss it further.
Hope opengpg-skt will be packaged for debian soon :)
Thanks

**Comment by MauroMombelli** [comment]
>Supposedly, all that user has to do on his PC is manually start ssh service, if it was not started already, and stop it after the key exchange.

this is not possible: the app need to scan all the ip in the network and find the ssh server(assuming is on port22), then he need username and password. at this point he has access to you pc shell and do whatever he want.

Lets eslude all the security issue, like your smart fridge faking to be your pc and getting all your key, do you think this is more KISS than just start the program and scan the QR?

**Comment by Valodim** [comment]
No matter. Let's just focus on the methods we do want to support :)

@MauroMombelli I'll keep pinging @dkg about that license issue. I'm sure he's fine with anything, just need to hear it from the horse's mouth

**Comment by MauroMombelli** [comment]
@Valodim yes, licence should be fixed before packet release to avoid any drama.

and also yes, lets concentrate to what we already have working, and if this issue get many +1 then we think how to proceed :)

**Comment by RonSidell** [comment]
Blind and visually impaired users will have- difficulty scanning s QR codes. I'm not sure what to do to address that, but I have a blind coworker and I won't be able to use QR codes to exchange key info with him. Perhaps this is the wrong place( to mention this i which case I apologize and I ask where I should make this comment instead. Perhaps NFC tags would be a good and simple alternative?

**Comment by bam80** [comment]
> The canonical and encouraged way to do this in the future, at least in an email context, will be the Autocrypt Setup Message -> see [k9mail/k-9#3342](https://github.com/k9mail/k-9/pull/3342)

I see the PR was merged, does it mean the new way to share a key is ready now?
