### ISSUE TITLE
OpenPGP-SmartCard PIN with alphanumerical characters are not supported

### ISSUE THREAD

**Issue by JanMosigItemis** [open-keychain/open-keychain#2311]
Cannot enter my Yubikey NEO's PIN into the OpenKeychain UI.

## Expected Behavior
UI accepts the same PINs that the NEO (== OpenPGP-SmartCard?) supports.

## Current Behavior
When decrypting mails with K9-Mail, OpenKeychain is fired up and asks for my Yubikey's PIN. Since the Yubikey supports alphanumerical PINs up to 127 characters, I am using my passphrase as a PIN. However, the text field in the OpenKeychain UI does only accept numerical input, so I cannot unlock the key.

## Possible Solution
Align PIN support with Yubikey's support and / or the specification of PINs in the OpenPGP-SmartCard standard.

## Steps to Reproduce (for bugs)
1. Have a decrypted mail in K9 and your keyring setup with OpenKeychain and Yubikey ready.
2. Tap the mail.
3. OpenKeychain asks for PIN. The dialog does not accept alphanumerical input.

## Context
I am trying to decrypt or sign emails with K9.
If in fact Yubico is violating the standard by accepting PINs that violate the specs, consider this bug report less important.

## Your Environment
* Android Version: 8.0.0
* Device Model: Honor 9
* OpenKeychain Version: 5.0.1 (50100)
* K-9 Mail 5,403
* From Google Play

**Comment by Valodim** [comment]
There is a button labeled "abc" next to the input field, which allows entering alphanumeric pins. That should cover your use case. 

Note however that this is less useful in practice than one might expect: yubikeys allow only three attempts to input the pin, after which the admin pin is required to unlock the token. With only three attempts, even a four digit pin can't practically be brute forced. Anything more complicated is just making things less convenient for negligible returns in security.

**Comment by JanMosigItemis** [comment]
Thank you very much for the insights. I really didn't notice the "abc" button. Maybe it would be a good idea to make it more prominent. Anyway, I'll consider you advice. Bug is "solved".
