### ISSUE TITLE
Key backup fails - wrong passcode reported on verification check

### ISSUE THREAD

**Issue by fsantiago07044** [open-keychain/open-keychain#2312]
Key backup is failing each time I try. When it prompts me to write down the security code and then enter it back in, it states i have entered the wrong code. Have tried numerous times, in between app restarts.

I did customize my gpg key with an expiration date and 3 separate subkeys for each of the default 3 usages.

It is valid otherwise and I have exported it to keyservers. 

* Android Version: 8.1.0, 4/5/18 patch level
* Device Model: Google pixel 2
* OpenKeychain Version: 5.0.1 (50100)
* From Google Play or F-Droid?: Google play

**Comment by txthomas** [comment]
Got the same behavior, no key backup possible. Always promting that wrong key was entered.

**Comment by Valodim** [comment]
ooops that's probably my fault. will fix tomorrow and release asap, sorry about that.

**Comment by fsantiago07044** [comment]
Kewl thanks.
