### ISSUE TITLE
What is a 'stripped' subkey?

### ISSUE THREAD

**Issue by cpdyj** [open-keychain/open-keychain#2321]
Maybe this question is foolish. But… 
In my language the translation is “剥离”(zh-CN)

What means of stripped? Disable? Secret-key removed? Can I reactive a stripped subkey?
Thank you.

**Comment by Valodim** [comment]
A stripped key is a subkey where the secret key material has been stripped. That means it irreversibly can't be used for certification, signing, or decryption.

The term "stripped" is by no means perfect, but so far we couldn't come up with a better one :)

**Comment by cpdyj** [comment]
Thank you.
