### ISSUE TITLE
Passphrase stored in keyboard predictions?

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#2330]
From the mailinglist:

## Current Behavior
I am using Google keyboard and I realize that the passphrase I use is stored in the predictions. I I believe it is possible to switch the keyboard in "private mode" before asking the passphrase.

## Expected Behavior
Not stored as predictions

## Possible Solution

https://developer.android.com/reference/android/support/v13/view/inputmethod/EditorInfoCompat#IME_FLAG_NO_PERSONALIZED_LEARNING

**Comment by hagau** [comment]
#2331 should suffice as fix, but I can't/haven't tested it yet.
