### ISSUE TITLE
App crashes when trying to set-up along with K-9 mail

### ISSUE THREAD

**Issue by sivaraam** [open-keychain/open-keychain#2336]
## Expected Behavior
I expect to configure the key for signing messages successfully.

## Current Behavior
The OpenKeychain app crashes.

## Steps to Reproduce (for bugs)
1. Import a key into OpenKeychain
2. Configure OpenKeychain as OpenPGP app for K-9 mail
3. Go to an account settings of a corresponding account in K-9 mail
4. Tap on the 'Configuration' setting

## Context
I imported an existing key into OpenKeychain. Then I tried to enable signing of emails in K-9 email. For this I initially set-up OpenKeychaing as a OpenPGP app in the Cryptography settings. Then, I tried to configure the account's Cryptography setting to use my key. Unfortunately, the app crashes whenever I tap on the account-specific Cryptography setting. As a consequence I'm unable to sign my emails using K-9 mail.

## Your Environment
* Android Version: 5.1.1
* Device Model: Samsung SM-J111F
* OpenKeychain Version: 5.0.2
* From Google Play or F-Droid?: F-droid
* Note: A key with two-identities

**Comment by rschr** [comment]
Same behavior here.

- Android Version: 5.1
- Device Model: CHUWI Hi10 Plus Z8350
- OpenKeychain Version: 5.0.2
- From Google Play or F-Droid? Google Play

**Comment by jdstrydom** [comment]
Same here:

Android 5.1.1
Redmi Note 2
Openkeychain F-Droid newest

**Comment by sivaraam** [comment]
I tried building the debug version of the app following the instructions in the README. It doesn't seem to work properly. The app doesn't seem to be installed completely. So, I couldn't confirm this in the `master` branch and also couldn't get logcat outputs.

I guess the instructions in the README needs to be updated.

**Comment by jdstrydom** [comment]
The crash issue on Android 5.11 seems to have been resolved with the newest build for me. Thank you. 😊

**Comment by dschuermann** [comment]
@sivaraam is it fixed for you in 5.1.1?

**Comment by rschr** [comment]
Fixed for me. Thanks!

**Comment by sivaraam** [comment]
This seems to be fixed for me too. Thanks!
