### ISSUE TITLE
What do these icons mean?

### ISSUE THREAD

**Issue by 0x00000F5C** [open-keychain/open-keychain#2340]
I just generated new keys. Right is old, left s new. On the first subkey of the old one, there are three icons; a wax seal, a pen, and an ID card. But there are only two present in the new one; the wax seal and the pen.
What do these icon mean?
![Image](https://user-images.githubusercontent.com/24216586/41091018-cd81f808-6a6f-11e8-9bb0-088345b297d1.jpg)

**Comment by wiktor-k** [comment]
They are key capabilities:
  - red - certify,
  - blue pen - signing,
  - card - authentication,
  - padlock - encryption.

**Comment by 0x00000F5C** [comment]
I see... Well, I guess there's that then.

Thanks.

**Comment by Valodim** [comment]
The `card` icon indicates that the key may be used for authentication, for example using [Termbot](https://github.com/open-keychain/termbot). These flags can be changed at a later point though or a new subkey added that will be used for authentication, so you're not missing out on anything with your new key :)

**Comment by 0x00000F5C** [comment]
Yeah, I don't really use PGP keys to do that. I thought maybe there was something wrong with my new key or something.

**Comment by wiktor-k** [comment]
Authentication subkeys are neat, like Valodim said you can use them for SSH, on desktop and Android, I use them! :)

**Comment by 0x00000F5C** [comment]
How do I do that? I remember using Kleopatra to generate the old key, but I hated it because it requires constant internet connection to do things.

**Comment by wiktor-k** [comment]
What's your OS? There are multiple guides if you search for "ssh gpg" e.g. https://www.programmierecke.net/howto/gpg-ssh.html

**Comment by hagau** [comment]
You first have to add an authentication subkey in OpenKeychain (by pressing the big blue :heavy_plus_sign: while editing subkeys like in the screenshot yout provided and selecting *Authentication* as usage for the new subkey). Remember to backup your new key!
Then, in the *Share* tab, tap *Share as SSH public key with...* to export the public key to the desired target via your preferred sharing method. From here on out, any OS-specific SSH guide will suffice for adding the newly created key to the set of allowed SSH keys for the target.

**Comment by 0x00000F5C** [comment]
@wiktor-k I've been doing it wrong, then. I looked up "pgp authentication subkey" and not much help there. Thanks.

@hagau I've never noticed the blue + button there, whoa. Thanks.
