### ISSUE TITLE
Sign only errors

### ISSUE THREAD

**Issue by bikb** [open-keychain/open-keychain#2342]
Ehen I use openkeychain together with K9 mua and yubikey neo and I want to use PGP/mime to sign a message I got 2 errors.
First error: The displayed message in inbox of the receiver the message doesn't recognize the attachment. The E-Mail is displayed as sent without Signature.
Second error is worse:  The signature is broken. When checking with Thunderbird and enigmail it shows a different key owner. 

## Your Environment

* Android Version: 14.1 
* Device Model: S7 Galaxy
* OpenKeychain Version: 5.02
* From Google Play or F-Droid?: F-Droid

K9 Version: 5.403
 
Plesse can anyone reproduce / check?

**Comment by bikb** [comment]
Can anyone Plesse check? I'm not able to use openkeychain due to these errors.

**Comment by bikb** [comment]
I habe updates to newest Version 5.1.2 and it seems that the error was resolved-I will check!

**Comment by Valodim** [comment]
Sorry for the late reply. Please check if it's fixed with 5.1.2 indeed, otherwise I'll try to have a look when I find some time :)

**Comment by bikb** [comment]
K9 is displaying the signature check correctly now. I have tested with pgp/mime with and without attachment. :o)

I have a problem with this email sent with enigmail:
error message:
_Enigmail-Sicherheitsinfo:

Fehler - Überprüfung der Unterschrift fehlgeschlagen
Öffentlicher Schlüssel xxxxxxxxxxxx zur Überprüfung der Unterschrift benötigt

FALSCHE Unterschrift von xxx xxx@domain.com_

Enigmail has this subkey xxxxxxxxxxx imported but doesn't recognize it. When I send Emails with thunderbird I doesn't have such problems. Has anyone an idea what could be the problem?
(Sorry for posting it here)
