### ISSUE TITLE
Openkeychain 5.1.3 (51300) crashing 

### ISSUE THREAD

**Issue by gtalge** [open-keychain/open-keychain#2356]
5.1.3 Crashing when updating keys
or any key.

##Desired Behavior 
update keys on keyserver like version 5.01

## Current Behavior
Displays "Unfotuately, OpenKeyChain has stopped"

## Steps to Reproduce (for bugs)
Tap update all keys.

## Your Environment

* Android Version: 5.1.1
* Device Model: LG Treasure
* OpenKeychain Version: 5.1.3
* From Google Play or F-Droid?: Google Play.

This issue is the same as with 5.1.1 and 5.1.2.

I sent in a report to Google Play.

**Comment by gtalge** [comment]
Update: It also crashes on uploading a key to the keyserver. Included log on crash to Google Play.

**Comment by dschuermann** [comment]
Please try OpenKeychain 5.1.4 and report back

**Comment by gtalge** [comment]
It worked. Seemed to run a little slower though.

Gordon

On June 22, 2018 12:58:28 AM PDT, "Dominik Schürmann" <notifications@github.com> wrote:
>Please try OpenKeychain 5.1.4 and report back
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/2356#issuecomment-399356777

---
Deo Vindice

PGP : AA32DFCC (2023/07/14)

**Comment by gtalge** [comment]
Switched default keyserver from keyserver.ubuntu.com to pools.sks-keyservers.net.

This seemed to update keys faster and this time without any errors.



On June 22, 2018 12:58:28 AM PDT, "Dominik Schürmann" <notifications@github.com> wrote:
>Please try OpenKeychain 5.1.4 and report back
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/2356#issuecomment-399356777

---
Deo Vindice

PGP : AA32DFCC (2023/07/14)
