### ISSUE TITLE
k9 runs into keyrepository not found

### ISSUE THREAD

**Issue by Spiegel-Leser** [open-keychain/open-keychain#2357]
Using k9 on los 14.1 on LG G3 D855 with openkeychain,all current.

OpenKeychain has my key and other keys, looks normal.
On sending encrypted mail from K9 I get KeyRepository NotFoundException message.

**Comment by dschuermann** [comment]
We need the version numbers of OpenKeychain and K-9 Mail and where you installed them from.

**Comment by Spiegel-Leser** [comment]
OK 5.1.4
K9 5.403
Installed from Yalp 0.42


Am 24. Juni 2018 11:45:07 MESZ schrieb "Dominik Schürmann" <notifications@github.com>:
>We need the version numbers of OpenKeychain and K-9 Mail and where you
>installed them from.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/2357#issuecomment-399743504

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by Spiegel-Leser** [comment]
I did,and it worked,but the real reason was to reconfigure K9 to use my key.

Am 24. Juni 2018 18:26:53 MESZ schrieb "Dominik Schürmann" <notifications@github.com>:
>Can you please install them from a trusted source such as F-Droid or
>Google Play and report back if the problem persist?
>We do not support Yalp.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/2357#issuecomment-399768750

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
