### ISSUE TITLE
Nitro Key Pro - Error: USB: failed to connect to device.

### ISSUE THREAD

**Issue by hacksys1337** [open-keychain/open-keychain#2366]
## Expected Behavior
As Per Release 5.1.4 Inserting Nitrokey Pro Works perfect when generating a security token.

## Current Behavior
In Debug mode running 5.2-beta2 on the same device Inserting the NitroKey device displays
"Error: USB: failed to connect to device.

## Steps to Reproduce (for bugs)

1. Select Create Key Icon
2. Select Use Security Token
3. Insert Attached OTG Cable with NitroKey Pro
4. Click OK on USB Notification
4. Receive Error

## Your Environment

* Android Version: 7.0
* Device Model: HTC 10
* OpenKeychain Version: 5.2-beta2
* From Google Play or F-Droid?: GitHub Running Debug Mode on the Phone

**Comment by Valodim** [comment]
Hm, I just plugged in a Nitrokey Pro with 5.2-beta2 installed, and I was able to create a key, sign some data with it and verified the signature. Perhaps the USB permissions are fixed to the play store version and the debug version can't get them, or something like that?

Please try going to your "Apps" settings, OpenKeychain (not debug), "Open by default", and resetting, then see if the token works in OpenKeychain (debug) when you select the app to use the token.

**Comment by hacksys1337** [comment]
I was able to fix this by uninstalling the The App Store version and
reinstalling via android studio Most likely an issue with android and dual
versions of the application were causing a fuss.

Thanks
Isaiah Williams

**Comment by Valodim** [comment]
We just released a beta that should both fix the interference issue between two openkeychain versions, and properly ask for permission if unavailable :)
