### ISSUE TITLE
Tried to decrypt already decrypted text.

### ISSUE THREAD

**Issue by dscotese** [open-keychain/open-keychain#2370]
## Expected Behavior
After opening a document which is encrypted and it gets decrypted with a saved passphrase, the app only allows the user to try to decrypt it again, which always fails with "error reading pgp data." I'll clear the passphrase and see if it works any better.

Open any encrypted file with the app.
Enter the passphrase and enjoy the cleartext for a moment. 
Open a different encrypted file and nite that it is automatically decrypted, but to an unknown filename that you can't find.

## Context

I opened an encrypted file from gmail inbox. I later opened it from local storage. The first file I tried was an old version and didn't have the info I wanted, so I grabbed the later one from my drafts folder.

## Your Environment

* Android Version: yeah, it's old :-(
* Device Model: Samsung s4
* OpenKeychain Version: doesn't show a version. Maybe your should put that on the main screen?
* From Google Play or F-Droid?: 
 Google play.

**Comment by dscotese** [comment]
Long click on the unknown filename to get a menu that allows you to save it.

I suggest putting that right under the unknown filename button for people like me :-).

**Comment by Valodim** [comment]
Long clicks are problematic wrt discoverability, I've been planning to replace this with overflow vertical dots for a while. That should help this problem :)

**Comment by dscotese** [comment]
Excellent.  This is really a deeper issue in the realm of standard UI practices.  A long click should be a shortcut to a slightly longer process (the overflow menu, like you said), but the longer process should mention the long click.  In other words, how about _adding_ the overflow menu along with a little "long click works too," instead of replacing it?

**Comment by Valodim** [comment]
What for? The overflow menu is right there, and doesn't take as long to click :)

**Comment by dscotese** [comment]
Well, you're right.  I was actually thinking about that too.  It would be useful only for something that would otherwise require more work.

I'm curious, but busy, but if I weren't busy I'd Google "overflow vs long click" to see if any UI designers have ever considered these things before.  Why is a long click ever useful?  Maybe there should be some kind of feedback on an element if long-clicking it is useful.  When the first step of a process is to select something from a list, then long clicking would be a way to get to the second step without an extra tap.

**Comment by Valodim** [comment]
Of course they have, and the conclusion is that long clicks aren't discoverable and avoiding them is the way to go. For instance, the gmail app moved from long clicks to initiate a multi select to (regular) clicking the user avatars to do the same thing, hinting at that fact by turning over the avatars when selected.

Anyways. The overflow menu should work fine like this :)
