### ISSUE TITLE
Empty screen when opening a key through Contacts app

### ISSUE THREAD

**Issue by wiktor-k** [open-keychain/open-keychain#2371]
## Steps to Reproduce (for bugs)

1. Open Contacts book (phone app)
2. Search for a contact that is generated by OpenKeychain (one that has a key)
3. Click "Show key"

## Expected Behavior

I should see a key associated with that contact.

## Current Behavior

I see this:

![no-key](https://user-images.githubusercontent.com/1718963/42592899-4e2b5918-854b-11e8-9878-bf39593f36e7.jpg)

## Context

I found out that OKC populates contacts from key OKC keys and tried to click one contact's "show key" button.

## Your Environment

* Android Version: 8
* Device Model: Note8
* OpenKeychain Version: 5.2-beta2
* From Google Play or F-Droid?: Google Play

**Comment by Valodim** [comment]
There was indeed a rather stupid mistake in ViewKeyActivity causing this. Luckily nothing in the data model was wrong :) Thanks
