### ISSUE TITLE
How to export public key to clipboard?

### ISSUE THREAD

**Issue by gulkily** [open-keychain/open-keychain#2387]
Please forgive me if this is obvious, but I've looked all over the UI and the FAQ and haven't found the answer. How do I export a public key from my keychain so that I can paste it into another app?

## Expected Behavior

Easy way to copy public key exists

## Current Behavior

Cannot figure out how to copy public key to clipboard.

## Steps to Reproduce (for bugs)

1. Open the OpenKeychain app on Android
2. Ensure that at least one key exists in keychain
3. Attempt to copy public key to clipboard somehow
4.

## Context

I'm trying to copy my public key so that I can use it in another application. Not being able to copy my key makes it impossible to register a profile in the application I'm using.

## Your Environment

* Android Version: 6.0
* Device Model: Blu Vivo 5 mini
* OpenKeychain Version: 49200
* From Google Play or F-Droid?: Google Play

**Comment by hagau** [comment]
First of all: update your OpenKeychain! Version 4.9.2 is fairly old by now.

To copy a public key to the clipboard:
- select the key then select `Advanced` from the options menu on the top right hand side of the screen.
- in the `Advanced` properties of the key, select the `Share` tab
- select `Share with...`  to either share with other apps or copy to clipboard

**Comment by Valodim** [comment]
If anyone wants to make a PR, we'd be happy to have a Share button in the view key activity.

**Comment by Grossdm** [comment]
I'm with @Valodim w.r.t. having a more accessible means of copying/sharing your public key.

A button would be fine, but also on a context menu would be nice.

Thanks to all the developers!
Doug

**Comment by gulkily** [comment]
Thank you guys so much for responding so quickly and thoroughly! You're awesome.

**Comment by Grossdm** [comment]
This Pull Request #2388 looks great!

Thanks for the fast response!
