### ISSUE TITLE
Contact sync not working on Android 9

### ISSUE THREAD

**Issue by Chartman123** [open-keychain/open-keychain#2395]
## Expected Behavior
In the settings, switch "Link keys to contacts" on for syncing contacts

## Current Behavior
Since upgrading my Oneplus 6 to Omnirom 9.0 the switch always goes back to off.

## Your Environment
* Android Version: 9.0 September patch level
* Device Model: Oneplus 6
* OpenKeychain Version: 5.2
* From Google Play or F-Droid?: F-Droid

Here's a logcat of the in my opinion relevant lines. Seems like some missing permissions. The contacts permission, however, is granted to the app.

[2018-09-17-17-14-13.txt](https://github.com/open-keychain/open-keychain/files/2389286/2018-09-17-17-14-13.txt)

If you need further assistance, please let me know.

**Comment by mase76** [comment]
I have this issue also on Android 8.1.

**Comment by ssdnvv** [comment]
I  have that very same issue on
Samsung Galaxy S7 Duos
Android 8.0, stock ROM rooted, patchlevel 01.Aug.2018

**Comment by IvanStanul** [comment]
Same issue on stock 9.0 ROM, security patch 5th of November on Pixel XL.

**Comment by richardnbanks** [comment]
I also have this issue.
Android 8.1.0 patch level 1 August 2018 (Android One)

Both standard and work profiles have this issue.

I have also tried revoking contact permissions, the app requests access but the option is not enabled after approving.

**Comment by AGithub457** [comment]
I am also having this issue
Pixel 2 XL 9.0 Stock, October 2018 security patch

**Comment by KabirKwatra** [comment]
Same issue, 
OnePlus 5T 9.0, December 2018 Security Patch

**Comment by doctormetal** [comment]
The same occurs on my Nokia 8.1 running Android 9 January 2019 patch. No problems on my Samsung Galaxy Tab S2 running Android 7. Both devices have version 5.2 installed from F-Droid.

**Comment by evil-rob** [comment]
Same on my Pixel 1 running Android Jan 5, 2019 patch level.

**Comment by bin101** [comment]
Same for me:

    Android Version: 9.0  Januar 2019 sec patch
    Device Model: Oneplus 6
    OpenKeychain Version: 5.3-beta3(53002)
    From Google Play or F-Droid?: Play Store Beta Programm

**Comment by gtalge** [comment]
Same issue here. I have Android 8.1.0 Kernel 3.18.71 
L212Vl13a. 

Didn't have this issue with 5.1.1 unless Openkeychain was stored on the SD card. When in internal memory it synced ok in 5.1.1

No such option to store apps on the SD card with 8.1.1.

**Comment by gtalge** [comment]
Sorry. Just found out you can store some apps on the SD card. However, I have not put Openkeychain on the SD card.

**Comment by gtalge** [comment]
Update:

Just did a security patch update and OpenKeyChain's contact sync feature mysteriously started working!

Android 8.1.0
Patch May 1, 2019
Kernel Ver: 3.18.71
 Build: OPM1.171019.019
L212VL15a

**Comment by KabirKwatra** [comment]
I'm on Android Pie (9.0) with the may security patch but I still have the problem

**Comment by gtalge** [comment]
I have no explanation of what happened.

I went into setting for apps and under access to contacts I turned off OpenKeyChain then turned it back on.

I then went into OpenKeyChain and set it to sync.

Then went back into settings under accounts and sync and told OpenKeyChain to sync now and it synced.

The app is in internal memory not on the SD card. I noticed on 5.1.1 the app would sync when installed on the SD card.

**Comment by schmitzel76** [comment]
Just tried this too on my phone running the May update of Pie. Toggling the permission for contacts seem to resolve it this time. Have tried this in the past and it never worked, but now it apparently does. Maybe it was an incompatibility that has been solved with the Android security update.

**Comment by httpLov3craft** [comment]
Same issue. OnePlus 7 pro on 9, and Essential PH-1 on 9

**Comment by Chartman123** [comment]
Yes seems to work for me, too. Should we leave the issue open for some time as there was no obvious fix?

**Comment by gtalge** [comment]
I don't think the issue should be closed yet, until they know what the cause was and until more users with the issue are satisfied the issue is solved.



On May 31, 2019 10:46:17 AM PDT, Chartman123 <notifications@github.com> wrote:
>Yes seems to work for me, too. Should we leave the issue open for some
>time as there was no obvious fix? 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/2395#issuecomment-497800379

-- 
Deo Vindice
PGP : AA33DFCC (2023/07/14)

**Comment by evil-rob** [comment]
> I have no explanation of what happened. I went into setting for apps and under access to contacts I turned off OpenKeyChain then turned it back on. I then went into OpenKeyChain and set it to sync. Then went back into settings under accounts and sync and told OpenKeyChain to sync now and it synced. The app is in internal memory not on the SD card. I noticed on 5.1.1 the app would sync when installed on the SD card.
> […](#)
> On May 31, 2019 7:53:30 AM PDT, Kabir Kwatra ***@***.***> wrote: I'm on Android Pie (9.0) with the may security patch but I still have the problem -- You are receiving this because you commented. Reply to this email directly or view it on GitHub: [#2395 (comment)](https://github.com/open-keychain/open-keychain/issues/2395#issuecomment-497738327)

This did the trick for me. I don't think toggling the permissions in the "App & notifications" settings was the thing that corrected the issue. It was turning on Account sync for OpenKeychain in "Accounts" under Android Settings that fixed things. I can't remember if the on-boarding for OpenKeychain prompted me to turn on account sync or not. It's possible that maybe it did and my paranoia about allowing apps access to my contacts made me choose not to. I'm inspired to remove the app and reinstall it to see if the that's what happened.

**Comment by Chartman123** [comment]
No, this alone can't be the reason as I did just enable account sync this week and it didn't help.

**Comment by protist** [comment]
FWIW my system hasn't updated since 1 Feb 2019, but toggling the permissions then turning on account sync works for me.

**Comment by schmitzel76** [comment]
If it isn't related to the security update, it might be related to Play Services, which does get updated regularly. Maybe Play Services had some issues on pie as it always worked fine on my tablet running nougat.

**Comment by Kaliaila** [comment]
I just installed this today, and even I had to do the permission toggle to get it to stop resetting and popping up the notification again.  Of note, this is not the first time that this has been an issue.  https://github.com/open-keychain/open-keychain/issues/1720  So it could be the same root problem just showing up again due to changes that have came with Pie.

**Comment by HuckToohey** [comment]
This has been plaguing me and if it doesn't  get resolved I may have to abandon the framework. Currently on Pie with One UI 1.5; Samsung Galaxy S10+. The notifications tray persistently says 'Access to contacts required'. Expanding the notification by pulling down reveals 'Touch to configure linking to contacts'. Touching notification opens app Settings, with Automatic key updates == on; Sync only on Wi-Fi == on [I'm connected]; and Link keys to contacts has reverted to off, after having turned it on the last time I went through this.  Conversations and K-9 Mail seem to work, and all the key management and crypto functions that I've tried are working. I've reinstalled a number of times. Last time was catastrophic since my full backup with secring was not where I specified, couldn't be found at all, when I tried importing after the reinstall that I went through in order to resolve this, unsuccessfully. In app settings I've manually ensured contacts-access permissions, in case the app has been unable to configure itself normally. Unsure what, if anything, I've missed. And this isn't documented except in bugs, isn't in FAQ?

**Comment by heinrich-k** [comment]
Problem also occurs on Nokia 6.2 with latest Updates/Security Patches...

**Comment by MartinX3** [comment]
Same issue on my Xperia XZ2 with LineageOS 17.1 based on the Sony Open Devices Project.

**Comment by AlekEagle** [comment]
I got the issue here too, running Android 10 on a Samsung a11

**Comment by PhSnake78** [comment]
Same here Samsung Galaxy S10+, Rooted (Exynos) Android 10

**Comment by Valodim** [comment]
I'm curious, is contact sync a valuable feature to you in practice?

I've been considering removing the feature altogether (#2586), precisely because 1) we haven't kept it up to date and it deteriorated over the android versions, and 2) it's not clear to me what value it really brings for the user.

**Comment by Chartman123** [comment]
Nice point... I think it's not really needed and as it causes more problems than it does good... So for me it would be ok to drop the feature 👍🏻

**Comment by heinrich-k** [comment]
So, I've never seen the feature in action, but I'd like a feature, where the app would automatically scan my contacs and search for keys for them automatically. And, once I've selected a key for a contact, would probably save that key in the contact...

**Comment by ssdnvv** [comment]
For me it works - installed openkeychain, imported my keys and after that imported my contacts (via CardDAV). The contacts with public key available got directly synced successfully.
Sony Xperia XZ2 compact, LineageOS official.
I really missed this feature on my previous smartphones (Xperia z3 compact, Samsung Galaxy S7 duos) and am happy that it s now working correctly - so please keep this feature!

**Comment by Valodim** [comment]
As we can see from this issue, the feature also causes problems on several devices. Dominik and I have no time to work on this (blog post upcoming on that), and I'd rather remove it altogether than leave it in broken. Any volunteers to work on this?

**Comment by protist** [comment]
@Valodim Hope all is well with you.

For the record, I find this feature useful. It was also broken for me until I followed @gtalge's workaround [above](https://github.com/open-keychain/open-keychain/issues/2395#issuecomment-497746412). After doing that once, it has been working perfectly for me for the last 15 months. It would be a shame to remove this feature, given it's working for some out-of-the-box, and working for others after a simple toggle of the settings.

**Comment by Valodim** [comment]
Can you elaborate on how you used it? I found I haven't ever actually "used" contact sync myself, in the sense that it helped me *do anything* with it. It's mostly just.. been there and looked nice. That's why I wonder.

**Comment by protist** [comment]
Good to know @Valodim. So hard to know what could be problematic nowadays!

I think I was under a misapprehension about what contact sync actually did. I thought contact sync was required when composing a new email in K-9, to find the associated key .

However, I disabled sync and unlinked a contact, and K-9 was still perfectly fine. What does contact sync actually do? Is it just for Android's contact app, where it just provides a link to OpenKeychain? If so, then yeah, probably not a big deal. It's nice to see the contacts with keys in the native Android contact app, but I could just as easily use OpenKeychain directly instead.

**Comment by gtalge** [comment]
What contact sync does.

When you use the mail program K-9 Mail, and you compose an email to someone on your contact list, and they are contact synced to Open-keychain, a little padlock icon appears and gives you the option to encrypt and sign your message.

If the contact is not synced with Open-keychain then no such options are given



On September 6, 2020 6:46:31 AM PDT, protist <notifications@github.com> wrote:
>Good to know @Valodim. So hard to know what could be problematic
>nowadays!
>
>I think I was under a misapprehension about what contact sync actually
>did. I thought contact sync was required when composing a new email in
>K-9, to find the associated key .
>
>However, I disabled sync and unlinked a contact, and K-9 was still
>perfectly fine. What does contact sync actually do? Is it just for
>Android's contact app, where it just provides a link to OpenKeychain?
>If so, then yeah, probably not a big deal. It's nice to see the
>contacts with keys in the native Android contact app, but I could just
>as easily use OpenKeychain directly instead.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/2395#issuecomment-687793758

-- 
PGP : AA32DFCC (2020/07/14)

**Comment by Valodim** [comment]
> I think I was under a misapprehension about what contact sync actually did. I thought contact sync was required when composing a new email in K-9, to find the associated key.

Interesting. You're perfectly right, contact sync only affects how keys are shown in contacts, it has nothing to do with K-9 Mail.

> If the contact is not synced with Open-keychain then no such options are given

Those mechanisms are entirely independent, I would be surprised if that was true :)

**Comment by protist** [comment]
> If the contact is not synced with Open-keychain then no such options are given

@gtalge I [tested this](https://github.com/open-keychain/open-keychain/issues/2395#issuecomment-687793758), and it seemed to link fine without contact sync on.

> contact sync only affects how keys are shown in contacts

@Valodim In that case, it's less useful than I had originally thought.  I agree that it's "nice to have" and easier to access contacts, but realistically not something I use that often personally.

**Comment by gtalge** [comment]
Yes, openkeychain will work without contact sync.

What I ment was, that if you start out to compose a message in K-9 Mail, and you have your contacts synced, you will see a little padlock option up in the upper right corner giving you the option of encrypting your message.

If the contact does not have a pgp key on your ring,  then no so such option appears.







On September 6, 2020 4:21:03 PM PDT, protist <notifications@github.com> wrote:
>> If the contact is not synced with Open-keychain then no such options
>are given
>
>@gtalge I [tested
>this](https://github.com/open-keychain/open-keychain/issues/2395#issuecomment-687793758),
>and it seemed to link fine without contact sync on.
>
>> contact sync only affects how keys are shown in contacts
>
>@Valodim In that case, it's less useful than I had originally thought. 
>I agree that it's "nice to have" and easier to access contacts, but
>realistically not something I use that often personally.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/open-keychain/open-keychain/issues/2395#issuecomment-687931022

-- 
Deo Vindice
PGP : AA32DFCC (2020/07/14)

**Comment by protist** [comment]
@gtalge I'm not sure if I have some residual linkage on my system, but I actually see the opposite.

* My contact has a key in OpenKeychain, but I have disabled contact sync.
* In Android's address book, my contact does *not* have a linked OpenKeychain profile.
* In K-9 Mail, if I compose an email to that contact, I can still see the padlock option in the upper right.

**Comment by Valodim** [comment]
Right, K-9 Mail does not depend on contact sync. The key just has to be in OpenKeychain's list of contact keys :)

Altogether, looks like contact sync can go. Thanks for your input everyone! :tada:

**Comment by hoamyj** [comment]
The Google Contact non-Syncing issue is caused by the incompatibility of the Google Contact(sync) with the Google framework/Google play installed. 
Try to find and install the different version of the Contact app until the syncing starts.
Besides Google app store, there are many Android  app markets that you can find different version of the Contact Sync app. You will find one finally if you are lucky. I finally found the suitable one from Huawei apps Gallery. 😉
