### ISSUE TITLE
Security Tokens wiki page readabilitly

### ISSUE THREAD

**Issue by wsygog** [open-keychain/open-keychain#2401]
Currently the [Security Tokens wiki page](https://github.com/open-keychain/open-keychain/wiki/Security-Tokens) uses 𐄂 (http://graphemica.com/%F0%90%84%82) for the X mark, but [this](https://i.imgur.com/7f3HdIs.png) is how it renders on my system, and I'm probably not the only one. I propose using ❌ (https://emojipedia.org/cross-mark/) instead.

**Comment by dschuermann** [comment]
done
