### ISSUE TITLE
keybase proofs

### ISSUE THREAD

**Issue by sbriskin** [open-keychain/open-keychain#2406]
List of keybase proofs duplicates entries

**Comment by wiktor-k** [comment]
I've seen this once or twice but can't replicate now. Could you provide a screenshot and/or the key in question? (also standard stuff like OKC version)

**Comment by sbriskin** [comment]
After the last beta update i can't replicate it too.

**Comment by wiktor-k** [comment]
Hmm... then it's either fixed or hard to replicate :)

Maybe it's good to close the issue and re-open if there are new cases of this bug?

**Comment by Valodim** [comment]
sounds reasonable

**Comment by sbriskin** [comment]
I figured it out. Pressing the "update key" button inside the key card results in multiple entries.
