### ISSUE TITLE
Can't decrypt BCPG 1.60 Messages

### ISSUE THREAD

**Issue by d-t-o** [open-keychain/open-keychain#2413]
My bank recently updated their pgp infrastructure in an attempt to support MDC. They changed their key ( https://www.1822direkt.de/pgp5key.asc ) and went from Cryptix OpenPGP to BCPG 1.60. Since then I can't decrypt their messages anymore that they send, encrypted with my public key. The decryption works fine with Thunderbird + Enigmail, but K9 + openkeychain can't decrypt them. I tried decrypting the message body from clipboard to make sure K9 is not involved in this issue, but I only get the message

"no encrypted data with known secret key found"

Not quite sure why, since on my end my keys stayed the same.

## Expected Behavior
BCPG decryption is possible

## Current Behavior
"no encrypted data with known secret key found"

## Steps to Reproduce (for bugs)
1. try to decrypt the message below
2. get error message

## Your Environment
* Android Version: 7.1.2
* Device Model: redmi 4x (santoni) on resurrection remix
* OpenKeychain Version: 5.2 52009
* From Google Play or F-Droid?: google play store

The problematic message:
```
-----BEGIN PGP MESSAGE-----
Version: BCPG v1.60

hQIMA50n90XpDXX/AQ/8D4nMnHxTpVjkuPRmhyq2Sobjw+SDH5MgNR6VbfVyaXwI
G09eyIYr8XiG+d9memcYe4MMR6XBReDaS4xEACt6EBUJAqhye7RQQoVBtYF8QP9d
5eg/un0ISjIKfKct8jch5cQE0cE/EmBKFqNOFC1B0mda1T49ZIdaEddWraS5yf6W
1PfNz2XcefGSfzHNodjcakzCms/AqqBk2Jh4vk0tJJDxjmaAN52zDIzhjy61vQ7z
mFB3kahi4pJ2UzeJ4HF5wZx+2dgeqwPkVGMB+fMEPXnd3trkOKLlrYBocjsDDrIB
LSNO3pe17xhSdiyIvb2MDszTdmfADxFBVlLNDuBcxuVjUR44iEz8LXz5gi2HCpx/
JSkJJUbp+AEcCZ8k3kgP8t41d2XBS5EZ3QRXvv2/id2I2DbG/phc6sEPY3x6UJMN
CPY2o/3lK3JhKFO9vrCdcKkRLAK3ijP+ECbk8meFq504YY5YddN9ybjGDmmpo6po
7vQgHt+s8HXz+QZQJ8n4KJLSdi1Q3wvDv9nBKDJqIYWF5Ho0xng0zEOLSzarYPdL
LR+fJzkeBU6Cyls+JIBeGvOhbqRg0lMCqG/ZqlHX1ONExqXi2yHU3RsASTZew2Br
VFiZ4AfmXCLYRELeUzpupoa29ACGKfCkCWOlUnIVXYj2Sa2ntiU0SgqO/T9PwFjS
waYBrKkrNQIKpoMbYN8DHLIHaThtVUtTYwE6xYmnhoOz0raODFzvjvNrTg2Czi4x
lrodAqnhEKYHX9rqhPtFM1cQiZGTJxYFgWCtPD8U86Ljxfp/ND0XXNpf4KXAdaZf
zSeeBul3BW85cnDZ4YGpQCKbR4sPl1M4AUlMIuGXSjkY+MgZjLtg3XbzwCM+1jpu
HcORALY09kO6fQTIFkIPuXbnQMYj1uk+eRVy2sgh9BGMqsTVdYiSDlaj90YgspFQ
Zjf/4OOVTporQ7FWUt6atI2y8BnCBO6nDkC6fP8sh6E5BMdqjw7tFZAEpy5sGxvM
mg+/8hkToMivajYFb0FxJZxp0eOYpPqJvNGlw8cRQhdMiJ6PwZhFV+pFscQ5Hwwp
Q1ovyYSiBzcVlmLVtjeLoYVtHLlkGYf20IZpwTJ8ld40R6Gnw3cvOYwbfN6rwE4r
Ol2mqTYI9vX1SVCL2svMXG2lPAqfA+/y6pYh2tIOmZNtkQDeRoaMdFfBmCQXF8Xq
Y4WssjFTDJmAmexZRypu5yVxF+FxPgNbzzRQjjsvo5BqDOp/6taZuhovCI7czf0f
FsYMtKrZeB6QIadTvioVgf4YeJJ9PikPqpEM/BUt7ZpQsBofcZLsKAYFTJZShIms
SZalQdg9aDkseeZKKhLO+9QECXU2puUnZ1PnkUIKMmbDZ3oqlIkOb6E3XnBbvLj2
Jsu6k3NjwHSi88Ca37/7AtOKVJ2Dv1Hm5xa6oEpYce2GV3/YxNrXa87859wlr5Z7
9D7Dhgf6EJMQgdCi1EbTAZeH1mGXlxPfy8zlP2xW2hWkoHTfEMBP/w==
=ofKw
-----END PGP MESSAGE-----
```
Infos about my public key:
```
:public key packet:
        version 4, algo 1, created 1463182997, expires 0
        pkey[0]: [4096 bits]
        pkey[1]: [17 bits]
        keyid: 9D27F745E90D75FF
:user ID packet: "<my mail address>"
:signature packet: algo 1, keyid 9D27F745E90D75FF
        version 4, created 1463182997, md5len 0, sigclass 0x13
        digest algo 2, begin of digest 8a 38
        hashed subpkt 2 len 4 (sig created 2016-05-13)
        hashed subpkt 27 len 1 (key flags: 23)
        hashed subpkt 9 len 4 (key expires after 5y0d0h0m)
        hashed subpkt 11 len 5 (pref-sym-algos: 9 8 7 3 2)
        hashed subpkt 21 len 5 (pref-hash-algos: 8 2 9 10 11)
        hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
        hashed subpkt 30 len 1 (features: 01)
        hashed subpkt 23 len 1 (key server preferences: 80)
        subpkt 16 len 8 (issuer key ID 9D27F745E90D75FF)
        data: [4095 bits]
:public sub key packet:
        version 4, algo 1, created 1463182997, expires 0
        pkey[0]: [4096 bits]
        pkey[1]: [17 bits]
        keyid: 6E695BC4304554A2
:signature packet: algo 1, keyid 9D27F745E90D75FF
        version 4, created 1463182997, md5len 0, sigclass 0x18
        digest algo 2, begin of digest d9 33
        hashed subpkt 2 len 4 (sig created 2016-05-13)
        hashed subpkt 27 len 1 (key flags: 0C)
        hashed subpkt 9 len 4 (key expires after 5y0d0h0m)
        subpkt 16 len 8 (issuer key ID 9D27F745E90D75FF)
        data: [4094 bits]
```

**Comment by Valodim** [comment]
Thanks for this detailed report!

```
gpg: encrypted with RSA key, ID 0x9D27F745E90D75FF
gpg: decryption failed: No secret key
# off=0 ctb=85 tag=1 hlen=3 plen=524
:pubkey enc packet: version 3, algo 1, keyid 9D27F745E90D75FF
	data: [4092 bits]
# off=527 ctb=d2 tag=18 hlen=3 plen=614 new-ctb
:encrypted data packet:
	length: 614
	mdc_method: 2
```

The message is encrypted to your primary key (9D27F745E90D75FF), not the subkey (6E695BC4304554A2). However the flags of the primary key indicate that it should only be used to certify, sign and authenticate (key flags 0x01+ 0x02 + 0x20 = 0x23). It's cryptographically necessary to respect those flags, and OpenKeychain is doing the right thing not decrypting things that were encrypted to a subkey that wasn't meant to be used in this way. Allowing an attacker leeway like this is exactly what leads to issues like Efail. Your bank seems to take a rather "let's just shuffle things around until they work" approach to their crypto.

It's also a bug that gnupg decrypts those messages. I'll make a report about that. :)

**Comment by Valodim** [comment]
Your key is perfectly fine, it's a typical key as OpenKeychain or GnuPG would generate by default. Primary keys can be used for encryption, but are typically not, so your bank is indeed behaving incorrectly with this common key configuration, and the (fairly minor) bug in GnuPG masks that issue. I suspect the programmers at your bank just shuffled things around until they worked with GnuPG. I made a report to GnuPG [here](https://dev.gnupg.org/T4235).

The "foolproof key" solution you propose would indeed work (ignoring the sadness that such a tactic would be necessary with a bank).

**Comment by d-t-o** [comment]
@Valodim I gave them a supposedly idiot-proof key with just a primary key:
```
:public key packet:
        version 4, algo 1, created 1540674138, expires 0
        pkey[0]: [4096 bits]
        pkey[1]: [17 bits]
        keyid: 7C67454FE00D5098
:user ID packet: "my mail address"
:signature packet: algo 1, keyid 7C67454FE00D5098
        version 4, created 1540674138, md5len 0, sigclass 0x13
        digest algo 2, begin of digest b4 b0
        hashed subpkt 2 len 4 (sig created 2018-10-27)
        hashed subpkt 27 len 1 (key flags: 0F)
        hashed subpkt 9 len 4 (key expires after 5y0d0h0m)
        hashed subpkt 11 len 5 (pref-sym-algos: 9 8 7 3 2)
        hashed subpkt 21 len 5 (pref-hash-algos: 8 2 9 10 11)
        hashed subpkt 22 len 3 (pref-zip-algos: 2 3 1)
        hashed subpkt 30 len 1 (features: 01)
        hashed subpkt 23 len 1 (key server preferences: 80)
        subpkt 16 len 8 (issuer key ID 7C67454FE00D5098)
        data: [4095 bits]
```
and now they send me this
```
-----BEGIN PGP MESSAGE-----
Version: BCPG v1.60

hQIMA3xnRU/gDVCYAQ//WvIP9Bv9+Y9KUd5NW50tTCjiwhgBP3K+bwtxLIzohUic
w/0S0f75cev9MWII5/tbJkn4ybtQu6P+I05iC78ery54PyMKTslunxv6G2jCPtfK
sRhgagYkPOmiUIZJpu5cS19EJguEGwno4DElNJVmmfRutletqHxOAHuEnOfdH5n2
O4EPxbafmmtHoGDg8rpLwkZe91h9wHq1QsvxENgc4EUC0zjsX+5aIZCYqugWjDYX
lM0zc+d2ZYVQ4Gd5EPIRxN3MDFsxFx5v5d8TQ2KRj3tlMHNnMh+2w4655TD+YTJ0
YT/MSUnPoGjCUKL9SPyd1O6BLD2RkHPavBXki27wVoETev2SQouxDIEeEiP5aREL
S3Tdd3mG4nCDjmd+npVNZubCk4+F78JblmwzITdDS+JkHYpyPHyVl2IdBM1nhV65
K1tPn1mgu3SWUpp4Vsr4BOER24qdOZl2bAx/6Gg4fULCaYjzk/Affqzx7PtowDF4
49+gFZA/PbQpqcCV2pi7uQZUyyXhqpgRTysRagaUzwmL/ZbZ+rj1sJyv59lDKyj2
241N/sSk1UDUvGVtORS/RWRbvNJbmzg50cU+xWgiNgyRVKGYySqEIBn69tGhPVbf
fERIm5MMo8p+m167YuCMRQ8ksO9le9aTKfVNYOS533dUXIi3FBaHNdinjFpYE8HS
wa0BinVL7cIP6upHRtrjv/bBbQ4L2kVLCywCYk8TcxkoAbZFCpnTTvZeKTb6kkBu
keDsEA25sT1wLx5V/PBNHr5y/Ai8f1UKF3DjuWQgNFRZbYB9mMZdrSgpnn+S5mQL
ccAxcr0b7/lEwj1IE2ygN0dpwKEFoUFySK91/tkz6EZNWOBBG3sfEodbPfMI82AZ
R+Kzqfa6RmzjlXhXBGlmAzr2hY36CNyryKkdGRTdhGEn9PgGHoXXTO3TAYvSxUqH
QGOOvVk6eq6Xc6PGMgPyXI177vQNMSxagahWG9eJq0eV3r5BxldshldCGQhIelEI
jhpq91DQLdx4G7cpw4G7fNyxAXGKQ/f8BlgVllbf0pNAX8tbMqd8U9wIe+eo+Xc1
kd0ZzQRD2sYr6hd7ocIbDTGMeaGzQIy1tM4+PpoWiRbdXTqLAkMFysWd9BrLkAUK
YosevZFH4CeceSrM4DJfS0UnmLmKxryLsMGqAm839Q9erUIg0/7Xprlh46TTkDxn
TaceFDx1POgzA3NRdIaols2VjqI7b5wA2ZOcXXHY/bpNRuqIhKrOnAy7S3TX5XOG
Dus51LVh9BZmJaDbWKHppOEDgt3u4zis0splaZQAc+6Zgxum4ygHpwatt6hufYMn
lnfA6K9hB34BrDYhBbqG1eQr47nNUGBNEi+vOSlpYhbrRgzytzK3e5rryBcdxwHB
bpvMXMt4IbZKvu9ljzFFuSX3wl/BYkiwYJMmh3ouGf5os43scOUwshVqvQS75O1j
2ThfVPbAmL4RC8CHD5Nmdm8E02PjtQKmxnjhv2+u8OliDuOrJZJFk5eqonXlYLQ=
=35e+
-----END PGP MESSAGE-----
```
I'm one step further now since openkeychain unlocks that key and starts 'Processing literal data' but this step ends with the error message 'Missing signature data!'.

Can you confirm that this is a valid point from openkeychain and stopping there is the right way to handle this? Enigmail once more decodes this without complaints :unamused:

**Comment by Valodim** [comment]
Can you do `gpg --list-packets` on the file?

**Comment by d-t-o** [comment]
sure:
```
gpg: armor header: Version: BCPG v1.60
:pubkey enc packet: version 3, algo 1, keyid 7C67454FE00D5098
        data: [4095 bits]

gpg: public key is E00D5098

You need a passphrase to unlock the secret key for
user: "my mail address"
4096-bit RSA key, ID E00D5098, created 2018-10-27

:encrypted data packet:
        length: 621
        mdc_method: 2
gpg: encrypted with 4096-bit RSA key, ID E00D5098, created 2018-10-27
      "my mail address"
gpg: AES256 encrypted data
:compressed packet: algo=1
:onepass_sig packet: keyid BF670FDA2FFBD7A8
        version 3, sigclass 0x00, digest 10, pubkey 1, last=1
:literal data packet:
        mode b (62), created 1540891810, name="_CONSOLE",
        raw data: 1128 bytes
```

**Comment by Valodim** [comment]
The encrypted data here contains a "onepass_sig" packet that basically says "the following data is signed by this key with the following hashing algorithm. the actual signature will follow after the data". And then, no signature follows. It appears that your bank tried to sign the data with [their key](http://keyserver.ubuntu.com/pks/lookup?search=0xBF670FDA2FFBD7A8&op=vindex) but failed to actually do so.

And once again, OpenKeychain rejects fishy packet structures, while GnuPG doesn't care and probably just treats the data as unsigned.

**Comment by wwender** [comment]
I have the same issue with the same bank :) . The most comfortable way would be to allow fishy packet structures with a separate confirmation by the user. (Yes I agree comfortable but insecure)

**Comment by dschuermann** [comment]
I just contacted the bank via email and am waiting an answer. We should simply fix that on their side.

**Comment by wwender** [comment]
I also contacted the bank. Lets make sure they get the message. (However as always I guess the number of people complaining will be far too less for a fast change cause people really interested in security are always a small minority. )

**Comment by dschuermann** [comment]
Their answer: "Gerne beantworten wir Ihre Frage. Wir konnten den Fehler bereits lokalisieren und sind um eine schnelle Behebung bemüht. Wir bitten um Ihr Verständnis, dass wir Ihnen aktuell noch keinen Termin zur Behebung nennen können."

**Comment by wwender** [comment]
Similar answer to me: ..."Wir konnten den geschilderten Sachverhalt reproduzieren und werden uns schnellstmöglich darum kümmern. Wir bitten um Ihr Verständnis, dass wir Ihnen aktuell keinen verbindlichen Termin nennen können bis wann der Fehler behoben ist. Für die entstandenen Unannehmlichkeiten bitten wir Sie ausdrücklich um Entschuldigung."...

**Comment by Valodim** [comment]
That's actually a pretty good response. Nice to hear. :+1:

**Comment by sicherist** [comment]
I just encountered the same problem and I'm pleased to see you have already figured out what the cause is. 

@dschuermann  @wwender @d-t-o Did you find a workaround for the meantime until the bank fixes the problem?
