### ISSUE TITLE
Gladle sync failed in a android studio

### ISSUE THREAD

**Issue by HackM3nt3** [open-keychain/open-keychain#2416]
I am trying to sync the code with android studio but i always got these errors

Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Configuration 'testCompile' is obsolete and has been replaced with 'testImplementation' and 'testApi'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Configuration 'testApi' is obsolete and has been replaced with 'testImplementation'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

Unable to resolve dependency for ':libkeychain@debug/compileClasspath': Could not resolve project :openpgp-api-lib.
Open File
Show Details

What do i have to do to make it work?  Do i have to change the build.gradle upgrading the code changing those words or what? please somebody

**Comment by hagau** [comment]
```
Unable to resolve dependency for ':libkeychain@debug/compileClasspath':
  Could not resolve project :openpgp-api-lib.
```
Did you run ```git submodule update --init --recursive``` in the project root directory like mentioned in the [README.md#build-with-gradle](https://github.com/open-keychain/open-keychain/blob/master/README.md#build-with-gradle)?

**Comment by HackM3nt3** [comment]
thanks, it worked perfectly
