### ISSUE TITLE
Help recovering private keys, after uninstall

### ISSUE THREAD

**Issue by benjjyman** [open-keychain/open-keychain#2424]
Help Girl friend accidentally uninstalled openkeychain, I have grabbed an image of the memory inside the phone including operating system, and blank unallocatted space before anything gets overwritten.
My problem is that I know the keys were held at /data/data/org.sufficientlysecure.keychain/databases/openkeychain.db

The image is in raw format can anyone help me locate these keys, I dont want to lose them.

Thankls

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version: 
* Device Model: 
* OpenKeychain Version: 
* From Google Play or F-Droid?:

**Comment by Grossdm** [comment]
Raw image?

Do you mean Nandroid?

Help others to help you...
