### ISSUE TITLE
Youbikey 5 NFC support

### ISSUE THREAD

**Issue by sestus** [open-keychain/open-keychain#2429]
I am trying to use open-keychain with my new Youbikey 5 NFC. When I touch my Youbikey in the NFC reader of my phone (my youbikey has 3 keys installed, uploaded to the public servers and is working properly on my laptops), i get a "Key not found!" message so I am not able to import my keys.

Is Youbikey 5 NFC not supported? If so, I would like to contribute, could you please point me to the right directions?

Thanks in advance.

**Comment by sestus** [comment]
Ignore that. It's working fine

**Comment by ndrewtl** [comment]
@sestus, if you don't mind, could you tell me what got this working? I'm getting the same error message with a Yubikey 5 NFC and I'd like to know what fixed your problem

**Comment by sestus** [comment]
Hey @ndrewtl . I think the problem back then was that I haven't uploaded my public key to a keyserver. Apparently, that's a requirement. Hope it helps!
