### ISSUE TITLE
German Translation for send/share: canot distinguish between encrypt and decrypt on small screen

### ISSUE THREAD

**Issue by k3b** [open-keychain/open-keychain#2434]
When i want to share an encrypted file i see "Mit OpenKeychain..." and "Mit OpenKeychain..." : The most important word "verschlüsseln/entschlüsseln" (encrypt/decrypt) is at the end of the string is cut off on small screens in the send/share menu.

Can you change this from "Mit OpenKeychain ver/entschlüsseln" to "Ver/Entschlüsseln mit OpenKeychain " ?

**Comment by dennis-mb** [comment]
![grafik](https://user-images.githubusercontent.com/36963191/54271217-63dc7200-4581-11e9-82bd-5a1c4310f5cc.png)
The same is for "Schlüssel mit Openkeychain" ...

**Comment by dennis-mb** [comment]
Let me suggest:
(Sorry for not providing in diff or transifex format)
```

 <!--Intent labels-->
  <string name="intent_decrypt_file">Entschlüssle Datei mit OpenKeychain</string>
  <string name="intent_import_key">Importiere Schlüssel mit OpenKeychain</string>
  <string name="intent_send_encrypt">Verschlüssle mit OpenKeychain</string>
  <string name="intent_send_decrypt">Entschlüssle mit OpenKeychain</string>
<string name="intent_autocrypt_setup">Importiere Autocrypt Setup-Nachricht</string>

```
Taken from:  open-keychain/OpenKeychain/src/main/res/values-de/strings.xml (ff55287) lines 585..

**Comment by dschuermann** [comment]
Fixed on transifex, thanks

**Comment by k3b** [comment]
perfect. thanks a lot
