### ISSUE TITLE
Why is there no longer the promt to set a passwort at key creation?

### ISSUE THREAD

**Issue by SebiderSushi** [open-keychain/open-keychain#2439]
## Expected Behavior
When creating a key, OpenKeychain promts to specify a key password. This can be skipped.

## Current Behavior
The setup proceeds to key creation without mentioning any key password. Instead, the feature is sort of hidden away under "Change key configuration". 

## Context
A new user may be unaware of the ability to set a key password for protection and is probably rather unlikely to dig into advanced options. This vital feature of gpg should be presented directly to the user right away upon key creation to enable protection from the first moment.

## Your Environment
* OpenKeychain Version: 5.2 (52009)
* From Google Play or F-Droid?: F-Droid

**Comment by dschuermann** [comment]
This is a deliberate design decision.
