### ISSUE TITLE
[FEATURE REQUEST] Integrate PEP (Pretty easy privacy)?

### ISSUE THREAD

**Issue by CryptoStar2000** [open-keychain/open-keychain#2440]
Hi there, would it be possible to integrate PEP (Pretty Easy Privacy) to OpenKeyChain as well? Its also available on FDROID and its open source. That would be great since K9 could remain only eMail app then.

**Comment by dschuermann** [comment]
Currently this is not planned, sry.

**Comment by pravi** [comment]
@dschuermann can this be reconsidered. PEP makes encryption really easy and this will be a very important feature. PEP already supports importing a key. But currently it means creating a backup, then decrypting the backup and then importing the key to pep app. If Open Key Chain allows a direct export to PEP, that will really go a long way for people switching to pep. Between the decryption does not work with split screen on Android 10, that is probably another bug.
