### ISSUE TITLE
Signature generated by OpenKeyChain can not be verified

### ISSUE THREAD

**Issue by dawin1981** [open-keychain/open-keychain#2446]
I've created key and imported into OpenKeyChain, and tried to use the OpenPGP API example to do DETACHED SIGN test, the signature was given out successfully. I verified the signature using GnuPG on PC where I generate the key but failed with "BAD signature".

## Expected Behavior

Signature verify should be ok.

## Current Behavior

Signature generated by OpenKeyChain can not be verified by GnuPG.

## Steps to Reproduce (for bugs)

1. gpg --openpgp --expert --full-gen-key
2. gpg --openpgp --edit-key KEY-ID and add sign subkey
3. gpg --openpgp --export-secret-keys --armor KEY-ID > file
4. Import file to OpenKeyChain
5. Use OpenPGP API to test "DETACHED SIGN" function for a text string.
6. Save the signature to a file and transfer to PC, file name is test.txt.asc.
7. Create a file with the text string which is signed by OpenKeyChain, file name is test.txt.
8. Use GnuPG to verify signature:  gpg --verify test.txt.asc test.txt

## Your Environment

* Android Version: 8.1
* OpenKeychain Version: 5.2 
* gpg (GnuPG) 2.1.11

**Comment by DDoSolitary** [comment]
Hello, I just encountered the same problem. Have you solved it?
