### ISSUE TITLE
Ubuntu Keyserver Certificate

### ISSUE THREAD

**Issue by OnSerious** [open-keychain/open-keychain#2461]
## Expected Behavior
Ubuntu Keyserver is set as standard keyserver to check, upload, revoke PGP Keys generated on phone

## Current Behavior
Keyserver is not reachable, Certificate Error. Can not check, upload, revoke PGP Keys on Ubuntu Keyserver. 

## Steps to Reproduce (for bugs)
Use Google Play Beta or FDroid Version, this happens directly out of the box.

## Possible Solution
Ubuntu Keyserver has new certificate which was generated on 12th May 2019 and is valid till 9th August 2019. - Change DigiCertGlobalRootCA.cer to new Certificate and make new build. - Already done this for myself and build a new apk. Now it is working on my Samsung S8+

Replace everything in DigiCertGlobalRootCA.cer to:
-----BEGIN CERTIFICATE-----
MIIFYDCCBEigAwIBAgISAwfBM5AzqhaMKV4GxVX5hy2/MA0GCSqGSIb3DQEBCwUA
MEoxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MSMwIQYDVQQD
ExpMZXQncyBFbmNyeXB0IEF1dGhvcml0eSBYMzAeFw0xOTA1MTIwMjA5NTlaFw0x
OTA4MTAwMjA5NTlaMB8xHTAbBgNVBAMTFGtleXNlcnZlci51YnVudHUuY29tMIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5+M+Y9zdQJ77XHNgfKzI31yK
B8KWdAqgSL12iCreN5XK7yzbc7JbxdkxtmPiZrRcI02mCkOXbESCFU/qa+/jhTIm
UxyOOmrZ/S3LrrNSKPbyfGMEf2EyTjHjtq2mCvsA2jM72ovHoct1bpmm3yOmN+fy
xni3RYewW/tGwyw/YW2j+SD8bTtIg8gA0VVxgpYoMp98SP8vYxtDq7/syF2dT7PJ
l/9Xt97rm8Kl6h+T9LI1/S6dzOXtnSQyjRgK5ojV6N+ga3AsJBZaXubD5XclEcIy
gpkebwyNFeSLwM2MqBwCsnrOAgP1pfrztq5mHHKGaC5FlLZq/zB9nWXGvSHSGwID
AQABo4ICaTCCAmUwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMB
BggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTjgAdsUoyG/Ae3mw/X
Dwt6COwI8jAfBgNVHSMEGDAWgBSoSmpjBH3duubRObemRWXv86jsoTBvBggrBgEF
BQcBAQRjMGEwLgYIKwYBBQUHMAGGImh0dHA6Ly9vY3NwLmludC14My5sZXRzZW5j
cnlwdC5vcmcwLwYIKwYBBQUHMAKGI2h0dHA6Ly9jZXJ0LmludC14My5sZXRzZW5j
cnlwdC5vcmcvMB8GA1UdEQQYMBaCFGtleXNlcnZlci51YnVudHUuY29tMEwGA1Ud
IARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0
dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDw
AHYA4mlLribo6UAJ6IYbtjuD1D7n/nSI+6SPKJMBnd3x2/4AAAFqqgTCVQAABAMA
RzBFAiBnVWPp+b8M6uUqI3/to7aRWmobtlUFKZyIC74/oBiuuwIhAJwMBi/BSyjV
isYR0BvSRCEQxSQCOehuGshJm9nmbSHpAHYAKTxRllTIOWW6qlD8WAfUt2+/WHop
ctykwwz05UVH9HgAAAFqqgTCSAAABAMARzBFAiAegQJ3Eq3aviZwWYJk2d6Iib2i
APKiGhyBE1Ez71/xLwIhALID/BmFla4+r24IQcwkdd0+HyD+dMmxOkkfd3ptTZUS
MA0GCSqGSIb3DQEBCwUAA4IBAQBfg28gfqZDK79qSwxS/TpBb1Xfa9faj0zL12vr
msWTLfVJ4fa/P+Ft/PZzuUq8eKjgPPJuACTi8appOWVwkr4d+OxsAYiNyeQ4DOCJ
7avViyaSPeafNhHygI8JBuOjzzRAAaoXea9SJQg5mRmbLMkQ0HahWDsGBSabKniq
/b8yVHQT74F87h9fSFe9zn3BjI1HFlW7KdRrQ4TfrxyXFCl4iX6KezLhoRLVlmd6
nPBTy7/pb0ig0qhXjfEwWuveGqvdBzCZsl3ADhe28hc1hA3Ek9RWLo8lv8rg5ucc
f1RHtK+NmPC8G1p2xWHDPuS72MiPkjsbMWib4A/bj17ihDCR
-----END CERTIFICATE-----

**Comment by wiktor-k** [comment]
@OnSerious If you did that and it works maybe submit a PR? I guess it's less work for project maintainers to review a PR than to do the job themselves.

**Comment by dschuermann** [comment]
fixed in https://github.com/open-keychain/open-keychain/commit/adcb39b5c831f8a7cb9ef6a01ddeaae2e202e878 and released in 5.3
