### ISSUE TITLE
Setting linkage to contact list problem

### ISSUE THREAD

**Issue by alexandre1985** [open-keychain/open-keychain#2465]
I'm trying to enable the option Linkage of keys to contacts that is on Configuration > Synchronization > Linkage of keys to contacts
I can set it, but when I quit the app and, after passing some time, I got back to the app, that configuration is maggically disabled.

## Expected Behavior

When setting this option if it is not supported somehow it show message an error to the user on enabling the feature.
If this option is supported on all androids and there is no way that this option cannot work, then it should not disable automagically this option after some time.

## Current Behavior

After enabling the option, exiting the app and waiting some time, when I go to the configurations to see if this option is enabled, it is not.

## Possible Solution

See Expected behaviour

## Steps to Reproduce (for bugs)

1. Open OpenKeychain
2. Configuration > Syncronization > Enable "Linkage of keys to contacts" option
3. Exit OpenKeychain
4. Wait some time
5. Recheck Configuration > Syncronization menu panel

## Context

I'm trying to experiment this option to see what it does and if I want to use it

## Your Environment

* Android Version: Oreo 8.0.0
* Device Model: Samsung Galaxy J3 - SM-J330F
* OpenKeychain Version: 5.2
* From Google Play or F-Droid?: F-Droid

**Comment by trainmeditations** [comment]
I'm having a similar problem in Pie, except just leaving the settings screen and reentering shows the feature is disabled. It was constantly notifying me to enable it but I was able to get it to stop asking me.

**Comment by Grossdm** [comment]
@trainmeditations,
Please share how you were able to get OpenKeychain to stop this problem.
I would be very grateful.

BTW, I'm also running Pie (OxygenOS) on a OnePlus 6T.

**Comment by eggixxl** [comment]
I'm having the same problem (Android Pie, S8 and S10). Obviously not yet solved. Too bad

**Comment by Grossdm** [comment]
@eggixxl,

At this _moment,_ I do not seem to be having this problem.
I did spend a significant amount of time toggling the related options/switches in the app and in Android apps and accounts, but I really have no idea what seems to have (for the moment) worked around this prolific bug.

If you want to spend time trying to "fix" this, I can only suggest that you find every place in Android and the app that there is a switch for syncing or permission to access contacts, then iteratively toggle them in all the permutations.

If you do this, please consider documenting your exact steps. Hopefully this will help others with a workaround.

The developers seem to have considered this bug a low priority.
I am not a developer, so I can't second guess this decision.
It has been reported by many users, from what I have seen.

Best of luck to you.

**Comment by trainmeditations** [comment]
@Grossdm I was able to get it to stop prompting by manually turning it on, then turning it off again without leaving the settings page.

**Comment by Grossdm** [comment]
@trainmeditations,
My current settings seem to be stable, so I'll take your word for it.
Thanks for your feedback.
