### ISSUE TITLE
Yubikey 5c not detected on Pixel Slate

### ISSUE THREAD

**Issue by clementop** [open-keychain/open-keychain#2482]
Inserting a yubikey 5c into a usb-c port on the Google Pixel Slate (ChromeOS) is undetected by Open Keychain. On a pixel 3, the device is immediately detected and keys are imported from it. I've managed to share the key from the pixel 3, however once attempting to encrypt content, the app hangs waiting for the yubikey to be connected to the tablet.

## Expected Behavior
Inserting the yubikey 5c into either of the Usb-c ports should be detected by the app

## Current Behavior
The app correctly prompts for a pin number but then waits endlessly as if the device were never connected.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. Menu > Manage My Keys
2. Use Security Token
3. Insert Yubikey 5c into usb-c port

## Context
ChromeOS supports Android apps, apparently natively.
I would like to use OpenKeychain in conjunction with Password Store in order to gain access to my passwords in this device, as I have already done with my other android devices.

## Your Environment
* Android Version: 9
* Device Model: Pixel Slate
* OpenKeychain Version: 5.3 (53004)
* From Google Play or F-Droid?: Google Play

**Comment by dschuermann** [comment]
The USB API is currently not supported on Chrome OS: https://developer.android.com/topic/arc/manifest

There is nothing we could do about that.

**Comment by clementop** [comment]
Thanks for getting back so quickly. That's such a bummer!
