### ISSUE TITLE
Feature Request: add more key type option when creating new key.

### ISSUE THREAD

**Issue by evan0greenup** [open-keychain/open-keychain#2484]
It would be awesome if more advanced option can be set when generating new key.

This option can put into a entry named "Advanced Option" to avoid confusing ordinary users.

It would be also awesome to add support to ECC algorithm support.

**Comment by klaernie** [comment]
I would think this option is already there:
![Screenshot_20190911-072333](https://user-images.githubusercontent.com/5636383/64670437-58510180-d465-11e9-856c-159020acb6e7.png)

Under there you can also change the key type to ECC.

**Comment by evan0greenup** [comment]
Sorry, I didn't notice it.
