### ISSUE TITLE
[Feature Request]: Add support for brainpool ecc curves.

### ISSUE THREAD

**Issue by stevenleeS0ht** [open-keychain/open-keychain#2487]
The version of Open-keychain I use: 5.3 (53004).

It would be awesome if open-keychain support brainpool ecc curves.

**Comment by stevenleeS0ht** [comment]
@dschuermann, and @Valodim, what's your opinion toward this requests?

**Comment by dschuermann** [comment]
We support brainpool curves. You can generate one using GnuPG and import the key into OpenKeychain.
We currently do not plan to expose them during key generation.
