### ISSUE TITLE
Importing keys from Yubikey fails

### ISSUE THREAD

**Issue by sauyon** [open-keychain/open-keychain#2491]
## Expected Behavior
I can add a key using my yubikey (off public keyservers).

## Current Behavior
Adding the key fails with after "Removing invalid user ID 'Sauyon Lee <s [at] uyon [dot] co>" (for the master key ID `0x74a6dd284bf8a1d7`)

## Your Environment

* Android Version: 9 (kernel 4.14.83)
* Device Model: V50 ThinQ
* OpenKeychain Version: 5.3
* From Google Play or F-Droid?: Play

**Comment by Valodim** [comment]
Your key, at least the version that's on the sks pool, has weirdly ordered packets that aren't spec compliant and that openkeychain doesn't handle. What did you use to create it? While this is handled by *some* implementations that attempt to reorder the packets to fix this issue, something like that shouldn't happen in the first place.

You'll proably run into trouble using that key every once in a while, I would recommend creating a new one.

**Comment by sauyon** [comment]
It was created using `gpg` on Arch, so I'm really not sure how that's happened.
