### ISSUE TITLE
Decrypt from Clipboard Error on Android 10 (Sep 5, 2019 Update)

### ISSUE THREAD

**Issue by kkelvin1987** [open-keychain/open-keychain#2492]
Decrypting from clipboard no longer works on Android 10 (version QP1A.190711.020).

## Expected Behavior
Previously, on Android 9, any encyrpted messages (which are copied to the clipboard) can be decrypted in OpenKeychain through "Encrypt/Decrypt --> Decrypt/Verify --> Read from Clipboard".
 
## Current Behavior
Doing the above results in a message: "No data to decrypt!"

## Steps to Reproduce (for bugs)
1. Copy any encrypted message to clipboard
2. Open the app OpenKeychain
3. Go to "Encrypt/Decrypt --> Decrypt/Verify"
4. Select "Read from Clipboard"
5. Message: "No data to decrypt!" pops up

## Your Environment
* Android Version: 10 (QP1A.190711.020)
* Device Model: Google Pixel 3XL
* OpenKeychain Version: 5.3 (53004)
* From Google Play or F-Droid?: Google Play

**Comment by ilyail3** [comment]
I can confirm same error on Pixel 2XL as well
(same build and openkeychain version - google play).

**Comment by pspuser666** [comment]
Same error:

Android version: 10
Device Model: Oneplus 7 Pro
Openkeychain: 5.4 (54000)
From Google Play.

**Comment by yw662** [comment]
Comfirmed on Android 10. Not able to decrypt clipboard, and not able to import keys from clipboard.

Android 10 Oct 9, 2019
Openkeychain 5.4 54000

**Comment by egooner** [comment]
Same here - but noticed my OpenKeyChain had not been updated and had problem with version 5.2, just updated and now on 5.4 with the same problem, 
Android 10
Google Pixel 2XL

**Comment by htomsirveaux2** [comment]
Same issue here with a OnePlus6. After Android 10 update OpenKeychain cannot read anything from the clipboard at all.

**Comment by pokebox** [comment]
OnePlus 6T update to Android 10 also confirmed this problem.
