### ISSUE TITLE
ERROR: Unable to resolve dependency

### ISSUE THREAD

**Issue by Ahmado0o** [open-keychain/open-keychain#2498]
i'm using android studio 3.5 and when i try to build the application it shows me these errors.

ERROR: Unable to resolve dependency for ':libkeychain@debug/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: libkeychain

ERROR: Unable to resolve dependency for ':libkeychain@debugAndroidTest/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: libkeychain

ERROR: Unable to resolve dependency for ':libkeychain@debugUnitTest/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: libkeychain

ERROR: Unable to resolve dependency for ':libkeychain@release/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: libkeychain

ERROR: Unable to resolve dependency for ':libkeychain@releaseUnitTest/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: libkeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebug/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebug/compileClasspath': Could not resolve project :extern:minidns.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebug/compileClasspath': Could not resolve project :KeybaseLib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebug/compileClasspath': Could not resolve project :safeslinger-exchange.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugAndroidTest/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugAndroidTest/compileClasspath': Could not resolve project :extern:minidns.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugAndroidTest/compileClasspath': Could not resolve project :KeybaseLib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugAndroidTest/compileClasspath': Could not resolve project :safeslinger-exchange.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugUnitTest/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugUnitTest/compileClasspath': Could not resolve project :extern:minidns.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugUnitTest/compileClasspath': Could not resolve project :KeybaseLib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugUnitTest/compileClasspath': Could not resolve project :safeslinger-exchange.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidRelease/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidRelease/compileClasspath': Could not resolve project :extern:minidns.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidRelease/compileClasspath': Could not resolve project :KeybaseLib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidRelease/compileClasspath': Could not resolve project :safeslinger-exchange.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidReleaseUnitTest/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidReleaseUnitTest/compileClasspath': Could not resolve project :extern:minidns.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidReleaseUnitTest/compileClasspath': Could not resolve project :KeybaseLib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidReleaseUnitTest/compileClasspath': Could not resolve project :safeslinger-exchange.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugWithTestCoverage/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugWithTestCoverage/compileClasspath': Could not resolve project :extern:minidns.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugWithTestCoverage/compileClasspath': Could not resolve project :KeybaseLib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugWithTestCoverage/compileClasspath': Could not resolve project :safeslinger-exchange.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugWithTestCoverageUnitTest/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugWithTestCoverageUnitTest/compileClasspath': Could not resolve project :extern:minidns.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugWithTestCoverageUnitTest/compileClasspath': Could not resolve project :KeybaseLib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@fdroidDebugWithTestCoverageUnitTest/compileClasspath': Could not resolve project :safeslinger-exchange.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleRelease/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleRelease/compileClasspath': Could not resolve project :extern:minidns.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleRelease/compileClasspath': Could not resolve project :KeybaseLib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleRelease/compileClasspath': Could not resolve project :safeslinger-exchange.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleReleaseUnitTest/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleReleaseUnitTest/compileClasspath': Could not resolve project :extern:minidns.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleReleaseUnitTest/compileClasspath': Could not resolve project :KeybaseLib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleReleaseUnitTest/compileClasspath': Could not resolve project :safeslinger-exchange.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleDebugWithTestCoverage/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleDebugWithTestCoverage/compileClasspath': Could not resolve project :extern:minidns.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleDebugWithTestCoverage/compileClasspath': Could not resolve project :KeybaseLib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleDebugWithTestCoverage/compileClasspath': Could not resolve project :safeslinger-exchange.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleDebugWithTestCoverageUnitTest/compileClasspath': Could not resolve project :openpgp-api-lib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleDebugWithTestCoverageUnitTest/compileClasspath': Could not resolve project :extern:minidns.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleDebugWithTestCoverageUnitTest/compileClasspath': Could not resolve project :KeybaseLib.
Show Details
Affected Modules: OpenKeychain

ERROR: Unable to resolve dependency for ':OpenKeychain@googleDebugWithTestCoverageUnitTest/compileClasspath': Could not resolve project :safeslinger-exchange.
Show Details
Affected Modules: OpenKeychain

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version: 
* Device Model: 
* OpenKeychain Version: 
* From Google Play or F-Droid?:

**Comment by dschuermann** [comment]
Init and update the submodules.
