### ISSUE TITLE
C#/win 10 - problem with decrypting on android 

### ISSUE THREAD

**Issue by razielsoft** [open-keychain/open-keychain#2505]
Hi, 

First of all I need encrypt some files on PC or from c# and then decrypt on android device
but when I encrypt a file on windows on open-keychain is decrypting fine but without the name of file.

but when I encrypt the file from c# I have an error on open-keychain: 

![obraz](https://user-images.githubusercontent.com/57355755/68123497-5ce9e180-ff0d-11e9-8d4a-f160fae6f76b.png)

c# use: PgpEncryptedDataGenerator encGen = new PgpEncryptedDataGenerator(SymmetricKeyAlgorithmTag.Aes256, withIntegrityCheck, new SecureRandom());

soo I doing something wrong? or what? how I should encrypt that without problem?

I try on emulator nox (android 5.1) and on-device xiomi redmi 6a (android 8.1) on both the same error. 
problem is not in the secret key because on windows is working almost good and encrypting on android and then decrypting on android is decrypting perfectly with a name.

**Comment by Valodim** [comment]
The data is encrypted to a subkey that doesn't have the "encryption" capability. We *could* decrypt this data, but it's similarly incorrect to do as considering a signature valid from a key that isn't supposed to be used for signing operations.

For your case, the correct solution would be to either add the encryption capability flag to the key you encrypt to, or encrypt to a different subkey that has that flag.
