### ISSUE TITLE
Add ability to sign binary files without encryption.

### ISSUE THREAD

**Issue by WAR10CKfreeworld** [open-keychain/open-keychain#2509]
## Issue Summery
I just tried to sign a video file with one of my keys without encrypting it. But when I tried to do so, I was unable to.
## Expected Behavior
In the "Encrypt" section of the side menu of the app, when you select "Encrypt Files" and are taken to the file encryption interface, you should be able to select your file/s and then add your key to the "Sign with" field but leave the "Encrypt to" field blank.

When the encryption is performed by pressing one of the buttons on the upper right hand corner of the interface, a detached .SIG or .ASC file should be generated for each file like this:
Input: "Example.rar"
Expected output: A new file called "Example.rar.sig" or "Example.rar.asc" is generated and placed in the same directory/folder as the input file.
## Current Behavior
An error is thrown that says: Sign-only operation of binary files is not supported. Select at least one encryption key.
## Possible Solution
I found an existing opensource java based application you could pull code from: http://ppgp.sourceforge.net/
There are some more I have on my computer. I will try to find them and add the links here.
## Context
This is a common and basic feature that has been implememted in all of the PGP applications I have used on my computers and is also built into the GnuPG command line interface as well. 

It would be useful when sending image or other non-text files as attachments via Android email clients that you want to be verified as sent by you. Or managing release files via Android tablets or phones.

**Comment by Valodim** [comment]
This is a niche use case that is pretty awkward to do with Android workflows. As such, we decided (a long time ago) that it is out of scope for OpenKeychain itself.

However, for users who have that specialized use case, this would be fairly simple to do with an external App that uses our API.

**Comment by yrtimiD** [comment]
@Valodim , does this decision also apply for file signature verification? This case might be very useful for verifying 3rd party apk files.

**Comment by PHPoenX** [comment]
@yrtimiD there isnt pgp signature in apk files

**Comment by PHPoenX** [comment]
> This is a niche use case

Many people dont think so
