### ISSUE TITLE
[Feature Request] Fetch public key of OpenPGP smart card trough  NFC

### ISSUE THREAD

**Issue by LoHub** [open-keychain/open-keychain#2511]
Hello and thank you for this wonderful application which is very helpful for me.

First of all I am sorry if what I ask is impossible. I do not know what NFC protocol allow to do.

I would like to know if OpenKeyChain could download public key of a smart card by reading public key URL trough NFC and next check the authenticity with smart card.

I think that could be a very convient method to share his/her public key to other people.
Thank you for your help.

**Comment by Valodim** [comment]
It is possible to download public keys via the URL on the smartcard. We already do that, to help people set up their own smartcards.

However, sharing public keys with this method would require people to hold their cards to other people's phones. That's really not something we want to encourage.
