### ISSUE TITLE
Error: BAD PIN after nitrokey start update to RTM.8

### ISSUE THREAD

**Issue by gvintux** [open-keychain/open-keychain#2551]
I'm using it with nitrokey start, I've updated it yesterday to RTM.8 (it was RTM.5)
When I'm trying to encrypt data or use PasswordStore, it asks me for PIN. And it worked yesterday.
## Expected Behavior
PIN is OK, data processed successfully
## Current Behavior
It says "Error: Bad PIN! Take away Security Token now and touch TRY AGAIN", but on PC it works perfectly
## Context
I can't decrypt my password store on my phone
## Your Environment
* Android Version: 8.1
* Device Model: Blackberry BB100 (KeyOne)
* OpenKeychain Version: 5.5
* From Google Play or F-Droid?: Google Play (but I tried F-Droid too)

**Comment by szszszsz** [comment]
Just retested. Results in https://github.com/Nitrokey/nitrokey-start-firmware/issues/31#issuecomment-625189457

cc @Nitrokey @alex-nitrokey

**Comment by gvintux** [comment]
Now the key has forgotten my pin. I'm trying to cancel it. GPG tool reports: card error. Seems like firmware update was the gates to hell for my nitrokey. I've tried to update firmware again - it doesn't help
