### ISSUE TITLE
Better handling of orientation change instead of using android:configChanges

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#257]
Currently we use 
`android:configChanges="orientation|screenSize|keyboardHidden|keyboard"` everywhere which is a bad practice. We need to recover better from config (e.g. orientation) changes. This means starting lists again or searching again.

see
http://stackoverflow.com/questions/7818717/why-not-use-always-androidconfigchanges-keyboardhiddenorientation

Example: ImportKeyActivity without configCahnges xml:
1. rotate device, fragment will be restarted and mListFragment is null because startListFragment is not called
2. import something -> crash with nullpointer

**Comment by Valodim** [comment]
works in:
- mainactivity
- certifyfingerprint
- certify
- viewcert
- encryptfiles
- encrypttext
- decrypt
- displaytext
- viewkeyadv
- viewkey
- logdisplay

does NOT work in:
- importactivity

untested:
- createkey
- editkey
- uploadkey
- settings
- settingskeyserver
- importproxy (is this one even relevant?)

**Comment by Valodim** [comment]
I'm pretty sure we correctly do onSaveInstanceState everywhere at this point, however the only place where we actually need this is backupactivity since it has a different layout for landscape. for all others, recreating the activity on a configChange is just a performance cost for no gain.

**Comment by dschuermann** [comment]
If it works everywhere we should remove the configChanges lines from the manifest. It's definitely not recommended to do it. I also remember that the font size etc is not resized correctly currently...

**Comment by Valodim** [comment]
I think this is only relevant for configuration-dependent layouts, and our layouts are - besides backupactivity - configuration-independent. The recommendation is that an app must be *able* to handle these changes, which we do. I'm fine with changing them though, our activities are all simple enough that we don't need the extra performance.

**Comment by Valodim** [comment]
so, what about keyboard|keyboardHidden? strictly speaking, the same argument applies since it's a change of screen size...

**Comment by Valodim** [comment]
[ ] set and [x] tested:

- [ ] mainactivity
- [ ] certifyfingerprint
- [ ] certify
- [ ] viewcert
- [ ] encryptfiles
- [ ] encrypttext
- [ ] decrypt
- [ ] displaytext
- [ ] viewkeyadv
- [ ] viewkey
- [ ] logdisplay

**Comment by Valodim** [comment]
tested and committed the above activities into https://github.com/open-keychain/open-keychain/tree/v/configChanges

**Comment by dschuermann** [comment]
For now closing this.
