### ISSUE TITLE
Authentication with NFC token and ECC key

### ISSUE THREAD

**Issue by kusyka911** [open-keychain/open-keychain#2571]
## Expected Behavior
The app can successfully authentication ECC keys on the NFC security token.

## Current Behavior
When trying to connect to the ssh server Termbot calls Openkeychain popup to unblock key and read NFC token.

## Steps to Reproduce (for bugs)
1. Open Termbot
2. Configure the connection to use Openkeychain with an ECC key on NFC token
3. Try to connect
4. Pay attention to the result
P.S. Sometimes can be successfully authenticated.
P.P.S. For me it looks like Openkeychain has been crashed and Termbot tying to start keyboard-interactive authentication.

## Your Environment
* Android Version: 10.0.5 (MIUI Global 11.0.5 Stable)
* Device Model: Remi Note 8 pro
* OpenKeychain Version: 5.5
* From Google Play or F-Droid?: F-Droid
* Security token: Yubikey 5 NFC
* Termbot: F-droid 1.9.2-termbot.5

**Comment by dangfan** [comment]
This might be caused by the same reason as #2497.

**Comment by dschuermann** [comment]
Should be fixed in 5.7
