### ISSUE TITLE
Cannot encrypt e-mails with fairmail

### ISSUE THREAD

**Issue by schiavonedimitri** [open-keychain/open-keychain#2572]
On a xiaomi mi 9t pro with miui 12(Android 10) encrypting emails with openkeychain pgp provider doesn't work. When i try to send an encrypted email the application tries to redirect me to openkeychain for password input(for the pgp keys) but it doesn't work and the email gets saved to drafts. In previous versions of android this worked fine and each time an application needed to use a pgp key it would redirect fine to openkeychain.

**Comment by myasn1k** [comment]
It might be that in general openkeychain doesn't work under miui12
If you go in cryptography section in android settings you can't choose a key manager.
I've got Poco x3 nfc and i'm using password store and the two apps can't talk to eachother

**Comment by dingwen07** [comment]
Open app settings of OpenKeychain in MIUI, allow Autostart, then under "permissions", allow "display pop-up windows".

**Comment by schiavonedimitri** [comment]
@dingwen07 Thanks for your help, this solved my issue.
