### ISSUE TITLE
Error Encrypting in Password Store

### ISSUE THREAD

**Issue by CaptainVonNutbar** [open-keychain/open-keychain#2579]
Attempting to encrypt a new (or modified) password entry in Password Store, I receive an error stating that my key id is invalid.
I'm pretty sure this is happening because my key id is an email address, but it's of the form user@host rather than the expected user@domain.tld.  This is technically a valid email address and I would expect it to find the key.

Android 10, OnePlus 7 Pro, OpenKeychain 5.5 from Google Play

**Comment by msfjarvis** [comment]
@dschuermann I'd like to help get this fixed, do you have any ideas on where I should start?

**Comment by dschuermann** [comment]
If this bug really depends on the email address and we would need to change the User ID parsing for it, I am not sure if we like to do it. It's already complicated enough. It all depends on the underspecified way User IDs are defined and parsed.

@msfjarvis But feel free to propose a PR if you can reproduce the issue.

**Comment by msfjarvis** [comment]
> If this bug really depends on the email address and we would need to change the User ID parsing for it, I am not sure if we like to do it. It's already complicated enough. It all depends on the underspecified way User IDs are defined and parsed.
> 

I spent some time with the problem today, and narrowed it down to the email parser regex in the API library (https://msfjarvis.dev/aps/pr/1400). Will send a PR shortly.

**Comment by msfjarvis** [comment]
Since the pattern used in the library is private to it I don't believe bumping the submodule in this repo is strictly necessary, but I can send a PR doing that if it's desirable, after https://github.com/open-keychain/openpgp-api/pull/17 is merged.

**Comment by dschuermann** [comment]
@msfjarvis Thanks. 

splitUserId is used at several points in the OpenKeychain project. Yup, please bump the submodule and add a test here: https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/test/java/org/sufficientlysecure/keychain/pgp/SplitUserIdTest.java

**Comment by msfjarvis** [comment]
> splitUserId is used at several points in the OpenKeychain project. Yup, please bump the submodule and add a test here: https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/test/java/org/sufficientlysecure/keychain/pgp/SplitUserIdTest.java

Done: #2699
