### ISSUE TITLE
Problem with signing subkeys stored on Yubikey 5 NFC

### ISSUE THREAD

**Issue by elijahmathews** [open-keychain/open-keychain#2589]
Ultimately this is perhaps the same problem mentioned in #2538 which deals with authentication subkeys, but it appears that my `ed25519` signing subkey (along with my authentication subkey) that is stored on a Yubikey 5 NFC is not playing nicely with OpenKeychain.

Here's some screenshots. On the left is my `ed25519`/`cv25519` key, which displays as not being configured for signing operations. On the right is my `rsa4096` key, which is otherwise set up in the exact same way (i.e. signing/authentication/encryption subkeys stored on a Yubikey 5 NFC).
<img src="https://user-images.githubusercontent.com/23229627/92947551-c1bf7380-f41d-11ea-8966-f53310a21456.png" alt="Screenshot_20200911-105215" height="275"/><img src="https://user-images.githubusercontent.com/23229627/92947557-c4ba6400-f41d-11ea-9516-858e65b0c713.png" alt="Screenshot_20200911-105151" height="275"/>

I do know for a fact that my `ed25519` signing subkey on the Yubikey is working properly with GnuPG 2.2.20 (same goes for my authentication subkey).

## Environment

* Android Version: 10
* Device Model: Google Pixel 4a
* Yubikey (storing my `ed25519`/`cv25519` subkeys): Yubikey 5 NFC with firmware 5.2.7
* Yubikey (storing my `rsa4096` subkeys): Yubikey 5 NFC with firmware 5.1.2
* OpenKeychain Version: 5.5

**Comment by TaaviE** [comment]
I have just encountered this myself. Seems to reject the ed25519 signing subkey for some reason.

**Comment by pgmr2** [comment]
I have the same problem. Sorry

**Comment by TaaviE** [comment]
@dschuermann 

I tested the new release, I had to delete my key from the device and reimport it. It couldn't fix the broken Curve25519 subkey otherwise. Maybe that could be improved?

**Comment by dschuermann** [comment]
@TaaviE which version?

**Comment by TaaviE** [comment]
@dschuermann 5.7 from Google Play

**Comment by dschuermann** [comment]
@TaaviE maybe I don't fully understand your issue. Can you open a new issue with a detailed report of your key configuration?

**Comment by TaaviE** [comment]
@dschuermann 

It's the exact same one as this issue. I just imported my keys from token into OpenKeychain before the 5.7. update, the bugfix doesn't provide a way of fixing keys that are already broken but imported.

**Comment by dschuermann** [comment]
Ah now I understand. No we currently do not provide an upgrade path sry.
