### ISSUE TITLE
Link keys to contacts’

### ISSUE THREAD

**Issue by jackthebean** [open-keychain/open-keychain#2595]
## Expected Behavior
I would expect enabling 'Link keys to contacts’ in Settings/Synchronisation would save that setting.

## Current Behavior
I can enable it and back out of Settings and it justs disables again.

This is in Android app v5.5
## Steps to Reproduce (for bugs)

1.  Click on notification about 'Link keys to contacts'
2.  Enable
3.  Back out
4.  Get notification again

or

1 Go into settings/sychronisation
2 Enable Link Keys to contacts
3 Back out
4 Repeat

## Context
Keep getting notification asking/suggesting that I enable this setting.

## Your Environment

* Android Version: 10
* Device Model: Huawei Honor View 20
* OpenKeychain Version: 5.5
* From Google Play or F-Droid?:  Play

**Comment by Valodim** [comment]
Thanks for the report! This feature is going to be dropped in the next version due to its questionable usefulness and bugginess, see #2395 for a discussion
