### ISSUE TITLE
Nitrokey Start: USB error - failed to transmit data (-1/15)

### ISSUE THREAD

**Issue by Alexus9** [open-keychain/open-keychain#2602]
I cannot access my Nitrokey Start. When I select in OpenKeychain
`Manage my keys > Use security token` 
I get the error message 
`usb error - failed to transmit data (-1/15)`

## Expected Behavior
The key from Nitrokey Start should be presented for selection

## Current Behavior
Just the error message 
`usb error - failed to transmit data (-1/15)`

## Possible Solution
Analysis in OpenKeychain which conditions produce the error message. Correction of OpenKeychain or hint what causes the malfunction.

## Steps to Reproduce (for bugs)
Not applicable for you. For me at any time.

## Context
Cannot use my Nitrokey Start with my smartphone - the reason why I have bought it.

## Your Environment
* Android Version: 8.1.0
* Device Model: bq Aquaris X with cable TUPower A11 USB C Adapter
* OpenKeychain Version: 5.5 (55000)
* From Google Play or F-Droid?: Google Play
* Nitrokey Start firmware version: RTM10

**Comment by Alexus9** [comment]
I've tried a different smartphone/Android version/cable, same result: unable to access Nitrokey Start, `usb error - failed to transmit data (-1/15)`.

- Android Version: 5.1.1
- Device Model: Huawei P7-L10 with cable Hama Micro USB OTG Adapter Cable

Problem with Nitrokey firmware RTM.10?

**Comment by szszszsz** [comment]
subscribing @Nitrokey @jans23 to this ticket

**Comment by szszszsz** [comment]
Linking support forum ticket: 
- https://support.nitrokey.com/t/nitrokey-start-rtm-10-not-usable-in-android-with-openkeychain-5-5/2711/2

**Comment by jans23** [comment]
@Alexus9 In case you have a Nitrokey Start without important keys. Could you downgrade to firmware RTM.8 and test if this issue still occurs?

**Comment by Alexus9** [comment]
Yes, I did it.

I’ve seen that the Nitrokey Start was recognized by OpenKeychain immediately after downgrade to RTM.8 (no keys moved to it). Directly after plugging the Nitrokey Start into my mobile, OpenKeychain accessed it automatically and displayed that it is empty. Very nice behavior.

Then I moved keys to the Nitrokey Start and OpenKeychain couldn’t access it any more (error as usual: `usb error - failed to transmit data (-1/15)`). This time the access happened automatically, only manually via `Manage my keys > Use security token` in OpenKeychain. 

The keys are of type Elliptic Curve, could this be a reason?

Then I wanted to test whether the Nitrokey Start could also be accessed by OpenKeychain immediately after upgrade to RTM.10, without keys. This failed. Now, I cannot access my Nitrokey Start at all, it isn’t recognized by Linux any more. I had done a factory reset and an attempt to update, please see the attachment for the detailed steps.

What now? Is my Nitrokey Start broken?

[commands.docx](https://github.com/open-keychain/open-keychain/files/5471134/commands.docx)

**Comment by szszszsz** [comment]
Hi @Alexus9,
Regarding the last firmware update, do you have the logs produced by the update tool (from path `'/tmp/nitropy.log.junlzkxg'`)?

**Comment by Alexus9** [comment]
I'm very sorry. I've seen that my Opensuse uses tmpfs for `/tmp`, so `/tmp `is cleared after each reboot, and I didn't copy the nitropy logfiles elsewhere.

**Comment by Alexus9** [comment]
I got a replacement Nitrokey by the merchant. The error didn't occur any more, probably the former Nitrokey was partially defect and completely defect finally. But I got problems with multiple identities (pl. see https://github.com/open-keychain/open-keychain/issues/2619)
