### ISSUE TITLE
2047 bit key marked as insecure

### ISSUE THREAD

**Issue by aryasenna** [open-keychain/open-keychain#2612]
Apparently there are some implementation quirks/edge cases in key generation that 2047 bit key is generated instead of 2048 bit.

https://randomoracle.wordpress.com/2019/12/04/off-by-one-the-curious-case-of-2047-bit-rsa-keys/amp/

http://codeverge.com/mozilla.dev.security.policy/rsa-keys-2047-bits-2048-bits/1507024

Can OKP not mark these keys are insecure?
2047-bit is very marginally weaker than 2048-bit.

## Expected Behavior

2047-bit marked is not marked insecure, however practically it has the same key strength compared to 2048 bit.

## Current Behavior

2047-bit marked as insecure simply because it is < 2048, without considering practical key strength.

## Possible Solution

Modify ne off less than equal in the key length check here 
https://github.com/open-keychain/open-keychain/blob/61892a65703fe29c916b873e54b1b38a201d72df/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/pgp/PgpSecurityConstants.java#L153

## Steps to Reproduce (for bugs)

1. Import private key with 2047 bit length
2. Verify that operation (sign/encrypt) is not possible.

## Context

Key length size check when importing keypair.

## Your Environment

n.a. (applicable to all supported environment)

**Comment by dschuermann** [comment]
We'll not support this corner case.
