### ISSUE TITLE
Importing/Recovering Key on Android

### ISSUE THREAD

**Issue by rudeboy500** [open-keychain/open-keychain#2615]
Ok so this is an interesting situation. I lost access to my Android Tablet which had my openkeychain PGP Key set up. When I first made the account, I backed up the Key, and wrote down the code, however I can’t figure out which of my 100 emails I saved/shared the backup file or if I did at all. Now I’m wondering if there is anyway I can recover this key with this Backup code Only? What specifically is the backup file? Trying to understand better and hoping I didn’t screw up like my last encounter with this issue where I had the backup key but lost the backup code? Is this the same thing if I lost the backup key, but have the code? Or is there anyway the backup key can be found/salvaged if I have my PGP KEY and Backup Code?? Please help!

**Comment by dschuermann** [comment]
You need the backup file. It contains the secret keys encrypted with the code.
