### ISSUE TITLE
Site/app linking to the legacy Password Store

### ISSUE THREAD

**Issue by evelikov** [open-keychain/open-keychain#2617]
Both https://www.openkeychain.org/ and app (menu->apps) link to the legacy version of Password Store.

Namely:
https://f-droid.org/packages/com.zeapo.pwdstore/
https://play.google.com/store/apps/details?id=com.zeapo.pwdstore
https://github.com/zeapo/Android-Password-Store

With the f-droid app/link no longer being available.

The new links are:
https://f-droid.org/en/packages/dev.msfjarvis.aps/
https://play.google.com/store/apps/details?id=dev.msfjarvis.aps
https://github.com/android-password-store/Android-Password-Store

**Comment by Valodim** [comment]
thanks for the heads-up, will be fixed in the next release

**Comment by evelikov** [comment]
Thanks latest version has it fixed.
