### ISSUE TITLE
Possible issue with Android 10 and key contact sync

### ISSUE THREAD

**Issue by PaxJaromeMalues** [open-keychain/open-keychain#2618]
Hi, I am running Android 10 on my Moto G9 Plus but open key chain is constantly requesting access to the contacts for syncing keys with. whenever I grant that access the app resets the setting.

**Comment by Oclair** [comment]
Me too Samsung s20 5g

**Comment by WebworkrNet** [comment]
Same problem with Samsung Galaxy XCover 4s

**Comment by MaxEtMoritz** [comment]
Same problem for me, using Samsung Galaxy A40

**Comment by Valodim** [comment]
We removed contact sync since it wasn't useful anyways, fix will be will be in an upcoming release
