### ISSUE TITLE
Allow Yubikey PINs to contain more than just digits

### ISSUE THREAD

**Issue by errhammr** [open-keychain/open-keychain#2628]
I have initialized a new Yubikey 5 NFC on my desktop PC and used a PIN containing letters, digits and special chars. Then I tried using this Yubikey via NFC with OpenKeychain.

## Expected Behavior

I'd expect to be able to get a full keyboard on Android when entering the PIN, not just the number keyboard. Or have a setting somewhere to enable the full keyboard.

## Current Behavior

Currently I'm stuck with the number keyboard and have no way of entering the letters and special chars that are in my Yubikey's PIN.

## Possible Solution

Add an advanced setting to enable the full keyboard that contains all letters and special chars for PIN entry.

## Steps to Reproduce (for bugs)

1. Use a PC to set the PIN of a Yubikey to something that contains at least one letter.
2. Unplug the Yubikey from your PC.
3. Try signing or decrypting something (anything) using OpenKeychain with that Yubikey.
4. Try to enter the PIN (that contains letters) using the number keyboard. This will not work on devices/ROMs that have a dedicated number keyboard that doesn't let the user enter letters.

## Context

I'm trying to use my Yubikey that I have set up with my PC. I cannot use my Yubikey because I cannot enter a PIN that contains letters and special chars. OpenKeychain only offers me the number keyboard that does not have any letters on it.

## Your Environment

* Android Version: 10 (LineageOS 17.1 with the default keyboard that ships with LineageOS for the OnePlus 3T)
* Device Model: OnePlus 3T
* OpenKeychain Version: 5.5
* From Google Play or F-Droid?: I think both the Play Store version and the F-Droid version are affected.
 
**EDIT** 2020-12-21: added more detail about which model of Yubikey I am using and that I'm trying to use the NFC interface.

**Comment by nurupo** [comment]
When asked to enter the PIN, there is `abc` button at the right side of the input field, click it to change to the full keyboard.
