### ISSUE TITLE
How do you clear sign a text?

### ISSUE THREAD

**Issue by birdietheowl** [open-keychain/open-keychain#2635]
How does one do an equivalent of --clear-sign a text in app on android?

**Comment by JamesGreen31** [comment]
I believe that you would just leave the encrypt to field blank. Then you get something like this:

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Your message here
-----BEGIN PGP SIGNATURE-----

iQJFBAEBCgAvKBxKYW1lcyBHcmVlbiA8amFtZXMuZ3JlZW4zMUBvdXRsb29rLmNv
bT4FAmAEzSEACgkQaXtupkYnFDThQg//W1yLNt6gmkaJr1aKNoPg8rxKoJQFMel/
1k2+WfH6EdNWUc8AAiFCwhZZ/A3eOfmNJyRM2yiiWW0aFdcicuw+0mAxGX0z6Bks
2qKsb2Fts+Ue6811n5chYyfigfZeEAwyNwwiDfObY71o+FXFScW0PkQR1bmTip2R
/F9wFu8QVEAGLoqnMq8OhL0/Oq+x/kCKQrbWvRKz1zJM8qnIfmdA4zN4/v8pgbAT
KOGGvUIICnS+M/WW++ONqM/zbEYp8d4pL+oPpPdcli9J2eHkTFUFIdw/nJKJ5Gn1
R1zZv1ldw/NstObIezWw3o+2BFgIE+AnqCSQShg6zPRXUfX6MbRayGrFgWEiSupU
GKf+9kzU7gTefXdfKIsTKXpU5Rw83y0ctp8//Q2ikpHmNa/j+Q8qY+09eEkfncui
bWC9WYJRvqjBwWe9wO65aiA2k1Tx41vzU3oQ1yJY+jvYqE/OHxPZmCUgZ9W5mBkh
9B9kRF2eVOTf1EaCCgsoec7dyHRseFhSqVJB0NQ5DxasyvwMdP0UBQKNSZq50haS
gEdK5l8UMl2Qtl+cHJ9fUFFb3oYQY9WntdIUb0mmP0yZE16P8UZjX5Nr8IwmrTMU
hdjSLBSnQeLNTGypWl5g0VQCIXh+NEQpSwiyVhB5X4T2xyNluqxvCVv9T52zgjDU
Jj7Sh3W4yOU=
=KY/l
-----END PGP SIGNATURE-----

**Comment by Valodim** [comment]
That's correct. Clearsigning is a rare use case (especially on Android?) so it's not well advertised that this works.
