### ISSUE TITLE
F-Droid lacks updates?

### ISSUE THREAD

**Issue by anon97945** [open-keychain/open-keychain#2641]
Hello, 

is the app on F-Droid still maintained? Its last updated on 2020-01-23 ....

regards

**Comment by TJ-Hooker15** [comment]
There haven't been any new releases since then. https://github.com/open-keychain/open-keychain/releases

**Comment by anon97945** [comment]
So, when do we get the update on fdroid? 😅

**Comment by anon97945** [comment]
So, when do we get the update on fdroid? 😅

**Comment by Valodim** [comment]
fdroid is just slow. you can see [here](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.sufficientlysecure.keychain.yml#L736) that metadata updated correctly, but they have a long build queue that takes forever, and there's nothing we can do to influence that.
