### ISSUE TITLE
Publish sshauthentication-api artifacts to Maven Central

### ISSUE THREAD

**Issue by msfjarvis** [open-keychain/open-keychain#2645]
JFrog has made the decision to [shut down Bintray](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/) on May 1st 2021 which means libraries that are only available on JCenter will stop resolving for users. It'd be greatly appreciated if this library is also published to the [Sonatype OSS repository](https://repo1.maven.org/maven2/) so that projects can continue depending on it after JCenter is gone.

**Comment by Valodim** [comment]
Yep, we'll do that

**Comment by msfjarvis** [comment]
Any progress on this front?

**Comment by dschuermann** [comment]
I released it to Jitpack for simplicity. Can you try the following and report back if it works:
```gradle
repositories {
    maven { url 'https://jitpack.io' }
}

dependencies {
    implementation 'com.github.open-keychain.open-keychain:sshauthentication-api:-SNAPSHOT'
}
```

**Comment by msfjarvis** [comment]
> I released it to Jitpack for simplicity. Can you try the following and report back if it works:
> 
> ```groovy-gradle
> repositories {
>     maven { url 'https://jitpack.io' }
> }
> 
> dependencies {
>     implementation 'com.github.open-keychain.open-keychain:sshauthentication-api:-SNAPSHOT'
> }
> ```

JitPack is...suboptimal. This works, but I'll at least need a tagged release, `-SNAPSHOT` is a moving qualifier.

**Comment by dschuermann** [comment]
try ```implementation 'com.github.open-keychain.open-keychain:sshauthentication-api:v5.7'```

**Comment by msfjarvis** [comment]
v5.7 doesn't seem to work, here's our corresponding [pull request](https://github.com/android-password-store/Android-Password-Store/pull/1348/files) and [build log](https://github.com/android-password-store/Android-Password-Store/runs/2136005902?check_suite_focus=true#step:5:105).

**Comment by dschuermann** [comment]
Jitpack had some build problems. Please try with 
```implementation 'com.github.open-keychain.open-keychain:sshauthentication-api:v5.7.1'```

**Comment by msfjarvis** [comment]
> Jitpack had some build problems. Please try with
> `implementation 'com.github.open-keychain.open-keychain:sshauthentication-api:v5.7.1'`

That works, thanks!
