### ISSUE TITLE
Regression OpenPgpApi.ACTION_DECRYPT_VERIFY after upgrading to 5.6

### ISSUE THREAD

**Issue by iNPUTmice** [open-keychain/open-keychain#2649]
Hi,

after upgrading to 5.6 I’m no longer able to verify signatures using `OpenPgpApi.ACTION_DECRYPT_VERIFY`.

Unfortunately the discovery of this coincided with me migrating to a new phone so I blamed myself first and didn’t properly record logs.

The error I’m getting back (through the API) is "Encountered an error reading input data!" (and error code 0)

Signing and decrypting (the other two operations Conversations does) seem to work just fine. However with 'verify' being the discovery mechanism it limits my testing capabilities a bit.

Downgrading to 5.5 (from F-Droid) solved the issue for me.

I’ll set up a proper testing environment tomorrow. Just thought I'll give a heads up in case this immediately rings a bell with someone.

**Comment by Valodim** [comment]
dang, that's unfortunate. I don't have a concrete cause for this in mind, please do tell when you have something. I'll try to look into it when I can.

**Comment by iNPUTmice** [comment]
For reference here is the code in question that call OpenKeychain: https://github.com/iNPUTmice/Conversations/blob/master/src/main/java/eu/siacs/conversations/crypto/PgpEngine.java#L150-L192

Maybe my formatting here is garbage and earlier versions just silently dealt with it or something.

**Comment by Valodim** [comment]
I *think* I didn't change anything in that regard, but we did update bouncycastle so maybe it's something in there.

cleartext signatures are also very brittle in general, if possible it's much preferrable to use detached signatures instead. in particular when you are piecing the clearsig text together as you are doing there :)

**Comment by FoxKyong** [comment]
I can confirm the problem. I also updated OpenKeychain today and now I can't send OpenPGP encrypted messages. It just says for me that my contact doesn't announcing public key. The same for him. Decrypting older messages works.

**Comment by Valodim** [comment]
Any further insight here @iNPUTmice? It could be useful if you can capture the exact clearsign data you pass as input.

That said, I would strongly recommend you use detached signatures for those procedures. You should be able to pass in the raw bytes as input, plus the (raw) signature via `EXTRA_DETACHED_SIGNATURE`. The stitched clearsigs are a bit of a vile abuse of that API :)

**Comment by iNPUTmice** [comment]
I've switched to detached signatures and this has solved the issue for me.

Now that I had to decode ASCII armor myself (as the API takes raw bytes as you mentioned) I discovered that my formatting was very strange and probably invalid. I suppose that previous versions of bouncy castle just took that and newer versions are a bit more strict.
