### ISSUE TITLE
Add keys.openpgp.org as a keyserver

### ISSUE THREAD

**Issue by trymeouteh** [open-keychain/open-keychain#2654]
Please add keys.openpgp.org as a key server in the app without having to add it manually

https://keys.openpgp.org/

**Comment by Valodim** [comment]
this is [already the default](https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/src/main/java/org/sufficientlysecure/keychain/Constants.java#L167) on new installations. I just checked and on 5.6.1 this works correctly.

**Comment by trymeouteh** [comment]
keys.openpgp.org is the primary keyserver for uploading your public key to?
