### ISSUE TITLE
Openkeychain Do you support KDF mode active?

### ISSUE THREAD

**Issue by tigernero79** [open-keychain/open-keychain#2658]
I wanted to know if on my Yubico 5 NFC I enable the KDF mode, which in practice sends hash of my pin, no longer in clear text to my yubico, to know if this activation is supported by openkeychain.  

Enabling must be done with these commands right?  

```
Enable KDF

$ gpg --edit-card
gpg/card> admin
gpg/card> kdf-setup
gpg/card> passwd
gpg: OpenPGP card no. D2760001240103030006294453760000 detected

1 - change PIN
2 - unblock PIN
3 - change Admin PIN
4 - set the Reset Code
Q - quit

Your selection? 1
PIN changed.
```

when version 5.6.2 that fixed the bug

https://github.com/open-keychain/open-keychain/pull/2653

**Comment by hagau** [comment]
Yes, `kdf-setup` enables KDF mode on Yubikeys supporting that feature.
Unfortunately, this first requires a `factory-reset`.
