### ISSUE TITLE
5.6.2 from f-droid breaks ssh: Error converting public key to SSH format: Unknown key algorithm

### ISSUE THREAD

**Issue by 532910** [open-keychain/open-keychain#2669]
While 5.5 works fine, ssh support is broken in 5.6.2 for [OkcAgent](https://f-droid.org/packages/org.ddosolitary.okcagent/) and [Password Store](https://f-droid.org/packages/dev.msfjarvis.aps/)

Error message is the same in both cases (okc and pass):
`Error converting public key to SSH format: Unknown key algorithm`

**Comment by 532910** [comment]
https://github.com/DDoSolitary/OkcAgent/issues/46

**Comment by dschuermann** [comment]
Sry, I think this will be fixed in the next release.

**Comment by dschuermann** [comment]
I just released 5.7. Please try with this version when it is available on F-Droid and report back. If it still fails re-open this issue.

**Comment by 532910** [comment]
5.7.3 doesn't throw the error above, but ssh just doesn't work.
#2686 possibly is about the same.
