### ISSUE TITLE
Pre-hash EdDSA signatures with NFC Security Key for signature subkeys

### ISSUE THREAD

**Issue by tigernero79** [open-keychain/open-keychain#2677]
I have a yubico 5 nfc with key ed25519 and pin kdf enabled on on, when I try to encrypt and sign even a simple image file it goes into signature error.  I attach error.  can it be kdf pin compatibility problem or key eddsa signature?  I am attaching screenshot error

![Screenshot_20210321-185225_OpenKeychain](https://user-images.githubusercontent.com/35575744/111915553-392e2980-8a77-11eb-9f78-b780cef79f63.jpg)

**Comment by tigernero79** [comment]
I want to clarify that the signature works with my token for the text.  but it doesn't work if I have to sign a file

**Comment by tigernero79** [comment]
i also get this error if i try to format a file for another identity other than mine, with token yubico 5 nfc.  key ed25519

![Screenshot_20210322-215419_OpenKeychain](https://user-images.githubusercontent.com/35575744/112057269-5affdd00-8b59-11eb-8b68-11094104e259.jpg)

**Comment by dschuermann** [comment]
Unfortunately, this issue makes sense.
The EdDSA signature is done over the full input and not hashed in OpenKeychain before it is sent to the token over NFC.
Not sure how to handle this properly without violating the spec.

**Comment by dschuermann** [comment]
Ok, the issue is as follows:
For authentication subkeys that are (used with SSH) we should not pre-hash, but for signature subkeys (used with OpenPGP signatures), we need to pre-hash: https://datatracker.ietf.org/doc/html/draft-ietf-openpgp-rfc4880bis-10#section-14.8

**Comment by tigernero79** [comment]
Good👍
