### ISSUE TITLE
App disappeared

### ISSUE THREAD

**Issue by mishanna** [open-keychain/open-keychain#2678]
Hello

I downloaded your app earlier today, and i generated a pgp key which i uploaded to a website that needed it for 2 factor authentication.  

Just now, i could not find the app, and it seems like it was uninstalled.  BUT I DID NOT UNINSTALL IT!  I reinstalled it to see if i can find my key, but it is gone... 

How do i retrieve it? I have the email from openpgp.org , but that is the public key. How do i retrieve my personal key. If i make a new key then i won't be able to log onto the website anymore, and i have a lot of money deposited there. 

What can i do? How did the app get uninstalled. I am very disturbed. Please help. 
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version: Android 11
* Device Model: samsung gaaxy S10
* OpenKeychain Version: 5.7
* From Google Play or F-Droid?: Google Play

**Comment by dschuermann** [comment]
If you don't have a backup, we can't help you. That's the key idea in end-to-end security.

**Comment by Valodim** [comment]
OpenKeychain does not uninstall itself, and there would be no technical way to do so even if it tried to. If apps mysteriously vanish on your phone, something else is going on that we have no influence over. If OpenKeychain was uninstalled at some point, the app data and your key and cannot be recovered. Sadly, that means that unless you have a backup, your data is lost.

Sorry, nothing we can do here. :(

**Comment by mishanna** [comment]
Thank you so much. I understand. 

I did not formally backup the data, but i did copy and paste my personal key into a note. I see an option on the app to import a keye. How can i make the text copy of the key into a format that can be imported? 

I need to run a virus/security check... Some strange things have happened.

I
