### ISSUE TITLE
"Error: Invalid KEK!" with security key and ECC NIST curve

### ISSUE THREAD

**Issue by roberti42** [open-keychain/open-keychain#2681]
## Expected Behavior

I'm trying to decrypt a file using my healthy key hosted in a security token.

## Current Behavior

Instead of decrypting the file if shows me an error (more on it later).

## Steps to Reproduce (for bugs)

1. Open menu
2. Choose Encrypt/Decrypt
3. Click Select input file
4. Choose a *.gpg file 
A message is displayed that ask me to "Hold Security Token against the NFC marker at the back of your device."
5. Hold the security token like requested
A message is shown: "Error: Invalid KEK!"

## Your Environment

* Android Version: 10 - LineageOS 17.1
* Device Model: Xiaomi Redmi Note 8T
* OpenKeychain Version: 5.7.2 (57200)
* From Google Play or F-Droid?: Google Play

**Comment by dschuermann** [comment]
We also need: What kind of security key are you using? What algorithms are you using on the key?

**Comment by roberti42** [comment]
I'm using a Yubikey 5 NFC; the algorithm is nistp521

**Comment by stelian42** [comment]
I'm seeing this also, with a custom SmartPGP applet, when encrypting to clipboard, then trying to decrypt the clipboard.

Keys are ECC P-256, generated by OpenKeyChain itself.

APDU log:

 -> 00a4040005a000000617
 <- 6a82
 -> 00a4040006d27600012401
 <- 9000
 -> 00ca006e00
 <- 6e81e54f10d276000124010304afaf0000000000005f520a00c1c573c001800590007381c3c00aff030020048000ff0000c10a132a8648ce3d030107ffc20a122a8648ce3d030107ffc30a132a8648ce3d030107ffc407007f7f7f030003c53cd6b47ed72763ee44949ca03c3f19478a767b59318b2a1db6142f5127aa339cc34f752806cc2d0617c5db754f6f22612f622bd6be86d37544fa98d80dc63c000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000cd0c6065bd6b6065bd6b6065bd6b9000
 -> 00ca00d400
 <- d40a122a8648ce3d030107ff9000
 -> 0047810002a60000
 <- 6a88
 -> 00ca00f900
 <- 8101009000
 -> 0020008206343536373839
 <- 9000
 -> 002a808648a6467f4943864104d7d5d29056760232216a25977732be29a7aed380c3d4cb8d9a8d14dd44ac95d777ef7651c9710b02fb8df7614689719323df6f41e9ce0c9c091d0fcb3018fd0941
 <- 036731c359efe4e6ec24b35a9669c83bfde2d57298fca68cd19f91ca70d176689000

**Comment by stelian42** [comment]
I have just reset my token, and generate RSA-3072 keys instead, and now it works properly.

**Comment by canary5** [comment]
Can confirm on yubikey 5. Tried generating keys with openkeychain, gpg same error on all ecc keys. Also tried kdf on/off

**Comment by mkfrey** [comment]
This seems to be a regression. I remember it working a few versions ago.

**Comment by stelian42** [comment]
I have bisected this down to commits e82fb82c4466a4d1f5c9540bc9bb94ef68104ca2 and 04a6740cecf236f3cbb5703baffda597db30c067 . Backing out those two commits make the encryption, decryption and sign work for me.

However, those commits are supposed to fix exactly the problems they are creating for me, so I believe someone with a better understanding of the inner workings of OpenKeychain should take a look at this.

Patch attached below.
[fix-invalid-kek.txt](https://github.com/open-keychain/open-keychain/files/6334776/fix-invalid-kek.txt)

**Comment by dschuermann** [comment]
@dangfan Can you look into this?

**Comment by rjhwelsh** [comment]
I can confirm the same issue with OpenKeychain version 5.7.3 from F-droid.
I am using a Nitrokey Pro, with an ECC brainpoolP256r1 curve for encryption.

**Comment by dangfan** [comment]
From rfc6637#section-7: The input of KDF should be the x portion of the point.
However, the result of ECDH can be expressed in two formats: compressed and uncompressed. GnuPG can deal with both cases but before Open-Keychain 5.7, it only supports the compressed format and after 5.7 (since commit e82fb82) it only supports the uncompressed format.
PR #2693 first checks if the ECDH is the compressed format and then extracts the x portion accordingly.

**Comment by stelian42** [comment]
I can confirm the PR #2693 fixes my encrypt/decrypt/sign from clipboard with ECC P-256 generated by OpenKeychain into a secure token (running a custom SmartPGP applet inside).

**Comment by dschuermann** [comment]
I released 5.7.4 with this fix.
