### ISSUE TITLE
Recovering info

### ISSUE THREAD

**Issue by mishanna** [open-keychain/open-keychain#2682]
Hi. I had previously innquired about the app getting somhow deleted from my device  having said that, I did not formally backup the data, but i did copy and paste my personal key into a note. I see an option on the app to import a key. How can i make the text copy of the key into a format that can be imported into the app once i reinstall?

**Comment by Valodim** [comment]
what kind of data exactly did you write down, and from where? it's not impossible that this will help, but it's much more likely that you only wrote down the public key part, so don't get your hopes up.

**Comment by mishanna** [comment]
I thought it was the private key. It is 20 characters, all lettrrs no numbers. As i mentioned, i simply copied and pasted it instead of backing up.

**Comment by Valodim** [comment]
that's likely the fingerprint of the key, an identifier that can be used to identify your key among others. it is used in some flows like confirming other people's keys, but it won't be helpful for recovering your data.

sorry, there is nothing we can do here.
