### ISSUE TITLE
Set up security token with new key fails with Error: Failed to change PIN

### ISSUE THREAD

**Issue by stelian42** [open-keychain/open-keychain#2684]
Setting up a security token with new key fails with Error: Failed to change PIN

## Expected Behavior

The key generation and saving into the token should work properly, not fail.

## Current Behavior

Saving into the token fails with Error: Failed to change PIN

## Possible Solution

I have traced this into the code, see below.

## Steps to Reproduce (for bugs)

1. Launch OpenKeyChain
2. Go into Manage my keys
3. Use security token
4. Reset security token if needed
5. Click on "Set up with new key"
6. Fill full name, email, pin with whatever information you want
7. Notice the admin PIN written below: 12345678
8. Choose any algorithm for the keys
9. Click Next
10. Review input, and click "Create key"
11. It will successfully create the key, but when trying to save it into the token you will get "Error: Failed to change PIN"

## Your Environment

* Android Version: 9
* Device Model: custom
* OpenKeychain Version: 5.7.2
* From Google Play or F-Droid?: compiled locally from github sources
 
Tracing the APDU exchange show that the error is here:
-> 002400831020202020202020203132333435363738
<- 6982

For some reason OpenKeyChain tries to use "        " as the old admin PIN, which is of course incorrect.

Tracing the code this comes from doSecurityTokenInBackground(), in SecurityTokenOperationActivity.java . Around line 257 (case SECURITY_TOKEN_MOVE_KEY_TO_CARD) the adminPin is statically initialized with "12345678", and the APDU will be generated later by ModifyPinTokenOp.create().modifyPw1andPw3Pins().

But between the two (initialization and call to modifyPw1andPw3Pins), there is a loop where putKeyUseCase.changeKey() is called. And changeKey() calls  putKey(), which in turn calls verifyAdminPin(), which finally calls adminPin.removeFromMemory();

So after the first call to putKeyUseCase.changeKey() the key will be wiped from memory, but will be later reused.

As a workaround, I have commented out the call to adminPin.removeFromMemory() in verifyAdminPin(), and the whole procedure works now correctly.

This of course needs a proper fix.

But I also wonder what is the whole point of changing the admin pin ? If we had dialogs for letting the user type the old and the new admin pin it would make sense, but here we are just trying to change the admin pin from 12345678 to ... 12345678 ! Also, if the token has a different factory admin pin (I can for example build a SmartPGP javacard applet with a different default admin pin), there is no way this could work at all.

**Comment by hagau** [comment]
Thanks for debugging and reporting this!
Actually, deleting the call to `removeFromMemory` is the proper solution.
The `Passphrase` object holding the admin PIN clears the PIN when the object is being freed.

**Comment by dschuermann** [comment]
thx @stelian42 and @hagau . I released 5.7.3
