### ISSUE TITLE
Sec.pgp backup file forcing me to start with numbers that aren't the back up code. 

### ISSUE THREAD

**Issue by Trypt4638** [open-keychain/open-keychain#2689]
!--- Provide a general summary of the issue in the title >>

## Expected Behavior
Backed up pgp backup code starts with 71 but when recovering from the .sec.pgp file it made when I went to go recover from fil it forced me to start code with 81. So I lost access to my key. Because it won't accept the one generated when I backed up to file

## Current Behavior
Backed up pgp to file. When to recover. Code it gave me starts with 71. It's forcing me to start code with 18. I made a new key backed it up recovered from file it that time it worked properly. So my backup key file may be corrupt. The second one that works is a different format that mm the one that didnt work like a bug occluded generating the first backup file. 

## Possible Solution

Either need to uncorruptible the file or find a way to get me access back into my key and accounts please asap

## Steps to Reproduce (for bugs)

1.backup from file
2.forces me to start with 18 as code
3.original back up file code starts with 71
4.so I am stuck and locked out of 4 accounts 

## Context

I wanted to call you resolve this asap. I  was in the middle of a 3000 multi transaction deal when my pgp stopped working lost access to my ability to log in. So I have no idea if I lost the money or not. 

Verify and get me back into my account tryptic

## Your Environment

* Android Version: galaxy s21 5G
* Device Model: SM-G991U
* OpenKeychain Version: 5.7 
* From Google Play or F-Droid?: 
* Google Play store

**Comment by Valodim** [comment]
> 1.backup from file
> 2.forces me to start with 18 as code
> 3.original back up file code starts with 71
> 4.so I am stuck and locked out of 4 accounts

The first two digits are placed plaintext in the backup file, as a hint to the user which backup code is the right one for that file. If the numbers differ from the ones you have noted down, it's extremely likely that the code you have isn't the one used to encrypt that backup file.

You *can* do the following to double-check: Open the file in a text editor, find the line with those two numbers (should look something like `Passphrase-Begin: 18`, third line or so), remove that line, save a copy and import it. When you do that, the first two numbers won't be prefilled and you can type any passphrase you want.

It is very very unlikely that this is a bug on our side.

**Comment by Trypt4638** [comment]
I changed the text in WordPad from 18 to 71 saved it and when I put the code in is decryption failed. I only originally backed up and deleted my key and reinstalled then app because it was giving me an error before all this "error streaming data or something like that. So it wasn't working at all for no reason. Then I backed up and reinstalled and it's saying it starts with 81 instead of 71 which is not the code it gave me at all. And when I replaced the two first characters it still fails to decrypt. It's possible the file is corrupted. Because I made a new key backed that up deleted it and had no problem using that code to restore that temporary key. But I know for a fact I'm using the right back up code it gave me but the file seems corrupted. Because only this file has a shortcut image of a fingerprint and labeled .sec.pgp while the other keys I made that work to recover and have no file extension name. So this back up I made look different and Is labeled different like its corrupted or something

**Comment by Trypt4638** [comment]
I can give you the file and back up code to verify but this is a legitimate bug and I know I wrote the right numbers. Please help me get my key back.

**Comment by Trypt4638** [comment]
I deleted the app and backed up the key and reinstalled to restore. In the first place because my key telling me streaming decrypt error. So it wasn't working at all I thought backing up and restore would fix it

**Comment by Trypt4638** [comment]
![Uploading Screenshot_20210414-124205_Gallery.jpg…]()

**Comment by Trypt4638** [comment]
The image of the file with the finger print is the back up file that's not working. The other back up file is the one I made right after to test if that one works. And the one that doesn't work has an icon of a fingerprint and then that doesn't has an icon of a file. So I think the fingerprint one messed up and got corrupted. Please help me.

**Comment by Valodim** [comment]
Sorry, there's nothing we can do. Backup files are encrypted with the code you're given, it is exceedingly unlikely that the code suddenly changed in the file. We have no way of getting to your data, if you only have that one file, and only that one backup code that doesn't match, there's nothing you can do.

**Comment by Trypt4638** [comment]
I figured. I understand This bug made me loose $3000 everything I has but I
have 2000 left to remake my orders to buy my sacred medicine. I will
continue to use your app. Please make sure it gets fixed.
