### ISSUE TITLE
Key search does not work

### ISSUE THREAD

**Issue by stelian42** [open-keychain/open-keychain#2690]
Key search on standard keyserver yields no results.

## Expected Behavior

It should find the key.

## Current Behavior

It doesn't find anything.

## Your Environment

* OpenKeychain Version: latest git, locally compiled

**Comment by stelian42** [comment]
Fixed by PR #2691

**Comment by Valodim** [comment]
Pretty odd that this broke along the way. I remember testing this not too long ago when I fixed #2638

**Comment by dschuermann** [comment]
I released 5.7.4 with this fix.
