### ISSUE TITLE
openkeychain stopped on processing

### ISSUE THREAD

**Issue by tigernero79** [open-keychain/open-keychain#2694]
on s10 plus when i try to encrypt a text and sign it, the app gets stuck on the screen as attached photo.  "processing" 

![Screenshot_20210421-223506_OpenKeychain](https://user-images.githubusercontent.com/35575744/115618115-87db1780-a2f2-11eb-86a8-99c7e31b6348.jpg)

although the encrypted text exists in the clipboard.  I have to force close the application to be able to reuse it.  this happens on samsung s10 plus.  on my second pixel 2Xl phone the bug doesn't exist.  can it be solved?  I am attaching screenshots of the problem

**Comment by Valodim** [comment]
should be fixed with 1e584a368dc8aae1a7882aecfc9e55fe5f572133 (if anyone still cares :shrug:)
