### ISSUE TITLE
Allow specifying an encryption subkey in client API

### ISSUE THREAD

**Issue by msfjarvis** [open-keychain/open-keychain#2697]
An APS user reported [here](https://github.com/android-password-store/Android-Password-Store/issues/1360) that they use a GnuPG functionality that allows enforcing the use of a specific encryption key as opposed to relying on some default mechanism.

I can replicate the parsing logic inside APS, but I'll need to be able to specify the subkey when encrypting, something OpenKeychain doesn't seem to support from my reading of the API library. It'd be great if this could be implemented, and I am willing to contribute the functionality if given pointers for where to start.

**Comment by jlariviere1** [comment]
I would love it if I could do this as well!

**Comment by msva** [comment]
+1 for this request.

It would also be useful for cases like "proxying" subkeys in ssh-agent mode (through OkcAgent) in Termux.

By the way, looks like this issue directly touches this problem https://github.com/DDoSolitary/OkcAgent/issues/83 (subkeys support on GPG side)

**Comment by msfjarvis** [comment]
OpenKeychain is in maintenance mode with no plans to add any features and I don't wanna get notifications about this any more
