### ISSUE TITLE
Decrypt from clipboard don't working at Android 12 (Google Pixel 6)

### ISSUE THREAD

**Issue by kanopeld** [open-keychain/open-keychain#2780]
## Context
Any attempts to use decryption are failed, from clipboard and files
Log says: Processing input data > Attempting to process OpenPGP data > Ecountered an error reading input data!
I'm trying to decrypt a message created by gnupg

## Your Environment

* Android Version: 12
* Device Model: Google Pixel 6
* OpenKeychain Version: 5.7.5
* From Google Play or F-Droid?: Google Play

**Comment by TiAlex4Real** [comment]
I've encountered the same problem with gpg keys generated by gpg in Termux. Using keys generated on a Linux host fixed that problem. Don't know if it's your case, but hope it helps.
