### ISSUE TITLE
Open-Keychain crashes when de-/encrypting PGP emails K9 (& FairMail)

### ISSUE THREAD

**Issue by moritzp** [open-keychain/open-keychain#2808]
Open-Keychain crashes when trying to de-/encrypt PGP emails in K9 (also tried FairMail), with my Yubikey. This has been working for ages but recently stopped on my Pixel6 (Android 13, Build TQ1A.221205.011)

## Expected Behavior
1. Clicking on encrypted email, entering the PIN for the Yubikey, placing it on the back of the phone (NFC), removing it and the decrypted mail is shown in the client (K9 or FairMail).

2. Enable encryption for an email, click on send, enter the PIN, place the Yubikey on the back of the phone (NFC), remove it and the encrypted mail is sent.

## Current Behavior
1. Clicking on encrypted email, entering the PIN for the Yubikey, placing it on the back of the phone (NFC), removing it -> Full crash of Open-Keychain, as well as the client (K9 or FairMail).

2. When trying to encrypt an email, Open-Keychain also crashes and leaves the drafted email in the Drafts folder.

## Possible Solution
None :(

## Steps to Reproduce (for bugs)
See above.

## Context
I'm trying to de-/encrypt PGP emails, which doesn't work anymore.

## Your Environment
* Android Version: 13, Build TQ1A.221205.011, security update from December 5th
* Device Model: Pixel6
* OpenKeychain Version: 5.7.5
* From Google Play or F-Droid?:  Google Play
* K9: 6.400

**Comment by johnfedoruk** [comment]
Same problem on Pixel 6 + Android 13. Here are some more details:
- only NFC, a USB C YubiKey works as expected
- impacts Password Store
- impacts encrypt / decrypt / sign in OpenKeyChain app

**Comment by johnfedoruk** [comment]
Here are the crash reports

![Screenshot_20221229-170034](https://user-images.githubusercontent.com/16842229/210019318-8d758ada-6f34-48bd-9182-6c3ca599d15a.png)
![Screenshot_20221229-170057](https://user-images.githubusercontent.com/16842229/210019333-f8ea6528-3de0-43a3-b96d-e03f79332eb3.png)

**Comment by timhae** [comment]
see #2805 and #2804

**Comment by MarcSchuhTNG** [comment]
After uninstall and installing OpenKeyChain, I am not able to import the key from the yubikey. Neither NFC nor USB-C works for me.

**Comment by Valodim** [comment]
the crash originally reported here is fixed in v8.5.2
