### ISSUE TITLE
Ability to Encrypt to own key

### ISSUE THREAD

**Issue by BitBoy14** [open-keychain/open-keychain#2810]
## Expected Behavior
During encryption, one should be able to chose its own public key. 

## Current Behavior
Now I can only chose other public keys

## Possible Solution
Add ability to chose own key

## Steps to Reproduce (for bugs)
1. Chose to encrypt text. You will see that you cant chose own pubkey

## Context
I am on my Phone want to encrypt a password or other sensitive text before sending it to my self and opening it on my laptop.

## Your Environment
* Device Model: Pixel 7
* OpenKeychain Version: 5.8.2 (58902)
* From Google Play

**Comment by ethyoo** [comment]
It's already possible. Your public key needs to be in OpenKeychain

**Comment by rafaelrandomize** [comment]
It's working for me, I can encrypt using the public key and sign using the private key of the same keypair.

**Comment by Valodim** [comment]
Right, we use the signing key as an additional encryption key. If you want to add your own key for encryption without that, simply add it to the list of recipients :)
