### ISSUE TITLE
Потерял код 

### ISSUE THREAD

**Issue by Nikita23117** [open-keychain/open-keychain#2811]
Здравствуйте, потерял pgp ключ помогите пожалуйста, что делать?

**Comment by Fusted** [comment]
Восстанавливать из бэкапов

**Comment by Nikita23117** [comment]
Я переустановил телефон и ключ пропал, не могу восстановить

**Comment by Fusted** [comment]
Бэкапы хранятся там, где пожелаешь. Желательно сделать это максимально защищенным способом
Создай новые ключи, если не делал бэкапов, все равно никакой важной информации не потеряешь

**Comment by Nikita23117** [comment]
Где их взять ??

**Comment by Fusted** [comment]
> 

Там где ты их предварительно сохранил

**Comment by Nikita23117** [comment]
Можно просто восстановить мой ключ

**Comment by Nikita23117** [comment]
Я не делал их

**Comment by Nikita23117** [comment]
К моей почте не привязано ключей даже говорит

**Comment by Fusted** [comment]
> Я не делал их

Ключи не привязываются к почте, посмотри как работает gpg и не делай таких ошибок

**Comment by Nikita23117** [comment]
Можно с поддержкой свЯзаться чтоб помогли

**Comment by Nikita23117** [comment]
OPENPGP4FPR:C0D6E7DA310B50BF4A13586B9EEEB0C1A68F0027 Это что???

**Comment by rafaelrandomize** [comment]
К сожалению, вы не сможете восстановить свой ключ, после создания пары ключей приложение может автоматически загрузить открытый ключ на сервер ключей, но резервную копию закрытого ключа можно создать только вручную в автономном файле, зашифрованном в .pgp, и его необходимо сохранить. где-нибудь, например, в вашей электронной почте, на USB-накопителе, внешнем жестком диске или другом носителе данных. Перед созданием резервной копии приложение отображает резервный код, состоящий из 36 цифр, разделенных четырьмя знаком минус, это пароль зашифрованного файла резервной копии, который вы должны использовать для восстановления резервной копии в openkeychain или описан в другом openpgp программное обеспечение, чтобы иметь доступ к открытым и закрытым ключам, то его необходимо записать на бумаге, чтобы использовать позже, но если вы не сделали резервную копию, не сохранили файл где-то еще или не записали резервный пароль прежде чем потерять его ключ, вы просто потеряли свой ключ и ничего не поделаешь. Что вы можете сделать, так это создать новую пару ключей, создать ее резервную копию, записать пароль и сохранить этот файл в безопасном месте, кроме вашего телефона.

Прошу прощения за возможные ошибки, я не говорю по-русски, я бразилец, пользуюсь гугл-переводчиком.

**Comment by Valodim** [comment]
Please keep this issue tracker in English. Thanks
