### ISSUE TITLE
Не могу рассшифровать

### ISSUE THREAD

**Issue by Nikita23117** [open-keychain/open-keychain#2813]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version: 
* Device Model: 
* OpenKeychain Version: 
* From Google Play or F-Droid?: 
 
Восстановить pgp  ключ не могу

**Comment by rafaelrandomize** [comment]
Если это файлы, зашифрованные потерянным ключом, к сожалению, расшифровать эти файлы будет невозможно.

**Comment by Valodim** [comment]
:shrug:
