### ISSUE TITLE
Yubikey email signing feature request

### ISSUE THREAD

**Issue by J0nnyMak0** [open-keychain/open-keychain#2826]
## Expected Behavior
I use yubikey with mutt to sign emails. And this is how it works:

1. Compose email
2. Hit send
3. Mutt (via pinentry-gnome3) prompts to insert yubikey/enter pin
4. Mutt signs email and sends it

It would be nice if openkeychain can provide a comparable workflow so my private keys remain on my yubikey.

## Current Behavior
I have to import my private keys into openkeychain for my mail client (k9mail) to be able to sign my messages.

## Possible Solution
When sending emails from k9mail (or other apps that support openkeychain), it spawns openkeychain which can in turn prompt to NFC scan yubikey and enter pin to sign the message.

## Context
For my use case yubikeys provide a good solution in terms of security for separating private and public key storage as well as securing private keys with pin and auto wipe features. I would like to avoid duplicating a similar workflow on the phone with other apps if possible and not store my private keys on the phone.

## Your Environment

* Android Version: 13
* Device Model: Pixel 6
* OpenKeychain Version: 5.7
* From Google Play or F-Droid?: Google Play

**Comment by CueHD** [comment]
This is the current behavior. Here is how you would set it up:
Import your **public** keys into Open-Keychain
Touch your YubiKeys to let Open-Keychain know that the private keys are stored on a smartcard (YubiKey).
Proceed as normal with your e-mail client.

This is what a private key that is stored on a Yubikey will look like in Open-Keychain. Note that I specifically chose to not have the private master key on this YubiKey. Normally, it would be present.
![Screenshot](https://github.com/open-keychain/open-keychain/assets/33906238/02cd236f-d7d5-4c91-a2ab-6077dd06e624)
