### ISSUE TITLE
Does not support AES256.OCB encrypted data

### ISSUE THREAD

**Issue by flowthentic** [open-keychain/open-keychain#2830]
## Expected Behavior
Read content of an encrypted file created with `pass generate` using GnuPG as it's backend.

## Current Behavior
When I open the file in PasswordStore android app.
Error from OpenKeyChain: Encountered an error reading input data.

## Possible Solution
There should be a way to force older encryption mode in GnuPG, which I couldn't find, or implement the new cipher mode in OpenKeyChain.

## Context
I am using OpenKeyChain with password store. On computer when I encrypt a new file (generate password), it is not possible to decrypt on my phone with OpenKeyChain. Probably gpg started to use new encryption mode since some update.

gpg -v **working.gpg** 
gpg: public key is 9B879EF42D61922A
gpg: using subkey 9B879EF42D61922A instead of primary key 1BADF951CFDB441B
gpg: encrypted with rsa4096 key, ID 9B879EF42D61922A, created 2020-05-13
gpg: **AES256.CFB encrypted data**

gpg -v **not_working.gpg**
gpg: public key is 9B879EF42D61922A
gpg: using subkey 9B879EF42D61922A instead of primary key 1BADF951CFDB441B
gpg: encrypted with rsa4096 key, ID 9B879EF42D61922A, created 2020-05-13
gpg: **AES256.OCB encrypted data**

## Your Environment
* OpenKeychain Version: 5.8.2.58902
* From F-Droid

**Comment by JacksonChen666** [comment]
> There should be a way to force older encryption mode in GnuPG, which I couldn't find

I'm not sure if that option is even possible in GPG, but Thunderbird encrypted emails seems to work similar to whatever was `working.gpg` for you and is decryptable for OpenKeychain.

**Comment by flowthentic** [comment]
Actually, when I save an OpenKeyChain encrypted message into file it is decryptable on my PC. However, it is not vice versa. So even something encrypted directly by GnuPG is not decryptable for OpenKeyChain.

**Comment by flowthentic** [comment]
I have found the solution in a [comment by dvzrv](https://github.com/open-keychain/open-keychain/issues/2096#issuecomment-1885199511)
