### ISSUE TITLE
Thunderbird (OpenPGP) -> OpenKeychain | Keys are stripped

### ISSUE THREAD

**Issue by 40ZqTYY4ag3tAO4hdlxR1** [open-keychain/open-keychain#2848]
## Expected Behavior
Thunderbird (OpenPGP) -> OpenKeychain import works as designed

## Current Behavior
Steps followed to export private keys from thunderbird 
https://kb.mailfence.com/kb/export-openpgp-keypair-thunderbird/

Thunderbird generates the correct file I guess myemail@gmail.com-(0x1234566756756856)-secret.asc

Once imported the keys are stripped. OpenkeyChain claims its a private key, but the keys _cannot be used to decrypt or encrypt messages_. See image(s) below.

**OpenKeyChain sees the key, and says its the secret key**
![Step_1_OpenKeychain](https://github.com/open-keychain/open-keychain/assets/52233671/b85aa660-9fb7-4435-9866-4ecbac35efe8)

**OpenKeyChain has imported the key but it is stripped.**
![Step_4_OpenKeychain](https://github.com/open-keychain/open-keychain/assets/52233671/3c328c0c-0324-4399-b6e7-1f6aac9612f2)
![Step_6_OpenKeychain](https://github.com/open-keychain/open-keychain/assets/52233671/70dd82bf-068e-4711-a998-eafd3c592a3a)

**The key works perfectly in Thunderbird**
![Step_12_Thunderbird_](https://github.com/open-keychain/open-keychain/assets/52233671/a5d075a6-811a-4cb9-937d-f1b640316ba1)

## Possible Solution
Its one of two things. Thunderbird broke it or OpenKeyChain misread it.
![spider](https://github.com/open-keychain/open-keychain/assets/52233671/a5137ff2-0827-4ad6-a8dd-9af485f71c28)

## Steps to Reproduce (for bugs)
Export private key from Thunderbird 115 and import it in to open-keychain 

## Context
This has worked succesfully in the past for me on my other android device(s) Thunderbird → OpenKeychain → K9
Probably done this thrice in the past using the same steps each time. This time tried reinstalling OpenKeychain twice.

On my first try this time, I simply restored the OpenKeyChain backup file _MyBackup_YYY-MM-DD.sec.pgp_ . This has been my preferred restore method in the past. When that did not work, I first assumed the backup file might have gotten corrupted. So exported a fresh private-keyfile from Thunderbird. No Joy.

Note : K9 is behaving as expected.

## Your Environment

* Android Version: 11
* Device Model: G920F
* OpenKeychain Version: 5.8.2
* From Google Play or F-Droid?: F-Droid

**Comment by rafaelazvdo** [comment]
Well, I did a test here and the key pair generated in Thunderbird worked perfectly in Openkeychain together with K-9 Mail and FairEmail.  But one thing I noticed from your prints, was that you did not export the public key from Thunderbird and did not import this public key into Openkeychain, probably that alone would not cause this error, but do the test and export the public key of this pair in Thunderbird and import into Openkeychain.

**Comment by 40ZqTYY4ag3tAO4hdlxR1** [comment]
Just tried your recommendation. 

In order to start with a clean slate, first removed all previous key import attempts, cleared app cache, app data, uninstalled, reinstalled from F-droid.

Exported the public key from Thunderbird and the private key. Got two files. `mykey-pub.asc` and `mykey--secret.asc`

Moved them to the Android device. 
**First imported the public key.**
![Import_Public_Key_1_OpenKeychain](https://github.com/open-keychain/open-keychain/assets/52233671/b55f8756-733a-4c27-9753-c873b5929d26)

Then imported the secret key... **No Joy**.
![Import_Public_Key_2_OpenKeychain](https://github.com/open-keychain/open-keychain/assets/52233671/ae543daf-0437-4069-bd6e-f63a74e13f5a)


Will post screenshots of an import of a known good OpenKeyChain backup file in the next post.

**Comment by rafaelazvdo** [comment]
Well, very strange, have you tried creating another key to see if the behavior repeats itself?

**Comment by 40ZqTYY4ag3tAO4hdlxR1** [comment]
Good point will do try that.
I have a separate email address in Thunderbird that does not have PGP yet. Will try that and report back.

Even though I would like to blame Thunderbird, and it deserves the blame for the way they implement OpenPGP. I have a suspicion that this has to do with permissions for org.sufficentlysecure.keychain . 

Bear with me on this, the known good back up is dated backup_2023-07-24.sec.asc , version 5.8.2 was released on January 7 2023 on Github and the next day on F-Droid. Openkeychain has been functioning flawlessly till last week on another device, and still is. But it refuses to work on this device. Nothing has changed in the f-droid file, or the known good backup file.

Where is the keystore that Openkeychain accesses? Could it be that it does not have the correct permissions to read/write that file. This is just speculation, _as I do not know what I am talking about._

**Next step will** 

1. Create a new key and test as suggested by @rafaelazvdo 
2. If step 1 does not work. Will also try to install org.sufficentlysecure.keychain as a system app to test my permissions hypothesis. ( _am confident that this is the absolute worst thing to do from a security perspective, if this had any use the authors would have done it_  )

**Comment by 40ZqTYY4ag3tAO4hdlxR1** [comment]
Giving up and closing the issue. New keypair idea did not work either.

NSA is welcome to read my spam store signup emails from anonaddy. Maybe they can clean up the my inbox while they are at it :)

Thank you to @rafaelazvdo helping in troubleshooting this issue.

**Comment by CueHD** [comment]
It looks as though you did not export all of the subkeys.
This website shows two ways to export your secret key from Thunderbird. Perhaps one way works well and the other does not.
https://kb.mailfence.com/kb/export-openpgp-keypair-thunderbird/

**Comment by 40ZqTYY4ag3tAO4hdlxR1** [comment]
> It looks as though you did not export all of the subkeys. This website shows two ways to export your secret key from Thunderbird. Perhaps one way works well and the other does not. https://kb.mailfence.com/kb/export-openpgp-keypair-thunderbird/

That is the **same** sequence of steps & URL that was followed from the **mailfence documentation** that was referenced when I opened the issue.

The same exported backup file, works in other places when tested. Its a open-keychain file permission issue. Not waiting for it to be fixed, will wait for Thunderbird Android , their roadmap says the first release may come in Q4 2023.

**Comment by 40ZqTYY4ag3tAO4hdlxR1** [comment]
That was the first suspect, exported using both sequences. Both the exported backup files, work in other places when tested, just in open-keychain. Will wait for the Thunderbird Android release https://developer.thunderbird.net/planning/android-roadmap
