### ISSUE TITLE
Vulnerability in OpenKeychain

### ISSUE THREAD

**Issue by 012git012** [open-keychain/open-keychain#2856]
Hello,

Researchers discovered a vulnerability in OpenKeychain. The technical report was sent by email (security@openkeychain.org), no response. Please contact us.

**Comment by CryptGoat** [comment]
@dschuermann @Valodim Is this just some bogus report to pick up some facilitated bounty or is this a valid claim?

**Comment by 012git012** [comment]
Hi,

I successfully contacted the security team. The problem is being fixed.
