### ISSUE TITLE
Удалил приложения, но омтался крд от резервного копирования,  больше нечего нет. Помогите востановить пожалуйста 

### ISSUE THREAD

**Issue by Furikjbl** [open-keychain/open-keychain#2875]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Android Version: 
* Device Model: 
* OpenKeychain Version: 
* From Google Play or F-Droid?:

**Comment by rafaelazvdo** [comment]
Unfortunately there is no way to restore the key, the files/emails that were encrypted with the deleted keys are lost forever.

**Comment by kolAflash** [comment]
> Удалил приложения, но омтался крд от резервного копирования, больше нечего нет. Помогите востановить пожалуйста

https://translate.google.com/  
> I deleted the applications, but lost the backup from the backup, there is nothing else. Help me restore please

&nbsp;

As @rafaelazvdo said, there is no way to restore the key, the files/emails that were encrypted with the deleted keys are lost forever. Thats the whole point of encryption. You can only read the mails when you got the key. I'm sorry for you. But it looks like there's no way recovering your emails.
By the way: Please use https://translate.google.com/ or something similar to translate your messages to English. English is also not my mother tongue. But this way it's the easiest. Thanks :-)

https://translate.google.com/  
Как сказал @rafaelazvdo, восстановить ключ невозможно, файлы/электронные письма, зашифрованные с помощью удаленных ключей, теряются навсегда. В этом весь смысл шифрования. Вы сможете читать почту только тогда, когда получите ключ. Мне жаль тебя. Но похоже, что восстановить электронную почту невозможно.
Кстати: используйте https://translate.google.com/ или что-то подобное, чтобы перевести свои сообщения на английский язык. Английский также не является моим родным языком. Но так проще всего. Спасибо :-)
