### ISSUE TITLE
Bug in the Dark/Light mode selection

### ISSUE THREAD

**Issue by krabat693** [open-keychain/open-keychain#2878]
## Expected Behavior
When Selecting light/dark mode the UI should change its colour palette accordingly.

## Current Behavior
On android 14
The switches do the exact opposite. Light mode changes the Colour palette to a dark one and vice versa.

On a little bit of testing, this does occur regardless of my system default (light/dark) 

The automatic option acts as expected.
![Screenshot_20240209-104701_OpenKeychain](https://github.com/open-keychain/open-keychain/assets/140731271/e2a0b08d-7dac-4005-968d-ded0fef5966f)
![Screenshot_20240209-104655_OpenKeychain](https://github.com/open-keychain/open-keychain/assets/140731271/b2603a5e-23c2-4efd-a905-18e65d0e119e)

## Context
Because of the mention of bad visibility for some icons I wanted to force the app to light mode, that's when I noted the unexpected behaviour of that menu option.

## Your Environment

* Android Version: 14
* Device Model: Asus Zenfone 10
* OpenKeychain Version: 5.8.2
* From Google Play or F-Droid?: Google Play

**Comment by Valodim** [comment]
thanks for your report. should be fixed with #2883 and released soon
