### ISSUE TITLE
Version 6.0.0 from F-Droid does not work with FairEmail

### ISSUE THREAD

**Issue by bbbhltz** [open-keychain/open-keychain#2884]
Since upgrading to version 6.0.0 FairEmail is unable to send encrypted or signed emails. Decrypting still works.

## Expected Behavior

* Choose option to encrypt or sign
* receive prompt to select key and enter passphrase/password
* email sends

## Current Behavior

* No prompt to enter password
* Returns `OpenPgp error 0: ResultSet returned more than 1 row for Keys.sq:selecteEffectiveSignKeyIdByMasterKeyId`

![Screenshot_20240217-075410_1](https://github.com/open-keychain/open-keychain/assets/12626746/5985c153-f825-4d33-8b82-f5724f38efdc)

## Possible Solution

* **Currently downgraded to previous version which works as expected**

## Steps to Reproduce (for bugs)

1. write email
2. select option to sign or encrypt, etc. , etc.
4. proceed to send email 
5. error

## Context

* sending encrypted emails
* sending signed emails

## Your Environment

* Android Version: 13
* Device Model: CROSSCALL CORE-Z5
* OpenKeychain Version: 6.0.0
* From Google Play or F-Droid?: F-Droid

**Comment by rafaelazvdo** [comment]
It is the same error that appears with K9-mail, the error has already been corrected in #2881 and a new version will be released soon.

**Comment by bbbhltz** [comment]
Thanks! Sorry for the duplicate issue in that case. I did read the other issue but was uncertain if it was the same error.

**Comment by Valodim** [comment]
new version has been tagged some days ago, should be on fdroid as soon as they finished building it

**Comment by bbbhltz** [comment]
Version 6.0.2 works without issue. Thanks!
