### ISSUE TITLE
Changelog is out of date

### ISSUE THREAD

**Issue by flossposse** [open-keychain/open-keychain#2887]
The changelog has not been updated since v5.7

## Expected Behavior
changelog shows what changed in each version up through the currently installed one

## Current Behavior
changelog stops after 5.7

## Steps to Reproduce (for bugs)
1. From hamburger menu navigate to _Help > CHANGELOG_
OR
from F-Droid, tap on _Links > Changelog_

## Context
Changelogs are important for 
- understanding why the app looks or behaves differently and whether it's intentional
- assessing how urgent an update is
- making a more informed guess as to the potential for broken functionality after install
- knowing when an issue was introduced
- if a downgrade becomes necessary, knowing which version to downgrade to

## Your Environment
* OpenKeychain Version: 6.0
* From Google Play or F-Droid?: F-Droid

**Comment by Valodim** [comment]
I don't think I care enough to spend the effort, sorry. feel free to go through the commits and contribute a changelog, though. I would recommend keeping it at a very high level, one or two bullet points per version maybe.

**Comment by flossposse** [comment]
> I don't think I care enough to spend the effort, sorry.

I'm interpreting this to mean that you don't care to go digging through the commit logs to create all the entries for historical releases, which is fair enough.  I've opened https://github.com/open-keychain/open-keychain/pull/2888 for that.  

I do hope that going forward, though, committers can be reminded to update the changelog when they fix an issue or add a feature.  It's a lot more efficient, and more likely to be accurate, if the author includes that in their PR.
