### ISSUE TITLE
Version 6.0.2 : error decrypting email (K-9 Mail & FairEmail)

### ISSUE THREAD

**Issue by Sami32** [open-keychain/open-keychain#2889]
OpenKeychain 6.0.2 fail to decrypt email with K-9 Mail.
It was working fine before the version  6.0.0.

## Your Environment
* Android Version: 7.0
* Device Model: Xiaomi Redmi Note 4
* OpenKeychain Version: 6.0.2
* From Google Play or F-Droid?: F-Droid
* K-9 Mail v. 6.717 from GitHub

![IMG_20240225_100808](https://github.com/open-keychain/open-keychain/assets/18471069/4dadb9c7-bae6-414f-95b4-d6443f228da5)

**Comment by Valodim** [comment]
Thanks for the screenshot, that should be enough figure this out. I'll look into it.

**Comment by rafaelazvdo** [comment]
> Thanks for the screenshot, that should be enough figure this out. I'll look into it. 

@Valodim I'm having this error in FairEmail.

![Screenshot_20240226_092900_FairEmail.jpg](https://github.com/open-keychain/open-keychain/assets/122113441/292b8e49-9fb0-4c43-a048-77a402faf0f6)

**Comment by Valodim** [comment]
Fixed in c3e330b30413e79a1f48a432d21a1b557acced49
