### ISSUE TITLE
6.0.2 still crashing with k9mail

### ISSUE THREAD

**Issue by q-pa** [open-keychain/open-keychain#2891]
Adding an address that is connected to a key crashes k9mail. Other addresses work. 

## Expected Behavior

No crash. 

## Steps to Reproduce (for bugs)

1. activate openkeychain with email account in k9mail
2. add an email address into TO: field (e.g. your own address which has a key
3. observe a quick crash
4. -

## Your Environment

* Android Version: 14 (LineageOS 21)
* Device Model: Pixel 3 XL
* OpenKeychain Version: 6.0.2
* From Google Play or F-Droid?: F-Droid

**Comment by q-pa** [comment]
Crashes seem to be connected to the search routine. Cannot use any letters for address completion that are also part of key-connected addresses. Others seem to work.

**Comment by rafaelazvdo** [comment]
What version of K9-mail are you using?

**Comment by q-pa** [comment]
Version 6.603

**Comment by pokulo** [comment]
I also encounter the crash still. I just reported the traceback I recorded in the old issue:
https://github.com/open-keychain/open-keychain/issues/2881#issuecomment-1963045391

**Comment by pokulo** [comment]
I propose PR #2892 to fix this crash as well (not tested yet).

**Comment by Valodim** [comment]
Should be fixed in the next release

**Comment by pokulo** [comment]
looking forward

**Comment by pokulo** [comment]
Fixed for me. Ca now write encrypted mails again. Thanks @Valodim .

**Comment by q-pa** [comment]
Also fixed for me. Thanks @Valodim
