### ISSUE TITLE
помогите пожалуйста

### ISSUE THREAD

**Issue by Casper3103** [open-keychain/open-keychain#2894]
## Steps to Reproduce (for bugs)

1. телефон на котором был востоновочный файл и сам аунтификатор утеряны. я нк могу зайти на площадку . соответсвенно мои деньги застряли. помогите!!
2.
3.
4.

## Your Environment

* Android Version: 11
* Device Model: n950f
* OpenKeychain Version: 5.8.2
* From Google Play or F-Droid?:

**Comment by rafaelazvdo** [comment]
Well, unfortunately your money will remain tied up forever.

Что ж, к сожалению, ваши деньги останутся привязанными навсегда.
