### ISSUE TITLE
version 6.0.4 was tagged and now gone

### ISSUE THREAD

**Issue by licaon-kter** [open-keychain/open-keychain#2895]
F-Droid checkupdate picked it up https://gitlab.com/fdroid/fdroiddata/-/commit/a6d7a6c1599deed8d1d8b2ce64f8c702311c9488

ref: https://github.com/open-keychain/open-keychain/commit/e40797b919cf920e7ccd91b11648325527eb8720

should F-Droid not build it?

**Comment by Valodim** [comment]
This was an accidental push, sorry about that. Man fdroid is fast, it was only there for a minute or so :see_no_evil: yes, please drop it from fdroid.

**Comment by licaon-kter** [comment]
thanks https://gitlab.com/fdroid/fdroiddata/-/commit/d41bd1bd33ce5ee9c5acaeb8c015a3c4a6bd38bd
