### ISSUE TITLE
"No encrypted data with known secret key found in stream"

### ISSUE THREAD

**Issue by em2943** [open-keychain/open-keychain#2899]
I have encrypted a file with gpg on my laptop & put it on my phone to decrypt later, but openkeychain doesn't decrypt it, instead it says "No encrypted data with known secret key found in stream" the secret key is in openkeychain
![Screenshot_20240302-210405_OpenKeychain_1](https://github.com/open-keychain/open-keychain/assets/79891947/d6750941-e440-40cc-b4db-42f53f397bb1)

## Steps to Reproduce (for bugs)

1.  gpg -se filename
2. move the file to phone
3. try & decrypt it with openkeychain
4. "No encrypted data with known secret key found in stream"

## Your Environment

* Android Version: 12
* Device Model: SM-A125U Galaxy A12
* OpenKeychain Version: 6.0.2
* From Google Play or F-Droid?: F-Droid

**Comment by rafaelazvdo** [comment]
What version of gpg is installed on your laotop?

**Comment by em2943** [comment]
2.4.4
> What version of gpg is installed on your laptop?

**Comment by rafaelazvdo** [comment]
> 2.4.4
> > What version of gpg is installed on your laptop?
> 

Was the key pair created using this version of gnupg?

**Comment by em2943** [comment]
yes
> > 2.4.4
> > > What version of gpg is installed on your laptop?
> 
> Was the key pair created using this version of gnupg?

**Comment by rafaelazvdo** [comment]
Apparently Openkeychain is not compatible with encryption created with gpg version above 2.2 and keys created with gpg above version 2.2.  You can use these keys created with gpg 2.4, but you will have to use gpg 2.2 to encrypt the files for them to work on Openkeichain.

**Comment by em2943** [comment]
ah, hope that changes sometime

**Comment by em2943** [comment]
I tried 2.2.40 & it also doesn't work

**Comment by rafaelazvdo** [comment]
> I tried 2.2.40 & 2.2.17 it also doesn't work, this may not be a version issue

I tested it here and it worked the way I said in the comment above, I created a new pair of keys with gpg 2.4.4 but I used gpg 2.2.27 to encrypt the files using this pair of keys, I was able to decrypt the files using Openkeychain.

**Comment by em2943** [comment]
are you using any flags that I may not be, because it still doesn't work for me on 2.2.27

> > I tried 2.2.40 & 2.2.17 it also doesn't work, this may not be a version issue
> 
> I tested it here and it worked the way I said in the comment above, I created a new pair of keys with gpg 2.4.4 but I used gpg 2.2.27 to encrypt the files using this pair of keys, I was able to decrypt the files using Openkeychain.

**Comment by em2943** [comment]
I just now made a key on 2.2.27 & encrypted a test file & imported the priv key to openkeychain, same error

**Comment by rafaelazvdo** [comment]
> I just now made a key on 2.2.27 & encrypted a test file & imported the priv key to openkeychain, same error

Update Openkeychain to version 6.0.4, and try again, I used Kleopatra with gpg 2.4.4 on Windows to create the keys and I used Kleopatra with gpg 2.2.27 on Linux to encrypt the files.

**Comment by feelamee** [comment]
@em2943
Hey, you closed issue.
May be you founded solution for this? I have same problem

**Comment by em2943** [comment]
No I have not
