### ISSUE TITLE
Can't restore Backup

### ISSUE THREAD

**Issue by vigi86** [open-keychain/open-keychain#2906]
## Expected Behavior
Successful Backup Import

## Current Behavior
Because of issue #2905 I made a backup, reinstalled the app and wanted to import the backup. I am unable to restore the backup. App was already newest version before initializing backup.

## Steps to Reproduce (for bugs)

1. I go to "Backup/Restore".
2. I choose the backup file to restore
3. I see that in the background a loading icon is turning and next to it says that "reading data" ("Daten werden gelesen..." in German)
4. I type in the transfer code in the modal window.
5. Modal window reopens asking to type in the transfer code and is empty again. 
6. Nothing happens. 
7. If I click next to the modal window, the banner says "process cancelled" ("Vorgang wurde abgebrochen" in German)

## Context

It affects me, that I lost all the keys.

## Your Environment

* Android Version: 13
* Device Model: Samsung Galaxy S20 Ultra 5G
* OpenKeychain Version: 6.0.4
* From Google Play or F-Droid?: Google Play & F-Droid has same behaviour.

**Comment by vigi86** [comment]
> Try decrypting the key with Kleopatra on Linux or Gpg4Win on Windows and then try importing the .asc file into OPK.

You mean open the backup file in Kleopatra/Gpg4Win?

**Comment by rafaelazvdo** [comment]
> > Try decrypting the key with Kleopatra on Linux or Gpg4Win on Windows and then try importing the .asc file into OPK.
> 
> You mean open the backup file in Kleopatra/Gpg4Win?

Yeah, that's right, when typing the password, you must type the sets of numbers and the dashes that separate them too.

**Comment by vigi86** [comment]
OK, that worked. I was able to decrypt and open it with Kleopatra. At least the backup works. Under "Keys" I can now select the decrypted file and it recognizes all the keys.

Thanks for your help, Rafael. 👍🏻 

Guess my system is just being weird.

Victor
