### ISSUE TITLE
ZXING installation

### ISSUE THREAD

**Issue by faysalhossain2007** [open-keychain/open-keychain#427]
When i try to do a qr scan it suggests me to install zxing applicaiton  in my device. We can add the zxing source to the existing openpgp-keychain  so it doesn't need to have the zxing scanner installed in the device. I think it will be more user-friendly.

**Comment by janseeger** [comment]
What happened to *not* including the zxing lib between back then and now?

**Comment by dschuermann** [comment]
It was a security decision.
Other apps can define and intent filter for ZXing's scanning Intent. If they are selected they could return a different fingerprint than the one that was actually scanned. Because there is now also a maintained scanning library we decided to include it.
