### ISSUE TITLE
Lookup missing key more than only once

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#486]
Pendingintent should work more than once. Others also?

**Comment by mgeier63** [comment]
+1 and please also consider this related use case:

An app calls decrypt and gets back a PendingIntent to enter the key password in OpenKeyChain. The app then shows a notification that tells the user that he needs to enter the password in OpenKeyChain, when tapping that notification the original PendignIntent from OpenKeyChain will get fired.

If the app now does another decrypt information (in the background), before it uses the original PendingIntent to unlock the key, it gets a new PendingIntent and the PendingIntent from the first operation becomes stale, i.e. can't be used any more, will throw an IntentSender exception or so when attempting to use.
 
I had to do implement quite some workaround in my app to make sure that only the _latest_ PendingIntent gets used and/or that no other decrypt operation happens before using the PendingIntent of the last operation.

A possible easy workaround for me would be if you would just somehow expose (possibly in the OpenKeyChain Intent API) a method or Intent that I could call _anytime_ to unlock a specific key - even preemptively _before_ attempting a decrypt operation.

**Comment by dschuermann** [comment]
@mgeier63 You are commenting on a closed issue from 2014, please open a new one
