### ISSUE TITLE
UI for detached file signatures

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#557]
The OpenPGP standard contains a way to generate detached file signatures. There is also an example in Bouncy Castle

**Comment by uweplonus** [comment]
When implementing the third possibility proposed by me in [Extending Open-Keychain](https://groups.google.com/d/topic/openpgp-keychain-dev/cDcnWYLnUyg/discussion) then this bug should be solved at almost no further cost.

**Comment by dschuermann** [comment]
We need a UI to allow detached file signatures from OpenKeychain, so if anyone wants to work on it...

**Comment by dschuermann** [comment]
Now here: https://github.com/open-keychain/open-keychain/issues/1380
