### ISSUE TITLE
gradle's build task fails on Mac OS X (javadoc encoding issue)

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#558]
gradle's build task seems to depend on javadoc task, preventing the project to be build on Mac OS X because of encoding issues.
Exporting JAVA_TOOL_OPTIONS="-Dfile.encoding=UTF8" is a reported workaround.

Maybe we need to add ``options.encoding = 'UTF-8'`` to some javadoc tasks?

**Comment by kritkaran94** [comment]
@dschuermann The build failed for me too on Mac OS X. Any other alternatives ?

**Comment by dschuermann** [comment]
@kritkaran94 I don't know, I don't have a Mac. Can you search online for the error?

**Comment by kritkaran94** [comment]
No worries @dschuermann I will find a solution for this.
