### ISSUE TITLE
Implement better exception handling in KeychainIntentService

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#559]
Implement a better exception handling in KeychainIntentService.sendErrorToHandler()
* currently the messages shwon in the activities are created here based on the exceptions
* we should however create messages in the activity because it is part of the UI code
* services can't throw exceptions easily to activities in Android
-> find a better way

**Comment by Valodim** [comment]
this was fixed with the introduction of operations and result parcels
