### ISSUE TITLE
Openkeychain 2.6 crashes when trying to add encryption key from K-9

### ISSUE THREAD

**Issue by bungabunga** [open-keychain/open-keychain#593]
1. downloaded aplha version of k-9 with API v3 / Openkeychain support
2. set the encryption to Openkeychain on k-9
3. opened encrypted e-mail and clicked decrypt button
4. allowed Openkeychain to access k-9
5. was prompted to set new account / choose key to decrypt message
6. when clicked button to choose key app crashed

then i exported all keys, deleted them on Openkeychain, re-import them (as suggested on Openkeychain's G+ page). tried to decrypt that email once again but Openkeychain crashed again.

so i uninstalled the app, installed it again and imported keys again.

now everything works!

it seems to me an upgrade issue...

**Comment by pereimer** [comment]
I just (that is today, 29 Nov 2017, downloaded K-9 and openkeychain from google, and have this exact problem.  Openkeychain crashes when I hit send.  I've tried to reinstall both K-9 and openkeychain twice and have the same results.

**Comment by pereimer** [comment]
I forgot to mention that it has no problems decyrpting e-mail with K-9 and openkeychain

**Comment by Valodim** [comment]
That's not the same issue. It's likely fixed by 62528fc941fd2c3f5543b7f550933e13ee3d886d already, which will be in a bugfix release very soon.
