### ISSUE TITLE
Generic OpenPGP SEND Intent

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#618]
Similar to Intent.ACTION_SEND with same extras (http://stackoverflow.com/questions/2197741/how-to-send-email-from-my-android-application), but only applications supporting OpenPGP API should register the intent filter!

1. New Intent action: ``org.openintent.openpgp.action.SEND``
2. Patch K9 to use it
3. Make email buttons to OK user id list

**Comment by Valodim** [comment]
is this one still relevant?

**Comment by dschuermann** [comment]
Half-relevant. I would do it differently in comparison to this old idea. Will open a new issue for it
