### ISSUE TITLE
OpenPGP Error. Unknown object in stream: 16

### ISSUE THREAD

**Issue by sbriskin** [open-keychain/open-keychain#635]
I have an error message on decryption of email containing encrypted reply with previous encrypted message - one encrypted block inside other.
Other mail clients (Thunderbird, Claws and Evolution) opens it easily.

**Comment by dschuermann** [comment]
K-9 Mail related bug reports are now tracked at https://github.com/k9mail/k-9/milestones/PGP/MIME
If no corresponding bug report exist under https://github.com/k9mail/k-9/milestones/PGP/MIME, please open a new one.

Also read our announcement at https://www.openkeychain.org/k-9/
