### ISSUE TITLE
K-9 Mail: partially signed messages

### ISSUE THREAD

**Issue by ashh87** [open-keychain/open-keychain#637]
Long term thought for a feature:

enigmail doesn't completely reject emails where only part of the message is signed, namely replies to signed messages (in the correct format). Currently, the app says the signature on such an email is invalid, but it would be neat if it could behave similarly to Enigmail, although I wonder if it would need to be made clear exactly which parts were correctly signed.

**Comment by dschuermann** [comment]
K-9 Mail related bug reports are now tracked at https://github.com/k9mail/k-9/milestones/PGP/MIME
If no corresponding bug report exist under https://github.com/k9mail/k-9/milestones/PGP/MIME, please open a new one.

Also read our announcement at https://www.openkeychain.org/k-9/
