### ISSUE TITLE
SecureRandom not sufficiently random on Android

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#69]
On Android < 4.2 SecureRandom has problems.

https://news.ycombinator.com/item?id=6195493

Use http://code.google.com/p/bitcoin-wallet/source/detail?r=04d2044880d88107ee4a939a516fb4be4cedeaf9&name=bitcoinj-0.10

**Comment by bulldozer2003** [comment]
I'm sorry to comment on a closed issue, but should key-pairs generated with this app, on Android <4.2, prior to the vulnerability disclosure, be discarded/revoked, or at least no longer used?

**Comment by dschuermann** [comment]
@bulldozer2003 Better safe than sorry, so yes.
