### ISSUE TITLE
Export private key funtionality missing?

### ISSUE THREAD

**Issue by quatrox** [open-keychain/open-keychain#700]
I generated my private key on my android device and would like to export it so I can use it on other devices as well.  How can I do that?

**Comment by dnwk** [comment]
I do not see that export to a file option right now. Is there anyway to export the private key to be used in a different system?

**Comment by Valodim** [comment]
The "export" feature has been renamed to "backup", which is a more conventional term for writing important data to a file for later than "export". this backup is encrypted in the usual pgp format, and can be opened with GnuPG or other implementations. there is a point about this in our [faq](https://www.openkeychain.org/faq/) as well.

**Comment by Isenhorn** [comment]
Am I missing something or doesn't the backup "export" the private key in the current version?
I've created a key wit OKC...made a backup and transfered it to my laptop. Decryption and import worked, but it only imported the public key.

**Comment by dschuermann** [comment]
@Isenhorn you are commenting on a closed issue. Please write general questions to our mailinglist.
You need to click "All keys + your own keys" inside our backup to also export the private keys.
