### ISSUE TITLE
OK caching passphrase forever?

### ISSUE THREAD

**Issue by petervnv** [open-keychain/open-keychain#809]
Hi,

I'm experiencing a strange issue with latest OK (also happened with 0.7) and K9 on my Samsung Tab4 (SM-T530) with stock ROM (4.4.2)
Basically, even though I tell OK not to cache my passphrase, whenever I open an encrypted email in K9 it gets automatically decrypted without prompting for my passphrase.

The same software versions (OK and K9) on my S3 with custom ROM (Liquidsmooth 3.0 with 4.4.4) works as expected, so I assume that my Tab4 is somehow caching the passphrase. The passphrase continues to stay cached even after a full reboot, so I'm not sure where I can look to see what's happening.

Anyone else experiencing this? Obviously this is a major security issue since anyone with physical access to the Tab4 can read all emails without entering the passphrase for the private key.

Thanks

**Comment by davidhedlund** [comment]
I have selected the "Remember until cleared" option when I typed the password but it is forgotten when the phone is rebooted.

**Comment by davidhedlund** [comment]
Should this issue be re-opened?

**Comment by bam80** [comment]
> Starting with OK 2.8, we show a notification including a button to clear the cache. Is this notification shown? If yes, does clicking the button clear the cache or is this also not working?

Is the notification still showing? I don't see it and don't know how else to clear the password:
#2988

**Comment by davidhedlund** [comment]
* https://github.com/open-keychain/open-keychain/issues/2989
