### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by twprogrammers** [open-keychain/open-keychain#854]
I love this PGP app. It's faster and has more features than APG. I only have 2 issues with it:
1. The theme scalds my eyes. I hate white themes, they hurt the eye late at night.
2. The other issue is more of a mild annoyance that I can get used to: the encrypt buttons are backwards to me. It makes more sense to me to have "Encrypt & Save"/"Encrypt & Copy" then "Encrypt & Share" and I find it confusing the way it is now. I would have put "Encrypt" separate from the "Copy" and "Share" on plain text and have "Encrypt & Save" then "Encrypt & Share" on files.

**Comment by mark-orion** [comment]
Just to throw in my 1000 points for the dark theme.

**Comment by dschuermann** [comment]
Will be an experimental feature in the upcoming version.
