### ISSUE TITLE
Yubikey:  key generation (on or off key)

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#875]

**Comment by Valodim** [comment]
promotion of public keys to yubikey-attached-secret-keys is done (#1028)

generating keys on the yubikey itself or generating them then moving them to the yubikey is a whole different beast, and requires evaluation if it even works reasonably well via nfc. seems low-prio for the moment

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/commit/a9c606d49bf7d4e7a30b7265cd1fb04ff1c3c01c
