### ISSUE TITLE
Yubikey: NfcActivity UI should be more usable

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#890]
* When the Yubikey is attached correctly and the Intent is received in ``onNewIntent`` the user should be informed to not release the Yubikey while the operation is executed. Maybe some kind of progress bar would help.
* Replace "Yubikey" with more generic "NFC-enabled OpenPGP-card"? Actually I think we can leave "Yubikey" as long as no one shows me an alternative to the Yubikey NEO (I haven't found any other product with the same features)
* Better image to show how to hold the Yubikey against the device or a heat map like in https://play.google.com/store/apps/details?id=co.mclear.nfcringpro ?

**Comment by Valodim** [comment]
(sorta done, might close)
