### ISSUE TITLE
k9mail quotes ASCII-armored encrypted block in reply

### ISSUE THREAD

**Issue by mikebw** [open-keychain/open-keychain#896]
When replying to an encrypted message, including from the screen where it is already correctly decrypted and readable, k9mail quotes the ASCII-armored encrypted message. This is never useful, as the addition of leading ">" indicators makes the quoted block unable to be automatically decrypted.

If this is a misguided security feature, it would be better to entirely disable quoting in reply to an encryted message, but this would lead to a great deal of inconvenience and confusion in dealing with e-mail. The desired behavior is what APG does, which is to quote the decrypted message text.

**Comment by dschuermann** [comment]
K-9 Mail related bug reports are now tracked at https://github.com/k9mail/k-9/milestones/PGP/MIME
If no corresponding bug report exist under https://github.com/k9mail/k-9/milestones/PGP/MIME, please open a new one.

Also read our announcement at https://www.openkeychain.org/k-9/
