### ISSUE TITLE
Verify Yubikey signatures

### ISSUE THREAD

**Issue by Valodim** [open-keychain/open-keychain#903]
Currently, we trust that the signed hash we get from a yubikey is correct and deliver it without further checks. I'd much rather throw an error than give an invalid signature here.

Validating is an expensive operation and we'd have to go through the data a THIRD time to do that - we however already have the data digest hash! Unless I get my crypto wrong here, we should be able to do "signature^d mod n" and if the signature is correct receive the hashed digest. I'm not sure if there is a way to coerce PGPSignature to just verify() without init() and update(), should look into that.

This is "nice to have" priority at best, just leaving this here for maybelater.

**Comment by dschuermann** [comment]
@Valodim Is this still true?

**Comment by Valodim** [comment]
Well it's true in principle, but I reckon a check for the key fingerprint on the yubikey is just as good...
