### ISSUE TITLE
K-9 Mail: auto-sign/ auto-encrypt

### ISSUE THREAD

**Issue by dschuermann** [open-keychain/open-keychain#920]
Implement Auto-sign/ auto-encrypt in k9 using the GET_KEY API method

**Comment by SourcemakerHD** [comment]
Are there any plans to implement it? In AGP it's available, but OpenKeyChain seems to be better :)

**Comment by dschuermann** [comment]
Yes plans exist, somebody needs to do it... ;)

**Comment by derNarr** [comment]
Does the plans still exists and include the near future for this feature? This is the show stopper for me at the moment. All other things look very nice within OpenKeyChain :) but I am to lazy in order to do not have this feature... :(

**Comment by JessieAMorris** [comment]
I'm taking a look into this. Looking at the OpenPgpService in the mBinder class there is a case for the GET_KEY API. I'm going to do some more research and see if I can figure out exactly where the issue is. I want to get this fixed and submit a pull request this weekend.

**Comment by dschuermann** [comment]
@JessieAMorris There is no real issue, nobody did this until now :) We would be happy if you would like to work on this issue. If you have any questions don't hesitate to ask. The API should hopefully provide all required information to implement this in K-9 Mail.
K-9 Mail is has changed a lot internally compared to the published version so there is much to implement currently. Also see https://github.com/k9mail/k-9/issues/572

**Comment by JessieAMorris** [comment]
It looks like this is an issue inside of K9 mail (https://github.com/k9mail/k-9/blob/5.0-MAINT/src/com/fsck/k9/activity/setup/AccountSettings.java#L748).

They're checking the name of the provider and if it isn't APG then they're disabling the option. Looks like I  am going to be making a pull request for K9 Mail and maybe Open Keychain as well.

**Comment by JessieAMorris** [comment]
Scratch that, it was removed on the master branch. I'm still working on understanding the K-9 project. It was removed and I'm working to add it back in.

**Comment by bitkleberAST** [comment]
Hi, I'd like to ask what's the current state of this issue? Will be there a solution (someday)? How high is the demand for this feature, or is there still someone demanding this? I'd love to see this, because OK is the best key provider in the market and it would help me in "spreading the word" to get my family and friends to encrypt just every email they write without thinking about it. :)

**Comment by linkp** [comment]
I realize that this is an issue with K-9 code, but it has bitten me on more than one occasion, and I would love to see it fixed. Does anyone know if it has a related bug over at K-9? I did not find one with a cursory search of their open issues that contained the term "openkeychain". (There are no issues that contain "open-keychain".)

**Comment by dschuermann** [comment]
@Valodim is working on this one.

**Comment by Valodim** [comment]
I am. No reason to track it here either, imo
