### ISSUE TITLE
Allow to set multiple keys by account

### ISSUE THREAD

**Issue by cjeanneret** [open-keychain/open-keychain#923]
Hello!

I love openkeychain integration with k9. Really.
I just stumbled on a bad behavior/limitation though: I have one mail account with a lot of aliases. And about 10 gpg keys (all independent).
When registering k9 to OK, it detects mail account, and propose to selection one key. Meaning future encryptions or decryptions are forced through this unique key…
In my case, this isn't good at all :( .

Would be really great of we could select multiple keys for one account. Or have a way to tell OK "find if you have a key matching email/id"

Thanks a lot for this nice app - ui is just amazingly smooth and easy.

Cheers,

C.

**Comment by Valodim** [comment]
no longer relevant, accounts are deprecated
