### ISSUE TITLE
K9: verify signature without private key

### ISSUE THREAD

**Issue by sedrubal** [open-keychain/open-keychain#947]
Hi, I want to use OpenKeychain to verify signatures of emails in k9 mail (and maybe encrypting unsigned mails) without saving my private key on my smartphone, because I don't want to decrypt or sign emails on the phone. Why do I have to select a private key for my k9 mail accounts to use  OpenKeychain? APG supports this but  OpenKeychain doesn't...

**Comment by sharvadharma** [comment]
hi , 
i m beginner for this encryption decryption 
i used openkeychain and k9 mail 
i create a private sks server by the following link
https://njh.eu/keyserver
and then i add my key server in openkeychain as following
hkp://myserverip:11371
and i uploaded my key to the server through openkeychain 
and i checked that key in server server has that key 
 i tried to search the key from the server 
i recieved mesage no keys found 

what i have to do for importing keys in open keychain 

thanks in advance
