### ISSUE TITLE
Add support for PQC algorithms?

### ISSUE THREAD

**Issue by gmkarl** [open-keychain/open-keychain#957]
Bouncy/spongycastle already includes the BCPQ provider for post-quantum cryptographic algorithms.  It would be great for open-keychain to allow creating and using such private keys.

**Comment by jayb-g** [comment]
@dschuermann maybe its time to reopen ?

**Comment by sebbu2** [comment]
It definitively is, it's been added to gnupg last year in v2.5.0, and rfc is in progress (draft-ietf-openpgp-pqc-12).
Edit: FIPS (202-205) has already standardized it last year too.
