### ISSUE TITLE
Link all "my keys" to the PROFILE contact in Android

### ISSUE THREAD

**Issue by Magissia** [open-keychain/open-keychain#958]
Own key isn't linked to "myself" in Contact app like is "myself" Google+ account on AOSP contact app. 

The "myself" contact entry do have the same mail address and name than the Open-keychain key have.

**Comment by dschuermann** [comment]
@adithyaphilip You did great work on the other sync related problems. Would you like to look into this? Should be easy:  Link all "my keys" from OpenKeychain to this one "me" contact without doing email checks.

**Comment by adithyaphilip** [comment]
Yup, I'm on it! :)
