### ISSUE TITLE
Deleting a Key does not prompt to create revocation certificate

### ISSUE THREAD

**Issue by baudtack** [open-keychain/open-keychain#970]
Sooo... I generated keys with openkeychain and it crashed. twice. When I finally managed to make a key, I found the other two keys living there. However, not thinking they were valid or that they had been uploaded to a keyserver, I just deleted them. So now i have in the wild two dead keys that will never be able to get rid of.

**Comment by dschuermann** [comment]
done in https://github.com/open-keychain/open-keychain/pull/1435
