### ISSUE TITLE
Certify screen: Wording discussion

### ISSUE THREAD

**Issue by timbray** [open-keychain/open-keychain#971]
I’m running a week-or-so old build and the new certify is an improvement, but it still isn’t very civilian-friendly.  I sketched in code (just XML fiddling) to try to make what’s going on a little more useful to non-geeks.  Useful direction?

![screenshot_2014-10-20-11-34-14](https://cloud.githubusercontent.com/assets/17555/4706840/5bfdc664-5888-11e4-8a8d-2d7e4a21ad41.png)

**Comment by dschuermann** [comment]
closing this discussion for now. I recently changed to "confirm". Let's see how this will be received in our next release. Also there is an explanation in the help screens about our trust model.
