### ISSUE TITLE
Creating a new key shouldn't have "never" as expiry

### ISSUE THREAD

**Issue by turion** [open-keychain/open-keychain#988]
When creating a new key, it's maybe more sensible to have the default expiry date 4 years in the future, or at least give the user the option to set it.

**Comment by Valodim** [comment]
I agree with this.

@dschuermann?

**Comment by dschuermann** [comment]
I don't like the general concept of expiry in PGP. After discussing with @Valodim again, I have written an entry in our FAQ about it: https://github.com/open-keychain/open-keychain/wiki/OpenPGP-Security#no-expiry
