### ISSUE TITLE
HTC One with YubiKey NEO: Freezes or "Connection error: transceive failed"

### ISSUE THREAD

**Issue by andrew-d** [open-keychain/open-keychain#990]
Hi there,

I'm running OpenKeychain on a HTC One M7 (bought in July of 2013) on Android 4.4.2, and attempting to use it with a Yubikey NEO.  TagInfo shows the NEO as supporting OpenPGP, but when I try and decrypt data, OpenKeychain shows that error message.  I'm not super-experienced with Android development or NFC tags, so let me know if there's any other information I can provide that would help.

**Comment by deermo** [comment]
Same here, with an HTC One m7 using CM12, K9-Mail and OpenKeychain. In 50% of the cases, de/encryption fails with "Connection error: Transmission failed". Still works like a charm sometimes, couldn't figure out any influences. 
NFC OATP works perfectly, as does OpenPGP via USB on Windows.

**Comment by deermo** [comment]
Just posting an update: With the newest nightly of CM12, the error rate went up to 90%. I.e., it takes around 10 trials to use the YubiKey, which unfortunately renders the combination useless. Additionally, after about 5-10 times, the NFC dialog hangs and only works after rebooting the device (I guess NFC service crashed?). And hey, no bad feeling here, I know you guys spend a lot of time with htis, and this issue might be M7 specific . However, if you have any clues for use, this would be highly appreciated! If any log files can help, I'm happy to provide them!

**Comment by deermo** [comment]
Got it working!

Maybe this also helps other people: Thanks to http://forum.yubico.com/viewtopic.php?f=26&t=1297, I now got the Yubikey working. It is important to keep the Neo about 5 mm away from the back of the phone and keep it there for about 1-2 seconds. This approach yields an 95% success rate! :)

**Comment by dschuermann** [comment]
Also reported by Jabber that OK freezes on HTC M8 when using NFC. A report should show up in the Google Play dev console soon.

**Comment by dschuermann** [comment]
Other apps also have problems with HTC One, see https://github.com/ikarus23/MifareClassicTool/issues/52

**Comment by dschuermann** [comment]
Not sure if this really helps us, but the MifareClassicTool guys released a patch for their problem at https://github.com/ikarus23/MifareClassicTool/commit/a7939813045995991a5b72dc30828bc6ec76eec3

**Comment by dschuermann** [comment]
I started a wiki page about NFC problems: https://github.com/open-keychain/open-keychain/wiki/NFC-devices

Unfortunately, we can't do much more at this point
